### ISSUE TITLE
Shortcut localization (bold)

### ISSUE THREAD

**Issue by remileblond67076** [ONLYOFFICE/DocumentServer#2565] opened 2024-01-26 17:12 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Hello,

We are in the process of preparing a possible migration from Microsoft Office to OnlyOffice. In this context, we'd like to avoid disrupting the habits of our users.

In France, the standard keyboard shortcut for bold text is CTRL-G, not CTRL-B.

In OnlyOffice, is it possible to modify this shortcut for the French localization?

If not, is it possible to customize keyboard shortcuts?

Thank you in advance for your help.

**Comment by TatianaKirillova** [comment] 2024-02-01 12:15
@remileblond67076 Thanks for your request!
I can confirm - this is know bug, issue #50697 with your  proposal

**Comment by Rita-Bubnova** [comment] 2024-02-01 12:58
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/988.

**Closed by Rita-Bubnova** 2024-02-01 12:58 UTC
