### ISSUE TITLE
Nextcloud 12.0.9 <-> Document Server 5.1.x Fails to Update

### ISSUE THREAD

**Issue by idistech** [ONLYOFFICE/DocumentServer#359] opened 2018-08-06 10:09 UTC
Looking for a little guidance on where to find a problem.
Im trying to get nextcloud and the document server to talk and update files.
We have two separate servers, each working fine, and we have been able to easily open and edit documents..
BUT , the document server doesn't seem to consistently or regularly save the changes back.
I do/sometimes get file updates saved back, but this is not consistent or 'timely' .. ie it can save back once twice a day for document we are editing online.
We have tried fast and strict commit.

we have an "advanced setup". I was/did see some issues with UFW blocking ( rate limiting ) - but have disabled UFW while we try and resolve this.

Ubuntu 16.04 LTS patched.. We had the issue for some time, so its not 'new', 
Onlyoffice-documentserver : 5.1.5
Nextcloud 12.0.9
We have and havnt tried with php/opcache running .

If you edit your document-server session, and re-open the document in the browser, the changes are there.

If you look in the folder on Nextcloud , then changes are not there.. but they might eventually appear (hours? later ) 

Would welcome of where to look for Logs or how to increase verbosity.. 

The Nextcloud Apache Log ( tail -f /var/log/apache2/<server>.log has nothing ( its being called ? !  )

The Documentserver Log has the following error....

`# tail -n 50 out.log
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
[2018-08-01 22:33:24.824] [WARN] nodeJS - update cluster with 1 workers
[2018-08-02 09:20:15.306] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-08-02 09:20:15.353] [WARN] nodeJS - update cluster with 1 workers
[2018-08-02 09:20:15.382] [WARN] nodeJS - worker 27922 started.
[2018-08-02 09:20:15.382] [WARN] nodeJS - update cluster with 1 workers
[2018-08-02 09:20:16.440] [WARN] nodeJS - Express server starting...
[2018-08-02 09:20:17.107] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-08-02 09:28:56.592] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-08-02 09:28:56.620] [WARN] nodeJS - update cluster with 1 workers
[2018-08-02 09:28:56.647] [WARN] nodeJS - worker 1930 started.
[2018-08-02 09:28:56.647] [WARN] nodeJS - update cluster with 1 workers
[2018-08-02 09:28:57.693] [WARN] nodeJS - Express server starting...
[2018-08-02 09:28:59.088] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-08-02 14:15:36.901] [ERROR] nodeJS - error receiving response: docId = undefined type = unLockDocument
TypeError: Cannot read property 'id' of undefined
    at /var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1101:79
    at next (native)
    at onFulfilled (/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:65:19)
    at /var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:54:5
    at co (/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:50:10)
    at SockJSConnection.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1048:14)
    at emitOne (events.js:96:13)
    at SockJSConnection.emit (events.js:188:7)
    at Session.didMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/transport.js:246:25)
    at App.xhr_send (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/trans-xhr.js:81:15)
[2018-08-02 14:15:38.562] [WARN] nodeJS - error description: docId = 52797_1533200085 errorId = Update Version error
[2018-08-02 14:17:53.262] [ERROR] nodeJS - error receiving response: docId = undefined type = unLockDocument
TypeError: Cannot read property 'id' of undefined
    at /var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1101:79
    at next (native)
    at onFulfilled (/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:65:19)
    at /var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:54:5
    at co (/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:50:10)
    at SockJSConnection.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1048:14)
    at emitOne (events.js:96:13)
    at SockJSConnection.emit (events.js:188:7)
    at Session.didMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/transport.js:246:25)
    at App.xhr_send (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/trans-xhr.js:81:15)
[2018-08-02 17:05:43.034] [WARN] nodeJS - error description: docId = 52797_1533215738 errorId = Restore error. Locks not checked.
[2018-08-03 09:28:56.665] [WARN] nodeJS - update cluster with 1 workers
[2018-08-04 09:28:56.665] [WARN] nodeJS - update cluster with 1 workers
[2018-08-05 09:28:56.715] [WARN] nodeJS - update cluster with 1 workers
[2018-08-06 09:28:56.713] [WARN] nodeJS - update cluster with 1 workers
`

I assume this is related .. Any pointers greatly appreciated ..
Thank you

**Comment by ShockwaveNN** [comment] 2018-08-06 10:19
Possible duplicate of https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/139

**Closed** 2018-08-06 10:19 UTC
