### ISSUE TITLE
Use mariadb (Mysql) database as analternative to postgewss

### ISSUE THREAD

**Issue by ratermir** [ONLYOFFICE/DocumentServer#607] opened 2019-07-10 13:52 UTC
Mariadb (Mysql) is fast and effective database for small and middle-size projects. It is widely used across many installation of anything.  

Documentserver is usually installed in conjunction with some file-sharing tool ([Next/Own]Cloud, Communityserver, Pidio ... etc), which all usually use Mysql as a "core" database. So it seems natural to me to use the same - shared - database rather than instantiate its own database (which is currently Postgres) inside the container. 
The shared solution is better also from backing-up perspective (especially in Docker environment). 

I have seen some DB scripts in source codes (also in "Mysql" variants), and I think (from the source code ) that database usage in documentserver is not too complicated, so it should be quite easy to adopt Mariadn (Mysql) as an alternative database. 
So do you plan it in reasonable future?

**Comment by ShockwaveNN** [comment] 2019-07-10 14:58
@ratermir Hi, we support Mysql, you can change driver at `/etc/onlyoffice/documentserver/default.json`
But we never tryed `mariadb`, but it may work also

**Comment by ratermir** [comment] 2019-07-15 07:39
Thank you for response. It seems working, but I have one more objection on this topic:
During documentserver installation I am forced to have postgres installed on the box, even if I will not  using it in production (installation process creates database just in postgres and requires it) and I don't use it at all (neither for any other tool). 
I am not able even uninstall postgres later on since there are hard dependencies defined between documentserver and postgres. 

So I would appreciate decoupling these tools and to allowing database creating after documentserver is installed (for example as a separate script)

**Comment by ShockwaveNN** [comment] 2019-07-15 08:09
@ratermir Yes, we understand this is a problem, we think we may redone requirements for packages about databases, but currently I cannot give your any ETA

**Comment by ratermir** [comment] 2019-07-15 08:13
Great news that you are thinking about this. Thank you :)

**Comment by HolgerHees** [comment] 2020-03-15 08:55
Hi I'm using onlyoffice running the docker container with the version 5.5.0.165 and everything works fine.

Now I try to use my own mariadb instance. I'm running mariadb in version 10.4.12

If I specify DB_TYPE=mysql it works. Onlyoffice is storing data inside mariadb and I can edit and view documents. But I get every hour a warning in the mariadb log file like that 

```
Aborted connection 15784 to db: 'onlyoffice' user: 'onlyoffice' host: '172.21.0.4' (Got timeout reading communication packets)
```
It happens exactly every hour permanently.

If I specify DB_TYPE=mariadb nothing works. I always get the warning in the mariadb log file like

```
Aborted connection 15741 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
```

additionally I get the error log in the onlyoffice log file "onlyoffice/documentserver/docservice/out.log" like

```
[ERROR] nodeJS - Sun, 15 Mar 2020 08:22:27 GMT uncaughtException: Cannot read property 'name' of undefined
[2020-03-15T08:22:27.654] [ERROR] nodeJS - TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/pg/lib/connection.js:130:27)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by ShockwaveNN** [comment] 2020-03-16 09:21
@HolgerHees 
Currently we cannot guarantee that `mariadb` will work and seems I can confirm (but get some other error)
`error receiving response: docId = undefined type = auth`
Reproduces with: 
```
docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=my-secret-pw -p 3306:3306 -d mariadb:10.5
docker run -it -e DB_TYPE=mariadb -e DB_HOST=my_ip -e DB_USER=root -e DB_PWD=my-cret-pw -p 80:80 onlyoffice/documentserver-ie
```

**Comment by agolybev** [comment] 2020-03-16 13:36
@ShockwaveNN, An error occurs when use `DB_TYPE=mariadb`, we'll fix it soon. Now you can use `DB_TYPE=mysql` with MariaDB. I've added a test for it in Docker-DocumentServer repo.
https://github.com/ONLYOFFICE/Docker-DocumentServer/commit/37c058d2810fcf0007fc8785a4ffea9667e9b892

**Comment by HolgerHees** [comment] 2020-03-16 13:55
nice to see this fast reaction time. :-)

will this coming fix also handle "Aborted connection 15784 to db: 'onlyoffice' user: 'onlyoffice' host: '172.21.0.4' (Got timeout reading communication packets)"

What I found so far is that this is related to a not proper close connection or a still exiting connection which is not sending any ping.

In my scenario I got it if i was using mariadb with DB_TYPE=mysql during a long idle period e.g. during the night where only office was not used. This warning occurs in the log file exactly every hour.

**Comment by succeedmr123** [comment] 2022-05-25 08:06
Excellent topic, completely relevant, most small projects use mariaDB inside LAMP stack (mySQL drop-in replacement - mySQL is out long time ago as mariaDB is superior as a drop-in replacement)

In a system where one component might do the job, inducing the functional equivalent to double the resource usage  is, we may agree, usually unwise in the context of efficiency.

That effectively prevent onlyOffice to spread not only inscenarios of resource limitiation, but also inducing complexity where it might have been avoided elegantly.

So, to make onlyOffice adopted in a wider sense, dropping hard requirements on nginx and postgres could be an excellent move

Thank you

**Comment by igwyd** [comment] 2022-05-31 08:22
@HolgerHees hello, sorry for the late reply. We fixed error with DB_TYPE=mariadb, you can use this variable, mariadb connection also not interupted.
@succeedmr123 as you see in this topic you can replace postgre with mariadb. With Nginx it imposable yet. I see your point, but this thread discusses about mariyadb. You can create a new one with a question about replase nginx.

**Comment by ShockwaveNN** [comment] 2022-05-31 10:53
I'll close this issue since original problem should be resolved right now

**Closed by ShockwaveNN** 2022-05-31 10:53 UTC
Labels: enhancement
