### ISSUE TITLE
Why does the name does not display Chinese in the font list

### ISSUE THREAD

**Issue by niushuai1991** [ONLYOFFICE/DocumentServer#1286] opened 2021-06-03 15:00 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
English is currently displayed in the font list. For example, 仿宋 Font should be displayed as "仿宋" instead of "Fangsong"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![fontlist](https://user-images.githubusercontent.com/6659062/120664204-5347a780-c4bd-11eb-992a-dbfb4547f555.png)

**What is the expected behavior?**
I want to display the real font name in the font list, Like 仿宋.
I think this problem should be caused when using the allfontsgen tool.

**Did this work in previous versions of DocumentServer?**
No, I think it should be the same.

**DocumentServer version:**
Lasted
**Operating System:**
Windows 10,  DocumentServer in Docker
**Browser version:**
Firefox 89.0(64 bit)

**Comment by ShockwaveNN** [comment] 2021-06-03 15:03
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/332

**Closed by ShockwaveNN** 2021-06-03 15:03 UTC
