### ISSUE TITLE
Array Formula in Excel is not supported

### ISSUE THREAD

**Issue by sacesare** [ONLYOFFICE/DocumentServer#491] opened 2019-01-29 14:53 UTC
In Excel you can return multiple cells from VLOOKUP/INDEX- just set array to return and press "CTRL+SHIFT+ENTER" on cells returning data into.
Something like:
=VLOOKUP( C1, A:B, {1,2}, 0)
, then select cells to place referenced data and press CTRL+SHIFT+ENTER.
Excel make Array formula, designated as {=VLOOKUP( C1, A:B, {1,2}, 0)} .
Onlyoffice does not support that functionality ,hence can't even read correctly xlsx document, that contains such construction.

Thanks.

**Comment by Rita-Bubnova** [comment] 2019-01-30 07:35
Hello, @sacesare.
This problem is related to the lack of arrays created by functions in the table editor (bug 36111 in our internal issue tracker).

**Comment by hifihedgehog** [comment] 2019-06-24 17:04
@Rita-Bubnova : As a footnote to this problem, I have provided a sample driver-rider document. This document uses an array of cells in a VLOOKUP search to cross-check the number of occurrences of a selected driver in a ride table with the assigned number of open seats in the vehicle of the selected driver in an accompanying driver table. As it turns out, when the number of occupants is not surpassed, the column that should display "yes" to indicate the number of riders has not yet been surpassed erroneously shows a "no" instead.

[Test.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3321788/Test.xlsx)

**Comment by Rita-Bubnova** [comment] 2019-06-25 09:48
@hifihedgehog thank you for the attached file. 
Issue 36111 in our internal issue tracker fixed. But I can confirm that the problem with the calculation of the VLOOKUP function is relevant.

I created a new issue 41950 in our private issue tracker.

**Comment by hifihedgehog** [comment] 2019-06-25 16:30
Thanks. Here is a corrected example for future reference since the earlier version of the file had a few mistakes.

[Test.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3326334/Test.xlsx)

**Comment by hifihedgehog** [comment] 2019-09-10 15:43
I recently updated OnlyOffice and it appears the issue I submitted has recently been fixed so that now VLOOKUP obtains the correct number and the comparison operation calculates accurately.

**Comment by rsnegirev** [comment] 2023-12-13 14:23
@hifihedgehog the problem was fixed in this commit https://github.com/ONLYOFFICE/sdkjs/commit/adef90f8eac0c9461e04213ebac4166fc6c8f58e

It will be released in the next major version.

**Comment by Rita-Bubnova** [comment] 2024-02-01 08:35
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-02-01 08:35 UTC
Labels: confirmed-bug, fixed-release
