### ISSUE TITLE
Cant edit old MS Office Documents

### ISSUE THREAD

**Issue by kwmkjf** [ONLYOFFICE/DocumentServer#368] opened 2018-08-21 12:38 UTC
Im using the Documentserver with my nextcloud for editing documents online. With docx, xlsx or pptx it works just great. But when I use files with the old format like doc, xls or ppt it opens the file, but the bar at the top is missing and I cant write into the file.

**What is the expected behavior?**
I would expect onlyoffice to let me edit the files even in the old format.

**Operating System:**
Ubuntu Server 18.04.01 LTS

**Browser version:**
Firefox 61.0.2 but all others too

**Comment by ShockwaveNN** [comment] 2018-08-21 12:49
Duplicate of https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/196

**Closed by ShockwaveNN** 2018-08-21 12:49 UTC

**Comment by timm2k** [comment] 2018-08-21 12:51
You can click on "..." (three-dot-context-menu) and choose "Open in ONLYOFFICE". In the next step your are asked for converting the file to Office OpenXML...
