### ISSUE TITLE
Input slows down after typing a few sentences

### ISSUE THREAD

**Issue by XXDoMi77** [ONLYOFFICE/DocumentServer#1501] opened 2021-11-07 10:48 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When editing a large document, after typing a few sentences input becomes very slow. I type or delete a character and there is a very large delay between me pressing the button and the character appearing/ disappearing on the screen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Type a few sentences in a presumably large document, haven't tested whether it happens on other large documents yet, but I definitely have this issue on at least one of my documents. Also tried to downgrade to 6.3.2-2 and the issue is still there.

[![Demo](https://img.youtube.com/vi/viEMiwEgFKI/0.jpg)](https://www.youtube.com/watch?v=viEMiwEgFKI)

I hope it comes across on the video, but the more you type the the more the input lags behind what you actually type, so the faster you type the more noticeable it gets.

**What is the expected behavior?**
The input doesn't slow down...

**Did this work in previous versions of DocumentServer?**
I tried downgrading to 6.3.2-2 didn't help. Otherwise I am not sure.

**DocumentServer version:**
onlyoffice-documentserver |    6.4.2-6 | https://download.onlyoffice.com/repo/debian squeeze/main amd64 Packages
From 6.3.2-2 to 6.4.2-6 the issue is present.

**Operating System:**
Ubuntu 20.04.3 LTS x86_64

**Browser version:**
Google Chrome | 95.0.4638.69 (Official Build) (64-bit) (cohort: Stable)
I am not sure about other browsers, but it definitely has this behavior in chrome as I am not the only one experiencing this issue.

**Comment by XXDoMi77** [comment] 2021-11-07 22:11
After some more research not only does the input slow down, but the client as whole.

**Comment by XXDoMi77** [comment] 2021-11-07 22:15
By the looks CPU usage also goes up to over 100%

![image](https://user-images.githubusercontent.com/27887974/140663730-f0c32c38-3dbf-4928-ae64-3d3b420817ff.png)

**Comment by XXDoMi77** [comment] 2021-11-07 22:21
I just tried it in Edge and the same thing happens. Also forgot to mention that once you refresh the site, the issue restarts, so the lagging goes away, until you type some sentences again...

**Comment by systemx-xx** [comment] 2021-11-08 02:36
I can confirm I am seeing the same behavior I have tested it on Chrome 95 for OSX (Intel) and Windows 10. We have a very basic 6.3.1 install with no additional plugins, but I have also tested it on an older Only Office 5.1.4 and it does the same thing. I rolled back to Chrome 94 and the problem is gone, problem does not seem to be there in Firefox or Safari.

You can see this behavior on the very latest build if you go to https://www.onlyoffice.com/document-editor.aspx and use the demo editor. After typing approximately 4 or more lines it starts to slow down.

**Comment by ShockwaveNN** [comment] 2021-11-08 07:03
Hi, we can confirm this issue, and we strongly think this is some kind of bug in Chrome engine itself

Since this problem only actual in Chrome (not Firefox or Safari) and seems that this problem is already fixed in Beta version of Chrome 96 

Perhabs you should test Chrome 96 temporary and see if this problem actual there and if it fixed I think we have no other choice, than waiting for Chrome 96 release in a month

**Comment by XXDoMi77** [comment] 2021-11-08 10:08
Yeah, can confirm it's fixed in Chrome beta (Version 96.0.4664.35). Pretty unfortunate that we have to wait for the next Chrome update.

**Comment by ShockwaveNN** [comment] 2021-11-08 10:20
We understand this is no good, but we do not found any workaround for this problem

And since usually chrome release several bugfixes to v95 before shipping v96 I'll hope it'll be fixed, but I'm not sure how to check next bugfix of v95

**Comment by ShockwaveNN** [comment] 2021-11-15 11:03
Chrome v96 was released today and according to our tests - problem is fixed

I'll close this issue, but feel free to comment if release of new Chrome didn't fixed it for you
And please note that if you got this problem in other Chromium-based browser - release may took time

**Closed by ShockwaveNN** 2021-11-15 11:03 UTC
Labels: bug
