### ISSUE TITLE
Format of line number changes after file with .odt format is reopened after editing

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2785] opened 2024-07-02 06:11 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (RPM package)

### Version information

7.5.0

### Expected Behavior

Line numbering format should be 'Restart each page'.
File contains continuous line numbering instead of restarting line numbering for each page.

### Actual Behavior

Line numbering configuration is not saved for .odt file. Line numbering format configured as 'Restart each page' changes to 'Continuous' after saving & opening the same file. 

### Reproduction Steps

    Open .odt format file in browser.
    Click on 'Layout > Line Numbers > Restart each page'
    Line numbering should start from 1 for each page.
    Save and close the file.
    Open the same file in the browser.
    Observe the line numbering format of the file.

**Comment by ElenaMaaya** [comment] 2024-07-05 12:32
Hello, @Maaayank! 
Thanks for your report! 
The problem is not repeated in DocumentServer and DesktopEditor release version 8.1.0.169  on Windows 11.
Please update to version 8.1.0 and check the problem. 
If the problem persists, please write here again.

**Comment by Rita-Bubnova** [comment] 2024-07-05 12:39
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-07-05 12:39 UTC
Labels: fixed
