### ISSUE TITLE
In Google browser, pictures and characters are copied and pasted together, and pictures are not displayed. There is no such problem in IE.

### ISSUE THREAD

**Issue by 769876106** [ONLYOFFICE/DocumentServer#268] opened 2018-04-03 03:55 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Copy pictures and characters in word2016, paste together and do not show pictures.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In word2016, pictures and characters are copied together, and pasted in the online editor opened by Google browser. The picture is not displayed.
**What is the expected behavior?**
Pictures can be displayed
**Did this work in previous versions of DocumentServer?**
YES
**DocumentServer version:**
5.0.1CE
**Operating System:**
win10
**Browser version:**
Google 65.0.3325.181

**Comment by ShockwaveNN** [comment] 2018-04-03 08:24
Duplicate of #267

**Closed by ShockwaveNN** 2018-04-03 08:24 UTC
