### ISSUE TITLE
Ability to select file to Mail Merge without connecting to DMS

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#1300] opened 2021-06-14 08:00 UTC
**Do you want to request a *feature* or report a *bug*?**

FEATURE

**What is the current behavior?**

Implement mailmerge with document server

This will be also a highly added value functionality compared to MS-Office which does not allow mailmerge with remote excel file even on sharepoint (see https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/32802904-allow-mailmerge-using-sharepoint-and-oronedrive)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Provide mailmerge in Onlyoffice Document server (at minima in the paid version) and not only in the SaaS version. 

**Did this work in previous versions of DocumentServer?**

N/A

**DocumentServer version:**

6.3

**Operating System:**

N/A

**Browser version:**

N/A

**Comment by XDmitryK** [comment] 2021-06-15 10:28
@cpot  Hello
We didn't plan to merge email into DS because it would be very difficult to do without a connected portal.

**Comment by ShockwaveNN** [comment] 2021-06-15 10:47
Hi, I may be wrong and do not fully understand your request, but our current implementation of MailMerge support remote files

https://api.onlyoffice.com/editors/methods#setMailMergeRecipients

![image](https://user-images.githubusercontent.com/668524/122040145-25793180-cde0-11eb-9854-6feb7d00aba9.png)


If this is not that you want could you describe your use case in more details, for us MailMerge is not very widely used feature, so we probably do not consider all it use cases

**Comment by cpot** [comment] 2021-06-15 15:20
@ShockwaveNN in fact, the 'envelop' icon is greyed. to grey out you have to do the API call (thank you for the trick). we don't understand why it is not possible to do it through the interface.

and it was written in the doc https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-document-editor/usageinstructions/usemailmerge.aspx, it is said "Note: this option is available in the online version only.", which seems to be wrong.

**Comment by ShockwaveNN** [comment] 2021-06-15 15:34
> we don't understand why it is not possible to do it through the interface.

So your idea is to provide separate window to enter file url with mailmerge data, am I right?

> it is said "Note: this option is available in the online version only.", which seems to be wrong.

This mean this feature not available in DesktopEditors, but only in DocumentServer

**Comment by cpot** [comment] 2021-06-15 16:18
Not really, in your documentation it is written :
![image](https://user-images.githubusercontent.com/3287514/122088464-05f4ff80-ce06-11eb-9c51-8e8defa2529e.png)

But there is not such icon in our DocumentServer version (community or not)

**Comment by ShockwaveNN** [comment] 2021-06-16 08:41
> But there is not such icon in our DocumentServer version (community or not)

I think there should be icon in any cases (bottom right of my screenshot):

![image](https://user-images.githubusercontent.com/668524/122187109-65e7b680-ce97-11eb-9232-02952caed449.png)

But if you didn't call `setMailMergeRecipients` this icon is blocked

I'm personally not very good at details of it's init - but you can look at integrated test example (should bu turnoff according to instruction at `http://docserverurl/welcome` and accessable via `http://docserverurl/example`)

Example use only one static data list, but I think this can be enough to study how it works to implement in your own integration

**Comment by cpot** [comment] 2021-06-21 07:24
Hi @ShockwaveNN, 
Well there is just one small UI (modal ?) to build over this API (to enter the url of the xlsx file, ...) and you are done. should be very fast to implement, it has nothing to do with any integration IMHO

**Comment by ShockwaveNN** [comment] 2021-06-21 07:49
@cpot To be clear - are you wanting that this form be available in any integration, be a part of DocumentServer, not any connector\test example?

I'm not sure that devs are agree with it, but create a issue to discuss it and track users can not be a bad thing

**Comment by avanhove** [comment] 2021-06-29 08:35
Hello @ShockwaveNN,
All we want is a mail merge button (not blocked and clickable) that calls `setMailMerge`  and works all the time, and maybe open the form in a small modal.
Do you think this is possible?

**Comment by ShockwaveNN** [comment] 2021-06-29 08:40
@avanhove Same question to you

> Are you wanting that this form be available in any integration, be a part of DocumentServer, not any connector\test example?

**Comment by avanhove** [comment] 2021-06-29 08:41
Yes

**Comment by ShockwaveNN** [comment] 2021-06-29 08:46
@avanhove Ok, I'll create enhancement today to discuss with our dev team, but it's up to them if this really needed to be implemented

**Comment by avanhove** [comment] 2021-06-29 08:46
Thank you !

**Comment by ShockwaveNN** [comment] 2021-06-29 09:15
I've create issue 51024 in our private issue tracker

**Comment by cpot** [comment] 2021-10-30 10:08
Hi @ShockwaveNN Any news about this request, mailmerge is unusable without it, please check with @avanhove is the request is understandable

**Comment by ShockwaveNN** [comment] 2021-11-01 07:58
Thank you for noticing, actually we got news

The issue is fixed in https://github.com/ONLYOFFICE/web-apps/commit/b6aa262f2b3fbbf9d7f26a7d8986d42409c167fc
And in future version v7.0.0 you will be able to select files with mail merge data in 3 ways

1. From local file system
2. From public direct URL to file
3. From DMS (only way before)
![image](https://user-images.githubusercontent.com/668524/139640030-50a08bed-bc1d-4922-a21b-cf5f0c088410.png)

**Comment by cpot** [comment] 2021-11-01 12:07
This is a very good news, the mailmerge icon will be available and moreover several ways of choosing the address source, congrats ! 
Any ETA for v7 ?

**Comment by ShockwaveNN** [comment] 2021-11-01 12:09
@cpot I really hope we'll be able to release it in a month, but there are several major new features in this release, so I cannot promise anything

**Comment by cpot** [comment] 2021-11-01 12:12
@ShockwaveNN Thank you that would be perfect, could perhaps add into GoFAST v4 that we will release in December

**Comment by ShockwaveNN** [comment] 2022-01-18 12:27
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual

**Closed by ShockwaveNN** 2022-01-18 12:27 UTC
Labels: enhancement, fixed
