### ISSUE TITLE
Accents / styles in toolbar are not loading

### ISSUE THREAD

**Issue by NorseGaud** [ONLYOFFICE/DocumentServer#729] opened 2019-12-25 23:31 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

<img width="1675" alt="Screen Shot 2019-12-25 at 6 29 45 PM" src="https://user-images.githubusercontent.com/5896030/71451480-a18f3d80-2744-11ea-9301-461caf5394f0.png">
<img width="829" alt="Screen Shot 2019-12-25 at 6 30 46 PM" src="https://user-images.githubusercontent.com/5896030/71451482-b075f000-2744-11ea-8745-7faef3036c72.png">

The accents in the toolbar are showing an img src of unknown. Anyone know why?

**DocumentServer version:**

5.4.2.46

**Operating System:**

Ubuntu 18.04

**Browser version:**

Brave

**Comment by ShockwaveNN** [comment] 2019-12-26 08:29
Also seems this issue is not related to `onlyoffice-nextcloud`, moved to DocumentServer repo
So please fill version info, os info and browsers

**Comment by NorseGaud** [comment] 2019-12-26 14:08
I just noticed this is only a problem in the Brave browser. That's odd, I don't think I have anything special enabled for it that would block this. I'm guessing this is a known limitation?

**Comment by ShockwaveNN** [comment] 2019-12-26 14:09
So this is a duplicate of #539

**Closed by ShockwaveNN** 2019-12-26 14:09 UTC
Labels: waiting feedback
