### ISSUE TITLE
Incorrect display of Chinese fonts 宋体, 华文彩云, 华文琥珀, 华文行楷

### ISSUE THREAD

**Issue by cnraorong** [ONLYOFFICE/DocumentServer#1142] opened 2021-02-03 15:47 UTC
![1](https://user-images.githubusercontent.com/6263486/106771011-8138ee80-6679-11eb-9b19-05e16e4a42d6.png)

[somefont.zip](https://github.com/ONLYOFFICE/DocumentServer/files/5919651/somefont.zip)

#1099 It appears after the bug is fixed.

**Comment by cnraorong** [comment] 2021-02-03 15:58
here is test document file...
[test document.docx](https://github.com/ONLYOFFICE/DocumentServer/files/5919730/test.document.docx)
some font files in the topic file "[somefont.zip](https://github.com/ONLYOFFICE/DocumentServer/files/5919651/somefont.zip)"

**Comment by ShockwaveNN** [comment] 2021-02-04 08:45
@cnraorong Hi, thank for your report
I can confirm - this is a bug, I've create issue 48564 in our private issue tracker

**Comment by cnraorong** [comment] 2021-02-05 11:38
SimSun(宋体) is same too...Incorrect display...  the font file is too large, so me hanvn't upload...

**Comment by Malenconiaprincep** [comment] 2021-02-18 08:12
I happened same problem too

**Comment by cnraorong** [comment] 2021-02-26 04:34
> @cnraorong Hi, thank for your report
> I can confirm - this is a bug, I've create issue 48564 in our private issue tracker

Thanks!  Has this bug been fixed? When will the next version be released?

**Comment by ShockwaveNN** [comment] 2021-02-26 07:12
> @ShockwaveNN Thanks! Has this bug been fixed? When will the next version be released?

Sorry, no, issue still not fixed and I cannot guarantee any ETA of this fix. 
If you got any question about our issue fix priorities - it's better to direct to our sales team at sales@onlyoffice.com

**Comment by causkycn** [comment] 2021-04-02 06:24
Microsoft Windows Chinese font has 2 names
example: STZHONGS.ttf
name1:    platform: 3, language:1033, name: STZhongsong
name2:   platform: 3, language:2052, name: 华文中宋

name1 for format
name2 for display

**Comment by causkycn** [comment] 2021-04-02 06:36
Microsoft Windows Chinese font has 3 names
example: STZHONGS.ttf
name1: platform: 0, language:0, name:STZhongsong
name2 platform: 3, language:1033, name: STZhongsong
name3: platform: 3, language:2052, name: 华文中宋

name1&2 for format
name3 for display
[stzhongs.ttf.zip](https://github.com/ONLYOFFICE/DocumentServer/files/6248066/stzhongs.ttf.zip)

**Comment by ShockwaveNN** [comment] 2022-05-19 07:25
This issue is fixed via https://github.com/ONLYOFFICE/sdkjs/commit/288690feeaeb7bb70126f6391a5ea6bcaa3655d5

It will be released as v7.1.1 within a month (or two)

**Comment by ShockwaveNN** [comment] 2022-06-02 12:10
DocumentServer v7.1.1 is released and this issue should be fixed

I think there may be several issues here so if something is not completely fixed - I think it's better to create a new issue here

**Closed by ShockwaveNN** 2022-06-02 12:10 UTC
Labels: bug, fixed

**Comment by cnraorong** [comment] 2022-08-23 02:34
@ShockwaveNN Thanks!  We have upgraded to the latest version, but there are still some complicated formats that occasionally cause page confusion…

**Comment by ShockwaveNN** [comment] 2022-08-23 10:22
@cnraorong I think it's better to create a new issue with detailed description what you mean, since I do not understand you at all
