### ISSUE TITLE
Editing focus scrolls back and forth

### ISSUE THREAD

**Issue by ZID-TU-Graz** [ONLYOFFICE/DocumentServer#1999] opened 2022-11-11 15:56 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.1.34

### Expected Behavior

The focus on the window should not be changed

### Actual Behavior

When editing a document together the windows scrolls forth and back to the position where each person is typing

https://user-images.githubusercontent.com/100593683/201379965-f2a742c9-f843-4197-8f5c-a27b5d74a269.mov

### Reproduction Steps

1. Editing a document together
2. The windows scrolls forth and back to the position where each person is typing

### Additional information

We are not sure if it is related to the DocumentServer and/or the Nextcloud app.
Nextcloud ONLYOFFICE app version: 7.5.8
Tested clients: Windows 11, Firefox
The problems may occurs only with small(er) screen sizes (e.g. on notebooks).

**Comment by ShockwaveNN** [comment] 2022-11-14 07:35
Hi, could you reproduce this issue using DocumentServer integrated example (located at http://documentserver_url/welcome) to rule out that's not a problem with Nextcloud integration

And please state version of DocumentServer (from About tab in the left)

**Comment by ZID-TU-Graz** [comment] 2022-11-14 16:05
We was able to reproduce this issue  using DocumentServer integrated example.
Strange thing: not all users/documents of our nextcloud instance are affected by this issue. Our users reports that this issue occurs at least in (via circles) shared documents. But this does not explain why it occurs also using DocumentServer integrated example.

DocumentServcer 7.2.1.34 (docker)

**Comment by ShockwaveNN** [comment] 2022-11-15 07:13
I think it's a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1955

**Closed by ShockwaveNN** 2022-11-15 07:13 UTC
