### ISSUE TITLE
different character mapping for DOC and Spreadsheets/Presentation

### ISSUE THREAD

**Issue by michal-barteczko** [ONLYOFFICE/DocumentServer#1274] opened 2021-04-19 08:25 UTC
Hi

Onlyoffice 6.1 (443) on mac el Captain

For aplication Spreadsheets or Presentation when I type cmd+c I got „ć” or cmd+e I got „ę” polish character and this is good.
When open doc documet and typing cmd+c/cmd+e I got different special characters ©/€ . I can put „ć” or „ę” letters but only via Insert Symbol feature.
Using the same Arial font. It does not matter what language set I use pl-PL/en-US etc.
Any ideas?

**Comment by DenisDeeSign** [comment] 2021-05-20 11:08
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too.

**Comment by BubakPL** [comment] 2021-11-26 12:38
Hello. I have a same problem as OP. In my company we use MacOS, so we cannot use onlyoffice, because polish characters (ę and ć) not working correctly in documents. Could you please reflect on this topic? Thanks!

**Comment by szymonrucinski** [comment] 2021-12-11 12:19
It's same for me. I am coming back to OpenOffice because of this problem. It's very irritating to copy and paste diacritic symbols all the time.

> Hello. I have a same problem as OP. In my company we use MacOS, so we cannot use onlyoffice, because polish characters (ę and ć) not working correctly in documents. Could you please reflect on this topic? Thanks!

**Comment by micpiotrowski** [comment] 2022-02-23 09:21
Any news about this issue? We are still affected by this :/

**Comment by ShockwaveNN** [comment] 2022-02-24 10:08
@micpiotrowski Sorry, not news. If you really need this issue fixed - better contact sales@onlyoffice.com so we change priority of it

**Comment by Misokados** [comment] 2023-04-26 08:22
Hello,
The mentioned bug was fixed in v.7.3. Please update your installation and re-check the situation.

**Comment by maruacat** [comment] 2023-05-05 12:36
Hello!
We have fixed this issue and it is not reproducible in the latest released version 7.3.3.
Thanks a lot to every user!

**Comment by DenisDeeSign** [comment] 2023-05-05 12:45
DocumentServer v7.3.3 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed** 2023-05-05 12:45 UTC
Labels: bug, fixed
