### ISSUE TITLE
Unexpected behaviour causing data loss

### ISSUE THREAD

**Issue by putt1ck** [ONLYOFFICE/DocumentServer#1011] opened 2020-09-28 17:14 UTC
A user opens a file from Nextcloud; edits the file; sees the file is saved and tells a colleague the file is updated so they can send the file to the customer.  But the file is not updated (not saved in user speak) because they understand the file's location as being in the project folder on the company Nextcloud.

The expected behaviour when the file is "saved" is that it is saved in the location from which they opened it. Telling users that what they understood as "save" no longer means what they think it means, and the only way to save in their terms is to make all users with the document open close it, and then wait 10 seconds.

A prima facie simple fix for this would be that the current "saved" messaging is changed to "updated" (works for both users only working in OnlyOffice and those using separate file stores) and a save button added that writes the file back to the location it was opened from (or saves the file as most users understand the concept). The existing write back 10 seconds after all editor windows are closed can be retained for continuity and as a failsafe.

This bug is present in all versions of DocumentServer when used with Nextcloud (and presumably is the same issue for any use with a remote file store).

**Comment by putt1ck** [comment] 2020-09-28 17:15
Relates to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/257

**Comment by mvvvmd** [comment] 2020-10-15 08:27
We have found this to be a problem for our users also. They expect auto saving to mean the file in the Nextcloud folder is updated with the latest changes. Even when the document is still open. Some kind of change as described above could work to resolve this for sure.

**Comment by alexanderonlyoffice** [comment] 2021-06-03 10:41
Hello @putt1ck, @mvvvmd, please note that described behavior is not a bug, this is how the Document Server works. It downloads the file from the DMS (Nextcloud in your case) for editing. When the file is edited, all changes added to it are located in DB. "All changes saved" phrase means exactly that the changes are stored in DB and the final file version will be built after all browser tabs with this file are closed by all participants. After the file version is built it is sent to the DMS. 

There is a possibility to use "Keep intermediate versions when editing (forcesave)" to use 'Save' button in common understanding. Once it is clicked on the upper toolbar in the editor interface, current state of the file is built into an intermediate version and sent back to DMS.

**Closed by alexanderonlyoffice** 2021-06-03 10:41 UTC

**Comment by putt1ck** [comment] 2021-06-03 11:40
Thanks @alexanderonlyoffice that setting sounds like exactly the thing our (and most, in my experience) users would expect. I can't see a button to turn that setting on though. Does it have to be enabled in config or something?

**Comment by putt1ck** [comment] 2021-06-03 16:20
I found a setting in the admin part of NC which matches what you describe and this does seem to work. I'd recommend it was default on as it *is* the expected behaviour from a user perspective.
