### ISSUE TITLE
Conversion bug for table filter formulas

### ISSUE THREAD

**Issue by anthonychaussin** [ONLYOFFICE/DocumentServer#2882] opened 2024-09-11 07:44 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.3.4

### Expected Behavior

I'd like it to work like Excel, where the result only shows the corresponding records once.

### Actual Behavior

Currently, even if there is only one match, the result is duplicated over the entire result range. 
What's more, when the document is downloaded again, the formula is broken and the original behaviour is lost.

### Reproduction Steps

1. Upload the document to OnlyOffice
2. Modify the search by ‘DOE

### Additional information

Screen record : https://github.com/user-attachments/assets/888bcd46-1972-4706-a787-7d1de009cd42

Link to file https://kdrive.infomaniakgroup.com/app/share/100338/d197dd55-3dc9-4b4e-9842-3e387b3531a2

Original file : [PB_FILTER.xlsx](https://github.com/user-attachments/files/16959635/PB_FILTER.xlsx)

File after conversion : [PB_FILTER (1).xlsx](https://github.com/user-attachments/files/16959641/PB_FILTER.1.xlsx)

**Comment by rsnegirev** [comment] 2024-09-11 13:49
Hi @anthonychaussin 

The result is duplicated because the formula applied as an array, so this is not a bug.

More interesting how is formula was broken.

So you:
1. Edit the file in Excel.
2.  Save and close it.
3. Open it in ONLYOFFICE.
4. 3 times edit F1 cell.
Result: FILTER formula in E5 is broken. That is what I see on the record.

But I can't reproduce it.

Maybe I'm missing some steps?

**Comment by anthonychaussin** [comment] 2024-09-12 07:40
Hello @rsnegirev 

I understand the duplication of results, but it's a shame not to have the same behaviour as with Excel.

As for the broken formula, after re-testing I found several things.

- It's broken as soon as the file is imported, without even making any changes
- It doesn't happen on the desktop app or on a docker installation
- It happens on a kube instance

Hope this helps, feel free to close the ticket if you can't fix something.

Have a nice day and thanks for your help

**Comment by rsnegirev** [comment] 2024-09-13 12:42
Maybe on a Kube you have an older version? Because formulas don't depend on the installation types. And in the one of the previous versions we released some fixes on FILTER function.

**Closed** 2024-09-13 12:54 UTC
