### ISSUE TITLE
RTL In the Editor

### ISSUE THREAD

**Issue by ikfir** [ONLYOFFICE/DocumentServer#1621] opened 2022-02-05 11:01 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Only LTR

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can type in hebrew

**What is the expected behavior?**
To be able to type in hebrew

**Did this work in previous versions of DocumentServer?**
no

**Comment by ShockwaveNN** [comment] 2022-02-05 14:45
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Closed by ShockwaveNN** 2022-02-05 14:45 UTC
