### ISSUE TITLE
Help!I installed it by docker in linux, but where is my default.json? It's not at /etc/onlyoffice/documentserver/default.json?

### ISSUE THREAD

**Issue by FEliuze** [ONLYOFFICE/DocumentServer#934] opened 2020-07-23 11:43 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment] 2020-07-23 11:55
Are you looking for this file inside container? It's should be there

Should your `docker run` command

**Comment by ShockwaveNN** [comment] 2020-07-23 11:56
Duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/266

**Closed by ShockwaveNN** 2020-07-23 11:56 UTC
