### ISSUE TITLE
Disperse aligned text is set, and the imported text is justified

### ISSUE THREAD

**Issue by bszhct** [ONLYOFFICE/DocumentServer#1386] opened 2021-08-19 08:47 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Disperse aligned text is set, and the imported text is justified

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I set scattered alignment to the text "The text here needs to be scattered and aligned." in the docx file, but it is justified when opened with onlyoffice.

This is the display effect in wps:
![image](https://user-images.githubusercontent.com/56250514/130036511-44cbd204-d8d9-4e55-91fe-a1c27600fdb9.png)

This is the display effect in onlyoffice:
![image](https://user-images.githubusercontent.com/56250514/130037923-4ee17d2c-130b-4a96-a3b6-b353ac086a3e.png)

**What is the expected behavior?**
I hope that onlyoffice is also displayed in scattered alignment

**Did this work in previous versions of DocumentServer?**
Tried in 5.5.3 is also invalid

**DocumentServer version:**
6.3.1-32

**Operating System:**
macOS、10.14.5

**Browser version:**
Chrome、92.0.xxx

Hope to get help, thank you very much

**Comment by Rita-Bubnova** [comment] 2021-08-19 10:07
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1018.

**Closed** 2021-08-19 10:09 UTC
