### ISSUE TITLE
SyntaxError: Unexpected token M in JSON at position 0

### ISSUE THREAD

**Issue by sasori0623** [ONLYOFFICE/DocumentServer#2453] opened 2023-11-01 13:22 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.1

### Expected Behavior

The same error occurs in the latest version, 7.1, and I can read but not save.

This error occurs when accessing the site via Filerun, but not when accessing the test page.

### Actual Behavior

I set up JWT secret for OnlyOffice Document Server Docker in FileRun, and I can access the file, but I can't overwrite, save, etc., and I get the following error.

SyntaxError: Unexpected token M in JSON at position 0

### Reproduction Steps

As mentioned above, I would like to get this resolved because I am not sure if my settings are bad or if it is a bug.

I have tried reinstalling the software again, etc., but the situation is the same.

Thank you in advance.

### Additional information

The error log is below.

Thank you in advance for your cooperation.

Also, Token B Also, I get an M.

I can't find a solution to these problems anywhere, so I'm wondering if this is a bug.　If there is another way to solve this problem, please let me know.

`SyntaxError: Unexpected token M in JSON at position 0
2023-11-01 22:11:49     at JSON.parse (<anonymous>)
2023-11-01 22:11:49     at Object.parseReplyData (/snapshot/server/build/server/DocService/sources/DocsCoServer.js)
2023-11-01 22:11:49     at commandSfcCallback (/snapshot/server/build/server/DocService/sources/canvasservice.js)
2023-11-01 22:11:49     at commandSfcCallback.next (<anonymous>)
2023-11-01 22:11:49     at /snapshot/server/build/server/DocService/sources/canvasservice.js
2023-11-01 22:11:49     at Generator.next (<anonymous>)
2023-11-01 22:11:49     at onFulfilled (/snapshot/server/build/server/DocService/node_modules/co/index.js:65:19)
2023-11-01 22:11:49     at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by sasori0623** [comment] 2023-11-03 05:20
When I accessed OnlyOffice from FileRun with the JWT secret disabled, I was able to access it successfully.

Also, I get an error even though the JWT secret is correct.

Is there any other command I can add to Docker Run?

JWT related commands,
sudo docker run -i -t -d -p 80:80 --restart=always \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data \
    -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
    -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql \
    -e ALLOW_META_IP_ADDRESS="true" \ -e ALLOW_META_IP_ADDRESS="true
    -e ALLOW_PRIVATE_IP_ADDRESS="true" \ \
    -e JWT_ENABLED="true" \ -e ALLOW_PRIVATE_IP_ADDRESS="true" \
    -e JWT_SECRET=JWT_key \
    onlyoffice/documentserver

This command gave me the aforementioned error, so I'm pretty sure the JWT secret is the problem.

I would like to solve this problem somehow, so thank you in advance for your help.

Thanks again for your help.

**Comment by igwyd** [comment] 2023-11-16 05:53
Duplicate of #2419

**Closed** 2023-11-16 22:40 UTC
Labels: duplicate
