### ISSUE TITLE
documentserver-prepare4shutdown.sh stuck on upgrade

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#623] opened 2019-08-05 11:19 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
check if service is running 
if service running close all and do upgrade
if service not running continue upgrade

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
befor upgrade:
documentserver-prepare4shutdown.sh = don't matter 
supervisorctl stop all = don't matter to

on upgrade:
apt update && apt upgrade 
wait over 25 min on documentserver-prepare4shutdown.sh ( befor upgrade its finish in max. ~2min) maybe wrong exit code? wrong user on upgrade? 
ps auxf ( look for shutdown.js ) kill PROZESS 
upgrade continue 

No access on Server ( no open Document or anything else) 

**What is the expected behavior?**
do what script say's ;)

**Did this work in previous versions of DocumentServer?**
yes 5.2.8 ( and maybe the next release)

**DocumentServer version:**
5.3.2

**Operating System:**
Debian 9.9 no Docker

**Browser version:**
----

**Comment by hahaxd35** [comment] 2019-08-05 11:37
[2019-08-05T13:30:12.772] [DEBUG] nodeJS - shutdown remaining files:0
[2019-08-05T13:30:13.774] [DEBUG] nodeJS - shutdown remaining files:0
[2019-08-05T13:30:14.776] [DEBUG] nodeJS - shutdown remaining files:0
[2019-08-05T13:30:15.777] [DEBUG] nodeJS - shutdown remaining files:0
[2019-08-05T13:30:16.779] [DEBUG] nodeJS - shutdown remaining files:0
[2019-08-05T13:30:17.779] [DEBUG] nodeJS - shutdown stop wait pubsub deliver
[2019-08-05T13:30:17.780] [DEBUG] nodeJS - shutdown remaining files:0
[2019-08-05T13:30:17.909] [DEBUG] nodeJS - [AMQP] conn close
[2019-08-05T13:31:20.743] [DEBUG] nodeJS - shutdown start1830000
[2019-08-05T13:31:20.784] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-08-05T13:31:20.989] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

**Comment by ShockwaveNN** [comment] 2019-08-05 11:38
@hahaxd35 could you look at redis logs? maybe it crashed for some reason

**Comment by hahaxd35** [comment] 2019-08-05 11:43
AHH!
622:M 05 Aug 13:36:36.225 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
622:M 05 Aug 13:36:36.225 # Server started, Redis version 3.2.6
622:M 05 Aug 13:36:36.225 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.c
onf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
622:M 05 Aug 13:36:36.225 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue
run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restart
ed after THP is disabled.
622:M 05 Aug 13:36:36.227 * DB loaded from disk: 0.002 seconds
622:M 05 Aug 13:36:36.231 * The server is now ready to accept connections on port 6379

**Comment by ShockwaveNN** [comment] 2019-08-05 11:44
No older logs? why redis was stopped at 13:31 and started only at 13:36

**Comment by hahaxd35** [comment] 2019-08-05 11:49
in this time apt wait for documentserver-prepare4shutdown.sh to exit 

here another log from our testing server ( full log!) here i wait 25 min
718:signal-handler (1565000776) Received SIGTERM scheduling shutdown...
718:signal-handler (1565000776) Received SIGTERM scheduling shutdown...
718:M 05 Aug 12:26:16.904 # User requested shutdown...
718:M 05 Aug 12:26:16.914 # Redis is now ready to exit, bye bye...
8478:M 05 Aug 12:50:17.950 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
8478:M 05 Aug 12:50:17.950 # Server started, Redis version 3.2.6
8478:M 05 Aug 12:50:17.950 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.
conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
8478:M 05 Aug 12:50:17.950 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue
 run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restar
ted after THP is disabled.

**Comment by ShockwaveNN** [comment] 2019-08-05 12:00
Can you attach some kind of time table of your actions.
Because currently it's seems for me that redis was stopped at time of running `documentserver-prepare4shutdown.sh` and this cause unpredicted results

**Comment by hahaxd35** [comment] 2019-08-05 13:46
if have done 2 upgrades and 3 follow right now 

i will notice any step what should i do on Upgrade?
Like https://helpcenter.onlyoffice.com/server/linux/document/upgrade-document.aspx ?
first: documentserver-prepare4shutdown.sh 
second: apt update && apt upgrade? 

or:

first: documentserver-prepare4shutdown.sh 
second: supervisorctl stop all
third: apt update && apt upgrade

**Comment by ShockwaveNN** [comment] 2019-08-05 13:57
@hahaxd35 You should use `documentserver-prepare4shutdown.sh` before `supervisorctl stop all`
I think `supervisorctl stop all` not needed at all

**Comment by hahaxd35** [comment] 2019-08-05 14:58
Maybe i know the reason....
redis got some security updates:
https://www.debian.org/security/2019/dsa-4480

and maybe apt restart/stop redis service 

Redis Log:

`HERE i execute : documentserver-prepare4shutdown.sh`

1020:M 05 Aug 16:39:05.443 # User requested shutdown...
1020:M 05 Aug 16:39:05.443 * Saving the final RDB snapshot before exiting.
1020:signal-handler (1565015945) Received SIGTERM scheduling shutdown...
1020:M 05 Aug 16:39:05.581 * DB saved on disk
1020:M 05 Aug 16:39:05.582 * Removing the pid file.
1020:M 05 Aug 16:39:05.582 # Redis is now ready to exit, bye bye...
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 18581
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

18581:M 05 Aug 16:39:05.954 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18581:M 05 Aug 16:39:05.954 # Server started, Redis version 3.2.6
18581:M 05 Aug 16:39:05.954 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
18581:M 05 Aug 16:39:05.954 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18581:M 05 Aug 16:39:05.954 . Unrecognized RDB AUX field: 'redis-ver'
18581:M 05 Aug 16:39:05.954 . Unrecognized RDB AUX field: 'redis-bits'
18581:M 05 Aug 16:39:05.955 . Unrecognized RDB AUX field: 'ctime'
18581:M 05 Aug 16:39:05.955 . Unrecognized RDB AUX field: 'used-mem'
18581:M 05 Aug 16:39:05.957 * DB loaded from disk: 0.002 seconds
18581:M 05 Aug 16:39:05.957 * The server is now ready to accept connections on port 6379
18581:M 05 Aug 16:39:05.957 - DB 0: 2 keys (0 volatile) in 4 slots HT.
18581:M 05 Aug 16:39:05.957 - 0 clients connected (0 slaves), 1703544 bytes in use
18581:M 05 Aug 16:39:06.134 - Accepted 127.0.0.1:54030
18581:M 05 Aug 16:39:06.135 - Accepted 127.0.0.1:54032
18581:M 05 Aug 16:39:06.138 - Accepted 127.0.0.1:54034
18581:M 05 Aug 16:39:06.138 - Accepted 127.0.0.1:54036
18581:M 05 Aug 16:39:10.969 - DB 0: 2 keys (0 volatile) in 4 slots HT.
18581:M 05 Aug 16:39:10.987 - 4 clients connected (0 slaves), 1787000 bytes in use
{..........}
18581:M 05 Aug 16:43:06.717 - DB 0: 2 keys (0 volatile) in 4 slots HT.
18581:M 05 Aug 16:43:06.717 - 4 clients connected (0 slaves), 1786000 bytes in use

`HERE i have Killed shutdown.js `

18581:signal-handler (1565016186) Received SIGTERM scheduling shutdown...
18581:signal-handler (1565016186) Received SIGTERM scheduling shutdown...
18581:M 05 Aug 16:43:06.918 # User requested shutdown...
18581:M 05 Aug 16:43:06.918 * Saving the final RDB snapshot before exiting.
18581:M 05 Aug 16:43:07.060 * DB saved on disk
18581:M 05 Aug 16:43:07.060 * Removing the pid file.
18581:M 05 Aug 16:43:07.060 # Redis is now ready to exit, bye bye...
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 23957
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

23957:M 05 Aug 16:48:54.587 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
23957:M 05 Aug 16:48:54.587 # Server started, Redis version 3.2.6
23957:M 05 Aug 16:48:54.588 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
23957:M 05 Aug 16:48:54.588 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
23957:M 05 Aug 16:48:54.588 . Unrecognized RDB AUX field: 'redis-ver'
23957:M 05 Aug 16:48:54.588 . Unrecognized RDB AUX field: 'redis-bits'
23957:M 05 Aug 16:48:54.588 . Unrecognized RDB AUX field: 'ctime'
23957:M 05 Aug 16:48:54.588 . Unrecognized RDB AUX field: 'used-mem'
23957:M 05 Aug 16:48:54.590 * DB loaded from disk: 0.002 seconds
23957:M 05 Aug 16:48:54.590 * The server is now ready to accept connections on port 6379
23957:M 05 Aug 16:48:54.590 - DB 0: 2 keys (0 volatile) in 4 slots HT.
23957:M 05 Aug 16:48:54.590 - 0 clients connected (0 slaves), 1703544 bytes in use
23957:M 05 Aug 16:48:54.820 - Accepted 127.0.0.1:54264
23957:M 05 Aug 16:48:54.865 - Accepted 127.0.0.1:54266
23957:M 05 Aug 16:48:55.188 - Accepted 127.0.0.1:54268
23957:M 05 Aug 16:48:56.103 - Accepted 127.0.0.1:54282
23957:M 05 Aug 16:48:59.617 - DB 0: 2 keys (0 volatile) in 4 slots HT.
23957:M 05 Aug 16:48:59.617 - 4 clients connected (0 slaves), 1787048 bytes in use
{...............}
23957:M 05 Aug 16:52:20.324 - DB 0: 2 keys (0 volatile) in 4 slots HT.
23957:M 05 Aug 16:52:20.328 - 4 clients connected (0 slaves), 1787328 bytes in use

**Comment by ShockwaveNN** [comment] 2019-08-05 15:15
I just checked execution of `documentserver-prepare4shutdown.sh` with stopped redis and everything seems fine. 
Maybe upgrade started during some transaction, but I'm not sure we can fix this issue if we have no exact scenario

**Comment by hahaxd35** [comment] 2019-08-05 15:27
maybe this is a case specific problem while upgrade redis and onlyoffice at ones so prepare4shutdown.sh conflict with apt-get 

so next try:
apt(-get) install --only-upgrade onlyoffice-documentserver
and then 
apt upgrade (for redis server)

**Comment by ShockwaveNN** [comment] 2019-08-05 15:58
@hahaxd35 I think your variant is fine, but I think easier to remember to run `documentserver-prepare4shutdown.sh` first and after that run `apt upgrade`

**Comment by hahaxd35** [comment] 2019-08-06 07:40
`apt update; documentserver-prepare4shutdown.sh  && apt-get install --only-upgrade onlyoffice-documentserver-de (&& apt upgrade) `
Work in this case the problem was that redis was upgraded to 
Maybe you can put this into https://helpcenter.onlyoffice.com/server/linux/document/upgrade-document.aspx

**Comment by ShockwaveNN** [comment] 2019-08-06 08:09
@hahaxd35 I'm not sure this problem will be actual if commands will be executed in exact order as in instruction, I monitor this issue if anyone will have same problem and if there is several cases of it - we update instruction.

**Comment by ShockwaveNN** [comment] 2022-07-04 07:18
I'll close this isue since we didn't find a way to reproduce it and it was quite a long time ago

**Closed by ShockwaveNN** 2022-07-04 07:18 UTC
Labels: question
