### ISSUE TITLE
documentserver-generate-allfonts.sh Generates Wrong Font Family Name

### ISSUE THREAD

**Issue by shenhf** [ONLYOFFICE/DocumentServer#360] opened 2018-08-07 16:06 UTC
For those Font Family Name are multi-byte charactors, Generated AllFonts.js presents garbage char: 

```
window["__fonts_files"] = [
"001",
"000"
];

window["__fonts_infos"] = [
["??",1,0,-1,-1,-1,-1,-1,-1],
["????",0,0,-1,-1,-1,-1,-1,-1],
["WenQuanYi Micro Hei Mono",0,1,-1,-1,-1,-1,-1,-1]
];

window["__fonts_ranges"] = [
0,0,1,8,9,1,13,13,1,29,29,1,32,126,1,128,383,1,402,402,1,416,417,1,431,432,1,462,462,1,$

window["g_fonts_selection_bin"] = "AwAAACgAAABXAGUAbgBRAHUAYQBuAFkAaQAgAE0AaQBjAHIAbwAg$

```

Here is font name table:
```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.24">

  <name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x804">
      字体数据由北京中易中标电子信息技术有限公司提供。
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x804">
      黑体
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x804">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x804">
      黑体
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x804">
      黑体
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x804">
      Version 5.03
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x804">
      黑体
    </namerecord>
    <namerecord nameID="7" platformID="3" platEncID="1" langID="0x804">
      Trademark of ZHONGYI Electronic Co., Beijing
    </namerecord>
  </name>

</ttFont>
```

**Comment by ShockwaveNN** [comment] 2018-08-08 07:27
What is the font for which such thing happened? Could you link it?

**Comment by shenhf** [comment] 2018-08-11 02:45
@ShockwaveNN Thanks for reply. I found all the Chinese fonts have the problem. Here is  one of fonts link in Github. [SimHei Font File URL](https://github.com/StellarCN/scp_zh/blob/master/fonts/SimHei.ttf)

**Comment by ShockwaveNN** [comment] 2018-08-13 07:26
@shenhf Just tried on current stable docker image 
and AllFonts.js correctly contains
`["SimHei", 0, 0, -1, -1, -1, -1, -1, -1]`
Which OS and distribution are your using, also specify exact version of DocumentServer

**Comment by ShockwaveNN** [comment] 2018-08-14 06:50
@shenhf ok, I understand you. This is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/332
Correct me if I wrong

**Closed by ShockwaveNN** 2018-08-14 06:50 UTC
