### ISSUE TITLE
Spellchecker not working after upgrade to 5.5.0

### ISSUE THREAD

**Issue by kruthoff** [ONLYOFFICE/DocumentServer#810] opened 2020-03-14 22:03 UTC
This looks like a bug. I've upgraded to 5.5.0 today, and the spellchecker isn't working since then. The upgrade went without issues. I'm able to edit documents, but the spellchecker isn't running anymore (see logs below).

I'm running on linux mint 19.1 (ubuntu bionic), 5.3.0-40-generic #32~18.04.1-Ubuntu

The first few lines show the old version where everything was ok. After the upgrade at around 16:27, the spellcheck process starts and dies immediately.

err.log shows issues with node version?!

In 5.5.0 the spellchecker node modules can't be rebuilt, as the nodejs dependency was removed. spellchecker runs on its own.
[spellchecker-out.log](https://github.com/ONLYOFFICE/DocumentServer/files/4333391/spellchecker-out.log)
[spellchecker-err.log](https://github.com/ONLYOFFICE/DocumentServer/files/4333392/spellchecker-err.log)

Any help to resolve this issue is much appreciated.

**Comment by ShockwaveNN** [comment] 2020-03-16 08:47
@kruthoff Seems something went wrong during update, in 5.5.0 spellchecker (or any DocumentServer services) do not require nodejs to be presence, hence there should be no NODE_MODULE_VERSION error

Could you show me content of `/etc/supervisor/conf.d/ds-spellchecker.conf` - this file configure spellchecker service to start

**Comment by kruthoff** [comment] 2020-03-16 09:09
`[program:spellchecker]
command=/var/www/onlyoffice/documentserver/server/SpellChecker/spellchecker
directory=/var/www/onlyoffice/documentserver/server/SpellChecker
user=ds
environment=NODE_ENV=production-linux,NODE_CONFIG_DIR=/etc/onlyoffice/documentserver,NODE_DISABLE_COLORS=1
stdout_logfile=/var/log/onlyoffice/documentserver/spellchecker/out.log
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/onlyoffice/documentserver/spellchecker/err.log
stderr_logfile_backups=0
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
`

**Comment by ShockwaveNN** [comment] 2020-03-16 09:28
Everything seems fine

Try this:
```
supervisorctl stop ds:spellchecker
cd /var/www/onlyoffice/documentserver/server/SpellChecker
NODE_ENV=production-linux NODE_CONFIG_DIR=/etc/onlyoffice/documentserver ./spellchecker
```
This should run spellchecker service in foreground without any errors

**Comment by kruthoff** [comment] 2020-03-16 10:30
It shows the same errors as in the err.log

**Comment by ShockwaveNN** [comment] 2020-03-16 10:46
Hm, try to remove nodejs from your system, maybe this helps.

Is there any way you can share some kind of Docker image or VM image with this problem reproduced?

**Comment by kruthoff** [comment] 2020-03-16 11:29
I've purged nodejs. It didn't help. My installation is standard, based on [https://helpcenter.onlyoffice.com/de/server/linux/document/linux-installation.aspx]. I've upgraded from the previous version as described in that link. I don't have an image, unfortunately.

**Comment by kruthoff** [comment] 2020-03-16 11:32
From the error message: the 'node_modules' directory contains a 'nodehun.node' module which doesn't match. node_modules was from previous 5.4, I assume. The version mismatch is there.

**Comment by ShockwaveNN** [comment] 2020-03-16 11:55
@kruthoff Is there other files in `node_modules` exept this:
![image](https://user-images.githubusercontent.com/668524/76756048-0da69e00-6796-11ea-94bc-a34e5440cbba.png)

If there is no other files what is control sum of this file?
Correct is:
```
root@0761f88a0521:/# sha256sum /var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node 
4424817451f10a0b59e512c820c84e827a2b6243e6211c38f526a45416b76c1e  /var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node
```

**Comment by ShockwaveNN** [comment] 2020-03-16 12:06
I just checked update from 5.4.2 to 5.5.0 and commands listed [here](https://github.com/ONLYOFFICE/DocumentServer/issues/810#issuecomment-599432058) are working fine

**Comment by kruthoff** [comment] 2020-03-16 12:31
Different checksum. All files in node_modules are from Jul 12 2019. It looks like they weren't replaced?!

**Comment by kruthoff** [comment] 2020-03-16 12:41
To me it looks like Issue 312, but I can't rebuild the modules as the package.json isn't available anymore. :-(

**Comment by ShockwaveNN** [comment] 2020-03-16 13:08
> It looks like they weren't replaced?!

Seems so

> To me it looks like Issue 312

I don't think so, since 5.5.0 there is no need to rebuild anything.

So I think you should replace incorrect file by commands like this:
```
cd /tmp
wget https://github.com/ONLYOFFICE/DocumentServer/releases/download/ONLYOFFICE-DocumentServer-5.5.0/onlyoffice-documentserver_amd64.deb
dpkg-deb -xv onlyoffice-documentserver_amd64.deb /tmp/
cp /tmp/var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node /var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node

**Comment by kruthoff** [comment] 2020-03-16 13:38
Spellchecker is working!

**Comment by ShockwaveNN** [comment] 2020-03-16 13:42
@kruthoff Glad to hear. So I think I'll close this issue until someone can provide step-by-step instruction how spellchecker files are not replaced after upgrade

**Closed by ShockwaveNN** 2020-03-16 13:42 UTC

**Comment by kruthoff** [comment] 2020-03-16 17:31
[apt-term.log](https://github.com/ONLYOFFICE/DocumentServer/files/4339507/apt-term.log)
Here's my apt log from the upgrade, maybe it helps. I don't see any node_modules related log statements...

**Comment by ShockwaveNN** [comment] 2020-03-17 08:12
@kruthoff yep, everything seems fine
