### ISSUE TITLE
table review   cannot reject and accept

### ISSUE THREAD

**Issue by alexzzn** [ONLYOFFICE/DocumentServer#2425] opened 2023-10-16 15:23 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1

### Expected Behavior

The reviews in Table can accept or reject, expect accept cannot take effect
<img width="817" alt="iShot_2023-10-16_23 12 42" src="https://github.com/ONLYOFFICE/DocumentServer/assets/41319735/1c3e7945-dd01-49ae-a5c8-d75629384621">

### Actual Behavior

The reviews in Table can accept or reject, 

### Reproduction Steps

1,  open word document
2，set track changes true
3，insert a new Table
4，add text in Table cell and press enter，
5，click accept and reject no effect

**Comment by maruacat** [comment] 2023-10-20 12:13
Hello @alexzzn 
Thank you for your message.
I was able to reproduce the issue in version 7.4.1.36, but it doesn't reproduce in the new version 7.5.0.127
Please could you update editor to version 7.5.0 and check if the problem is reproduced?

**Comment by alexzzn** [comment] 2023-10-26 01:08
This issue was fixed after update 7.5

**Comment by Rita-Bubnova** [comment] 2023-10-27 11:30
@alexzzn thank you.
 I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-27 11:30 UTC
Labels: confirmed-bug, fixed
