### ISSUE TITLE
PDF documents open without annotations

### ISSUE THREAD

**Issue by jfzhangak** [ONLYOFFICE/DocumentServer#1025] opened 2020-10-16 08:23 UTC
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
PDF documents open without annotations
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add annotations to PDF documents, but opening annotations with OnlyOffice does not show
**What is the expected behavior?**
You can add annotations to PDF documents
**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
5.5.3
**Operating System:**
windows10
**Browser version:**

**Comment by Rita-Bubnova** [comment] 2020-10-16 10:21
Hello, @jfzhangak.
Can you attach PDF file with annotations?

**Comment by jfzhangak** [comment] 2020-10-19 07:28
[PDFfeil.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/5399864/PDFfeil.pdf)

**Comment by Rita-Bubnova** [comment] 2020-10-19 09:27
Duplicate of #https://github.com/ONLYOFFICE/DesktopEditors/issues/418.

**Closed** 2020-10-19 09:44 UTC
Labels: duplicate
