### ISSUE TITLE
Selected column crashes when trying to move it.

### ISSUE THREAD

**Issue by saitam1** [ONLYOFFICE/DocumentServer#392] opened 2018-09-13 09:27 UTC
Bug Report: Selected column crashes when trying to move it.

Steps to reproduce:
Open a new spreadsheet and select a whole column by clicking on e.g. A, B, C or D. 
Now move the mouse between the selected column and the columns next to it. Now grab the selected column and try to move it!

Version is: ONLYOFFICE Desktop Editors version 5.1.29.350

OS is: Ubuntu 18.04.1

**Comment by Rita-Bubnova** [comment] 2018-09-13 09:41
Hello, @saitam1.
Thank you. I can confirm - this is a known bug, issue 38754 in our internal tracker problem.

**Comment by Rita-Bubnova** [comment] 2018-09-13 10:05
The problem is actual on the current stable version of the DocumentServer (5.1.5 (build: 59)).

**Comment by Rita-Bubnova** [comment] 2018-09-18 10:36
Your issue fixed in https://github.com/ONLYOFFICE/sdkjs/commit/bc62cecf909cd9f73a6545a546a31a483aea8c6f and will be released as 5.2 in several weeks.
Later will be released version ONLYOFFICE Desktop Editors with this fixes.

**Comment by ShockwaveNN** [comment] 2018-09-28 14:38
DocumentServer 5.2.0 released
Issue should be fixed

**Closed by ShockwaveNN** 2018-09-28 14:38 UTC
Labels: bug, fixed
