### ISSUE TITLE
In the process of saving, open the file and lose the collaboration.

### ISSUE THREAD

**Issue by wdan-code** [ONLYOFFICE/DocumentServer#1782] opened 2022-06-07 08:56 UTC
onlyoffice version is onlyoffice/documentserver:7.0

The following scenarios:
A. B user cooperates to operate the same document x (corresponding key_x1)
1. When both a and B close the browser after editing, file saving will be triggered
2. When file x is saved: user a opens document x (corresponding key_x1)
3. When the file x is saved: user B opens the document x (corresponding key_x2)

You will encounter one tips：
![image](https://user-images.githubusercontent.com/30569668/172339825-5b35fcad-294e-4a30-9960-b250420b136f.png)

The following error messages will appear in the onlyoffice log：
![image](https://user-images.githubusercontent.com/30569668/172338456-cb9bc3f3-688f-46ba-94c7-7716863ae05c.png)

`[2022-06-07T08:37:15.660] [ERROR] nodeJS - sendServerRequest error: docId = 7595972034770622549;url = http://192.168.23.64:9528/track?filename=new.xlsx&userAddress=192.168.23.70;data = {"key":"7595972034770622549","status":2,"url":"http://192.168.23.64:9527/cache/files/7595972034770622549_2349/output.xlsx/output.xlsx?md5=vWi1OlVabUyv5RcqB9kIgQ&expires=1654591926&filename=output.xlsx","changesurl":"http://192.168.23.64:9527/cache/files/7595972034770622549_2349/changes.zip/changes.zip?md5=UFr9BWJmUvinJoz9Hqsa1g&expires=1654591926&filename=changes.zip","history":{"serverVersion":"7.0.1","changes":[{"created":"2022-06-07 08:36:24","user":{"id":"uid-1","name":"John Smith"}},{"created":"2022-06-07 08:36:32","user":{"id":"uid-1653965351931","name":"when (来宾)"}}]},"users":["uid-1653965351931"],"actions":[{"type":0,"userid":"uid-1"}],"lastsave":"2022-06-07T08:36:32.000Z","notmodified":true,"filetype":"xlsx"}
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:519:28)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:484:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[2022-06-07T08:37:15.660] [WARN] nodeJS - commandSfcCallback backoff limit exceeded: docId = 7595972034770622549
[2022-06-07T08:37:15.662] [WARN] nodeJS - storeForgotten: docId = 7595972034770622549
[2022-06-07T08:38:55.968] [ERROR] nodeJS - sendServerRequest error: docId = 6392285453467093956;url = http://192.168.23.64:9528/track?filename=new.xlsx&userAddress=192.168.23.70;data = {"key":"6392285453467093956","status":2,"url":"http://192.168.23.64:9527/cache/files/6392285453467093956_9429/output.xlsx/output.xlsx?md5=8bruswa1PxsXKK5cYOhudw&expires=1654592026&filename=output.xlsx","changesurl":"http://192.168.23.64:9527/cache/files/6392285453467093956_9429/changes.zip/changes.zip?md5=Vfs3L19mU-8Rz1HEoisH1g&expires=1654592026&filename=changes.zip","history":{"serverVersion":"7.0.1","changes":[{"created":"2022-06-07 08:38:12","user":{"id":"uid-1","name":"John Smith"}},{"created":"2022-06-07 08:38:26","user":{"id":"uid-1653965351931","name":"when (来宾)"}}]},"users":["uid-1653965351931"],"actions":[{"type":0,"userid":"uid-1"}],"lastsave":"2022-06-07T08:38:26.000Z","notmodified":true,"filetype":"xlsx"}
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:519:28)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:484:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)`

**After that, there will be occasional lack of collaboration and data coverage problems.**

**Comment by DenisDeeSign** [comment] 2022-06-07 09:48
Moving this issue to DocumentServer repo, since the issue in not related to CommunityServer.

**Comment by TatianaKirillova** [comment] 2022-06-07 10:42
Hello, @wdan-code! What Document Manager Server are you using?

**Comment by wdan-code** [comment] 2022-06-07 12:14
> Hello, @wdan-code! What Document Manager Server are you using?
Use the official Python version demo.
https://api.onlyoffice.com/app_data/editor/Python%20Example.zip

**Comment by wdan-code** [comment] 2022-06-07 16:01
> Document Manager Server

This is an extreme scene, which is difficult to reproduce. You need to add hibernation in the document manager server to increase the recurrence probability.
In the document manager server, when the data return status=2, I add a 10s sleep. During the sleep, user a opens file X; Wait until hibernation is completed, and user B opens file X. at this time, there is a probability that there will be a problem of non collaboration.
I operate 10 times and repeat 2 times.

**Comment by wdan-code** [comment] 2022-06-07 16:07
> > Document Manager Server
> 
> This is an extreme scene, which is difficult to reproduce. You need to add hibernation in the document manager server to increase the recurrence probability. In the document manager server, when the data return status=2, I add a 10s sleep. During the sleep, user a opens file X; Wait until hibernation is completed, and user B opens file X. at this time, there is a probability that there will be a problem of non collaboration. I operate 10 times and recurrent 2 times.

**Comment by ShockwaveNN** [comment] 2022-06-07 16:12
> You need to add hibernation in the document manager server to increase the recurrence probability.

If this case is difficult you got two option

1. Provide exact step-by-step guide how to reproduce this issue on nodejs example
2. Provide your full code for python including 
>You need to add hibernation in the document manager server to increase the recurrence probability. 

I'm not sure that we got enough free resources to properly look in that complicated case in other case

**Closed** 2022-06-11 11:06 UTC
