### ISSUE TITLE
Page numbers in presentations

### ISSUE THREAD

**Issue by romansimakov** [ONLYOFFICE/DocumentServer#397] opened 2018-10-03 18:30 UTC
I cannot find how I can do it and related description in help. I've found it only for document editor.

**Comment by ShockwaveNN** [comment] 2018-10-04 07:13
Duplicate of #245
This feature is not implemented

**Closed by ShockwaveNN** 2018-10-04 07:13 UTC

**Comment by romansimakov** [comment] 2018-10-04 09:21
Sorry, I did not find related issue and opened new one. I've subscribed to it. Thanks.
