### ISSUE TITLE
Lost files ..

### ISSUE THREAD

**Issue by ManuelRighi** [ONLYOFFICE/DocumentServer#229] opened 2017-12-22 08:35 UTC
Hello,
I have OnlyOffice Document Server version 4.4.3-7 installed on Ubuntu Server 16.04 LTS.
This is integrated with my owncloud version 10.0.2 with app OnlyOffice versione 1.1.6.
Today my all xlsx documents are empty.
I see thath onlyoffice document server never update my physical files in the owncloud, but I think save xlsx files only on the document server.

I need to restore files ...

Can you help me ?
Thanks
Manuel

**Comment by alexanderonlyoffice** [comment] 2017-12-22 08:54
Duplicate of #https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/140

**Closed by alexanderonlyoffice** 2017-12-22 08:54 UTC
