### ISSUE TITLE
OnlyOffice document doesn't fully support Khmer Unicode

### ISSUE THREAD

**Issue by kuyseng** [ONLYOFFICE/DocumentServer#732] opened 2020-01-02 03:09 UTC
I try to install "fonts-khmeros" 

`apt-get install fonts-khmeros` and run
`./documentserver-generate-allfonts.sh`

But I still cannot see correct Khmer font.

Let see the text in the document 
![image](https://user-images.githubusercontent.com/771344/71650298-8d9c9a80-2d47-11ea-99b7-16c9cbd6c3a8.png)

The text should be like this: 
ប្រាសាទ​​ អង្គរវត្ត​​ ស្ថិតនៅក្នុងប្រទេសកម្ពុជា

DocumentServer version: 5.4.2.46
I use docker image: onlyoffice/documentserver

**Comment by Rita-Bubnova** [comment] 2020-01-09 10:07
Hello, @kuyseng.
This problem is related to the lack of support for ligatures. Issue 38300 in our private tracker.

**Comment by kuyseng** [comment] 2020-01-10 01:40
@Rita-Bubnova Well noted. Thanks for your reply

**Comment by ramezrafla** [comment] 2020-01-20 02:10
@Rita-Bubnova 
It seems that in order to support ligatures you need to render text in words (or sentences) vs characters. Am I correct in identifying it as the underlying issue?

**Comment by K0R0L** [comment] 2020-01-20 07:42
ONLYOFFICE does not support ligatures. What are ligatures can be read on the internet).

**Comment by ramezrafla** [comment] 2020-01-20 07:47
@K0R0L 

Thanks for your reply

ONLYOFFICE indeed does not support ligatures. We are looking for ways to fix that so we can support Arabic, Hebrew etc.

I was looking at the code, the root cause seems to me that you render letter by letter. If that is the case there are ways to support ligatures by forcing the proper ligature character from the character map.

Can you please confirm that the root cause is the character-by-character rendering?

Thanks

**Comment by ramezrafla** [comment] 2020-01-20 07:50
@ShockwaveNN -- thanks for the label

Can you connect us with a developer who handles rendering? We may be able to support this effort that is preventing RTL

Thanks

**Comment by ShockwaveNN** [comment] 2020-01-20 07:56
@ramezrafla @K0R0L is developer who handles rendering

**Comment by ramezrafla** [comment] 2020-01-20 07:59
@ShockwaveNN  
Thanks for the quick reply

Looking forward to @K0R0L 's reply

**Comment by brandnewx** [comment] 2020-02-14 04:22
Well, what a bummer.

**Comment by TatianaKirillova** [comment] 2022-07-12 13:36
The bug will be fixed in the next major release

**Comment by ItsSunnyMonster** [comment] 2022-08-16 05:55
@TatianaKirillova When is the next major release going to be released?

**Comment by ShockwaveNN** [comment] 2022-08-16 05:59
@ItsSunnyMonster Sorry, we don't have exact date but probably around next month, but we cannot guarantee it

**Comment by ShockwaveNN** [comment] 2022-09-23 16:14
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Closed by ShockwaveNN** 2022-09-23 16:14 UTC
Labels: bug, fixed
