### ISSUE TITLE
Paste as plain text

### ISSUE THREAD

**Issue by alexeyvolkoff** [ONLYOFFICE/DocumentServer#2404] opened 2023-09-29 07:58 UTC
Editor lacks 'Paste as plain text' menu option. It makes it hard to keep the formatting clean when pasting text from other documents

**Comment by DenisDeeSign** [comment] 2023-10-02 12:23
Moving this issue to DocumentServer repo, since the issue is not related to CommunityServer.

**Comment by alexeyvolkoff** [comment] 2023-10-03 10:38
Yes. Is it already solved?

**Comment by ElenaMaaya** [comment] 2023-10-03 11:17
Hello @alexeyvolkoff!
The actual keyboard shortcuts for “Insert text without style formatting” are Ctrl+⇧ Shift+V.
Thank you for reaching out and have a nice day!

PS This is fixed in DocumentServer and DesktopEditors v7.4.1.

**Comment by Rita-Bubnova** [comment] 2023-10-03 11:28
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-03 11:28 UTC
Labels: duplicate
