### ISSUE TITLE
Locked cells in protected sheet is not working

### ISSUE THREAD

**Issue by kylianbrun** [ONLYOFFICE/DocumentServer#2230] opened 2023-05-04 13:51 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3.3.49

### Expected Behavior

I expect a locked cell to be not editable when the sheet is protected

### Actual Behavior

When I lock a cell inside a protected sheet, I can edit the cell.
When I export the file and open it in Excel, I don't have the same problem so I think its from OnlyOffice.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/59508914/236226613-b5dd4e1a-921e-42c0-bc03-fc2b4f1d0b7b.png">
<img width="157" alt="image" src="https://user-images.githubusercontent.com/59508914/236226772-e944976c-8da4-49a4-81cd-b0e93a58534f.png">

### Reproduction Steps

- Open a xlsx file
- Lock some cells
- Protect the sheet
- Try to edit a locked cell

**Comment by rsnegirev** [comment] 2023-05-10 10:54
Hi @kylianbrun 

We've reproduced the same correct behavior in Excel and OnlyOffice.

Could you please provide more detailed steps or attach an example file?

**Comment by kylianbrun** [comment] 2023-05-18 08:07
Hello @rsnegirev !

With the same file (opened into OnlyOffice & download from OpenOffice and opened into Excel) I have two differents behavior.

In OnlyOffice, I can edit the locked cells but not in Excel.

**Comment by rsnegirev** [comment] 2023-05-24 12:58
As we said, we cannot reproduce your problem with the following steps:
1. Open a xlsx file
2. Lock some cells
3. Protect the sheet
4. Try to edit a locked cell

After step 4 we can't edit locked sells, as it should be.

So, can you just provide an example file?

**Comment by trofim24** [comment] 2023-08-18 08:35
@kylianbrun can you provide an example file whithout personal data ?
If there is no responce within 30 days, we will be forced to close this issue

Thanks for understanding

**Comment by Rita-Bubnova** [comment] 2023-10-10 15:57
This issue was closed due no response.

**Closed** 2023-10-24 10:47 UTC
