### ISSUE TITLE
Animating Objects in presentation

### ISSUE THREAD

**Issue by Peter-YAN** [ONLYOFFICE/DocumentServer#1330] opened 2021-07-08 01:24 UTC
Cannot find Animating Objects in presentation to add animate text or objects.
Is there any solution?

**Comment by ShockwaveNN** [comment] 2021-07-08 07:06
Sorry, animations is not implemented

Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/348

**Closed by ShockwaveNN** 2021-07-08 07:06 UTC
Labels: duplicate
