### ISSUE TITLE
Chinese italic text loose italic style on some zoom levels

### ISSUE THREAD

**Issue by huisnotacouncillor** [ONLYOFFICE/DocumentServer#1104] opened 2020-12-17 12:50 UTC
**Do you want to request a *feature* or report a *bug*?**
 Bug
**What is the current behavior?**
The Chinese can not be italicized.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The font size is less than 12,  The Chinese text cannot be italicized. When the font size is more than 12, it can be italicized, also when the context is set bold, it can be italicized.  But printing preview, it displays normal.

As so far, I have tested it on many fonts, such as Calibri,  Consolas, Impact and so on, in .docx, .xls, .pptx file

**What is the expected behavior?**
The Chinese text can be displayed normal on each font.

**Did this work in previous versions of DocumentServer?**
 I'm not sure， only test it on Version 5.5.3

**DocumentServer version:**
Version 5.5.3

**Operating System:**
Windows

**Browser version:**
Latest Chrome

**Comment by ShockwaveNN** [comment] 2020-12-17 12:53
> DocumentServer version:
> Version 5.5.3

This is pretty old version of DocumentServer, and we do not support it, could you try to upgrade to 6.1 and check for your problem again

**Comment by huisnotacouncillor** [comment] 2020-12-17 12:59
Hi, I just test it on your website, The Chinese cannot be italic too as i described above.
The address is https://api.onlyoffice.com/editors/editor?method=docxEditor

**Comment by ShockwaveNN** [comment] 2020-12-17 13:00
@huisnotacouncillor Ok in that case I'll need exact font you're using and some example chinese words which correctly can be italized in other apps, since my knowledge in chinese are zero

**Comment by huisnotacouncillor** [comment] 2020-12-17 13:03
[test.docx](https://github.com/ONLYOFFICE/DocumentServer/files/5709618/test.docx)
Here you are.

**Comment by ShockwaveNN** [comment] 2020-12-17 13:10
I've copied content of this document to https://api.onlyoffice.com/editors/editor?method=docxEditor
And everything is fine with italic variant of text:
![image](https://user-images.githubusercontent.com/668524/102492177-5c18fe00-4082-11eb-9b0a-5946cf500cb0.png)
Font size is 10 for last line

**Comment by huisnotacouncillor** [comment] 2020-12-17 13:15
It's quite strange.
![image](https://user-images.githubusercontent.com/45624731/102492634-efffbf80-40ac-11eb-9883-e94ed8b7bc96.png)

**Comment by huisnotacouncillor** [comment] 2020-12-17 13:17
It's quite strange.
![image](https://user-images.githubusercontent.com/45624731/102492888-4a008500-40ad-11eb-83c6-47670f0a934c.png)

**Comment by huisnotacouncillor** [comment] 2020-12-17 13:21
Hi, when I zoom up, it becomes normal
![image](https://user-images.githubusercontent.com/45624731/102493195-cbf0ae00-40ad-11eb-8db8-904d42725fe6.png)

**Comment by ShockwaveNN** [comment] 2020-12-17 13:22
@huisnotacouncillor Yeah, I was able to reproduce your problem. For me in zoom 70% font is italized, but in zoom 60% font is not

**Comment by huisnotacouncillor** [comment] 2020-12-17 13:23
Aright, thank you very much.

**Comment by huisnotacouncillor** [comment] 2020-12-17 13:26
I am not sure, is it a bug?

**Comment by ShockwaveNN** [comment] 2020-12-17 13:49
@huisnotacouncillor Yeah, there is something wrong definitely

I've created an issue 48051 in our private issue tracker

**Comment by ShockwaveNN** [comment] 2020-12-17 14:00
Oh, @huisnotacouncillor thank you for this bug, this is very interesting situation

**Comment by ElenaMaaya** [comment] 2024-09-27 09:29
Hello, @huisnotacouncillor! This issue was fixed in version 8.1. 
If the problem persists, please write here again. 
Have a good day!

**Comment by Rita-Bubnova** [comment] 2024-09-27 09:32
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-09-27 09:32 UTC
Labels: confirmed-bug, fixed
