### ISSUE TITLE
Abnormal display of document title serial number in version 7.4.0

### ISSUE THREAD

**Issue by xsirl** [ONLYOFFICE/DocumentServer#2273] opened 2023-06-19 03:17 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.4.0.163

### Expected Behavior

The left title bar displays' 1.Title 1 '

### Actual Behavior

The left title bar displays "1.1. Title 1", with duplicate serial numbers.
![Snipaste_2023-06-19_10-51-35](https://github.com/ONLYOFFICE/DocumentServer/assets/54919759/26093f8c-3b49-4130-9fe8-c886187ef49f)

### Reproduction Steps

1. Select the style 'Heading 1'
2. Select a number
3. Enter any content

### Additional information

The left title bar is displayed normally in version 7.3.0, but there is a problem of duplicate title numbers after upgrading to 7.4.0. By the way, the desktop version is also like this

**Comment by TatianaKirillova** [comment] 2023-06-19 11:50
Hello, @xsirl
Thanks for your request!
I can confirm that the problem exists. I created ticket 63079 in our internal  tracker with your  issue

**Comment by HectorB-2020** [comment] 2023-06-24 19:46
I'm not sure if it's the same issue but at least it looks like an issue reported for previous versions.
* https://github.com/ONLYOFFICE/DesktopEditors/issues/1099

**Comment by Rita-Bubnova** [comment] 2023-07-21 14:31
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/66ea16683e83459d1704f23fc9919e7a381c82e7) in future major release.

**Comment by HectorB-2020** [comment] 2023-07-21 16:17
Do you refer to v7.5?

**Comment by Rita-Bubnova** [comment] 2023-07-21 16:25
Probably this fix will be included in the next bugfix version.

**Comment by Rita-Bubnova** [comment] 2023-08-01 07:14
DocumentServer v7.4.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-01 07:14 UTC
Labels: bug, fixed
