### ISSUE TITLE
Document Bouncing When Editing A Shared Document

### ISSUE THREAD

**Issue by Farwalker3** [ONLYOFFICE/DocumentServer#1955] opened 2022-10-25 17:30 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package), Linux (RPM package), Docker

### Version information

7.2.1.36

### Expected Behavior

When editing a document, I want to be able to see what I'm editing. I don't want the document to start jumping up and down every time someone else on the document makes an edit.

### Actual Behavior

When editing a shared document, whenever someone makes an edit the document would jump to that edit. So, when working on a shared document with multiple people, the document is very jittery. It is constantly jumping up and down, making it feel like you are editing during an earthquake.

### Reproduction Steps

1) Share a document with multiple people using an external link
2) Set everyone's access (the shared external link) to full access
3) Have everyone edit the document at the same time live

**Comment by ShockwaveNN** [comment] 2022-10-26 06:44
Hi, could you record a video, not quite sure that are you talking about

And you can enable `Strict` co-edit mode in settings, so document is updated only then you've pressed save

**Comment by Farwalker3** [comment] 2022-10-27 21:15
https://user-images.githubusercontent.com/30270971/198399359-82b5d1d0-aa2f-47ab-9403-7f395eeb94df.mp4

I have attached a video. In the video I show how Strict co-edit mode works fine, but fast co-edit mode does not (and my team wants to use fast co-edit mode).

**Comment by XDmitryK** [comment] 2022-11-08 08:40
@Farwalker3 Thank you for report.
I can confirm - this is bug issue 59647 in our private issue tracker.

**Comment by slater0013** [comment] 2022-11-30 07:50
hello @XDmitryK,  enterprise edition under support contract is also concerned (deb version 7.2.1-34) ! Do you have any roadmap to communicate ? Very annoying bug for collaborating users !
GS

**Comment by mvvvmd** [comment] 2022-12-01 09:37
> hello @XDmitryK, enterprise edition under support contract is also concerned (deb version 7.2.1-34) ! Do you have any roadmap to communicate ? Very annoying bug for collaborating users ! GS

FYI, I have just reported this to OO support, we have a contract.

**Comment by kdaun** [comment] 2022-12-07 10:48
Hi @XDmitryK,
thanks for the great work, so far I loved working with OnlyOffice. However, for us, this is a breaking change that makes OnlyOffice unusable in our workflow and already lead to discussions about switching to other options.
I would strongly encourage to treat this bug with high priority.

**Comment by wu-lee** [comment] 2022-12-08 16:29
We've also been experiencing this, just as described, in OO 7.2.1.34, running under Ubuntu Linux 8.04.6 (using Cloudron app server v7.3.4), with recent versions of Firefox and Chrome as the client. It does make things very difficult in collaborative meetings!

**Comment by jens-br** [comment] 2022-12-13 16:33
> hello @XDmitryK, enterprise edition under support contract is also concerned (deb version 7.2.1-34) ! Do you have any roadmap to communicate ? Very annoying bug for collaborating users ! GS

Could anyone share some information on the plans for a possible fix? We would highly appreciate that, since for the moment, the multi-user mode of OnlyOffice is unusable for more than one person - and we need it for our daily work.
Thanks! 🙂

**Comment by cpot** [comment] 2022-12-13 17:17
**SHOWSTOPPER BUG CONFIRMED** : We are going to stop all Onlyoffice Enterprise/community upgrade to 7.4.1 due to this bug, **waiting a very quick 7.4.2 fix**

**Comment by trofim24** [comment] 2022-12-13 18:17
Sorry for that bug 
We've already fixed it in 7.2.2
We're going to release as soon as possible

**Comment by cpot** [comment] 2022-12-13 23:32
I imagine the bug severity has been misqualified at the beginning or misunderstood. We are lucky we discovered it before deploying 7.2.1 to our customer so no harm. However 7.2.1 was a lot expected for bug fixes in ODF format, so we are in an uncomfortable position to our customers, several paying the Enterprise edition. There should be a simple QA testcase for that. Fast mode is often what users wants and benchmark to Gdocs/Offline Online.  
On a side note, I am sure you have a test management platform, but we use testrail which is very good.

We really hope 7.2.2 will be released in the next few days, in fact the bug could be a release on its own. Thanks

**Comment by mvvvmd** [comment] 2022-12-20 13:28
Version 7.2.2 is available, tested and seems to resolve the issue for me.

**Comment by DenisDeeSign** [comment] 2022-12-20 13:32
Yes, DocumentServer v7.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2022-12-20 13:32 UTC
Labels: bug, fixed

**Comment by cpot** [comment] 2022-12-20 13:46
> Yes, DocumentServer v7.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

7.2.2 released

**Comment by DenisDeeSign** [comment] 2022-12-20 14:18
@cpot, thank you for the noticing.

**Comment by unteem** [comment] 2023-10-13 08:48
Hi. There is a regression, while this issues was fixed this bug is back.

We are using the version 7.3.3

**Comment by Rita-Bubnova** [comment] 2023-10-13 09:01
@unteem, DocumentServer v7.4.1 is released. Please state is this problem still actual for you?

**Comment by unteem** [comment] 2023-10-16 10:06
Hi @Rita-Bubnova, update to latest 7.4.1 still have the issue. I managed to identity better the issue. 

If I place my cursor somewhere, scroll up to another page to read and someone edits the document and make my cursor move it will scroll me down.

**Comment by unteem** [comment] 2023-10-16 10:11
Should I create another issue ?

**Comment by Rita-Bubnova** [comment] 2023-10-16 10:46
> Should I create another issue ?

Yes, please create new issue. Thank you for your research.
