### ISSUE TITLE
Error copying content from local document to onlyoffice [ERROR] nodeJS - changesError:Uncaught ReferenceError: node is not defined Script: https://documentServer/7.1.1-23/sdkjs/word/sdk-all.js Line: 5411:56

### ISSUE THREAD

**Issue by Promisefm** [ONLYOFFICE/DocumentServer#2349] opened 2023-08-21 06:47 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Docker

### Version information

Version: 7.1.1 (build:23)

### Expected Behavior

No matter where the content is copied, it should be pasted into onlyOffice normally. This was possible before

### Actual Behavior

An error occurred when copying local document content and pasting it into an online document in OnlyOffice
![Feige图片20230821143540](https://github.com/ONLYOFFICE/DocumentServer/assets/13003560/a5e24bdf-7815-4a8c-8bbe-252d6edc0dff)

### Reproduction Steps

Open an empty document that has been uploaded to the onlyOffice service.
Copy content from local documents.
Error reported by ctrl+c in an opened onlyOffice document

### Additional information

[ERROR] nodeJS - changesError: docId = -697939547 Error: Uncaught ReferenceError: node is not defined Script: https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js Line: 5411:56 userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 platform: Win32 isLoadFullApi: true isDocumentLoadComplete: true StackTrace: ReferenceError: node is not defined
    at Ja.plg (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5411:56)
    at Ja.amg (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5409:107)
    at Ja.Qlg (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5392:414)
    at Ja.hoe (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5416:37)
    at Ja.o4a (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5416:121)
    at b (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5448:226)
    at Ja.V$a (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5450:375)
    at Uc (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5441:170)
    at Ja.V$a (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5452:388)
    at Uc (https://192.168.100.110:9003/7.1.1-23/sdkjs/word/sdk-all.js:5441:170)
Blocked script execution in 'https://192.168.100.110:9003/7.1.1-23/web-apps/apps/documenteditor/main/index.html?_dc=7.1.1-23&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor}' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by Promisefm** [comment] 2023-08-21 08:39
If you clear the document format and paste the same content in the same document, there will be no error reported.

**Comment by LuckySpecialist** [comment] 2023-08-21 09:52
Hi @Promisefm, please update DocumentServer to the current version of the application (7.4.1) and check the behavior on it.
If the problem persists, describe in detail the copy source and data type in any example. If you attach a video with a demonstration of the problem or the source files on which the problem is reproduced, it will be easier to understand the cause.
We are only looking at issues for the current version currently in release.
Thanks for understanding.

**Comment by Promisefm** [comment] 2023-08-22 08:11
Here's the new issue [https://github.com/ONLYOFFICE/DocumentServer/issues/2352](url)

**Comment by Rita-Bubnova** [comment] 2023-08-22 08:56
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-22 08:56 UTC
