### ISSUE TITLE
Cannot paste into spreadsheet

### ISSUE THREAD

**Issue by rqtruong** [ONLYOFFICE/DocumentServer#1887] opened 2022-09-01 03:38 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
 Cannot Ctrl+V into cryptpad spreadsheet

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
    Go to Spreadsheet
    Copy text outside of browser
    Try to paste clipboard into spreadsheet cell
    It won't let you

**What is the expected behavior?**
 I would expect that I would be able to paste into the spreadsheet

**Did this work in previous versions of DocumentServer?**
N/A

**DocumentServer version:**
N/A this is occurring on cryptpad.fr which does not use the OnlyOffice Document Server

**Operating System:**
Linux Mint 19.3

**Browser version:**
Firefox 104.0

Originally reported on the cryptpad issue tracker (https://github.com/xwiki-labs/cryptpad/issues/936) and directed here

**Comment by ShockwaveNN** [comment] 2022-09-01 06:05
Hi, could you check if the same problem occurs for you on personal.onlyoffice.com?

Because I'm not aware of a problem which cryptopad authors are talking about, so we need to figure out if this problem is present in our official stable version

**Comment by rqtruong** [comment] 2022-09-03 03:55
I could not replicate the issue on personal.onlyoffice.com
I can paste into a cell without any issue

**Comment by ShockwaveNN** [comment] 2022-09-03 07:41
In that case problem on cryptopad side, not sure why they ended you in our repo, but they modify our source code and that modification is unknown to me

So long story short - if any problem can be reproduced on our servers, our Docker image or DesktopEditors - it's definitely a problem in our product, but if it reproduces only in cryptopad - please do not file a bug in our repos

I'm closing this issue

**Closed by ShockwaveNN** 2022-09-03 07:41 UTC
