### ISSUE TITLE
*bug* (spreadsheet) vertical wrap digits issue

### ISSUE THREAD

**Issue by GregMighty** [ONLYOFFICE/DocumentServer#249] opened 2018-03-12 07:23 UTC
Hello

I noticed an error on the speedsheet editor.

**Current behavior?**

Wrong vertical digits.

![2018-03-10_13h19_42](https://user-images.githubusercontent.com/28106243/37270257-6b5bf808-25ce-11e8-8774-200d5a77cfe0.gif)

**Steps to have the bug**

- Type some digits on cells like 123456789
- Rotate text up

- Decrease column width

**DocumentServer version:**

5.0.7 deb package linux server and OnlyOffice integration app 1.2.0 for Nextcloud 13

**Operating System:**
N/A

**Browser version:**
Latest Chrome

**Comment by ShockwaveNN** [comment] 2018-03-12 07:45
Hello. Thank for your report.
This is known bug - issue 33946 in our internal ticket system

But also I notices some digits in your file are pretty strangly aligned.
Like last zero in `1.00` moved after you decrease column width.
Could you attach this we so we have a look?

**Comment by RainerBielefeld** [comment] 2019-06-05 13:42
I still see that problem with _onlyoffice Version 10.0.0_ in Document https://onlyo.co/2wCDDY0 sheet "VerticalNumbers".
It seems that the number display changes to "#####" when the column **width** becomes smaller than the  **number height**.
Serious problem for me because I excessively use vertical date numbers.

**Comment by trofim24** [comment] 2021-03-25 13:12
Duplicate of #182

**Closed by trofim24** 2021-03-25 13:12 UTC
Labels: bug
