### ISSUE TITLE
new create a PPT , and PPT is displayed as Chinese garbled.

### ISSUE THREAD

**Issue by hymany** [ONLYOFFICE/DocumentServer#320] opened 2018-06-12 10:05 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by hymany** [comment] 2018-06-12 10:07
![123](https://user-images.githubusercontent.com/19706331/41284223-3ecadc2e-6e6b-11e8-895e-3b10141952a6.png)

**Comment by ShockwaveNN** [comment] 2018-06-13 07:14
Duplicate of https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/189

**Closed by ShockwaveNN** 2018-06-13 07:14 UTC
