### ISSUE TITLE
Selecting multiple separate parts of a document

### ISSUE THREAD

**Issue by Thomsen-Codes** [ONLYOFFICE/DocumentServer#3062] opened 2024-12-19 18:28 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

OnlyOffice does not support selecting multiple, non-contiguous sections of a document simultaneously using the Ctrl+click method, which is a common feature in other office suites like Microsoft Word and Google Docs. This limitation can hinder productivity and efficiency, especially when working with large documents or complex formatting tasks. Kindly consider adding this feature.

**Comment by Thomsen-Codes** [comment] 2024-12-19 18:33
![image](https://github.com/user-attachments/assets/e6ac9ff5-d040-42e1-9d1f-3dae5ee0306a)
![image](https://github.com/user-attachments/assets/fdab3998-cfbf-4857-90ff-3f572dca8f70)

**Comment by ElenaMaaya** [comment] 2024-12-24 14:57
Duplicate of #1497

**Closed** 2024-12-24 15:01 UTC
