### ISSUE TITLE
Encrpyted files (i.e. Excel) could be accessed without password

### ISSUE THREAD

**Issue by nwpulele** [ONLYOFFICE/DocumentServer#490] opened 2019-01-29 04:00 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
After I uploaded a password protected file, it only required password when I first time access (online editting). (Not sure this behavior is normal?)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Upload a password protected Excel file;
2. Try to access it first time, it asks for password;
3. Try to access it second time, it won't ask again.

**What is the expected behavior?**
Password should be required each time when a user access it.
**Did this work in previous versions of DocumentServer?**
N/A
**DocumentServer version:**
CE 5.2.7
**Operating System:**
Windows 10 x64 (Doc Server deployed in a CentOS 7 server)
**Browser version:**
Firefox 58.0

**Comment by ShockwaveNN** [comment] 2019-01-29 08:18
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/171

**Closed by ShockwaveNN** 2019-01-29 08:18 UTC
