### ISSUE TITLE
Ability to change a slide master

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2103] opened 2023-02-08 11:47 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Please correct me if I am wrong, but I did not see how to change a slide master in OO.
A slide master can help you to define a style for the slides of your presentation, with for example images in the background, headers/footers, style for fonts, etc.

**Comment by Rita-Bubnova** [comment] 2023-02-21 11:33
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1551.

**Closed** 2023-08-04 09:09 UTC

**Comment by candideu** [comment] 2024-08-12 16:15
Now implemented: 

![image](https://github.com/user-attachments/assets/0e22240b-d823-47aa-b46b-ca3a6b1d9a35)
