### ISSUE TITLE
Docker6.1 version of the font dropdown selection box Chinese scrambling problem

### ISSUE THREAD

**Issue by niuqinpeng** [ONLYOFFICE/DocumentServer#1115] opened 2020-12-28 08:07 UTC
Hello, we want to buy the OnlyOffice of your company, but in the process of research, we found that the Chinese characters in the pull-down selection box of docker6.1 version of the font would be promiscuous. such as??? We find that the server version of 6.1 is Ubuntu 20.04.1LTS, and the server version before 6.1 is Ubuntu 18.04.5LTS. May I ask whether the Chinese random code problem is caused by the change of the server version?

**Comment by ShockwaveNN** [comment] 2020-12-28 13:24
Seems this is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1099

**Closed by ShockwaveNN** 2020-12-28 13:24 UTC
