### ISSUE TITLE
Important! Password protected documents when shared opened without pass request

### ISSUE THREAD

**Issue by realkot** [ONLYOFFICE/DocumentServer#171] opened 2017-09-21 12:41 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
pass protected docs opened without pass request!!!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- upload pass protected doc (xlsx) and share it
- open shared link
- enter pass
- all ok

- open shared link in another browser\pc
- pass ISN'T requested!!!

**What is the expected behavior?**
Every time u open pass protected doc - every time u ask to write pass to open doc

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**
current (21/09/2017) latest releases

**Comment by agolybev** [comment] 2017-09-21 13:47
Hi @realkot. Thank you for bag report!

**Comment by realkot** [comment] 2017-09-21 13:55
@agolybev 
Алексей, данная бага воспроизводится в десктоп редакторе в том числе. Т.е. у вас пароль на документ кэшируется(?) после первого ввода и при последующих открытиях документа более не запрашивается никогда.. Если этот же док открыть MS Office'ом, то пароль на документ запрашивается.

**Comment by agolybev** [comment] 2017-09-21 14:05
@realkot, now pasword used only to open the file. It won't be saved after file editing.

**Comment by realkot** [comment] 2017-09-21 14:17
@agolybev 
Алексей, это в какой версии?? Вы пишите либо про новую функциональность, либо не знаете всех возможностей вашей системы :)) Только что проверил, внес изменения, сохранил. Открываю в MS Office - пароль запрашивается. А в вэб и десктоп - нет.
Сейчас стоит последний СЕ, ставил буквально пару дней назад, если что..


Вот вам юзер-стори:
- заливаем пас-протектед файл
- шарим с правами только просмотр
- открываем, вводим пароль
- все последующие открытия БЕЗ запроса пароля

Вы считаете, что это корректное поведение?)

Если нужно, могу снять вам gif'ку с демонстрацией всего вышеописанного.

**Comment by agolybev** [comment] 2017-09-21 14:51
@realkot, we consider this issue like a bug, so I've marked  it with **bug** label.
P.S. Please, use English because it's public issue tracker.

**Comment by freezxp** [comment] 2017-11-01 02:38
Hi,

Is this a bug or by design? I have a password protected document, then I open it using onlyoffice. The moment I save the file, onlyoffice save it without the password anymore.

**Comment by reneglauser** [comment] 2017-11-01 08:13
We have the same problem and hope that this bug will be solved soon...

**Comment by agolybev** [comment] 2017-11-01 17:16
Hi @freezxp, @reneglauser.
We've made protected document support to help people just open such file. Now password protection erase after document editing but we've seen that people want to store it. 
We consider the issue us bug and we are going to fix it.

**Comment by dasaweb** [comment] 2019-01-16 17:01
I have the same problem, it would help me a lot if OnlyOffice would save password protected documents password protected again.
Unfortunately, the last entry here was quite a long time ago. Is there any reasonable hope that the problem will be addressed in the future?

**Comment by ShockwaveNN** [comment] 2019-01-17 09:38
@dasaweb We got this feature in development, but we cannot give any exact dates when it will be fully implemented

**Comment by Rangerok** [comment] 2019-07-22 06:42
Hi, we have the same problem and also we can contribute if you show us the direction

**Comment by ShockwaveNN** [comment] 2022-05-13 06:46
This is rather old issue and I think it should be resolved by now in v7.0 or v7.1

I'll close it but if someone got trouble with it - feel free to comment

**Closed by ShockwaveNN** 2022-05-13 06:46 UTC
Labels: bug
