### ISSUE TITLE
Function to modify capitalization or case of text

### ISSUE THREAD

**Issue by UltraBurstXD** [ONLYOFFICE/DocumentServer#991] opened 2020-06-23 18:17 UTC
Hi OnlyOffice devs,

The software is great and all, I'm using it on my Ubuntu OS and it is superb! But... Besides all good functions that offers a cool migration from MS Office to OnlyOffice, it is missing something: **Change case** function. I think It doesn't make sense to not have it, it is very helpful and important... 

It is very basic but a needed one. And seriously, that is very, very shameful.

**Comment by ShockwaveNN** [comment] 2020-09-11 07:25
Moved this issue to DocumentServer, since this is our base product and problem actual in DocumentServer

**Comment by adrianinsaval** [comment] 2021-01-09 21:23
Will this be implemented?

**Comment by Rita-Bubnova** [comment] 2021-01-12 12:09
> Will this be implemented?

Our team plans to implement this, but currently we have no ETA.

**Comment by HectorB-2020** [comment] 2021-01-14 13:52
I'm skimming through existing cases and believe these two requests are related, aren't they?
#https://github.com/ONLYOFFICE/DesktopEditors/issues/541#issue-778059883
#https://github.com/ONLYOFFICE/DesktopEditors/issues/395#issue-624398225

**Comment by guanolto** [comment] 2022-05-21 08:37
I hope this will be implemented soon. This really is an essential feature. It also should work with the usual keyboard shortcut that other programs use for this, Shift-F3.

**Comment by adrianinsaval** [comment] 2022-05-21 14:08
Isn't this already available? I have it for documents

**Comment by TatianaKirillova** [comment] 2022-05-23 08:00
The function of changing capital letters or text case has been implemented. Hotkeys do not work for her (there is a separate bug for this), but it is better to discuss this in a separate topic.

**Comment by ShockwaveNN** [comment] 2022-05-23 08:05
I'll close this issue since originally it was about Change Case function and this is implemented

If someone need to track hotkey issue for Change Case - it's better to create a new issue

**Closed by ShockwaveNN** 2022-05-23 08:05 UTC
Labels: enhancement

**Comment by HectorB-2020** [comment] 2022-10-16 08:32
@ShockwaveNN, @TatianaKirillova 
> If someone need to track hotkey issue for Change Case - it's better to create a new issue

This issue was closed. 
However I had asked for the hotkey in (https://github.com/ONLYOFFICE/DesktopEditors/issues/541) which was closed as a duplicate. Mind ir I reopen it?

**Comment by ShockwaveNN** [comment] 2022-10-16 16:55
@HectorB-2020 Yeah, sorry, this may happen then several different problem are in one issue, I'll reopen it and we'll handle it

**Comment by ShockwaveNN** [comment] 2022-10-17 14:40
@HectorB-2020 Yeah, we got a little confused

Your issue https://github.com/ONLYOFFICE/DesktopEditors/issues/541 was duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1941 - this issue about hotkey

This issue (DocumentServer#991) is about function in menu

So everything is correct, and there is function in menu, but there is no hotkey (and https://github.com/ONLYOFFICE/DocumentServer/issues/1941 is opened)
