### ISSUE TITLE
Cells value won't update on document opening

### ISSUE THREAD

**Issue by MedusaTree** [ONLYOFFICE/DocumentServer#2278] opened 2023-06-24 09:47 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.1.34

### Expected Behavior

When I open my Excel document in OnlyOffice, the document loads and my header cells display the first two letters of each days of the week for each months of this year (one month per tab)

It was working in the previous version of Nextcloud (currently it is Nextcloud 26.0.2), also I had to change the format parameter from "ddd" to "jjj" if I remember correctly.

### Actual Behavior

When I open my Excel document in OnlyOffice, the document loads properly, but my header cells are not updated (like the formula is not evaluated properly).
Result is I see "jj" in all the cells

Here is the formula : =GAUCHE(TEXTE(DATE(Projets!$E$22;$A$1;B2);"jjj");2)

BUT, when I enter in the cells like I want to edit the formula, and validate it, then I get my good value.
I can do that for all the cells, and check that the sheet is saved, but on next opening, I get back the "jj" :(
Anything that would trigger the expression to be reevaluated will get me the good values, but on next loading I lost them.

[DebugCellsValue.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/11856322/DebugCellsValue.xlsx)

### Reproduction Steps

1. Load the document, see that you have "jj" in the header cells (or maybe "dd" as I use french and probably you'll use english)
2. Enter in one cell and validate it, see that now you have the correct value
3. Save the document
4. Wait a little bit
5. Open it again, good value is lost, "jj" or "dd" are back

### Additional information

I use OnlyOffice in a Nextcloud instance as part of the StorageShare service from Hetzner

**Comment by rsnegirev** [comment] 2023-06-27 08:52
Hi @MedusaTree 

We checked this issue on 7.3.3 and 7.4.0 and it doesn't reproduce there. We repeated all the steps and in the fifth step, when the document is reopened, the first two letters of each day of the week are displayed, as it should be.

So we recommend to update your version of OnlyOffice.

**Comment by MedusaTree** [comment] 2023-06-27 10:11
Hi @rsnegirev,

Thanks for the feedback.
I am confused because when I go in the about tab of one OnlyOffice document, I see there version 7.2.1.34.
However, in my Nextcloud instance application manager page, I see OnlyOffice v7.8.0.

Which one should I believe ?

**Comment by rsnegirev** [comment] 2023-06-27 12:22
@MedusaTree 7.2.1.34 is version of the OnlyOffice DocementServer, exactly what you need to update. OnlyOffice v7.8.0 is version of the connector to Nextcloud.

https://www.onlyoffice.com/download-docs.aspx?from=officefornextcloud#docs-enterprise

**Comment by MedusaTree** [comment] 2023-06-27 14:03
Alright, thanks for the clarification :)

**Comment by DenisDeeSign** [comment] 2023-06-27 14:58
@MedusaTree I'm close this issue since the problem is solved. Feel free to create a new one if you got further questions.

**Closed by DenisDeeSign** 2023-06-27 14:58 UTC
