### ISSUE TITLE
Data in hidden by autofilter cells are replaced

### ISSUE THREAD

**Issue by RainerBielefeld** [ONLYOFFICE/DocumentServer#582] opened 2019-05-09 07:08 UTC
Spreadsheet suffers from LibreOffice Bug 35345 - Cells hidden with filters get changed
https://bugs.documentfoundation.org/show_bug.cgi?id=35345

Spreadsheet also suffers from LibreOffice Bug 125185 - Hidden cells also get contents pasted
https://bugs.documentfoundation.org/show_bug.cgi?id=125185

**Comment by ShockwaveNN** [comment] 2019-06-03 09:23
@RainerBielefeld Hi
https://bugs.documentfoundation.org/show_bug.cgi?id=35345
Accroding to libreoffice bugtracker this is not a bug, but designed that way.
MS Office works same
So I think if Libreoffice and MS office implement this feature in same way - we done it same in our product

**Comment by ShockwaveNN** [comment] 2019-06-03 10:16
@RainerBielefeld About 35345
Could you describe your problem in exact steps in this issue, we tryed to figure it out by libreoffice bug tracker, but not exactly sure what did you mean

**Comment by RainerBielefeld** [comment] 2019-06-03 14:10
@ShockwaveNN:
I cant' imagine a more simple description than https://bugs.documentfoundation.org/show_bug.cgi?id=125185#c0

May be https://onlyo.co/2wCDDY0 helps to understand?

**Comment by ShockwaveNN** [comment] 2019-06-03 14:14
@RainerBielefeld we understand part about 125185 and we do not plan to change that, as I noted earlier.
But we cannot reproduce 35345 and I asked you about this problem

**Comment by RainerBielefeld** [comment] 2019-06-03 14:30
@alexanderonlyoffice ShockwaveNN:
Please see Sheet2 in same document https://onlyo.co/2wCDDY0

**Comment by Rita-Bubnova** [comment] 2019-06-03 15:03
Hello, @RainerBielefeld.
Thank you. I can confirm - this is a bug, issue 41767 in our internal issue tracker.

**Comment by kanweiwei** [comment] 2022-01-07 07:09
[cell/view/WorksheetView.js](https://github.com/ONLYOFFICE/sdkjs/blob/9af7d085bf0717f978ed5bfc3595e37746880aeb/cell/view/WorksheetView.js#L12241-L12255)
```
var getOpenRowsCount = function (oRange) {
  var res = oRange.r2 - oRange.r1 + 1;
  if (excludeHiddenRows) {
    var tempRange = t.model.getRange3(oRange.r1, 0, oRange.r2, 0);
    tempRange._foreachRowNoEmpty(function (row) {
      if (row.getHidden()) {
        res--;
        if (!isCheckSelection) {
          hiddenRowsArray[row.index] = 1;
        }
      }
    });
  }
  return res;
};

```

 Why to check the `isCheckSelection` ?  It seems to be performing well when I remove the if condition like these:

```
if (row.getHidden()) {
        res--;
        hiddenRowsArray[row.index] = 1;
}
```

**Comment by ShockwaveNN** [comment] 2022-01-07 07:43
@kanweiwei Sorry, cannot say anything specific about this code, not my area

But it was added https://github.com/ONLYOFFICE/sdkjs/commit/5e82bd82a3505bb4850fd7390fb91b97d8c07f40

And seems it may needed to handle some edge cases, judging by bug 41767 - it has something to do with copy paste 
And not all cases are 100% resolved right now

**Comment by kanweiwei** [comment] 2022-01-12 02:52
@ShockwaveNN Sorry, it's my fault. `isCheckSelection` is useful, but it's useless in this code 
```
if (!isCheckSelection) {
      hiddenRowsArray[row.index] = 1;
}
```
I think the code which removing  all `false` can fix this issue. Maybe some edge cases should be discuss in other issues

**Comment by ShockwaveNN** [comment] 2022-01-12 07:18
@kanweiwei Thanks for your attention, I've shown this code snipped to developer team, they think it's really some dead code 

Because some lines earlier we got [code](https://github.com/ONLYOFFICE/sdkjs/commit/5e82bd82a3505bb4850fd7390fb91b97d8c07f40#diff-bff445e03932c33df24bf3c6cc86b2d931a86dbe3addd4fa70c004bfbea979e6R10355)
```
if(false && excludeHiddenRows) {
```

So this `if` will be skipped always

Dev team need some time to figure out why this was implemented in a such way but promises me to handle it

**Comment by Rita-Bubnova** [comment] 2022-03-21 09:42
This issue ( 41767 in our internal issue tracker) fixed in а future major release.
We've made a lot of fixes for this, so I can't give a commit.

**Comment by ShockwaveNN** [comment] 2022-05-12 16:45
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles

**Closed by ShockwaveNN** 2022-05-12 16:45 UTC
Labels: bug, fixed
