### ISSUE TITLE
Solved: Shared editing (collaboration) does not work

### ISSUE THREAD

**Issue by steve-s-71** [ONLYOFFICE/DocumentServer#129] opened 2017-06-28 12:55 UTC
I am using latewst version of Document server with Nextcloud. Another Nextcloud user told me a similar story, so I guess this is a bug:

While single user editing works like a charm, shared editing (collaboration) does not work. Once another user opens the document and start editing, changes are not saved anymore. Also, one can’t see the changes from the other user in real-time.

**Comment by ibnpetr** [comment] 2017-06-28 14:43
> Once another user opens the document and start editing, changes are not saved anymore. Also, one can’t see the changes from the other user in real-time.

Please note that [fast co-editing mode](https://helpcenter.onlyoffice.com/guides/collaborative-editing.aspx#step4) should be used by all users to display the changes in real-time. 
Otherwise you just should click on "save" button to show your changes to other users
If it doesn't help let us know, I am sure that the solution can be found.

**Comment by steve-s-71** [comment] 2017-06-28 15:27
Hi Alex,

I just quickly tried Strict mode. That seems to work much more stable, basically it works as you describe. 

But not so the Fast mode. Mostly not, but sometimes it shows the first 2 or 3 characters what the other user has typed, but then there is no more update. Occasionally the is also an error prompt saying "Connection is lost, you can still view...".

Just to avoid any doubt, the Nextcloud server is otherwise not having any trouble or performance issue. Document Server is installed on the same machine (I got it installed running this script: https://github.com/nextcloud/vm/blob/master/apps/onlyoffice.sh
 
Stefan

**Comment by trofim24** [comment] 2017-09-08 15:22
cc @LinneyS

**Comment by steve-s-71** [comment] 2017-09-12 21:10
Hi @alexanderonlyoffice 

NextCloud: https://s-em.de/
Document Server: https://office.s-em.de/

Screenshot:
![oo config](https://user-images.githubusercontent.com/17343515/30348354-4efb921a-980f-11e7-97bf-c624d935e496.jpg)

**Comment by agolybev** [comment] 2017-09-13 08:54
Added https://github.com/nextcloud/vm/pull/363 to fix websocket proxying error.

**Comment by alexanderonlyoffice** [comment] 2017-09-13 09:03
Hello @steve-s-71 ,

Please try to change port 9091 in the line 230 to port 9090. Follow the [link](https://github.com/nextcloud/vm/blob/master/apps/onlyoffice.sh#L230). The port 9091 is not being listened by the Document Server, because Apache Proxy Service is already set up for port 443.

**Comment by steve-s-71** [comment] 2017-09-13 15:23
I have changed the port in the script, then executed the script as root and modified the config so that it looks as in the new screenshot below. 

Unfortunately the issue is same: Mostly not, but sometimes it shows the first 2 or 3 characters what the other user has typed, but then there is no more update. 

If any port or configuration issue, I am wonder why it is able to show the first 2 or 3 characters sometimes?
![oo](https://user-images.githubusercontent.com/17343515/30385653-1d02674a-98a8-11e7-9f16-ddce0fd2a859.jpg)

**Comment by enoch85** [comment] 2017-09-13 19:56
I posted to support about this before, and they asked me to change to [this](https://github.com/nextcloud/vm/pull/316/files) instead. Collabora actually works out of the box, but OnlyOffice seems more complex to run out of the box. What my intention was (and still is) is to make it as secure as possible. according to Lukas (security at Nextcloud) we don't want to use a insecure connection.

**Comment by alexanderonlyoffice** [comment] 2017-09-14 11:57
Hello @steve-s-71 

According to the results of the tests, the problem is that websockets are not being proxied. It should be stated in your apache config. Please send the apache config, so we can check it.

**Comment by steve-s-71** [comment] 2017-09-14 12:28
Hi Daniel @enoch85 

I believe there are multiple apache config files, depending on PHP version and maybe other aspects. Please can you say what is the correct path to the relevant apache config file when using “your” VM?

**Comment by steve-s-71** [comment] 2017-09-14 12:37
Hello @alexanderonlyoffice 

Maybe it's just paranoia, but can you do me a favor and remove or cripple the 2 URLs to my server from your post above to avoid many search engines catch them?

**Comment by alexanderonlyoffice** [comment] 2017-09-14 12:52
Hello @steve-s-71 

I removed the addresses. We need the [config](https://github.com/nextcloud/vm/blob/master/apps/onlyoffice.sh#L195) created by the script you used. Unfortunately, we haven't tested that script.

**Comment by enoch85** [comment] 2017-09-14 19:46
@steve-s-71 

> apache config file when using “your” VM?

Yes, it's the VHOST in `sites-enabled`.

**Comment by steve-s-71** [comment] 2017-09-14 19:49
Thanks @enoch85 
@alexanderonlyoffice will check the apache config. Give me few minutes...

**Comment by steve-s-71** [comment] 2017-09-14 20:27
Hi @alexanderonlyoffice 

Ponting me to the Apache config was actually a very good hint.  I recognized that the port changes made in onlyoffice.sh have not been updated in the apache config.

What I found was even from an older version of the script, that was recent in the time when I installed the VM

What I found was this:
ProxyPass / http://127.0.0.3:9090/
ProxyPassMatch "/(.*)/websocket"  wss://127.0.0.3:9091/$1/websocket


After modifying the apache config to this:

ProxyPassMatch (.*)(\/websocket)$ "ws://127.0.0.3:9090/$1$2"
ProxyPass / "http://127.0.0.3:9090/"
ProxyPassReverse / "http://127.0.0.3:9090/"

shared editing (collaboration) works like a charm. Thank you for your help, you made my day.

The only remaining point is the security concern @enoch85 mentioned above. 
What impact on security do I need to expect when changing port from ws://127.0.0.3:9091/$1$2
to  ws://127.0.0.3:9090/$1$2  ?

**Comment by enoch85** [comment] 2017-09-15 05:44
What I'm talking about is using a secure websocket, 'wss'.

**Comment by enoch85** [comment] 2017-09-15 07:13
I've merged the fix by @agolybev so this shouldn't be an issue anymore. 

@alexanderonlyoffice Please test the script. I got login info to your official site from Tanya and I will write a blog post when I get some time left over. I want to make sure everything is in order before I do.

**Comment by alexanderonlyoffice** [comment] 2017-09-15 13:51
Hello @steve-s-71, 

you are already using the secured connection to your server, that's why you don't need **_wss_** inside the server. 

@enoch85, we will perform a basic testing of the script, but we can't guarantee that it will possess all the variants of possible issues.

**Comment by steve-s-71** [comment] 2017-09-15 16:34
Got it. Thank you @alexanderonlyoffice and @enoch85

**Closed** 2017-09-18 07:56 UTC
