### ISSUE TITLE
Converting/Saving file to .rtf format explodes file size

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/DocumentServer#1657] opened 2022-02-25 10:12 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When converting (through conversion API) or saving a file as .rtf just explodes file size.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a new docx file with simple content. Save it as the .docx original format to your file system. It will have about 20KB. Now save the same file with simple content to .rtf format using the "File/Download as..." option (or through the conversion API). It will have about 400KB.

**What is the expected behavior?**
The file should have a file size compatible with the .docx file. For example, if you open the .docx file on LibreOffice and save it as an .rtf file it will have about 8KB.
Unfortunately we still have legacy systems which still expect the files on the .rtf format (so we store them on that format on some cases) and this explosion on file size could be a problem for us. Could the conversion to .rtf be more size-efficient?
The file seems to have lots of the following blocks:
![image](https://user-images.githubusercontent.com/14880633/155696784-824d646c-14e4-49c4-9eb8-1c53c58ef7dd.png)
Are those really necessary?

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.6.5, 6.4.2, 7.0.1

**Operating System:**
Microsoft Windows 10. OnlyOffice running as a Docker container through the official Docker Hub image.

**Browser version:**
98.0.4758.102

**Comment by l8556** [comment] 2022-03-02 13:28
Thank you for your issue.
I can confirm—this is a bug. Issue 55848 in our private issue tracker.

**Comment by ShockwaveNN** [comment] 2022-03-02 14:50
We just got a talk with our dev team and solution for this problem is rather complicated and we don't planning to fix it, since it require a lot of changes in handling paragraph styles

I'll close this issue, but if you do not agree with this decision - please contact sales@onlyoffice.com

**Closed by ShockwaveNN** 2022-03-02 14:50 UTC
