### ISSUE TITLE
Cannont install on Ubuntu 16

### ISSUE THREAD

**Issue by thomaswollburg** [ONLYOFFICE/DocumentServer#396] opened 2018-10-01 10:07 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Trying to follow https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx and install on a new Ubuntu 16. Installation fails.
`
[10204.189187] AllFontsGen[20896]: segfault at 28701fd0 ip 00007f08732b1168 sp 00007ffc2cbaa698 error 4 in libc-2.23.so[7f0873163000+1c0000]`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Follow the guide. Error occurs at `sudo apt-get install onlyoffice-documentserver`

**What is the expected behavior?**

OnlyOffice should install

**Operating System:**

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by ShockwaveNN** [comment] 2018-10-01 10:18
@thomaswollburg This is strange, it's first time I see segfault on AllFontsGen
I got a [Dockerfile](https://github.com/onlyoffice-testing-robot/documentserver-install-from-manual/tree/master/Ubuntu-16.04) to check installation process described in [installation guide](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx)

First idea is to check libc version, in my Docker image it will be
```
# dpkg -l | grep libc
ii  libc-bin                     2.23-0ubuntu10                        amd64        GNU C Library: Binaries
ii  libc-dev-bin                 2.23-0ubuntu10                        amd64        GNU C Library: Development binaries
ii  libc6:amd64                  2.23-0ubuntu10                        amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64              2.23-0ubuntu10                        amd64        GNU C Library: Development Libraries and Header Files
```

Do you install some variant of Ubuntu or is it just official image

**Comment by ShockwaveNN** [comment] 2018-10-01 10:20
@thomaswollburg Does this error showed on `sudo apt-get install onlyoffice-documentserver` or then you manually try to run AllFontsGen?

**Comment by thomaswollburg** [comment] 2018-10-01 10:35
@ShockwaveNN the error occurs under the `apt install onlyoffice-documentserver`. Not trying to run it manually... wouldnt know where to be honest ;)

So my apt is complaining about `2018-10-01 09:52:12 status half-installed onlyoffice-documentserver:amd64 5.2.0-195` all the time now... any suggestions? I set up a AWS t2-medium machine just to use for our developer license for onlyoffice... and now I cant even install it :(

**Comment by thomaswollburg** [comment] 2018-10-01 10:36
![image](https://user-images.githubusercontent.com/11737019/46284015-9582f300-c576-11e8-9b52-e5939745ea91.png)
 libc list is quite long on my end...

**Comment by ShockwaveNN** [comment] 2018-10-01 10:38
@thomaswollburg so you just used official ubuntu AWS images? I try to reproduce your problem, meanwhile you can use Docker image, it should work fine

**Comment by thomaswollburg** [comment] 2018-10-01 10:44
Yes, it is the official U16 from AWS I used. Was trying to avoid the dockerised version as I had issues with SSL setup there earlier... will give it a try.

**Comment by thomaswollburg** [comment] 2018-10-01 11:11
So, docker version is running... but not too happy about that one either as I cannot open any documents... 
![image](https://user-images.githubusercontent.com/11737019/46285311-50ad8b00-c57b-11e8-8b0c-af6de6c30a52.png) - getting the same error in both presentation and word editors.

And now I really would need a good way of removing the error from my apt with that half installed package.

**Comment by ShockwaveNN** [comment] 2018-10-01 11:19
@thomaswollburg One problem at a time.
I checked installing on Ubuntu 16.04 on amazon image by name
`ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180814-d83d0782-cb94-46d7-8993-f4ce15d1a484-ami-04169656fea786776.4 (ami-068ab34816099a0a9)`
And everything is fine, can you give me a full name of your image

>And now I really would need a good way of removing the error from my apt with that half installed package.

Did you try to `sudo apt purge onlyoffice-documentserver`

> `putImageData` on `CanvasRenderingContext2d`

How did you run your docker version, seems this is config error and may caused by nextcloud\owncloud, I see DocumentView.js:226 line in your browser, I can be mistaken but seems this is not part of DocumentServer

**Comment by thomaswollburg** [comment] 2018-10-01 11:36
```
sudo apt purge onlyoffice-documentserver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  onlyoffice-documentserver*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 734 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 102594 files and directories currently installed.)
Removing onlyoffice-documentserver (5.2.0-195) ...
Preparing for shutdown, it can take a lot of time, please wait...Done
Stopping documentserver services...
onlyoffice-documentserver:metrics: stopped
onlyoffice-documentserver:spellchecker: stopped
onlyoffice-documentserver:gc: stopped
onlyoffice-documentserver:docservice: stopped
onlyoffice-documentserver:converter: stopped
dpkg: error processing package onlyoffice-documentserver (--purge):
 subprocess installed post-removal script returned error exit status 1
Errors were encountered while processing:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by thomaswollburg** [comment] 2018-10-01 11:38
Purging did not work out... maybe this all is related to me trying to compile on that box first... it did compile in the end but nginx only displayed 404. so I stopped everything and tried to just _install_ it... anyhow. The docker version seems to be running fine now. Although https://helpcenter.onlyoffice.com/server/developer-edition/docker/docker-installation.aspx does not contain information about where to put my license file.

**Comment by ShockwaveNN** [comment] 2018-10-01 11:43
>subprocess installed post-removal script returned error exit status 1

Try https://github.com/ONLYOFFICE/DocumentServer/issues/275#issuecomment-379657543

> does not contain information about where to put my license file.

You should put `license.lic` file in `/var/www/onlyoffice/Data` inside container
So it should be at `/app/onlyoffice/DocumentServer/data` on host if you use mounts from this guide

**Comment by ShockwaveNN** [comment] 2018-10-25 12:50
This issue was closed due to no response.

**Closed by ShockwaveNN** 2018-10-25 12:50 UTC
Labels: waiting feedback
