### ISSUE TITLE
WORKDAY.INTL function broken when using day-offset of 1

### ISSUE THREAD

**Issue by JhonHUBTEK** [ONLYOFFICE/DocumentServer#2168] opened 2023-03-14 15:10 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3.0.184

### Expected Behavior

When a date that falls on a Friday is entered as the first argument and a compensation of 1 day is entered as the second argument, it should exclude Saturday and Sunday and return a date for the following Monday.

### Actual Behavior

When a date that falls on a Friday is entered as the first argument and a compensation of 1 day is entered as the second argument, the returned date is Saturday. Similarly, when a date that falls on a Saturday is entered, the returned date is Sunday.

![image](https://user-images.githubusercontent.com/94491858/225044206-e77bf79c-a910-4f1d-be11-f501bcad8120.png)

### Reproduction Steps

Write the formula:
`=WORKDAY.INTL(E10,F10,1)`

Where E10 = '3/17/2023' > Friday OR Where E10 = '3/18/2023' > Saturday

Where F10 = 1

### Additional information

It's the same issue like https://github.com/ONLYOFFICE/DocumentServer/issues/184

**Comment by rsnegirev** [comment] 2023-03-17 11:40
Hi @JhonHUBTEK 

Can you please attach your file?

**Comment by JhonHUBTEK** [comment] 2023-03-17 15:12
Sure @rsnegirev 

I included a holiday that also not works:

![image](https://user-images.githubusercontent.com/94491858/225944966-00392ec1-37d6-46ec-8fbc-c88e1a2cbf81.png)


[example WORKDAY.INTL.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/11002724/example.WORKDAY.INTL.xlsx)

**Comment by rsnegirev** [comment] 2023-03-20 11:24
Hi @JhonHUBTEK 

I can confirm - this is the bug, issue 61688 in our internal issue tracker.
Thank you for report.

**Comment by rsnegirev** [comment] 2023-09-26 14:54
Hi @JhonHUBTEK 

The problem was fixed in this commit:
https://github.com/ONLYOFFICE/sdkjs/commit/bfa1b944d0677f9c5d4a631a6b4c79487893c3c3

**Comment by Rita-Bubnova** [comment] 2023-10-19 11:13
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-19 11:13 UTC
Labels: confirmed-bug, fixed-release
