### ISSUE TITLE
When editing a document, how can I make "Font name appear in Chinese"?

### ISSUE THREAD

**Issue by N-lucky** [ONLYOFFICE/DocumentServer#803] opened 2020-03-09 02:31 UTC
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I added "Chinese fonts" to the / usr / share / fonts / directory of the document server server.
Then run the /usr/bin/documentserver-generate-allfonts.sh script,
"Font displayed in Chinese" was not found in the font box, although "Chinese Pinyin for this font" was found,
But I want to know how to "make font name" appear in Chinese?

![ziti](https://user-images.githubusercontent.com/29221412/76178040-03622e00-61f1-11ea-952d-f5ac841f0c5c.jpg)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
Do not know

**DocumentServer version:**
DocumentServerv5.4

**Operating System:**
Ubuntu 1804

**Browser version:**
Google Chrome v80.0.3987.132

**Comment by ShockwaveNN** [comment] 2020-03-10 07:43
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/332

**Closed by ShockwaveNN** 2020-03-10 07:43 UTC
