### ISSUE TITLE
Spreadsheet: formula becomes incorrect when adding new rows

### ISSUE THREAD

**Issue by vimu86** [ONLYOFFICE/DocumentServer#1388] opened 2021-08-19 10:57 UTC
OnlyOffice Spreadsheet Bug: formula becomes incorrect when new lines are added - only in existing/saved files, not in fresh files.

The expected behavior is shown in step 4 of the instruction:

![image](https://user-images.githubusercontent.com/76959246/130054807-f1f6b234-df77-4ecc-a196-912a0c6aa11a.png)

Step 6+7 shows how to trigger the bug:

![image](https://user-images.githubusercontent.com/76959246/130055900-c4e77609-e828-4031-8c8f-f124e454535c.png)

Apparently, only formulas with a combination (e.g. product) of multiple cells are affected... The single reference of G11 is still correct( "=Sheet1!A4")...

I am using OnlyOffice 6.0.2.5. I assume the bug was introduced with a recent upgrade of our nextcloud infrastructure, otherwise I would have realized the behavior before.

**Comment by ShockwaveNN** [comment] 2021-08-19 11:03
> I am using OnlyOffice 6.0.2.5

Could you update to latest v6.3.2?

Because we may already fix this bug

**Comment by vimu86** [comment] 2021-08-19 11:08
It's a productive environment.. I will ask our IT department, they might have a "test" installation with a newer version.. I would appreciate if someone could figure out in which version the bug was fixed, so that we know which version we need at least.

**Comment by ShockwaveNN** [comment] 2021-08-19 11:10
It's always good idea to use latest stable version

But I'm not 100% sure this bug is fixed in latest stable

@Rita-Bubnova could you check for this bug in v6.3.2?

**Comment by Rita-Bubnova** [comment] 2021-08-19 11:25
Hello.
I checked it in Document Server version 6.3.2 (build:2) on Windows 10, Chrome 92. And this problem don't reproduce.

**Comment by ShockwaveNN** [comment] 2021-08-19 11:40
In that case I'll close this issue

If for some reason this problem still occurs for you in v6.3.2 - feel free to comment here or create new issue

**Closed by ShockwaveNN** 2021-08-19 11:40 UTC

**Comment by vimu86** [comment] 2021-08-19 12:42
small addendum:  I was able to confirm that the bug is apparently not present in v6.3.1 ...

**Comment by vimu86** [comment] 2021-08-22 21:08
I re-opened the issue here
https://github.com/ONLYOFFICE/DocumentServer/issues/1390

I think the problem with the above instruction to reproduce the problem is step 6: closing the file for a few second seems to reproduce the problem only on some sytems...  A better way is to download and upload the XLSX file...  in issue #1390 I provide a test-file...
