### ISSUE TITLE
Page error problem Help

### ISSUE THREAD

**Issue by mideming** [ONLYOFFICE/DocumentServer#2705] opened 2024-04-22 06:46 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.5.1

### Expected Behavior

Hi, I'm a developer in China,We have encountered some problems with onlyoffice.
I'd like to start from page three to the first page of the document, So I set the total number of pages through the domain code.as follows:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/30286761/dd19b4fd-db6f-41ef-a1a4-3dea4e5a6438)
I hope this is shown as follows
1/6，2/6，3/6...

### Actual Behavior

However, When I import into onlyoffice, the page number has changed, as follows:
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/30286761/0f86fe98-2d98-4586-bad8-129d21bc833f)
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/30286761/73948e2e-152f-4564-b6f1-a3e723046dd7)

The current page number and the total page number are the same for each page, So I would like to ask, is this problem caused by onlyoffice not supporting domain code?Or is there a way to calculate the total number of pages from the current page?
Thanks with best wishes.

**Comment by mideming** [comment] 2024-04-22 06:49
Sorry about the wrong version. It should be 7.5.1

**Comment by ElenaMaaya** [comment] 2024-04-24 13:31
Hello @mideming! 
Thank you for report! Please attach file for a more complete test.

**Comment by mideming** [comment] 2024-04-25 09:58
@ElenaMaaya @Rita-Bubnova

**Comment by ElenaMaaya** [comment] 2024-04-25 14:36
@mideming, Thank you for providing the file!
I will inform you as soon as there is information regarding this issue.

**Comment by ElenaMaaya** [comment] 2024-06-25 14:49
Hello, @mideming! The problem is not repeated in Document Server and Desktop Editor version 8.1 on Windows 11. Please update to release version 8.1.0. If the problem persists, please write here again.

**Comment by Rita-Bubnova** [comment] 2024-06-25 15:04
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-06-25 15:04 UTC

**Comment by rye0catcher** [comment] 2025-04-10 03:04
I met a similar problem. The field string of page number in footer part is: IF {NUMPAGES} > 1 "-{PAGE}-" "" .
The expected behaviour is:
  1. When there is only one page, there should be no page number. 
  2. Buf if there are muliple pages, the page number displays, e.g., "-1-", "-2-".

However, when the file is edited in onlyoffice DocSpace, the page number doesn't display as expected. 

![Image](https://github.com/user-attachments/assets/fe95be7c-c013-4f59-96d2-685b729857bf)

**Comment by rye0catcher** [comment] 2025-04-10 03:04
[testfile11_2p4.docx](https://github.com/user-attachments/files/19677313/testfile11_2p4.docx)

**Comment by ElenaMaaya** [comment] 2025-04-10 12:17
Hello, @rye0catcher ! 
Thank you for reaching out to us regarding your issue. 
To assist you better, could you please create a new issue? This will help us track your request and provide you with the most effective support.

**Comment by rye0catcher** [comment] 2025-04-11 00:57
> Hello, [@rye0catcher](https://github.com/rye0catcher) ! Thank you for reaching out to us regarding your issue. To assist you better, could you please create a new issue? This will help us track your request and provide you with the most effective support.

OK. The new issue created, see [#3199](https://github.com/ONLYOFFICE/DocumentServer/issues/3199) please.
