### ISSUE TITLE
Data loss with `at c.LTe` error

### ISSUE THREAD

**Issue by leo-lb** [ONLYOFFICE/DocumentServer#1004] opened 2020-09-25 15:23 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

There was data loss on at least one docx file, symptoms look similar to this: https://help.nextcloud.com/t/data-loss-after-onlyoffice-update/93008

All I have as information is these logs below, the document lost was edited but it seems it wasnt synced back to Nextcloud or got overwritten bypassing the Nextcloud version history (if that's possible). The document now appears empty.

Recently I upgraded Nextcloud to 19, and even more recently to 19.0.3.

Error logs:

```
[2020-09-23T06:40:07.527] [WARN] nodeJS - Express server starting...
[2020-09-23T06:40:07.531] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2020-09-23T06:40:07.677] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-09-23T07:12:30.741] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T07:31:38.728] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T08:24:04.747] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T08:49:34.975] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T09:02:02.503] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T10:35:31.196] [WARN] nodeJS - sendServerRequest returned an error: docId = 1617442338; data = {"error":1}
[2020-09-23T10:35:31.200] [WARN] nodeJS - storeForgotten: docId = 1617442338
[2020-09-23T10:36:31.757] [WARN] nodeJS - sendServerRequest returned an error: docId = 1617442338; data = {"error":1}
[2020-09-23T10:36:31.761] [WARN] nodeJS - storeForgotten: docId = 1617442338
[2020-09-23T10:36:37.391] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T10:37:42.702] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T10:38:53.324] [WARN] nodeJS - sendServerRequest returned an error: docId = 1617442338; data = {"error":1}
[2020-09-23T10:38:53.327] [WARN] nodeJS - storeForgotten: docId = 1617442338
[2020-09-23T10:47:31.919] [WARN] nodeJS - sendServerRequest returned an error: docId = 922434186; data = {"error":1}
[2020-09-23T10:47:31.924] [WARN] nodeJS - storeForgotten: docId = 922434186
[2020-09-23T11:12:24.130] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T11:14:29.437] [WARN] nodeJS - sendServerRequest returned an error: docId = 1617442338; data = {"error":1}
[2020-09-23T11:14:29.440] [WARN] nodeJS - storeForgotten: docId = 1617442338
[2020-09-23T11:48:14.658] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T11:48:37.063] [WARN] nodeJS - sendServerRequest returned an error: docId = 1617442338; data = {"error":1}
[2020-09-23T11:48:37.066] [WARN] nodeJS - storeForgotten: docId = 1617442338
[2020-09-23T13:03:48.033] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T13:27:33.810] [ERROR] nodeJS - changesError: docId = 3568620594 Error
    at c.LTe (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:1092:136)
    at c.ia (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:1087:214)
    at ab.EN (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6988:466)
    at ab.zpd (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7018:397)
    at ab.gqd (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7014:388)
    at ab.sBf (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6982:409)
    at Ya.Q7f (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6923:435)
    at Object.DEg (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7974:209)
    at d.close (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7527:16)
    at h.yXe (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7668:195)
[2020-09-23T13:27:36.046] [ERROR] nodeJS - Error saveChanges docid: 3568620594 ; deleteIndex: 66 ; startIndex: 65 ; deleteCount: -1
[2020-09-23T13:27:45.921] [ERROR] nodeJS - Error saveChanges docid: 3568620594 ; deleteIndex: 67 ; startIndex: 66 ; deleteCount: -1
[2020-09-23T13:28:28.556] [ERROR] nodeJS - Error saveChanges docid: 3568620594 ; deleteIndex: 68 ; startIndex: 67 ; deleteCount: -1
[2020-09-23T13:28:50.552] [ERROR] nodeJS - Error saveChanges docid: 3568620594 ; deleteIndex: 11034 ; startIndex: 11033 ; deleteCount: -1
[2020-09-23T13:29:08.430] [ERROR] nodeJS - Error saveChanges docid: 3568620594 ; deleteIndex: 11056 ; startIndex: 11055 ; deleteCount: -1
[2020-09-23T13:29:15.748] [ERROR] nodeJS - Error saveChanges docid: 3568620594 ; deleteIndex: 11057 ; startIndex: 11056 ; deleteCount: -1
[2020-09-23T13:32:58.219] [ERROR] nodeJS - Error saveChanges docid: 3568620594 ; deleteIndex: 11058 ; startIndex: 11057 ; deleteCount: -1
[2020-09-23T13:33:22.687] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T13:34:06.757] [WARN] nodeJS - sendServerRequest returned an error: docId = 3568620594; data = {"error":1}
[2020-09-23T13:34:06.761] [WARN] nodeJS - storeForgotten: docId = 3568620594
[2020-09-23T13:35:57.358] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T14:02:45.202] [WARN] nodeJS - sendServerRequest returned an error: docId = 922434186; data = {"error":1}
[2020-09-23T14:02:45.206] [WARN] nodeJS - storeForgotten: docId = 922434186
[2020-09-23T14:06:01.662] [WARN] nodeJS - sendServerRequest returned an error: docId = 922434186; data = {"error":1}
[2020-09-23T14:06:01.665] [WARN] nodeJS - storeForgotten: docId = 922434186
[2020-09-23T14:09:46.360] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T14:10:12.633] [WARN] nodeJS - sendServerRequest returned an error: docId = 3568620594; data = {"error":1}
[2020-09-23T14:10:12.737] [WARN] nodeJS - storeForgotten: docId = 3568620594
[2020-09-23T14:22:06.829] [WARN] nodeJS - sendServerRequest returned an error: docId = 922434186; data = {"error":1}
[2020-09-23T14:22:06.831] [WARN] nodeJS - storeForgotten: docId = 922434186
[2020-09-23T14:31:47.259] [WARN] nodeJS - sendServerRequest returned an error: docId = 3568620594; data = {"error":1}
[2020-09-23T14:31:47.262] [WARN] nodeJS - storeForgotten: docId = 3568620594
[2020-09-23T14:42:28.600] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T14:47:27.486] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T14:49:45.938] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T15:06:10.993] [WARN] nodeJS - sendServerRequest returned an error: docId = 3568620594; data = {"error":1}
[2020-09-23T15:06:10.997] [WARN] nodeJS - storeForgotten: docId = 3568620594
[2020-09-23T15:07:12.388] [WARN] nodeJS - sendServerRequest returned an error: docId = 3568620594; data = {"error":1}
[2020-09-23T15:07:12.391] [WARN] nodeJS - storeForgotten: docId = 3568620594
[2020-09-23T15:12:53.797] [WARN] nodeJS - sendServerRequest returned an error: docId = 3568620594; data = {"error":1}
[2020-09-23T15:12:53.801] [WARN] nodeJS - storeForgotten: docId = 3568620594
[2020-09-23T15:23:48.241] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T15:39:03.966] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T15:53:01.357] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T15:57:15.303] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
[2020-09-23T16:33:16.082] [WARN] nodeJS - sendServerRequest returned an error: docId = 3568620594; data = {"error":1}
[2020-09-23T16:33:16.092] [WARN] nodeJS - storeForgotten: docId = 3568620594
[2020-09-23T16:39:12.500] [WARN] nodeJS - error description: docId = 607984 errorId = Restore error. Document modified.
```

**DocumentServer version:**

5.6.5

**Comment by ShockwaveNN** [comment] 2020-09-25 16:59
Hi, first things first.
I'm not sure this is reas reason of data lost, but those lines indicate some major error, of this we are not aware

```
[2020-09-23T13:27:33.810] [ERROR] nodeJS - changesError: docId = 3568620594 Error
    at c.LTe (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:1092:136)
    at c.ia (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:1087:214)
    at ab.EN (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6988:466)
    at ab.zpd (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7018:397)
    at ab.gqd (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7014:388)
    at ab.sBf (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6982:409)
    at Ya.Q7f (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6923:435)
    at Object.DEg (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7974:209)
    at d.close (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7527:16)
    at h.yXe (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7668:195)
```

Those error are happened on front-end, result a message and disable editing of documents

If this is possible - we need scenario of this situation, this may happen to some specific file, or some specific actions in any file

**Comment by leo-lb** [comment] 2020-09-26 17:25
Unfortunately my users do not remember exactly what they did on files 15 days ago :-/

The scenario is they created a file 15 days ago, edited it a few times through ONLYOFFICE with 5-6 users at the same time and then recently they opened it again and it was empty. Nextcloud shows no previous versions in history at all and just shows the file was created 14 days ago.

**Comment by ShockwaveNN** [comment] 2020-09-26 17:36
In that case I'll leave this issue opened, there is definitely some kind of bug in our code, maybe someone (or we are) will be able to figure out scenario for this error

**Comment by leo-lb** [comment] 2020-09-26 19:30
Thanks a lot, I am sorry I do not have more information. Is there a way you think to recover that lost file with a docId ?

**Comment by ShockwaveNN** [comment] 2020-09-27 05:30
Maybe @DenisDeeSign will be able to help in recovery process

**Comment by kabliveru** [comment] 2020-09-28 20:14
same problem. and the same error when starting the server.
`[WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
`

**Comment by ShockwaveNN** [comment] 2020-09-29 11:59
@kabliveru Please note that 

```
Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
```

 message is normal, and if you have no more messages in logs - you got some other problem and create separate issue

**Comment by espenbo** [comment] 2020-11-27 15:10
My users to lose data they have written i nextcloud 19.4.  and onlyoffice.

tride to run sudo -u www-data /usr/bin/php7.3 /var/www/nextcloud/occ documentserver:flush
in crontab every 5 min to save the files.

It would be nice with a save icon that saved the file to nextcloud.

**Comment by ShockwaveNN** [comment] 2020-11-27 15:22
@espenbo could you desccribe your problem in more details, especially DocumentServer version. I'm note sure this is same issue as topic starter?

**Comment by espenbo** [comment] 2020-11-30 17:17
@ShockwaveNN Sorry for the late replay. I'm not sure if the issue is the same as topic startet.

ONLYOFFICE 6.1.0
Community Document Server 0.1.8

I'm using Nextcloud 19.0.4. ONLYOFFICE 6.1.0. and Community Document Server 0.1.8.

When I open a dokument and edit it in the webbrowser with onlyoffice. Everything works. I can edit, go out of the dokument and inn again. 
But If I try to open the dokument from from my local PC. That is synced with the place the dokument is stored. Then everything I have change in the dokument is not there.
Yes, I have check that every thing is marked as sync OK. And I have waited over 30 minuttes. 

I have tride to get the dokument server to save the dokumentents from the dokumentserver to nextcloud server every 5 minuttes. But it don't work everytime

sudo -u www-data /usr/bin/php7.3 /var/www/nextcloud/occ dokumentserver:flush

I don't now how often the dokumentserer should save to nextcloud. But now it's to slow. I think a save button that saves the dokument to nextcloud inn onlyoffice would be nice. A way for the user to save/sync to the nextcloud server when they would want to.

**Comment by ShockwaveNN** [comment] 2020-11-30 17:44
Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate [GitHub repository](https://github.com/nextcloud/documentserver_community). 

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation [guide](https://api.onlyoffice.com/editors/nextcloud)), we will be glad to answer your questions. Please see more info on our [forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).

**Comment by celevra** [comment] 2021-02-19 09:55
same Problem here
how to reproduce:
copy an existing doxc file
edit the copy with onlyoffice
if you click on file -> save you get an error (i think the autosaves drops an silent error)
in the logs i see:
```
[2021-02-19T09:52:12.886] [WARN] nodeJS - storeForgotten: docId = 927884457
[2021-02-19T09:52:29.796] [WARN] nodeJS - sendServerRequest returned an error: docId = 927884457; data = {"error":1}
```

regards

**Comment by ShockwaveNN** [comment] 2021-02-19 10:10
@celevra Thich version of DocumentServer are you using?
Are you 100% sure this is same error, is error is same like `at c.LTe` error`?

**Comment by celevra** [comment] 2021-02-19 11:22
@ShockwaveNN oh, my fault the storeForgotten and senServerRequest are the Same Errors, no c.LTe
Should I open an new report?
i'm on the latest Docker Container onlyoffice-document-server and newest NextCloud

regards

**Comment by ShockwaveNN** [comment] 2021-02-19 11:24
Yeah, better to create new issue with full versions of your environment (not latest, but exact) and attach logs of DocumetnServer

**Comment by barzog** [comment] 2021-05-30 17:08
Same with 21.0.2 and latest onlyoffice/documentserver (image id 30594f63d46c)

[2021-05-30T17:00:27.168] [WARN] nodeJS - Express server starting...
[2021-05-30T17:00:27.173] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-05-30T17:00:27.238] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.0. Build: 111
[2021-05-30T17:01:32.425] [WARN] nodeJS - Express server starting...
[2021-05-30T17:01:32.429] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-05-30T17:01:32.472] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.0. Build: 111
[2021-05-30T17:03:04.468] [WARN] nodeJS - sendServerRequest returned an error: docId = 1156482689; data = {"error":1}
[2021-05-30T17:03:04.470] [WARN] nodeJS - storeForgotten: docId = 1156482689
[2021-05-30T17:04:17.781] [WARN] nodeJS - sendServerRequest returned an error: docId = 1156482689; data = {"error":1}
[2021-05-30T17:04:17.783] [WARN] nodeJS - storeForgotten: docId = 1156482689
[2021-05-30T17:06:25.984] [WARN] nodeJS - sendServerRequest returned an error: docId = 1156482689; data = {"error":1}
[2021-05-30T17:06:25.987] [WARN] nodeJS - storeForgotten: docId = 1156482689

**Comment by ShockwaveNN** [comment] 2021-05-31 08:14
@barzog We still need some file or exact scenario when this error happens, maybe a video from client side
Logs are no enough, sorry

**Comment by barzog** [comment] 2021-05-31 08:50
Scenario is really simple: just open and edit any docx file in onlyoffice. After that I saw those warnings in documentserver logs. Furthemore: when I close this file in OO, and open in again in OO - my changes are in place. But if I share this file, downloaded file does not contain any changes.

**Comment by ShockwaveNN** [comment] 2021-05-31 08:55
@barzog To be clear you're not having any error that looks like:
```
[2020-09-23T13:27:33.810] [ERROR] nodeJS - changesError: docId = 3568620594 Error
    at c.LTe (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:1092:136)
    at c.ia (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:1087:214)
    at ab.EN (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6988:466)
    at ab.zpd (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7018:397)
    at ab.gqd (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7014:388)
    at ab.sBf (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6982:409)
    at Ya.Q7f (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:6923:435)
    at Object.DEg (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7974:209)
    at d.close (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7527:16)
    at h.yXe (https://cloud.matrice.io/onlyoffice/5.6.5-3/sdkjs/cell/sdk-all.js:7668:195)

```

in your logs? in that case this may be integration problem - better create new issue and describe your environment in more details (esepcially DMS (owncloud, nextcloud etc)

**Comment by celevra** [comment] 2021-05-31 08:57
for me the solution was to put ```  'allow_local_remote_servers' => true,``` inside the nextcloud config

**Comment by ShockwaveNN** [comment] 2021-05-31 09:01
@celevra Yeah, you may be right, there is a plenty of issues related to this problem, but them in another repo - like this
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/297#issuecomment-640428374

**Comment by barzog** [comment] 2021-05-31 09:08
No, I don't see any other errors except 
[2021-05-30T17:04:17.781] [WARN] nodeJS - sendServerRequest returned an error: docId = 1156482689; data = {"error":1}
[2021-05-30T17:04:17.783] [WARN] nodeJS - storeForgotten: docId = 1156482689

I have allow_local_remote_servers' => true in config.php. 
Open new issue: https://github.com/ONLYOFFICE/DocumentServer/issues/1280

**Comment by ShockwaveNN** [comment] 2021-05-31 09:11
@leo-lb Could you please state are you having similar error on latest version or we resolved problem in latest updates since your version 5.6.5

**Comment by leo-lb** [comment] 2021-06-01 21:33
@ShockwaveNN The reproduction scenario is unclear so I am unable to respond. Also, this error caused people over here to start distrusting ONLYOFFICE and start using Google Docs again. It is a really sad situation.

**Comment by ShockwaveNN** [comment] 2021-06-02 07:42
@leo-lb To be clear - are you updated to latest version of DocumentServer (v6.3.0) and your users still got some error with data loss?

> Also, this error caused people over here to start distrusting ONLYOFFICE

Sorry to hear that, but we're working hard that will not happened again

**Comment by ShockwaveNN** [comment] 2021-07-16 11:25
This issue was closed due to no response.

**Closed by ShockwaveNN** 2021-07-16 11:25 UTC
Labels: bug, waiting feedback
