### ISSUE TITLE
替代文本，使用poi替换图片不生效

### ISSUE THREAD

**Issue by feifaninternet** [ONLYOFFICE/DocumentServer#2992] opened 2024-11-15 11:10 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.2.0

### Expected Behavior

设置替代文本，使用poi替换图片成功

### Actual Behavior

设置替代文本，使用poi替换图片不生效

### Reproduction Steps

![91c7e35280cf04b200cf1dae8e948c4](https://github.com/user-attachments/assets/07d87454-8f2e-4abc-bb95-abf18aef9c76)
设置替代文本，使用poi替换图片不生效，office里面设置的可以成功替换

**Comment by Rita-Bubnova** [comment] 2024-11-15 11:28
Hello, @feifaninternet.
Please, fill in all the fields of the form on English.

**Comment by lucktoo** [comment] 2024-11-15 17:03
Images Not Replacing Correctly in ONLYOFFICE Online Mobile Version
By uploading a Microsoft Word document where images are set as variables, the generated file correctly replaces the images. However, after using the ONLYOFFICE online mobile version, the images are not being replaced properly. Please watch my 1-minute video.

**Comment by lucktoo** [comment] 2024-11-15 17:12
https://github.com/user-attachments/assets/4d9f6c2d-7355-4962-9cdb-d6856e49634e
@Rita-Bubnova

**Comment by Rita-Bubnova** [comment] 2024-12-18 12:52
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2992.

**Closed by Rita-Bubnova** 2024-12-18 12:52 UTC
Labels: duplicate
