### ISSUE TITLE
pdf editing text bug

### ISSUE THREAD

**Issue by yiwen9488** [ONLYOFFICE/DocumentServer#2802] opened 2024-07-17 03:41 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.1.26

### Expected Behavior

Edit text content normally

### Actual Behavior

Document content is lost and becomes blank

### Reproduction Steps

编辑内容

https://github.com/user-attachments/assets/85bac312-309d-4eb6-b434-978d129794a0

**Comment by Rita-Bubnova** [comment] 2024-07-18 12:30
Hello, @yiwen9488.
Could you attach the file with the problem?

**Comment by EasyIsAllYouNeed** [comment] 2024-07-18 16:20
any file will reproduce this bug

**Comment by yiwen9488** [comment] 2024-07-19 00:50
@Rita-Bubnova 
any file will reproduce this bug

**Comment by ElenaMaaya** [comment] 2024-07-19 14:39
Hello @yiwen9488!
Thank you for report! 
Unfortunately, I tried to reproduce this issue, but still unsuccessful (Windows 11  Pro 23H2 x64 and Kubuntu 23.10, DS v. 8.1.1.26, Browse Google Chrome 126.0 .
If you can please, attach test file and give OS and Browser version for a more complete test. Thank you!

**Comment by yiwen9488** [comment] 2024-07-20 00:41
Chrome 已是最新版本
版本 126.0.6478.183（正式版本） （64 位）

**Comment by yiwen9488** [comment] 2024-07-20 00:41
windows 11 pro 23hx x64     docker desktop 4.32.0

**Comment by EasyIsAllYouNeed** [comment] 2024-07-20 10:58
test on Community Edition  @ElenaMaaya

**Comment by ElenaMaaya** [comment] 2024-07-24 11:39
@yiwen9488, thank you! Can you attach a file "IDEA使用教程.pdf" for testing?

**Comment by fernfei** [comment] 2024-07-25 00:51
> @yiwen9488, thank you! Can you attach a file "IDEA使用教程.pdf" for testing?

hi here http://image.hi-hufei.com/IDEA%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B.pdf

**Comment by ElenaMaaya** [comment] 2024-07-26 09:27
Hello @yiwen9488!
Thank you for report!
I can confirm that the problem exists. I created ticket 69418  in our  issue tracker with your issue.

**Comment by ElenaMaaya** [comment] 2024-10-15 12:23
Hello @yiwen9488 ! This issue will be fixed in the next release. Please keep checking for updates.

**Comment by Rita-Bubnova** [comment] 2024-10-21 07:58
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-10-21 07:58 UTC
Labels: confirmed-bug, fixed-release

**Comment by EasyIsAllYouNeed** [comment] 2024-10-25 10:10
"Edit text" button has gone.............
Is it intentional or accidental？😂😂😂

**Comment by ElenaMaaya** [comment] 2024-10-25 11:22
Hello @yiwen9488! It's not a bug. "Edit text" button should not be in the DS Community Edition.

**Comment by jlemangarin** [comment] 2024-10-25 12:34
Oh wow, yeah that's technically a way to fix the issue 🤣

**Comment by yiwen9488** [comment] 2024-10-26 00:28
> Hello @yiwen9488! It's not a bug. "Edit text" button should not be in the DS Community Edition.

Ok, got it, the community edition editing feature was killed, thankfully it wasn't resolved for the person who raised the issue

**Comment by ibnpetr** [comment] 2025-04-21 14:56
>got it, the community edition editing feature was killed

We understand how important and widely used this feature is, which is why we’ve decided to restore it in the next release of Docs CE. 
Please be informed that more information will be shared soon via our blog, newsletters, and other channels. Stay tuned!
