### ISSUE TITLE
onlyoffice打开doc结尾的文件会报错

### ISSUE THREAD

**Issue by BuenosA** [ONLYOFFICE/DocumentServer#362] opened 2018-08-13 12:02 UTC
I installed onlyoffice in CentOS 7.5 as an official document, and I couldn't open part of the file at the end of the doc in Document Editors, but onlyoffice deployed with the docker could open it.

![image](https://user-images.githubusercontent.com/41983851/44030748-52a146e4-9f34-11e8-9e04-56149763f1b3.png)
![image](https://user-images.githubusercontent.com/41983851/44030777-69b19bc2-9f34-11e8-9133-25f8bf0b86de.png)

**Comment by BuenosA** [comment] 2018-08-13 13:50
I just deployed onlyoffice according to your official document and couldn't open a part of the document with the. doc suffix name; the other docker deployed, it's all OK. I'd like to ask if your version is a problem or a known bug, or how to modify the configuration to be implemented?


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 20:51，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA Please attach file and fill issue template accordingly

**Comment by ShockwaveNN** [comment] 2018-08-13 14:06
@BuenosA I need a file to reproduce a problem

**Comment by BuenosA** [comment] 2018-08-13 14:10
You can visit our website jisuclouds.Com, we have pointed to onlyoffice in the configuration file, or you can upload the. doc file, there will be part of the situation can not be opened, you can also grab the package to check, thank you.




| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:06，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA I need a file to reproduce a problem

**Comment by BuenosA** [comment] 2018-08-13 14:29
You can try this document, or there is such a document on our website.


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:19，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA I just loaded random doc to http://jisuclouds.com/ and everything opened fine

I need exact file for which problem happened.
And I don't understand what you mean by you can also grab the package to check

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易邮箱大师发来的云附件
智联招聘-任梅花-韩语翻译助理-中文-20180809-1533804959652.doc(100KB,2018年8月28日 22:28 到期)
下载

**Comment by ShockwaveNN** [comment] 2018-08-13 14:33
@BuenosA I cannot use your document, seems like github cannot load document via mail-reply, pleaase attach your doc file directly to github via web interface

**Comment by BuenosA** [comment] 2018-08-13 14:43
| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:33，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA I cannot use your document, seems like github cannot load document via mail-reply, pleaase attach your doc file directly to github via web interface

**Comment by BuenosA** [comment] 2018-08-13 14:48
Github does not support this format of the file, I added in the attachment, you try again, or you find a few. doc try, the problem is that most. doc files can not open, thank you ,please!
| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:43，18713212140<m18713212140@163.com> 写道：


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:33，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA I cannot use your document, seems like github cannot load document via mail-reply, pleaase attach your doc file directly to github via web interface

**Comment by ShockwaveNN** [comment] 2018-08-13 14:49
@BuenosA you can zip doc file and attach it to github

**Comment by BuenosA** [comment] 2018-08-13 14:49
| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:48，18713212140<m18713212140@163.com> 写道：
Github does not support this format of the file, I added in the attachment, you try again, or you find a few. doc try, the problem is that most. doc files can not open, thank you ,please!
| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:43，18713212140<m18713212140@163.com> 写道：


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:33，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA I cannot use your document, seems like github cannot load document via mail-reply, pleaase attach your doc file directly to github via web interface

**Comment by BuenosA** [comment] 2018-08-13 14:50
[11.doc.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2283463/11.doc.zip)

**Comment by BuenosA** [comment] 2018-08-13 14:51
You're smart！I have uploaded it up.


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 22:49，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA you can zip doc file and attach it to github

**Comment by ShockwaveNN** [comment] 2018-08-13 15:06
@BuenosA 
First of all, seems this is not a doc file, but html document
```
# file 11.doc 
11.doc: HTML document, UTF-8 Unicode text, with very long lines, with CRLF, LF line terminator
```
I renamed it to `11.html`, it converted to 11.docx as any other html file and it opened fine on my local server
![image](https://user-images.githubusercontent.com/668524/44040038-297624a8-9f23-11e8-8fd9-ba0550d3c045.png)

Second, if you have troubles opening this html file on your server - you should increase RAM size, since convert from html is pretty resourceful process for DocumentServer

Third - seems you using some custom config for example page, since html file is not converted to docx by default (also I see minor diffrences in css)
Onlyoffice DocumentServer cannot edit html directly, only by converting them to docx and editing docx

**Comment by ShockwaveNN** [comment] 2018-08-13 15:25
@BuenosA your attached not an doc file, it should not be opened properly
And I have a lot of troubles understanding that do you mean.

**Comment by BuenosA** [comment] 2018-08-13 15:33
You open this try, this is doc. please


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 23:25，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA your attached not an doc file, it should not be opened properly
And I have a lot of troubles understanding that do you mean.

**Comment by ShockwaveNN** [comment] 2018-08-13 15:35
@BuenosA you didn't attach anything

**Comment by BuenosA** [comment] 2018-08-13 15:37
[11.doc.zip](https://github.com/ONLYOFFICE/DocumentServer/files/2283621/11.doc.zip)

**Comment by BuenosA** [comment] 2018-08-13 15:37
| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 23:35，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA you didn't attach anything

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易邮箱大师发来的云附件
11.doc(100KB,2018年8月28日 23:37 到期)
下载

**Comment by ShockwaveNN** [comment] 2018-08-13 15:39
@BuenosA this is not a doc file as I said in https://github.com/ONLYOFFICE/DocumentServer/issues/362#issuecomment-412551072
I'm closing this issue, since you simply didn't understand me

**Closed by ShockwaveNN** 2018-08-13 15:39 UTC

**Comment by BuenosA** [comment] 2018-08-13 15:49
I apologize to you for my apology, sorry, can you delete the content of that document you sent, which leaked some personal information, I'm sorry, please


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 23:39，Pavel Lobashov<notifications@github.com> 写道：

Closed #362.

**Comment by ShockwaveNN** [comment] 2018-08-13 15:51
@BuenosA I deleted screenshot of this document and your links to it

**Comment by BuenosA** [comment] 2018-08-13 15:54
Thank you for your patience, good bye.


| |
18713212140
|
|
m18713212140@163.com
|
签名由网易邮箱大师定制


在2018年08月13日 23:51，Pavel Lobashov<notifications@github.com> 写道：

@BuenosA I deleted screenshot of this document and your links to it
