### ISSUE TITLE
Line wrapping was disabled for the table, but did not take effect

### ISSUE THREAD

**Issue by RebelTinker** [ONLYOFFICE/DocumentServer#2321] opened 2023-08-08 01:18 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1

### Expected Behavior

The height and width are fixed, and the text adaptively resizes

### Actual Behavior

Table line feed

### Reproduction Steps

1.New form
2.Right-click to set advanced table options
3.Uncheck the table line feed option

### Additional information

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/58228765/eda1afeb-e6be-45de-ac35-cd59330eb4df)
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/58228765/d347f3d1-a822-4645-826f-7c9a66f7e232)
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/58228765/9bf243b1-c05f-490a-b155-50d20eaf73c1)

**Comment by TatianaKirillova** [comment] 2023-08-10 10:48
Hello, @RebelTinker 
Thank you for report.
Please attach your problem file

**Comment by RebelTinker** [comment] 2023-08-10 11:18
[](url)
[test.docx](https://github.com/ONLYOFFICE/DocumentServer/files/12312111/test.docx)

**Comment by RebelTinker** [comment] 2023-08-10 11:18
[test.docx](https://github.com/ONLYOFFICE/DocumentServer/files/12312124/test.docx)
@TatianaKirillova

**Comment by TatianaKirillova** [comment] 2023-08-10 16:26
Thanks, @RebelTinker !

**Comment by RebelTinker** [comment] 2023-08-30 14:06
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/58228765/9f0e4e25-94b4-4319-8379-c574ac4219d2)
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/58228765/96f91193-536b-4b77-8931-b0865d0e648f)
I need to achieve this effect can I achieve it

**Comment by RebelTinker** [comment] 2023-08-30 14:06
@TatianaKirillova

**Comment by TatianaKirillova** [comment] 2023-08-30 14:21
@RebelTinker  Do you want the first cell to be without text wrapping?

**Comment by RebelTinker** [comment] 2023-08-31 03:37
yes @TatianaKirillova

**Comment by RebelTinker** [comment] 2023-09-27 02:55
@TatianaKirillova Hello, may I ask whether my feedback problem exists or is this a functional requirement, the effect to be achieved is that when the table is set not to break the line, then the text in the table will not break the line in any case and the text in the table will adjust its size adaptively

**Comment by TatianaKirillova** [comment] 2023-09-27 13:04
@RebelTinker Yes, this will also depend on the table fields on the ruler above.

**Comment by RebelTinker** [comment] 2023-09-27 13:06
@TatianaKirillova  So how do I need to implement the effect of no line feed and adaptive size, or will you support this feature later

**Comment by RebelTinker** [comment] 2023-09-28 02:09
@TatianaKirillova Is the enterprise edition supported? If it's supported, I can buy the enterprise edition

**Comment by TatianaKirillova** [comment] 2023-09-28 07:08
@RebelTinker For purchasing inquiries, please contact sales@onlyoffice.com

**Comment by TatianaKirillova** [comment] 2023-09-28 08:45
@RebelTinker, on the issue of implementation: Yes, I can confirm - this is a known bug, issue No. 52242 with your problem.

**Comment by RebelTinker** [comment] 2023-09-28 08:47
thank @TatianaKirillova

**Comment by Rita-Bubnova** [comment] 2023-09-28 14:21
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2119.

**Closed** 2023-09-28 14:21 UTC
Labels: duplicate
