### ISSUE TITLE
IPhone can't input Chinese，but Android and PC can

### ISSUE THREAD

**Issue by hqzhen** [ONLYOFFICE/DocumentServer#503] opened 2019-02-15 01:53 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**

**Browser version:**

**Comment by ShockwaveNN** [comment] 2019-02-15 07:45
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/299
If not - please fill table template correctly

**Closed by ShockwaveNN** 2019-02-15 07:45 UTC
