### ISSUE TITLE
Support relative URL hyperlink in cells

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#1075] opened 2020-11-23 14:27 UTC
**Do you want to request a *feature* or report a *bug*?**

**BUG**

**What is the current behavior?**

If in a cell of sheet A (C:\\my-sheetA.xlsx) you have a hyperlink reference to another sheet (C:\\my-sheetB.xlsx), and you move the sheet to another path/location, the link is not renamed relatively to the new path of sheet A (standard behavior of Excel see https://support.microsoft.com/en-us/help/328440/description-of-link-management-and-storage-in-excel)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1) C:\\my-sheetA.xlsx contains a cell with a hyperlink to C:\\my-sheetB.xlsx
2) my-sheetA.xlsx is moved to location D:\\toto\my-sheetA.xlsx
3) my-sheetA.xlsx still contains C:\\my-sheetB.xlsx

**What is the expected behavior?**

my-sheetA.xlsx hyperlink cell should contains  D:\\toto\my-sheetB.xlsx

**Did this work in previous versions of DocumentServer?**

NO

**DocumentServer version:**

6

**Operating System:**

Centos 7

**Browser version:**

Any

**Comment by Rita-Bubnova** [comment] 2020-11-25 12:51
Hello, @cpot.

If I understood your issue correctly, then this need the editor to support links to local files. But this isn't implemented in the document server. This is a technically difficult task. So this task can take a lot of time to implement.
In the future, we plan to add links to external files (issue 38646 in our private issue tracker).

**Comment by cpot** [comment] 2020-12-02 08:26
Hello @Rita-Bubnova,

I don't think you understood correctly. It is not a problem of file being local (i understood you don't have yet the functionality) or remote (ex. webdav link). It is, if you move 2 files (with cell referring to another one in the other file) from one location to another, Excel understand it and cell link see the new location.

In short, it has a path location included. It is well explained in the Microsoft link i attached.

So if my-sheetA.xlsx and my-sheetB.xlsx are in https://xxx.xxx.xxx/dirA/
and the 2 files are moved to https://xxx.xxx.xxx/dirB/

the link inside the cell is automatically changed for https://xxx.xxx.xxx/dirB/my-sheetB.xlsx (previously it was https://xxx.xxx.xxx/dirA/my-sheetB.xlsx

I hope it is clearer

**Comment by LuckySpecialist** [comment] 2020-12-24 15:42
Hi @cpot !
Based on the initial description (which, by the way, contains an error / typo in the expected behavior), I also realized that this is related to local files. It is not very clear how this can be applied to Document Server, if only to the Desktop Editor.

In the Microsoft article (which you gave) the description seems to be out of date because I could not repeat the scenario described there (similar to yours). If the files are in different folders, an error occurs: the specified file cannot be opened. This is how MS Excel 2013 works for me.

Your second scenario is clearer and more logical, because the files are in the same directory, but it has nothing to do with local files.

In any case, as @Rita-Bubnova has already written above, the application needs to be improved to support working with external files (no matter if they are local or on network resources). There are plans to do this, but the priority of this task is low and there are no specific deadlines.

**Comment by cpot** [comment] 2021-02-15 13:06
Hi @LuckySpecialist , perhaps it is not very clear but at the end it will be perfect to work as closely as Office. 

It seems that they have the path that can change dynamically even if it is C:\... and you move it on a remote server it will change to \\remote-server\ ....

**Comment by LuckySpecialist** [comment] 2021-02-17 08:16
Hello, @cpot !
Once again, I could not repeat the scenario with moving the file to another directory and having the link change automatically in either MS Office 2013 or MS Office 365. If you have a working script to reproduce the behavior you described, I can test it.

**Comment by ShockwaveNN** [comment] 2021-06-01 13:23
I'll close this issue since we cannot reproduce this problem but feel free to comment if something not right and we should reopen

**Closed by ShockwaveNN** 2021-06-01 13:23 UTC

**Comment by cpot** [comment] 2021-06-03 10:24
> 
> 
> I'll close this issue since we cannot reproduce this problem but feel free to comment if something not right and we should reopen

We will try to find time to document better this issue

**Comment by ShockwaveNN** [comment] 2021-06-03 10:29
@cpot Ok, thanks, you may create a new one or comment here and I'll reopen this one
