### ISSUE TITLE
/lib64/libcurl-gnutls.so.4: no version information available (required by /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t)

### ISSUE THREAD

**Issue by wpyuan** [ONLYOFFICE/DocumentServer#507] opened 2019-02-19 12:41 UTC
Error Log:
[ERROR] nodeJS - ExitCodecode=80;signal=null;error:-80;id=176445C2AFFA6D1EA7E1）
[ERROR] nodeJS - stdout (id=7EEC22E89FB5A33414A6):
[ERROR] nodeJS - stderr (id=7EEC22E89FB5A33414A6): /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t: /lib64/libcurl-gnutls.so.4:   no version information available (required by /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t)

Current Behavior:
After the server power failure, restart the onlyoffice service and use the online document preview service exception.
errorCode:  -82

Expected Behavior:
I want to use document previews normally.

DocumentServer version:  not latest

Operating System:  RedHat7

Browser version: Chrome70

**Comment by ShockwaveNN** [comment] 2019-02-19 12:51
Duplicate of #434

**Closed by ShockwaveNN** 2019-02-19 12:51 UTC

**Comment by wangka-na** [comment] 2021-08-17 11:40
I saw same question!Can you please answer how to solve the problem?

**Comment by ShockwaveNN** [comment] 2021-08-17 12:21
@wangka-na Are you sure you've using latest version of os and DocumentServer, I think problem was resolved a long time

**Comment by wangka-na** [comment] 2021-08-18 03:17
thanks，I had solved the problem！I do this：
**yum update libcurl
yum install libcurl-devel**
so,such as "no version information available" missed！But i have another question：download file failed!
At last,I update nodejs's version，solved it!
