### ISSUE TITLE
socket.io.min.js.map not found

### ISSUE THREAD

**Issue by markr512** [ONLYOFFICE/DocumentServer#2850] opened 2024-08-20 02:22 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.1-26

### Expected Behavior

docker container can found this file,and nginx log write client ip is docker inner ip not server ip

### Actual Behavior

docker container can't found this file,
nginx log error
2024/08/20 02:18:31 [error] 9047#9047: *98 open() "/var/www/onlyoffice/documentserver/web-apps/vendor/socketio/socket.io.min.js.map" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /8.1.1-26/web-apps/vendor/socketio/socket.io.min.js.map HTTP/1.1", host: "docservice"

**Comment by igwyd** [comment] 2024-09-02 12:04
Hello @markr512, we know about it ticket #61138, this message is for debugging and does not affect the operation of the ONLYOFFICE-Docs. 
Duplicate of #763

**Closed** 2024-09-02 12:28 UTC
Labels: duplicate
