### ISSUE TITLE
Upgrade 5.4 > 5.5: rendering fails, exception at node_modules/config/lib/config.js

### ISSUE THREAD

**Issue by thommierother** [ONLYOFFICE/DocumentServer#813] opened 2020-03-17 21:15 UTC
After upgrade of a doc server from 5.4.x to 5.5.0 through apt-get the rendering in the UX (integrated in owncloud 10.4)  fails and the logfile at var/log/onlyoffice/documentserver/docservice/err.log shows:

pkg/prelude/bootstrap.js:1185
      throw error;
      ^
Error: Configuration property "services.CoAuthoring.server.editorDataStorage" is not defined
    at Config.get (/snapshot/server/build/server/Common/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/license.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:25:18)

Do I have to modify the config manually and add this property?
This should have been done by the upgrade script ;-)

Bye, Thommie

**Comment by thommierother** [comment] 2020-03-17 21:27
Addon: it looks like docservce and converter can not start

root@docs:/var/www/onlyoffice/documentserver/server# supervisorctl start all
ds:docservice: ERROR (spawn error)
ds:converter: ERROR (spawn error)
ds:metrics: started
ds:spellchecker: started

**Comment by ShockwaveNN** [comment] 2020-03-18 08:48
@thommierother Hi, did you have any custom configs for DocumentServer 5.4? Did you agree to replace default config files on upgrade?

**Comment by thommierother** [comment] 2020-03-18 18:29
No custom stuff. The only thing I had to change before was on the oc side (oc connector) because I use master key encryption, see https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/296#issuecomment-573543232

I just followed the standard upgrade path with apt update, the 5.4 installation was running stable before.

**Comment by ShockwaveNN** [comment] 2020-03-19 09:47
@thommierother I think something went wrong during update and config file is not repleased, I just checked update from 5.4.2 to 5.5.0 and everything fine.

I think you should add missing keys to `/etc/onlyoffice/documentserver/default.json`
See default values here:
https://github.com/ONLYOFFICE/server/blob/master/Common/config/default.json#L87

**Comment by thommierother** [comment] 2020-03-19 14:36
Hm, the containers are starting now:

oot@docs:/var/www/onlyoffice/documentserver# supervisorctl status
ds:converter                     RUNNING   pid 12028, uptime 0:16:12
ds:docservice                    RUNNING   pid 12027, uptime 0:16:12
ds:metrics                       RUNNING   pid 12025, uptime 0:16:12
ds:spellchecker                  RUNNING   pid 12026, uptime 0:16:12
root@docs:/var/www/onlyoffice/documentserver# 

But I still get a download error on the oc server when I open a file, log:

OC
"reqId":"mb9z1JpVss3jnbQUHwYs","level":0,"time":"March 19, 2020 14:26:02","remoteAddr":"136.243.85.153","user":"--","app":"onlyoffice","method":"GET","url":"\/owncloud\/index.php\/apps\/onlyoffice\/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjExNzk1NjIsInVzZXJJZCI6InRob21taWU0Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.DvM020Z3MBAVPIDBoPkynuYjHDJr0V6dy7ikwgLGKwE","message":"Download: 1179562"}
{"reqId":"mb9z1JpVss3jnbQUHwYs","level":3,"time":"March 19, 2020 14:26:02","remoteAddr":"136.243.85.153","user":"--","app":"onlyoffice","method":"GET","url":"\/owncloud\/index.php\/apps\/onlyoffice\/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjExNzk1NjIsInVzZXJJZCI6InRob21taWU0Iiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.DvM020Z3MBAVPIDBoPkynuYjHDJr0V6dy7ikwgLGKwE","message":"Download without jwt"}
{"reqId":"1759d0f3-0137-4305-9107-abfc71cc9ace","level":0,"time":"March 19, 2020 14:26:12","remoteAddr":"87.183.228.49","user":"thommie4","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/thommie4\/","message":"updating token 94053, last check is now 1584627073"}

The nginx log shows noting useful. modified json is attached
[default.zip](https://github.com/ONLYOFFICE/DocumentServer/files/4355087/default.zip)

**Comment by ShockwaveNN** [comment] 2020-03-19 14:43
@thommierother seems that jwt settings are lost, you should configure jwt for DocumentServer again

**Comment by thommierother** [comment] 2020-03-19 14:49
Hu, I configured that last year, do you have a link for me for the documentation? That means we have to recreate the server key plus change the password on both OC servers using the docserver, correct?

**Comment by ShockwaveNN** [comment] 2020-03-19 15:19
https://api.onlyoffice.com/editors/signature/

If you didn't save your jwt key - yeah I think it's need to create a new one on OC servers.
Also if you got any troubles with integration with owncloud - I think it's better to create new issue at https://github.com/ONLYOFFICE/onlyoffice-owncloud since this will be no longer a problem in DocumentServer itself

**Comment by thommierother** [comment] 2020-03-20 22:33
I re-created the jwt values in local.json and on the OC server, but I still get "invalid token" on healthcheck although the string is identical on both sides. When I enter healthcheck through the browser, it replies with "true" The local.json shows:

           "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "[string]"
        },
        "outbox": {
          "string": "[string]"
        },
        "session": {
          "string": "[string]"
        }
      }
    }
  },
  "rabbitmq": {
    "url": "amqp://admin:6swdBuoXyyir8YmX@localhost"
  }

i see no error in the nginx log though. On the other side, on the OC server I see a message which points to an error appearing on the docserver:

{"reqId":"ypYdmtPforwYizmEhPOc","level":3,"time":"March 20, 2020 22:30:27","remoteAddr":"87.183.230.57","user":"admin","app":"onlyoffice","method":"PUT","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/settings\/address","message":"CommandRequest on check error: Error occurred in the document service: Invalid token"}
{"reqId":"CsvGpthqKNV3PlN4BYXs","level":0,"time":"March 20, 2020 22:30:34","remoteAddr":"87.183.230.57","user":"admin","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"token e26384e4ab9d1c10d47e856fe52970a34bbfb986ea88d6a07e0c323e32614e5a6d82189caa4bcbed737e45973c7564dbb8fa9b93e2e7d9fd4ca990c4ad071423 with token id 94292 found, validating"}
{"reqId":"CsvGpthqKNV3PlN4BYXs","level":0,"time":"March 20, 2020 22:30:34","remoteAddr":"87.183.230.57","user":"admin","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"token e26384e4ab9d1c10d47e856fe52970a34bbfb986ea88d6a07e0c323e32614e5a6d82189caa4bcbed737e45973c7564dbb8fa9b93e2e7d9fd4ca990c4ad071423 with token id 94292 found, validating"}

**Comment by thommierother** [comment] 2020-03-21 16:59
problem is solved. After some research and testing, I use the following configuration in local.json:

...
"token": {
  "enable": {
    "request": {
      "inbox": true,
      "outbox": true
    },
    "browser": true
  },
  "inbox": {
    "header": "AuthorizationJwt",
    "inBody": false
  },
  "outbox": {
    "header": "AuthorizationJwt",
    "inBody": false
  }
},
"secret": {
  "inbox": {
    "string": "[secret]"
  },
  "outbox": {
    "string": "[secret]"
  },
  "session": {
    "string": "[secret]"
  }
}
...

The trick was the "AuthorizationJwt" instead of "Authorization", see https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/153 Maybe you should check if the default local.json reflects this requirement ... There were no changes on the ownCloud connector side.

**Comment by ShockwaveNN** [comment] 2020-03-23 08:30
@thommierother by default JWT is disabled and in theory jwt header can be any. I think something wrong happens during update process, but since I cannot reproduce this issue and this issue is resolved - I close this issue. But feel free to comment if have any questions

**Closed by ShockwaveNN** 2020-03-23 08:30 UTC

**Comment by thommierother** [comment] 2020-03-23 08:42
Thats ok. Currently we only have one doc server here and if required, I will add another VM, but this will be a new installation then, so no need to update from 5.4 again
