### ISSUE TITLE
Request to set Takao Gothic as default Japanese font

### ISSUE THREAD

**Issue by satsuki-oshima** [ONLYOFFICE/DocumentServer#2758] opened 2024-06-06 02:42 UTC
### Problem Description
Currently, the default font for Japanese documents in the document-template of the connector application is Arial. This font does not properly support Japanese characters and does not lead to readability issues or an optimal user experience for Japanese speaking users. Also, because Arial is not a Japanese font, kanji characters are rendered in a Chinese style, which is not appropriate for Japanese text.

![Difference_between_Chinese_font_and_Japanese_font](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/assets/126237734/7bafd95e-a98f-421c-986b-d23113221ab7)

### Suggested **Solution**
We recommend setting **Takao Gothic** as the default font for Japanese documents. Takao Gothic is included in the core fonts available in ONLYOFFICE and provides excellent readability for Japanese text. This ensures that Kanji characters are displayed in the correct Japanese style.

### Benefits
- Improves readability and user experience for Japanese speakers.
- Avoids confusion with Kanji characters, as they are displayed in the correct Japanese style.
- Improved document presentation and consistency.
- Better support for multilingual documents.

### Add context
Including an appropriate Japanese font as the default will greatly improve the usability of ONLYOFFICE for Japanese-speaking users and make the platform more inclusive. This change is also in line with the high standard of document presentation expected by our users.

Thank you for considering this request. We look forward to receiving your positive response.

Sorry if it is difficult to read due to machine translation.

Best regards

**Comment by DenisDeeSign** [comment] 2024-06-07 07:42
Moving this issue to DocumentServer repo, since the issue is not related to Document Templates.

**Comment by TatianaKirillova** [comment] 2024-06-26 14:38
Hello,  @satsuki-oshima 
Thanks for your request! I can confirm - this is know bug, issue 47180 in our private issue tracker.

**Comment by Rita-Bubnova** [comment] 2024-06-26 14:40
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/746.

**Closed by Rita-Bubnova** 2024-06-26 14:40 UTC
