### ISSUE TITLE
Conversion from .docx to .rtf and back loses left indentation from custom style

### ISSUE THREAD

**Issue by tsmgodoi** [ONLYOFFICE/DocumentServer#1363] opened 2021-07-29 14:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When converting a .docx file to .rtf file and back, the resulting .docx file loses the left indentation of a custom paragraph style.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a .docx file using Microsoft Word.
2. Create a custom paragraph style with a left indentation.
3. Create a paragraph with text using this custom style.
3. Convert this .docx file to .rtf using OnlyOffice Document Server File Conversion API.
4. Now convert back this .rtf file to .docx using OnlyOffice Document Server File Conversion API.
5. The custom style loses the left indentation.

**What is the expected behavior?**
The custom style will keep its left indentation.

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
5.6.5 or 6.3.1

**Operating System:**
Windows 10 20H2 (OnlyOffice Document Server running under Docker on a Linux environment or on any docker environment)

**Browser version:**
Google Chrome 91.0.4472.114

**Comment by tsmgodoi** [comment] 2021-07-29 16:00
> Hi, I see your scenario require usage of `OnlyOffice Document Server File Conversion API`
> 
> Does same problem occur if we replace step 4 and 5
> 4. Open docx file in DocumentServer web and call `File -> Download as -> RTF`
> 5. Open result RTF file on DocumentServer?

No. Actually if you convert to RTF and back do DOCX using the File -> Download as it works as expected. Moreover, it seems to be losing that left indentation only when converting back from RTF to DOCX and only using the File Conversion API. Despite that, our integration needs to convert it automatically without user intervention. We have a corporate license, by the way.

**Comment by ShockwaveNN** [comment] 2021-07-30 07:31
> Despite that, our integration needs to convert it automatically without user intervention.

Ok, got it, my question was simply if this problem can be reproduced via GUI, since it's easier to write bug to our developers
If not - I'll try to reproduce it as you said

**Comment by Rita-Bubnova** [comment] 2021-07-30 08:42
Hello.
@tsmgodoi, thank you for the detailed report.
I can confirm - this is bug, issue 51616 in our private issue tracker.

**Comment by DenisDeeSign** [comment] 2023-04-27 11:27
I close this issue since DocumentServer v7.3.3 is released. Feel free to comment or reopen it if you got further questions.

**Closed by DenisDeeSign** 2023-04-27 11:27 UTC
Labels: bug, fixed
