### ISSUE TITLE
Feature request for viewing mode "View as Printed"

### ISSUE THREAD

**Issue by oMrSmith** [ONLYOFFICE/DocumentServer#1580] opened 2022-01-12 23:04 UTC
This would be a view which 

- replaces the cursor with a hand symbol (to grap the page)
- hides spelling and grammar issues
- as well as formating signs

... all with one click or shortcut.

As a result, the document would immediately look like a PDF.

This would be extremely helpful
in order to preview the outcome of your document. 

MS Word has an equivalent to this
which is rather slow however...

**Comment by Rita-Bubnova** [comment] 2022-01-13 07:18
Hello, @oMrSmith. 
Do you want to have a print preview?

**Comment by oMrSmith** [comment] 2022-01-13 12:05
No, I guess the equivalent of what I mean,
would be the "Read Mode" in MS Word

![image](https://user-images.githubusercontent.com/78870770/149327039-b546d545-51e5-4bd9-b05a-ba480fbf2d21.png)

It makes your document look like an PDF, but you can switch back and forth easily.

**Comment by Rita-Bubnova** [comment] 2022-01-14 07:42
@oMrSmith, Thanks for your reply.
Now I understand your enhancement. This is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1454.

**Closed** 2022-01-14 07:45 UTC
Labels: duplicate

**Comment by oMrSmith** [comment] 2022-01-14 11:39
Ah, I see! Sorry for duplication.

**Comment by ShockwaveNN** [comment] 2022-01-14 11:40
@oMrSmith It's okay, thank you for your report anyway
