### ISSUE TITLE
When Saving ODS with comment, cell is lost and comment move one column to the right

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#1883] opened 2022-08-29 08:20 UTC
**Do you want to request a *feature* or report a *bug*?**

BUG (CRITICAL)

**What is the current behavior?**

When Saving ODS with comment, cell is lost and comment move one column to the right

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. create an ods file with a cell with content and a comment in Libreoffice or Office (or use attached file)
2. open it in Onlyoffice 7.1 and save it
3. cell content has been deleted and comment has moved 1 column to the right

**What is the expected behavior?**

Cell is not deleted and comment stays in the cell

**Did this work in previous versions of DocumentServer?**

Don't know

**DocumentServer version:**

7.1

**Operating System:**

ALL

**Browser version:**

Firefox 103 and all other, Desktop version also

**Comment by cpot** [comment] 2022-08-29 08:21
here is the test file
[Issue with Comments in ODS.ods](https://github.com/ONLYOFFICE/DocumentServer/files/9442872/Issue.with.Comments.in.ODS.ods)

**Comment by Rita-Bubnova** [comment] 2022-08-30 01:41
Hello @cpot.
Thank you for report. 
I can confirm, this is bug - issue 58769 in our private issue tracker.

**Comment by Rita-Bubnova** [comment] 2022-09-04 19:39
This issue fixed (https://github.com/ONLYOFFICE/core/commit/27ea7c9ffc29e2c1012bf08ce552407d2c3ee4dd) in future major release.

**Comment by ShockwaveNN** [comment] 2022-09-23 16:12
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Closed by ShockwaveNN** 2022-09-23 16:12 UTC
Labels: bug, fixed

**Comment by cpot** [comment] 2022-11-23 14:44
Problem still occur in 7.2.1 please reopen

**Comment by Rita-Bubnova** [comment] 2022-11-23 15:06
> Problem still occur in 7.2.1 please reopen

Sorry, I can't reproduce this problem in version 7.2.1.34 (Windows 11, Chrome 07.0.5304.107). I use your file "Issue.with.Comments.in.ODS.ods". 
Could you attach a video with a demonstration problem?

**Comment by cpot** [comment] 2022-11-23 16:47
sorry, error on our side, it is fixed
