### ISSUE TITLE
When I remove the code on line 6604 of Run.js, it shows better

### ISSUE THREAD

**Issue by yayaQAQ** [ONLYOFFICE/DocumentServer#1552] opened 2021-12-14 02:31 UTC
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
No underline at the end of the line
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Underline at the end of the line
**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer version:**
lastest
**Operating System:**
mac
**Browser version:**

![image](https://user-images.githubusercontent.com/20497531/145921706-3fec3af2-d871-48b7-a395-d6f47d2926d2.png)

delete ```PDSL.Spaces>0``` shows better

![image](https://user-images.githubusercontent.com/20497531/145922182-e401481d-33d9-4627-a062-5e740708e475.png)

Therefore, I would like to know why the underline at the end of the line space is not rendered.

**Comment by ShockwaveNN** [comment] 2021-12-14 07:45
Hi, I think we designed our code that way so it provides better compatibility with Ms Office documents, this line was added a long time ago, before we moved to [git](https://github.com/ONLYOFFICE/sdkjs/commit/dcf16d1598b239330f8c9d5f131fe5c6714f17f1#diff-8cc4ab762b2b11e59e14fcc7218173c31f4b15110bf71e9b6ac627cee72f4cf2R2262)

Could you attach an example of a file in which we render those lines incorrectly?

And in your report there is the line:
> Did this work in previous versions of DocumentServer?
> yes

Could you specify the version in which it worked?

**Comment by yayaQAQ** [comment] 2021-12-14 08:14
[demo.docx](https://github.com/ONLYOFFICE/DocumentServer/files/7709741/demo.docx)
This is demo.

The underline at the end of the line should not be drawn in any version of onlyoffice.
Even the latest version.

This is the performance of the latest version of documentserver-ee (docker)，also not underlined on the end of paragraph. 
![image](https://user-images.githubusercontent.com/20497531/145958235-518b226e-f87b-46f8-b651-9baa72d1211a.png)
I would like to know if onlyoffice is now compatible with the latest version of the open xml protocol? And which version of openxml protocol is currently being followed?

> Hi, I think we designed our code that way so it provides better compatibility with Ms Office documents, this line was added a long time ago, before we moved to [git](https://github.com/ONLYOFFICE/sdkjs/commit/dcf16d1598b239330f8c9d5f131fe5c6714f17f1#diff-8cc4ab762b2b11e59e14fcc7218173c31f4b15110bf71e9b6ac627cee72f4cf2R2262)
> 
> Could you attach an example of a file in which we render those lines incorrectly?
> 
> And in your report there is the line:
> 
> > Did this work in previous versions of DocumentServer?
> > yes
> 
> Could you specify the version in which it worked?

**Comment by ShockwaveNN** [comment] 2021-12-14 08:42
> The underline at the end of the line should not be drawn in any version of onlyoffice.

I think you've found a bug

I've checked this file in MS Office 2021 and LibreOffice and seems that we're rendering this file incorrect (same as Libreoffice, but worse)

MS Word: LibreOffice: ONLYOFFICE DocumentServer
![image](https://user-images.githubusercontent.com/668524/145963333-da23fd1e-1cda-4fdf-b3f5-5afaa12951e6.png)

@TatianaKirillova Please take a look at that and file a bug in our issue tracker

> And which version of openxml protocol is currently being followed?

I'm not very sure, but latest on is 4th Edition, from 2016 and I think we're trying to follow it, to be compatible with latest version of MS Office

**Comment by TatianaKirillova** [comment] 2021-12-14 09:24
Hello, **@yayaQAQ**
Thanks for your request!
I can confirm - this is know bug, issue 53785 in our private issue tracker.

**Comment by ShockwaveNN** [comment] 2021-12-14 09:57
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1512

**Closed by ShockwaveNN** 2021-12-14 09:57 UTC

**Comment by yayaQAQ** [comment] 2021-12-14 12:15
> > The underline at the end of the line should not be drawn in any version of onlyoffice.
> 
> I think you've found a bug
> 
> I've checked this file in MS Office 2021 and LibreOffice and seems that we're rendering this file incorrect (same as Libreoffice, but worse)
> 
> MS Word: LibreOffice: ONLYOFFICE DocumentServer ![image](https://user-images.githubusercontent.com/668524/145963333-da23fd1e-1cda-4fdf-b3f5-5afaa12951e6.png)
> 
> @TatianaKirillova Please take a look at that and file a bug in our issue tracker
> 
> > And which version of openxml protocol is currently being followed?
> 
> I'm not very sure, but latest on is 4th Edition, from 2016 and I think we're trying to follow it, to be compatible with latest version of MS Office

As you show on your image, the underline of LibreOffice is not aligned, may I ask what is the cause of this? I also found this problem in onlyoffice.

**Comment by ShockwaveNN** [comment] 2021-12-14 12:31
> the underline of LibreOffice is not aligned, may I ask what is the cause of this

I do not know, I've have no knowledge of LibreOffice, maybe it's a bug for them also

> I also found this problem in onlyoffice.

Yes it is, and we filed a bug about this, but cannot promise any estimates on fixing it

**Comment by yayaQAQ** [comment] 2021-12-15 00:55
> > the underline of LibreOffice is not aligned, may I ask what is the cause of this
> 
> I do not know, I've have no knowledge of LibreOffice, maybe it's a bug for them also
> 
> > I also found this problem in onlyoffice.
> 
> Yes it is, and we filed a bug about this, but cannot promise any estimates on fixing it

Should this misalignment be documented as an issue?

**Comment by ShockwaveNN** [comment] 2021-12-15 07:14
> Should this misalignment be documented as an issue?

Sorry, do you talking about filing an issue at LibreOffice? If so - feel free to do this
But about ONLYOFFICE DocumentServer - as I said earlier - we already filed an issue
