### ISSUE TITLE
Fix default page size for Canadian users?

### ISSUE THREAD

**Issue by asifbacchus** [ONLYOFFICE/DocumentServer#2612] opened 2024-02-23 09:05 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

Could you *please* change the default page size for Canadian regions from A4 to US Letter? There is literally absolutely no one in the entire country that uses A4. We ALL use US Letter. I'm not even sure it's possible to buy A4 paper here 😛 Having to create a template or change this setting each time a document is created is quite painful for an otherwise outstanding product! Much appreciated if this can be done and set as a default.

Thanks for considering this request!

**Comment by TatianaKirillova** [comment] 2024-02-27 12:27
Hello, @asifbacchus 
Thank you for report. I can confirm - this is know bug, issue 59552 in our private issue tracker.

**Comment by Rita-Bubnova** [comment] 2024-02-27 12:35
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/1317.

**Closed by Rita-Bubnova** 2024-02-27 12:35 UTC
