### ISSUE TITLE
Change context of ODT file after resave it as ODT

### ISSUE THREAD

**Issue by jlemangarin** [ONLYOFFICE/DocumentServer#1375] opened 2021-08-06 08:13 UTC
**INFO** : Issue transferred from https://github.com/ONLYOFFICE/onlyoffice-alfresco/issues/99 because the behavior is the same using the "save as odt" in the desktop editor, meaning the issue is with the OnlyOffice core convertor

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
DOCX => ODT conversion issue with the tracking changes feature

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Files : 
- [revision1.odt](https://github.com/ONLYOFFICE/onlyoffice-alfresco/files/6937693/revision1.odt)
- [revision2.odt](https://github.com/ONLYOFFICE/onlyoffice-alfresco/files/6937694/revision2.odt)
- [revision3.odt](https://github.com/ONLYOFFICE/onlyoffice-alfresco/files/6937695/revision3.odt)

The original document is **revision1.odt** with multiple changes (hidden by configuration)

When opening the document with OnlyOffice, the ODT => DOCX conversion works and all is in place (the document have been truncated on purpose)

![image](https://user-images.githubusercontent.com/22454938/128330848-e07a26c4-c2e7-4b3a-aa09-3c9ee6c05006.png)

I accept a random change (The paragraph in the 2nd line) and close the document, so with the new version of the plugin it is converted back to ODT. But the document is malformed, this is **revision2.odt**.

When I open it again in Onlyoffice I see the same thing :

![image](https://user-images.githubusercontent.com/22454938/128331637-768aba14-b982-453c-a471-3cdedf7c57a4.png)

I thought there was some conversion issues because of missing features or something like this but now they are "fixed", so I just remove a blank line and close the document again, and after that I'm unable to open it anymore, this is **revision3.odt** : 

![image](https://user-images.githubusercontent.com/22454938/128331956-be8bb266-c042-4115-91e2-478306e088b6.png)

**What is the expected behavior?**
Conversion works

**Did this work in previous versions of DocumentServer?**
This is a new feature

**DocumentServer version:**
6.3.1 with Alfresco plugin 4.3.0

**Operating System:**
Centos 7

**Browser version:**
//

**Comment by XDmitryK** [comment] 2021-08-06 13:10
@jlemangarin 
Hi
Can you attach a short video of the problem here?
Because i tried reproduce this issue on our Alfresco server, unfortunately i can't repeat

**Comment by jlemangarin** [comment] 2021-08-11 15:10
Hello @XDmitryK,

Did you try to open the document with LibreOffice after doing the scenario ?

**Comment by cpot** [comment] 2021-08-11 16:09
I will add that it as soon as you do a modification of an odt with revision marks, when you reopen the odt document it is broken in Word, LibreOffice and also Onlyoffice, MAJOR issue here

**Comment by ShockwaveNN** [comment] 2021-08-12 06:58
Any chance we can reproduce this error without involving Alfresco?

In our team people who know DocumentServer very well (like me or @XDmitryK ) have almost no experience with Alfresco

If not, Alfresco is required for this issue - simple video will help us very much

**Comment by cpot** [comment] 2021-08-12 08:39
Hi @ShockwaveNN !
In fact it has nothing to do with Alfresco. You can reproduce it with Onlyoffice Desktop 6.3.1 in few clicks.
ODT engine is totally broken ... Please be aware that ODT format is the official format of several french ministries 

1) Open [example ODT problem with Onlyoffice.odt](https://github.com/ONLYOFFICE/DocumentServer/files/6973897/example.ODT.problem.with.Onlyoffice.odt) with Onlyoffice Desktop
2) You will first notice that a paragraph is in 10pts instead of 12pts but that is not the main issue
3) Add 'YYYYY' anywhere, SAVE
4) Reopen the saved file with Onlyoffice, everything is broken (see second screenshot)

Original ODT file in onlyloffice : 
![image](https://user-images.githubusercontent.com/3287514/129164456-9a123091-6eb0-4098-bb2e-0dfc65beb145.png)

File after Onyloffice edition : 

![image](https://user-images.githubusercontent.com/3287514/129165340-ee2037fd-b59c-4275-9daf-95551b3449b6.png)

**Comment by ShockwaveNN** [comment] 2021-08-12 08:41
@cpot Thank you we'll take a look, this scenario is much simpler that original one with alfresco

**Comment by Rita-Bubnova** [comment] 2021-08-23 11:33
This issue fixed (https://github.com/ONLYOFFICE/core/commit/d4708d8d2ea2efd33adf23c0bcaac18e9cdad433) in future major release.

**Comment by cpot** [comment] 2021-08-23 12:37
This is a very good news @Rita-Bubnova , 6.4 expected date is for ?

**Comment by ShockwaveNN** [comment] 2021-08-23 14:30
@cpot We really hope to release it in a week or two, but as always - we only on latest stage of testing process and we cann suddenly found any critical issue and move release a little bit

**Comment by cpot** [comment] 2022-03-19 11:26
Is this issue closed or not ?

**Comment by ShockwaveNN** [comment] 2022-03-20 07:33
Oops, sorry, seems we forgot to close it.

It should be fixed a long time ago, in v6.4
So I'm closing it

If you got any more trouble with similar scenario - I think it's better to create a new issue

**Closed by ShockwaveNN** 2022-03-20 07:33 UTC
Labels: bug, fixed
