### ISSUE TITLE
OnlyOffice document doesn't fully support Arabic language

### ISSUE THREAD

**Issue by Sys-Admin889** [ONLYOFFICE/DocumentServer#818] opened 2020-03-20 08:54 UTC
**Do you want to request a *feature* or report a *bug*?**
   Report a bug.

**What is the current behavior?**
   Using arabic language in documents.   

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
   When writing in Arabic language, the letters are not shown correctly.
  For example: once trying to write anything like "اللغه العربيه", character-by-character rendering is 
  happenning as the following screenshot.

![Capture](https://user-images.githubusercontent.com/59320357/77148887-1d292e00-6a99-11ea-84b0-a2f8e220677c.JPG)

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
   No.

**DocumentServer version:**
   Version 5.5.0.

**Operating System:**
   Ubuntu 18.04 LTS.

**Browser version:**
   Google Chrome version 80.0.3987.132 (Official Build) (64-bit)

**Comment by ShockwaveNN** [comment] 2020-03-20 09:51
RTL is currently not implemented. Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Closed by ShockwaveNN** 2020-03-20 09:51 UTC
