### ISSUE TITLE
Crash because of missing icon

### ISSUE THREAD

**Issue by major-mayer** [ONLYOFFICE/DocumentServer#812] opened 2020-03-17 10:52 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
My Onlyoffice DocumentServer Docker container crashed because of a missing icon:

```
2020/03/16 15:27:16 [error] 899#899: *38 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/img/header/dark-logo@1.5x.png" failed (2: No such file or directory), client: 172.19.0.1, server: , request: "GET /5.5.0-165/web-apps/apps/documenteditor/main/resources/img/header/dark-logo@1.5x.png HTTP/1.1", host: "xxx.xxx", referrer: "https://xxx.xxx/5.5.0-165/web-apps/apps/documenteditor/main/resources/css/app.css"
```
I checked the folder and it contains only these files:
```
root@913be0cfe153:/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/resources/img/header# ls -al
total 24
drwxr-xr-x  2 ds ds 4096 Mar  2 23:00 .
drwxr-xr-x 13 ds ds 4096 Mar  2 23:00 ..
-rw-r--r--  1 ds ds 1517 Mar  2 22:40 dark-logo@2x.png
-rw-r--r--  1 ds ds  727 Mar  2 22:40 dark-logo.png
-rw-r--r--  1 ds ds 2300 Mar  2 22:40 header-logo@2x.png
-rw-r--r--  1 ds ds 1013 Mar  2 22:40 header-logo.png
```

I was only able to notice the crash, because i forgot to enable the automatic restart feature of docker.

**What is the expected behavior?**
It should not crash

**Did this work in previous versions of DocumentServer?**
I don't know, it's the first time i noticed that.

**DocumentServer version:**
Just the latest Docker documentserver version: " onlyoffice/documentserver:latest"

**Operating System:**
The one from the docker container

**Browser version:**
Firefox 74

**Comment by ShockwaveNN** [comment] 2020-03-17 11:47
1.5x icon size currently is not fully implemented and it shouldn't be enabled, seems that problem in that.
Could you describe your display size, resolution, dpi and browser zoom for client for whom this error happened?

**Comment by major-mayer** [comment] 2020-03-17 16:19
I'm not exactly sure at which device this error happened, but if it was my browser then it must be:
Display Size: 27''
Resolution: 3840x2160
Dpi: must be 163 PPI then?
Browser Zoom: 100%

**Comment by ShockwaveNN** [comment] 2020-03-18 08:57
Still was not able to reproduce on my system with same specs, but issue is fixed 
https://github.com/ONLYOFFICE/web-apps/commit/f9d5ba38e5354309c85430ce2921c26439e8e1ab
And will be release in next minor update

**Comment by major-mayer** [comment] 2020-03-18 09:09
Okay that's weird, but thank you anyway!

**Comment by ShockwaveNN** [comment] 2020-03-18 09:16
I'll leave this issue opene until fix is released.
I was able reproduce missing icon with DPI 144, but this not cause DocumentServer to crash. And icon missing only on nextcloud integration.

**Comment by major-mayer** [comment] 2020-03-18 09:19
Okay it could be that the crash was not because of the missing icon.
I wasn't able to reproduce that again.
thanks again for the very fast support!

**Comment by ShockwaveNN** [comment] 2020-04-09 14:21
DocumentServer 5.5.1 released. This issue should be fixed.

**Closed by ShockwaveNN** 2020-04-09 14:21 UTC
Labels: bug, fixed

**Comment by igwyd** [comment] 2024-10-07 11:09
Hello @Ymetro, create a new issue and describe your stand and scenario in more detail so that we can repeat this

**Comment by Ymetro** [comment] 2024-10-24 06:43
Although I got these mentioned messages in the log of de Docker container, it seems that an extension called SafePal (a hardware crypto wallet) is the one culprit preventing opening documents within Nextcloud with the Document Server. I have contacted them about this.
