### ISSUE TITLE
Perfomance issue

### ISSUE THREAD

**Issue by Emil9736** [ONLYOFFICE/DocumentServer#1823] opened 2022-07-11 17:59 UTC
Very high CPU utilization while starting application and creating new text document or spreadsheet or presentation. It's more heavy and slow than Microsoft Office or any other office suite.

**Comment by Emil9736** [comment] 2022-07-31 09:10
I tried the latest version on that moment and got performance issue. Why it heavy on creating new empty file ?

**Comment by ShockwaveNN** [comment] 2022-08-01 07:59
> Why it heavy on creating new empty file ? I use only standard preinstalled fonts and fonts which come with LO

Didn't you install any custom fonts, like CJK?

And you still didn't filled out issue template, not to mention your system, type on installation or other custom steps

> Microsoft Office or any other office suite.

Since you've created this issue in DocumentServer repo I presume this is issue for documentserver (and not the duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/984 for other product) - it's not fair to compare our DocumentServer with MS Office 365 (other online suite), since we do some work on backend of documentserver and it's public, but backend of Office 365 are not publically aviable

**Comment by Emil9736** [comment] 2022-08-04 13:19
> Didn't you install any custom fonts, like CJK?
No I didn't.
> And you still didn't filled out issue template, not to mention your system, type on installation or other custom steps
On web site only available exe installer, full installation. Windows 10 19044.1826. 
> > Microsoft Office or any other office suite.
> 
> Since you've created this issue in DocumentServer repo I presume this is issue for documentserver (and not the duplicate of [ONLYOFFICE/DesktopEditors#984](https://github.com/ONLYOFFICE/DesktopEditors/issues/984) for other product) - it's not fair to compare our DocumentServer with MS Office 365 (other online suite), since we do some work on backend of documentserver and it's public, but backend of Office 365 are not publically aviable

I don't compare functional side. For me enough functions. Yes MS Office products is closed. No need to show their solutions to optimize performance fro own project.

**Comment by ShockwaveNN** [comment] 2022-08-15 13:40
> I don't compare functional side. For me enough functions. Yes MS Office products is closed. No need to show their solutions to optimize performance fro own project.

I don't understand this response, sorry, please fill out issue template and provide steps to how to reproduce this performance issue on our own servers

**Comment by ShockwaveNN** [comment] 2022-10-12 06:55
This issue was closed due to no response.

**Closed by ShockwaveNN** 2022-10-12 06:55 UTC
Labels: waiting feedback
