### ISSUE TITLE
Incorrect print range result for xlsx 

### ISSUE THREAD

**Issue by cpot** [ONLYOFFICE/DocumentServer#716] opened 2019-12-13 16:53 UTC
**Do you want to request a *feature* or report a *bug*?**
**BUG (HIGH)**

**What is the current behavior?**
- Print / PDF export does not take in account printing area anymore
- Print / PDF export looses "per tab" Scaling 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use the Excel attached document in which print area and scaling has been defined [Onlyoffice Printing Area and Scaling bugs.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3961769/Onlyoffice.Printing.Area.and.Scaling.bugs.xlsx)
Export for print with parameters : Page = All sheets 
Select "Sheet Settings" = "TAB2". Notice that for TAB2 Scaling is "Actual Size" but should be "Fit Sheet on One Page" (if opened with Excel or see here ![onlyoffice printing area and scaling bugs](https://user-images.githubusercontent.com/3287514/70817060-09eb3000-1dd1-11ea-838f-e09f6d1480cd.PNG))
Hit "Save & Print" : the PDF has 1500 pages (1498 empty ones)

**What is the expected behavior?**
Tab 1 has a print area which should produce 4 pages
Tab 2 has a print area which should produce 1 page 
**Did this work in previous versions of DocumentServer?**
To our knowledge, yes (however not sure)
**DocumentServer version:**
5.4.2
**Operating System:**
Win10
**Browser version:**
ALL + OO Desktop

**Comment by Rita-Bubnova** [comment] 2019-12-16 09:44
Hello, @cpot.

> Select "Sheet Settings" = "TAB2". Notice that for TAB2 Scaling is "Actual Size" but should be "Fit Sheet on One Page" (if opened with Excel or see here

This problem  is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/510/.

> Hit "Save & Print" : the PDF has 1500 pages (1498 empty ones)

This bug is issue 43887 in our internal issue tracker.
Thank you for your report.

**Comment by jlemangarin** [comment] 2019-12-24 15:41
Hello @Rita-Bubnova,

This issue is a regression from v5.4.1 to 5.4.2 and does not match with issue #510 

Could we have a feedback on this ?

Thanks in advance !

**Comment by Rita-Bubnova** [comment] 2019-12-25 08:05
Hello, @jlemangarin.
Could you describe what kind of regression we are talking about?
I check the printing of the “TAB 2” sheet in attach file (Onlyoffice Printing Area and Scaling bugs.xlsx)  in versions 5.4.1.39 and 5.4.2.46 and do not see any changes.

**Comment by jlemangarin** [comment] 2019-12-26 09:25
Sorry I should have been more specific..

If you try to print the tab 1 of this file it will try to print more than 1500 empty pages but the issue is the same in 5.4.1 and in 5.4.2 (I think I was wrong because I tried to print TAB2 on 5.4.1 and TAB1 on 5.4.2).

**Comment by Rita-Bubnova** [comment] 2019-12-27 09:17
@jlemangarin, I can confirm that printing 1,500 pages - this bug is issue 43887 in our internal issue tracker (as I wrote above).
If I understand you correctly, you have no other new problems?

**Comment by jlemangarin** [comment] 2019-12-27 09:28
Ok I've misread your comment, I thought you said issue 43887 is related to #510 

Thank you for your feedback, do you have any target fix version for this issue ?

**Comment by Rita-Bubnova** [comment] 2019-12-27 14:54
Issue 43887 has been fixed (https://github.com/ONLYOFFICE/sdkjs/commit/f16af252ebe0ffe48aa2cf794fc55e2815f93d83) and will be released in future major release.

**Comment by ShockwaveNN** [comment] 2021-06-11 10:41
I'm closing this issue since seems problem was resolved in v5.5

But feel free to comment or open new issue if got any more troubles

**Closed** 2021-06-11 10:41 UTC
Labels: bug, fixed
