### ISSUE TITLE
some text missing

### ISSUE THREAD

**Issue by fendaq** [ONLYOFFICE/DocumentServer#800] opened 2020-03-07 13:49 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
some text missing： 

in word
![image](https://user-images.githubusercontent.com/31738692/76144544-8897f680-60bc-11ea-9e23-6091c58e94c0.png)

in onlyoffice
![image](https://user-images.githubusercontent.com/31738692/76144600-03f9a800-60bd-11ea-849a-e53b6ce0e7aa.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

[1.zip](https://github.com/ONLYOFFICE/DocumentServer/files/4301875/1.zip)

unzip it and open in onlyoffice

**What is the expected behavior?**
 

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
5.4.2
**Operating System:**
ubuntu 18.04
**Browser version:**
chrome 80.0.3987.132

**Comment by Rita-Bubnova** [comment] 2020-06-17 08:45
Hello, @fendaq.
Sorry, we didn’t answer for a long time.

Can you check if the problem is relevant in the new version DocumentServer?
I opened your document in version 5.5.3 (build: 39) and the text on the fifth page is displayed (see screenshot).

![Issue800](https://user-images.githubusercontent.com/25282241/84876439-e52d8900-b08f-11ea-96d5-c680dcd1afb8.png)

But I see a problem with align text. I created new issue 45629 in our private issue tracker.

**Comment by ShockwaveNN** [comment] 2020-10-16 09:31
Actual issue was for missing text
This problem is not actual any more, so I'll close it

Problem with text align actually is for Distributed text property, currently we do not support it and we got new issue about it
https://github.com/ONLYOFFICE/DocumentServer/issues/1018

**Closed by ShockwaveNN** 2020-10-16 09:31 UTC
Labels: bug
