### ISSUE TITLE
Excel reports corruption in XLSX workbook after making edits involving Tables or PivotTables

### ISSUE THREAD

**Issue by IanHead** [ONLYOFFICE/DocumentServer#1567] opened 2021-12-30 01:11 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7, Linux (DEB package)

### Version information

6.4.2.6

### Expected Behavior

It is expected that all XLSX spreadsheets edited in OnlyOffice should also open in Excel with no issues.

### Actual Behavior

When opening an XLSX file where tables have been created or extensively changed in OnlyOffice Desktop Editors, Excel shows a choice dialog saying, "We found a problem with some content in '(file).xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

The 'repaired records' that Excel produces after attempting repairs consistently relate to either Tables, or PivotTables.

Opening the modified XLSX file in OnlyOffice Desktop Editors, LibreOffice Calc and WPS Spreadsheets all show no issues, it is only Excel that ever thinks there is a problem. These errors in the file persist even after accepting the 'repairs' and saving a copy of the file from Excel with further changes made.

### Reproduction Steps

1. Open existing XLSX workbook in Excel and confirm no errors showing.
2. Open same XLSX workbook in OnlyOffice desktop and work in it for a while, creating and manipulating tables.
3. Attempt to open same workbook in Excel again and note errors with tables.

I have attached example files, 'before' and 'after' - the former having been only edited in Excel, then the latter being a copy of the same file after being edited in OnlyOffice Desktop Editors.

[Examples.zip](https://github.com/ONLYOFFICE/DesktopEditors/files/7791132/Examples.zip)

### Additional information

I have been able to consistently reproduce this behaviour in previous versions of OnlyOffice Desktop Editors as well, on both Windows (10 and 11) and Linux (Zorin OS 16). Let me know if there is any other information I can provide on this. Many thanks!

**Comment by ShockwaveNN** [comment] 2021-12-30 08:38
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by IanHead** [comment] 2022-03-07 04:00
Hi all, I have noticed that I seem to be unable to reproduce this issue so far today in version 7.0.1, has it been resolved perhaps?

**Comment by alinasafonova** [comment] 2022-03-09 09:30
@IanHead
In version 7.0.1 this problem still can be reproduced in some scenarios.

But it is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/55bd1fce34b4a0a87fae8998de4c493f9b702f51
It will be released as v7.1.0

**Comment by mr-manuel** [comment] 2022-03-16 12:33
Hello,
I have a similar issue with Excel and cells which are formatted as table. If I enter multi line column names (`ALT + ENTER`) the Excel sheet gets damaged when it's edited with Onlyoffice (7.0.1.37). Then when opening in Excel it says that the sheet is damaged. Also in Onlyoffice the new line is shown as `_x000a_` instead of a new line:

### Excel
![grafik](https://user-images.githubusercontent.com/12592765/158590403-0416abe2-7599-48dc-8553-03e7a6bec370.png)

### Onlyoffice
![grafik](https://user-images.githubusercontent.com/12592765/158590439-3a091026-eb88-4fcc-817f-4b30b0b24635.png)

**Comment by alinasafonova** [comment] 2022-03-16 12:55
Hello, @mr-manuel
We think this problem is different from OP. Could you please create a separate issue?

**Comment by mr-manuel** [comment] 2022-03-16 12:57
Ok, sure

**Comment by ShockwaveNN** [comment] 2022-05-12 16:44
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles

**Closed by ShockwaveNN** 2022-05-12 16:44 UTC
Labels: bug, fixed
