### ISSUE TITLE
chinese order number lose when open docx file in onlyoffice

### ISSUE THREAD

**Issue by swwhcat** [ONLYOFFICE/DocumentServer#734] opened 2020-01-06 07:10 UTC
**Do you want to request a *feature* or report a *bug*?**
   report a bug

**What is the current behavior?**
upload a .docx file with chinese order number, then open in the onlyoffice, the order number lose.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
upload a .docx file with chinese order number, then open in the onlyoffice, the order number lose.
(the docx file see the attach file )
[培训记录.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4025034/default.docx)

**What is the expected behavior?**
   
**Did this work in previous versions of DocumentServer?**
   no

**DocumentServer version:**
   5.4.1
**Operating System:**
   centos
**Browser version:**
   chrome 79

**Comment by bigbencat** [comment] 2020-03-02 08:03
the same error ,please help!
[default.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4274125/default.docx)

use ms word:
<img width="702" alt="office2" src="https://user-images.githubusercontent.com/9876006/75656607-45461e00-5c9f-11ea-8f37-7f8ef4b0f37f.png">

use onlyoffice
<img width="400" alt="onlyoffice" src="https://user-images.githubusercontent.com/9876006/75656628-4d05c280-5c9f-11ea-87ff-4534b121d36b.png">

**Comment by Rita-Bubnova** [comment] 2020-03-02 10:05
Hello, @swwhcat and @bigbencat.
Thank you. I can confirm - this is a bug, issue 44723 in our internal issue tracker.

**Comment by ohmyheartbeat** [comment] 2020-09-11 08:18
@swwhcat you fixit? my version is 4.1.2,how to fix it. (ONLYOFFICE/sdkjs@19a220b) have noting in common.

**Comment by ohmyheartbeat** [comment] 2020-09-11 08:18
@Rita-Bubnova

**Comment by Rita-Bubnova** [comment] 2020-09-11 08:49
@ohmyheartbeat, as I wrote before  this issue fixed in future major release (possible version 6.0).

**Comment by ohmyheartbeat** [comment] 2020-09-11 09:07
I cant find the same source file in my program office code @Rita-Bubnova

**Comment by ShockwaveNN** [comment] 2020-09-11 09:40
> I cant find the same source file in my program office code ,just find sdk-all.js@Rita-Bubnova

Because we provide minified version to user installation

If you want to get this version as soon as possible - there is several variants to do it, but until we make a public release all those version can contain major bugs

**Comment by ShockwaveNN** [comment] 2020-10-16 09:20
DocumentServer v6.0.0 and DesktopEditors v6.0.0 are released.
This issue should be fixed.

Feel free to comment or create another if got any troubles.

**Closed by ShockwaveNN** 2020-10-16 09:20 UTC
Labels: bug, fixed
