### ISSUE TITLE
Nearly all my *.pptx corrupted after saving 

### ISSUE THREAD

**Issue by tobiasgu83** [ONLYOFFICE/DocumentServer#1191] opened 2021-03-23 18:35 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Opening my .pptx for online editing and save a new version. After saving the new version is corrupted.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the attachted .pptx with the online editor. Change something (works really well). Save/Close it. File (new version) is damaged and can't opened again.
[Test_empty.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/6191996/Test_empty.pptx)
**What is the expected behavior?**
Don't getting a damaged file after saving.
[output.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/6191995/output.pptx)

**Did this work in previous versions of DocumentServer?**
Don'n know. It's my first Version
**DocumentServer version:**
6.2 Developer
**Operating System:**
Windows Server 2019
**Browser version:**
Chrome latest

**Comment by Rita-Bubnova** [comment] 2021-03-24 09:05
Hello, @tobiasgu83.
I can confirm - this is bug, issue 49258 in our private issue tracker.

**Comment by tobiasgu83** [comment] 2021-03-24 09:12
Hello Rita,
I can support you with a lot more examples ;). Do you know how long it will take to fix the bug? I bought a real expensive license and have to go online within the next week...
Thanks a lot!

**Comment by trofim24** [comment] 2021-03-24 09:18
We fixed it - https://github.com/ONLYOFFICE/core/pull/548

**Comment by tobiasgu83** [comment] 2021-03-24 09:35
Perfekt! Thank you a lot! How can I get the Quickfix a bit faster? Can I get a dll to replace?

**Comment by tobiasgu83** [comment] 2021-03-24 10:08
Nevertheless I have many more pptx files corrupted after saving and I like to test whether the fix works for them as well. 
Thank you in advanced for your feedback.

**Comment by ShockwaveNN** [comment] 2021-03-24 10:46
@tobiasgu83 We are working hard to release this version as soon as we ablte to do

I see you got a lot of question, since 
> I bought a real expensive license and have to go online within the next week...

I think you should connect with support, which may help anwser for you question better and more detailed

**Comment by ShockwaveNN** [comment] 2021-04-01 07:36
DocumentServer 6.2.1 is released and this issue should be fixed

**Closed by ShockwaveNN** 2021-04-01 07:36 UTC
Labels: bug, fixed
