### ISSUE TITLE
Configured Animations for objects are not displayed in the received edited copy of .odp format file

### ISSUE THREAD

**Issue by Maaayank** [ONLYOFFICE/DocumentServer#2631] opened 2024-03-03 05:58 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server, Linux (DEB package)

### Version information

7.5.1

### Expected Behavior

All configured animation effects should be displayed in edited copy of the file. 

### Actual Behavior

Animations configured for objects are not displayed in the received edited copy of the .odp format file.
Animation is set to None for every object present in the received edited copy of the .odp format file.

### Reproduction Steps

    Open .odp format file in the browser.
    Add animation to objects present in the file.
    Save and close the file.
    Open the received edited copy of the same file and verify animations configured for the objects.

**Comment by ElenaMaaya** [comment] 2024-03-11 12:21
Hello @Maaayank !
Thanks for your report! The problem is not repeated in version 8.0.1 on Windows 11.  Please update to version 8.0.1 and check the problem. Please write here again and send a test file If the problem persists.

**Comment by Rita-Bubnova** [comment] 2024-03-11 12:59
DocumentServer v8.0.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-03-11 12:59 UTC
Labels: confirmed-bug, fixed
