### ISSUE TITLE
Problems with Sinhala language

### ISSUE THREAD

**Issue by Aikatsui** [ONLYOFFICE/DocumentServer#1691] opened 2022-03-19 12:39 UTC
**What is the current behavior?**

Script name: සිංහල (Sinhala)
Code: සිං | si
Language name: Sinhalese or also, sinhala

Cannot type some vowel signs on document, spreadsheet, presentation editors etc.. but we can type everything properly for folder names, file names, talk (jabber client)

![image](https://user-images.githubusercontent.com/63988538/159119528-6c9c0398-6dc0-4785-94a4-9abb3de68a5a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Steps to enable sinhala script: Settings --> Region & Language --> Input Sources --> + --> Sinhala --> Sinhala (wijesekara (m17n))

![image](https://user-images.githubusercontent.com/63988538/159121315-3a028d88-74f1-4973-b967-23aa88dec84e.png)

![image](https://user-images.githubusercontent.com/63988538/159121322-246da5ed-f26a-4617-91fb-a25c035711d1.png)

No problem on LibreOffice and other solutions.

**Operating System:**
Ubuntu 20.04.03

**Browser version:**
Chromium 101.0.4919.0 (Official Build) snap (64-bit)

**Additional Request**
Editors already come with "noto serif sinhala" then please add "noto sans sinhala" as well.
https://fonts.google.com/noto/specimen/Noto+Serif+Sinhala
https://fonts.google.com/noto/specimen/Noto+Sans+Sinhala

**Comment by ShockwaveNN** [comment] 2022-03-20 08:48
Hi, am I right that you cannot correctly type those symbols but if you open a file with those symbols - they are rendered correctly

So the problem in typing, not in rendering?

> but we can type everything properly for folder names, file names, talk (jabber client)

This may be correct, since ONLYOFFICE CommunityServer use completely another framework and seems that it just call browser methods directly, not like DocumentServer

**Comment by Aikatsui** [comment] 2022-03-23 06:52
>So the problem in typing, not in rendering?

Just typing doesn't work as mentioned so i think rendering cannot work too because application doesn't know how to function it. may be you can check libreoffice source too.

Also, you can enable sinhala input method and test typing by following the steps above and screenshot 2

1. Problem with vowel signs

https://user-images.githubusercontent.com/63988538/159638557-e8210f4e-1078-40dc-9c6b-3f8a90392a03.mp4

2. Problem with characters binding (supported characters can bind using " \ " key)

https://user-images.githubusercontent.com/63988538/159638691-0b2b57ff-87db-496f-9d30-56bb3321f557.mp4

3. Unable to write some signs (appear as its pronunciation form)

https://user-images.githubusercontent.com/63988538/159639241-4d0a5653-28e6-417e-8bc3-a8448ed9a5b1.mp4

4. Problem with specific vowels signs (they are not get converted)

https://user-images.githubusercontent.com/63988538/159638966-c73071c8-1c2d-4ce5-a219-49e20867a3a3.mp4

5. Appear duplicate character, if has "්" vowel sign in previous character

https://user-images.githubusercontent.com/63988538/159638249-4e5cebe4-8628-4e26-9063-035a3803ab5b.mp4

6. Signs do not appear with correct format

https://user-images.githubusercontent.com/63988538/159639647-0e5bd5cd-4797-4d4c-995b-1d3eadc60865.mp4

**Comment by ShockwaveNN** [comment] 2022-03-23 07:23
Thanks for detailed report, we'll look into that problem

**Comment by ShockwaveNN** [comment] 2022-04-13 09:09
> because that is urgent;

Hi, I'm sorry, but we handle all issues as soon as we can

If you need this issue with real high priority - it's better to contact sales@onlyoffice.com / support@onlyoffice.com
And they can promise some time frame of fixing it, but seems this issue is not easy to fix right now, so better to discuss estimates with support team. We (QA team) cannot promise any estimates

**Comment by TatianaKirillova** [comment] 2022-04-13 09:35
Hello, [@](https://github.com/michal-barteczko)[Aikatsui](https://github.com/Aikatsui)
I can confirm - this is know bug, issue 54872 in our private issue tracker.

**Comment by Aikatsui** [comment] 2022-04-26 18:48
Resources: If necessary, You can check opensource LibreOffice source code (it doesn't have this sinhala typing problem)

**Comment by KirillovIlya** [comment] 2022-04-27 19:07
@Aikatsui 
Hello, thank you for your report. We are working on fixing many typing issues right now. This issue will be fixed in one of the future releases.

**Comment by OperaART** [comment] 2022-08-21 14:08
We cannot use this office solution in our country :(
And other office solutions don't have this problem. As i see, this is a several years old bug. You have a partner for sri lanka but it seems, they have give-up too https://www.onlyoffice.com/find-partners.aspx
>**Digital Services Colombo (Pvt) Ltd.**
Digital Services Colombo (Pvt) Ltd. is a provider of digital solutions, hosting and cloud services for education segment, technology, infrastructure and economy development, agriculture and exports.

@ShockwaveNN @KirillovIlya

**Comment by ShockwaveNN** [comment] 2022-08-21 15:30
Hi, some (or maybe even all) of the issues with Sinhala are resolved in 7.2 (which will be released probably next month), but we need some time to actualize all the problems

**Comment by OperaART** [comment] 2022-08-21 15:58
>in 7.2 (which will be released probably next month)

Thanks. i like to test edge builds

>some (or maybe even all) of the issues with Sinhala are resolved

This is the main (or major) problem with sinhala; just cannot type properly (with vowels, character binding etc) and i haven't noticed any other problem. perhaps, all issues are related to this

**Comment by ShockwaveNN** [comment] 2022-08-21 16:41
> Thanks. i like to test edge builds

You can check them by installing in docker via

```
docker run -itd -p 80:80 onlyoffice/4testing-documentserver-ee:7.2.0.148
```

But please do not use it in production env

**Comment by OperaART** [comment] 2022-08-21 23:20
checked. no typing problem now.

**Comment by Aikatsui** [comment] 2022-10-01 20:57
Please keep things well - This is an office suite that use for typing, editing etc; If you break its main things then people will switch to other solutions or never try again.

**Document server 7.2.0.148**
No typing errors / problems  as @OperaART said.

Ubuntu 22.04.01 | x11 | Chromium 107.0.5304.10 (Official Build) snap (64-bit)

i found 1 old bug and 2 new bugs in **7.2.1.5** (picked randomly) and desktop editors (snap 7.2.0). 

**(a). 1 old bug**
>4. Appear a duplicate character, if has " ්" vowel sign in previous character

(new examples: 7.2.0.148 vs new versions)
(note: i forgot to use same font but not a font problem)

https://user-images.githubusercontent.com/63988538/193427480-d83ba183-d63a-4c70-b9c9-e1cc9c46c82d.mp4

How to type them?
![ksnip_20221002-005634](https://user-images.githubusercontent.com/63988538/193422365-d3adad72-3b8d-42b7-a7ea-8186c8d9c09f.png)


(old examples: onlyoffice vs libreoffice)

https://user-images.githubusercontent.com/63988538/193422188-337e9f70-f65e-444b-8631-e044354245e0.mp4

**(b). 2 new bugs**

1. onlyoffice doesn't print 5 characters and 1 vowel

![ksnip_20221001-202153](https://user-images.githubusercontent.com/63988538/193422452-7b1e2902-2431-4f23-a0fc-0c4da2d19894.png)

2. If fix a typo (single word) then onlyoffice print many characters

https://user-images.githubusercontent.com/63988538/193427975-e49c7889-d368-4465-9e57-5cdecc222884.mp4

**Comment by Aikatsui** [comment] 2022-10-02 12:04
**Note:** However i couldn't find any sinhala typing bug / problem in current onlyoffice cloud. i can type anything without trouble.

Affected:
onlyoffice document server (tested: 7.2.1.5)
onlyoffice desktop editors (tested: snap candidate / edge builds)

**Comment by Aikatsui** [comment] 2022-10-09 22:31
Note: This bug is partially persist in 7.2.0.148 because sometimes it occurs for e.g. (1), (4) words but almost persist in new versions 

![අනුරුව](https://user-images.githubusercontent.com/63988538/194782157-f1f3502e-62a4-48a8-b12c-a1e6d3d28a96.png)

**Comment by Aikatsui** [comment] 2022-10-10 00:37
Don't confuse with above comments.

This is for 7.2.0.148 (see quotes) (but applies to new versions)

> @ShockwaveNN  Hi, some (or maybe even all) of the issues with Sinhala are resolved in 7.2 (which will be released probably next month), but we need some time to actualize all the problems

>You can check them by installing in docker via
`docker run -itd -p 80:80 onlyoffice/4testing-documentserver-ee:7.2.0.148`

> @OperaART checked. no typing problem now.

You haven't applied any bug fixes to the spreadsheet.
Previously, I only tested document editor (apparently, @OperaART too) but today tested document, spreadsheet, presentation editors

![අනුරුව](https://user-images.githubusercontent.com/63988538/194786740-b3ca083f-e901-44c9-b2d8-0c5dca763cdd.png)

**Comment by Aikatsui** [comment] 2022-10-10 00:42
@ShockwaveNN @TatianaKirillova @KirillovIlya

**Comment by TatianaKirillova** [comment] 2022-10-10 08:16
Hey, @Aikatsui!
The table editor does not yet have language support, but we are working on it. In one of the versions the problem will be solved.

**Comment by pasan93** [comment] 2023-02-19 01:31
@Aikatsui Ligatures (බැඳි අකුරු) support is there from v7.2. Also in the official blog spot, Sinhala has been mentioned as an example for such languages. 

https://www.onlyoffice.com/blog/2022/09/meet-onlyoffice-desktop-editors-v7-2/

**Comment by pasan93** [comment] 2023-02-19 01:33
@Aikatsui Version 7.2 adds support for ligatures (බැඳි අකුරු). Sinhala was also cited as an example of such languages in the official blog article.

https://www.onlyoffice.com/blog/2022/09/meet-onlyoffice-desktop-editors-v7-2/

**Comment by TatianaKirillova** [comment] 2023-06-13 09:46
Hello, @Aikatsui 
I can confirm that the problem exists. I created ticket 63011 in our internal  tracker with your  issue

**Comment by K0R0L** [comment] 2023-06-13 11:02
Hello, @Aikatsui 
It is a chromium bug. In our desktop editor we use this web engine. Please check the problem in chrome - and you will help us if you report a bug on google chrome/chromium.

**Comment by Aikatsui** [comment] 2023-06-25 06:28
@K0R0L Can you please submit this to the chromium bug tracker (google chrome/chromium)? I don't know much about the technical side of this bug. Maybe you can submit it as an individual. Please share the link here; Then i can track it and provide script-related resources (if requested).

**Comment by Aikatsui** [comment] 2023-07-01 07:15
@KirillovIlya please take a look at https://github.com/ONLYOFFICE/DocumentServer/issues/1691#issuecomment-1605893637

**Update:** today i installed the OnlyOffice Desktop Editor (amd64.deb) package ~[github.com...releases/v7.4.0](https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v7.4.0) (2 weeks ago) / 7.4.0-163 and **i could type everything well.** But the problem persist on latest snap package (candidate / stable) june 26 / 7.4.0 rev. 155 https://snapcraft.io/onlyoffice-desktopeditors

https://github.com/ONLYOFFICE/DocumentServer/issues/1691#issuecomment-1588758373
>**(c) OnlyOffice Desktop Editor (Snap)**
(7.3.3  rev. 153  latest/edge)
>
>We cannot type anything with current onlyoffice desktop editor edge build. It doesn't print any e.g. sinhala, chinese, korean characters and only print english characters instead.

I still can see the problem on **OnlyOffice Cloud** https://github.com/ONLYOFFICE/DocumentServer/issues/1691#issuecomment-1588758373
>**(a) OnlyOffice Cloud**
>
>![image](https://github.com/ONLYOFFICE/DocumentServer/assets/63988538/e921c4e7-c116-4729-a2b9-2f0664577648)

I still can see all bugs on **Spreadsheet** (desktop editor & cloud)
>@KirillovIlya  The Spreadsheet editor does not yet have language support, but we are working on it. In one of the next versions the problem will be solved.

**Comment by Aikatsui** [comment] 2023-09-03 13:38
> Hello, @Aikatsui It is a chromium bug. In our desktop editor we use this web engine. Please check the problem in chrome - and you will help us if you report a bug on google chrome/chromium.

Don't worry. I'll submit a bug report to https://bugs.chromium.org/p/chromium and i didn't notice this bug when using onlyoffice cloud on firefox browser and only on chromium browser and onlyoffice desktop.

> Hey, @Aikatsui! The Spreadsheet editor does not yet have language support, but we are working on it. In one of the next versions the problem will be solved.

@Rita-Bubnova @TatianaKirillova Can you share ETA? Due to this reason, We can not switch to the onlyoffice platform.

**Comment by TatianaKirillova** [comment] 2023-09-04 08:11
@Aikatsui Work on this problem is underway. In one of the major releases, we expect a fix of the problem

**Comment by trofim24** [comment] 2023-09-04 13:07
link to issue in chromium bug tracker - https://bugs.chromium.org/p/chromium/issues/detail?id=1478610

**Comment by TatianaKirillova** [comment] 2024-06-21 14:52
I'm happy to announce that the problem in the table editor has also been fixed and is already included in version 8.1.0. Don't miss updates)

**Comment by Rita-Bubnova** [comment] 2024-06-21 14:55
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-06-21 14:55 UTC
Labels: confirmed-bug

**Comment by Aikatsui** [comment] 2025-03-23 22:59
@Rita-Bubnova @TatianaKirillova Please fix this bug

Spreadsheet - Text style boxes

![Image](https://github.com/user-attachments/assets/1842b27a-d193-4274-a5ab-fa1bba61d1d9)
(You can right-click this image and open it in a new tab for a better view)

**Expected result**

![Image](https://github.com/user-attachments/assets/c7738067-f3a1-4e4e-9572-f48a4319c587)

![Image](https://github.com/user-attachments/assets/50c44484-2c66-40c3-8c6c-26b204031c1a)
