### ISSUE TITLE
How to Generate User-specific Watermarks in ONLYOFFICE Preview (Without Using Nextcloud)

### ISSUE THREAD

**Issue by wai52168** [ONLYOFFICE/DocumentServer#2330] opened 2023-08-12 18:25 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

hello admin
Can the following be achieved (without using Nextcloud):
How can I generate watermarks based on the username when previewing in ONLYOFFICE?
Similar to the functionality provided by OnlyOffice with Nextcloud!
https://www.onlyoffice.com/blog/2020/07/onlyoffice-nextcloud-integration-how-to-protect-documents-with-watermark

**Comment by igwyd** [comment] 2023-08-14 11:38
Hello @wai52168, for this we have a plugin [settings](https://api.onlyoffice.com/plugin/example/settings), but it also restricts copying from a documents. You can change this by setting ```copyoutenabled : true``` in the plugin [code](https://github.com/ONLYOFFICE/sdkjs-plugins/blob/master/settings/scripts/code.js#L25).

**Comment by wai52168** [comment] 2023-08-15 01:17
Hello @igwyd

Thank you for your message, this is very helpful.
Is it possible to have a more advanced display mode? (Full-screen and repeated mode)
As I need to prevent photographs of my documents.
Can the watermark cover the entire page and be repeated? Like the example below.
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/81604190/eca193dd-9981-4d5b-8378-c1951e8e765f)


refer to
[Others have the same requirement!](https://github.com/ONLYOFFICE/DocumentServer/issues/1398#issuecomment-909406276)
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/81604190/e870ca82-1154-4345-9c52-02df649eac7a)

**Comment by igwyd** [comment] 2023-08-15 07:10
I created the enhancement bug 52376 for full-screen and repeated mode in the [issue](https://github.com/ONLYOFFICE/DocumentServer/issues/1398) which you found, but there is no news yet. You can try to contact our sales department to implement this. 
Can you explain in more detail what you would like with images/photographs in the document? Should images in watermark documents not be displayed?

**Comment by wai52168** [comment] 2023-08-15 12:31
hello @igwyd 

Thank you for your reply.
For safeguarding important documents, the current watermarking method is unable to provide complete global protection. As it cannot cover the entire page, there is a possibility of it being captured and manipulated.
It's possible to set the watermark dimensions to match the page dimensions and then repeat the generated text. However, this method is not very flexible.

Refer to the Shutterstock website:
https://www.shutterstock.com/
They use a full-screen repeating protection for their documents, which is an effective method.
If OnlyOffice can implement this security mechanism for easy, it would enhance document protection even further. I'm looking forward to it.
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/81604190/146624a6-744e-408a-a462-dff50dc55293)

**Comment by igwyd** [comment] 2023-08-15 12:44
Ok, i get it. I add your request to our enhancement bug 52376.

**Comment by Rita-Bubnova** [comment] 2023-08-15 14:52
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1398.

**Closed by Rita-Bubnova** 2023-08-15 14:52 UTC
