### ISSUE TITLE
nodeJS - changesError: Error: TypeError: L.Sg.PF is null Script

### ISSUE THREAD

**Issue by florian-bellencontre** [ONLYOFFICE/DocumentServer#1917] opened 2022-09-29 09:10 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When editing a document an error appears but it cannot be recovered. No data seems to be lost but you have to reload the document to be able to edit it again.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I do not know the steps to reproduce this error. 

**Did this work in previous versions of DocumentServer?**
Yes we never had this problem with the old version 7.1.1

**DocumentServer version:**
7.2.0

**Operating System of the server:**
Debian GNU/Linux 11 (bullseye)

**Browser version of the client:**
Firefox 104.0.2

**Error log:**
Onlyoffice:
```
[2022-09-29T00:00:11.663] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
[2022-09-29T00:00:11.668] [WARN] [localhost] [docId] [userId] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-09-29T00:00:11.800] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.2.0. Build: 204
[2022-09-29T09:09:04.572] [WARN] [localhost] [74526852] [oc189338b009_user1] nodeJS - error description: errorId = Update Version error
[2022-09-29T09:10:19.068] [WARN] [localhost] [74526852] [oc189338b009_user1] nodeJS - error description: errorId = Update Version error
[2022-09-29T10:29:02.749] [ERROR] [localhost] [3833270331] [oc189338b009_user23] nodeJS - changesError: Error: TypeError: L.Sg.PF is null Script: https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js Line: 2248:444 userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 platform: Linux x86_64 isLoadFullApi: true isDocumentLoadComplete: true StackTrace: a.AscFormat.che@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:2248:444
Ma.prototype.mNb@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all-min.js:1365:380
Cf.prototype.ewc@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:12494:498
Cf.prototype.zg@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:12427:368
lf.prototype.zg@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:9239:20
zi.prototype.zS@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:9998:393
Wk@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:2293:444
im.prototype.Wk@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:9336:310
lf.prototype.sga@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:9222:174
G.AscCommonSlide.HIi/this.Wk@https://onlyoffice_domain/7.2.0-204/sdkjs/slide/sdk-all.js:9083:20

[2022-09-29T10:32:06.603] [WARN] [localhost] [3833270331] [oc189338b009_user2] nodeJS - lockDocumentsTimerId timeout
```

nginx error:
```
2022/09/29 10:31:08 [error] 133572#133572: *15853 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/image-1.jpg" failed (2: No such file or directory), client: X.X.X.X, server: onlyoffice_domain, request: "GET /7.2.0-204/web-apps/apps/documenteditor/main/image-1.jpg HTTP/2.0", host: "onlyoffice_domain", referrer: "https://onlyoffice_domain/7.2.0-204/web-apps/apps/documenteditor/main/index_loader.html?_dc=7.2.0-204&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nextcloud_domain&uitheme=theme-classic-light"
2022/09/29 10:31:12 [error] 133572#133572: *15853 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/image-1.jpg" failed (2: No such file or directory), client: X.X.X.X, server: onlyoffice_domain, request: "GET /7.2.0-204/web-apps/apps/documenteditor/main/image-1.jpg HTTP/2.0", host: "onlyoffice_domain", referrer: "https://onlyoffice_domain/7.2.0-204/web-apps/apps/documenteditor/main/index_loader.html?_dc=7.2.0-204&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nextcloud_domain&uitheme=theme-classic-light"
2022/09/29 10:31:12 [error] 133572#133572: *15853 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/image-1.jpg" failed (2: No such file or directory), client: X.X.X.X, server: onlyoffice_domain, request: "GET /7.2.0-204/web-apps/apps/documenteditor/main/image-1.jpg HTTP/2.0", host: "onlyoffice_domain", referrer: "https://onlyoffice_domain/7.2.0-204/web-apps/apps/documenteditor/main/index_loader.html?_dc=7.2.0-204&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nextcloud_domain&uitheme=theme-classic-light"
```

**Comment by ShockwaveNN** [comment] 2022-10-04 18:31
I'm sorry but I don't think we can fix this bug without ability to reproduce and step-by-step description

There is definitely some bug here. since there is should not be any errors in JS logs, but I don't think we can diagnose without some file, applying changes and etc

**Comment by thibaultamartin** [comment] 2022-10-06 19:41
I have the same errors when setting up a fresh onlyoffice document server (image used: https://hub.docker.com/r/onlyoffice/documentserver/) served behind a traefik reverse-proxy.

The environement variables for the container are:
```
      "JWT_ENABLED": "true",
      "JWT_SECRET": "totallysecrettrustme",
```

and the volumes mounted are:
```
      - onlyoffice-data:/var/www/onlyoffice/Data
      - onlyoffice-logs:/var/log/onlyoffice
      - onlyoffice-cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - onlyoffice-files:/var/www/onlyoffice/documentserver-example/public/files
      - onlyoffice-fonts:/usr/share/fonts

```

After installing the container I monitor the logs to wait for all the services to be fully started, then run `docker exec mycontainer sudo supervisorctl start ds:example` to generate the container, and click on "Go to test example". I create a new spreadsheet, try to open it.

When trying to open it, I get following error server side:
```
[2022-10-06T19:36:04.661] [ERROR] [localhost] [92.139.234.7__10.88.0.9new.xlsx1665084962528] [uid-11] nodeJS - changesError: Error: TypeError: this.Ec is null Script: https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js Line: 1520:368 userAgent: Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 platform: Linux x86_64 isLoadFullApi: true isDocumentLoadComplete: false StackTrace: cc.prototype.izh@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:1520:368
onDocumentContentReady@https://docs.staging.ergaster.org/7.2.0-204/web-apps/apps/spreadsheeteditor/main/app.js:8:2367570
onLongActionEnd@https://docs.staging.ergaster.org/7.2.0-204/web-apps/apps/spreadsheeteditor/main/app.js:8:2362683
D@https://docs.staging.ergaster.org/7.2.0-204/web-apps/apps/spreadsheeteditor/main/app.js:8:7870
m.bind</n<@https://docs.staging.ergaster.org/7.2.0-204/web-apps/apps/spreadsheeteditor/main/app.js:8:8074
b/<@https://docs.staging.ergaster.org/7.2.0-204/web-apps/apps/spreadsheeteditor/main/app.js:8:1249
B.prototype.trigger@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:1159:262
cc.prototype.xe@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:1422:462
cc.prototype.Zy@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:1252:443
cc.prototype.O5e/<@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:1260:480
ke@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:697:115
G.AscCommon.E3h/<@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:697:341
error@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:461:402
Sg/jf.onreadystatechange@https://docs.staging.ergaster.org/7.2.0-204/sdkjs/cell/sdk-all-min.js:477:25

```

Client side I'm greeted with the following:
![Screenshot from 2022-10-06 21-36-26](https://user-images.githubusercontent.com/1688309/194403704-7404ca7c-daed-459b-a4be-ba6d899429fa.png)

Opening Firefox' console gives me:
![Screenshot from 2022-10-06 21-38-09](https://user-images.githubusercontent.com/1688309/194403815-e1b8c2b2-f714-41aa-aa96-79c7d24916dd.png)

Note that whatever kind of document I try to open, I always get the modal telling me "An error has occurred while opening the file".
The stack trace only happens server side when trying to open a spreadsheet though

**Comment by Y0ngg4n** [comment] 2022-10-06 20:57
I think mine is the same issue #1924

**Comment by ShockwaveNN** [comment] 2022-10-09 16:50
@thibaultamartin I think your issue is not related to original one, since you got another error codes
There may be a problem with traefic setup, but not sure how to debug it
Try to disable all traefic options and enable them step-by-step until issue is started to occur again

**Comment by ShockwaveNN** [comment] 2022-10-09 16:51
@Y0ngg4n yours can be the same issue, but if problem occurs for any spreadsheet file - there should be something wrong with your setup

You can check integrated example at `http://docserverurl/welcome` and see if problems occurs where

**Comment by ShockwaveNN** [comment] 2022-10-12 14:48
Thanks! This is really helpfull, we'll check it

**Comment by ShockwaveNN** [comment] 2022-10-12 15:42
I'll leave this issue opened until we release version with fix

**Comment by ShockwaveNN** [comment] 2022-10-21 19:03
DocumentServer v7.2.1 is released and this problem should be fixed

**Closed by ShockwaveNN** 2022-10-21 19:03 UTC
Labels: bug, fixed

**Comment by classical** [comment] 2024-08-01 03:04
TypeError: Cannot read properties of undefined (reading 'UD')
![image](https://github.com/user-attachments/assets/feaa3094-f5cf-447d-9ad7-ecd121be187b)
I also got this error (Onlyoffice 7.2). How to resolve it, thanks
