### ISSUE TITLE
Formula obtained value, cell not updated.

### ISSUE THREAD

**Issue by RumbleWx** [ONLYOFFICE/DocumentServer#2323] opened 2023-08-09 08:14 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2.1

### Expected Behavior

Formula obtains value, cells should be updated immediately.

### Actual Behavior

Formula obtained value, cell not updated.

### Additional information

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/75654441/1b4a8109-ba57-44d2-a569-f640501a5b63)
![image](https://github.com/ONLYOFFICE/DocumentServer/assets/75654441/a0e289ab-b114-4393-9ea0-a2b3eb63aefc)

This is my custom formula that takes values through the network and returns them to cells. If a value cannot be obtained, it defaults to returning a “/” symbol.
But when I opened the file, I found through the development tool that the formula had already taken a value, but the cell was still a “/” symbol.
Only when I reactivate a cell or recalculate a formula will all cells on the entire page update their latest values.

**Comment by RumbleWx** [comment] 2023-08-10 06:23
When the document is opened, the formula is indeed calculated.
It seems that the editor's view has not been refreshed.

**Comment by VladimirProkofiev52** [comment] 2023-08-16 13:28
Hello! @RumbleWx,
Unfortunately, we have not yet implemented an automatic recalculation of the formulas when it is opened files. 
This issue is in our internal tracker is number 51178.
Thanks for your report.

**Comment by Rita-Bubnova** [comment] 2023-08-16 13:33
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1321.

**Closed by Rita-Bubnova** 2023-08-16 13:33 UTC
