### ISSUE TITLE
compatibility problem between Microsoft Word and OnlyOffice documents that use roman page numbers

### ISSUE THREAD

**Issue by charlyrock** [ONLYOFFICE/DocumentServer#2521] opened 2023-12-12 06:14 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1.23

### Expected Behavior

Roman page numbers created in MS Word are also correctly displayed and adopted in OnlyOffice. 

### Actual Behavior

Unfortunately, there is still a compatibility problem between Microsoft Word and OnlyOffice documents that use roman page numbers. We first noticed this in OO version 6.0.2.5. We are currently using version 7.5.1.23 and the problem still exists. 
Roman page numbers are displayed as Arabic page numbers in OnlyOffice. 
Different page number formats are used very often, that directories are marked with roman page numbers and the content with arabic page numbers. It would be great if this could be taken into account and integrated into OnlyOffice in the near future. It would also be great if formatting relating to MS Word page numbers were not lost. 

### Reproduction Steps

1. Create a Word Document in Microsoft Office
2. Format the page numbers for some pages to roman page numbers and for some pages to arabic page numbers
3. Open the document with OnlyOffice
4. Check the page numbers -> it show only arabic page numbers

Microsoft Office Word:
![Screenshot 2023-12-12 070747](https://github.com/ONLYOFFICE/DocumentServer/assets/67680741/7bc89870-33da-4066-9465-1ee53e66f529)

OnlyOffice:
![Screenshot 2023-12-12 070909](https://github.com/ONLYOFFICE/DocumentServer/assets/67680741/c03ae0d8-310c-495c-8af8-3a3fb65fe490)

**Comment by TatianaKirillova** [comment] 2023-12-12 10:29
Hello, @[charlyrock](https://github.com/charlyrock) 
Thanks for your request!
I can confirm - this is know bug, issue #48898 with your problem

**Comment by Rita-Bubnova** [comment] 2023-12-12 10:30
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1251.

**Closed by Rita-Bubnova** 2023-12-12 10:30 UTC
