### ISSUE TITLE
After upgrade to 6.0.1-32 docx documents fail to open

### ISSUE THREAD

**Issue by caniwi** [ONLYOFFICE/DocumentServer#1043] opened 2020-10-28 21:37 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Onlyoffice-documentserver 6.0.1 fails to open existing docx document

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Upgrade from either 5.6.5 or 6.0.0 and an existing docx does not open.  Creating a new document seems fine.

**What is the expected behavior?**
The document would open showing the changes made.

**Did this work in previous versions of DocumentServer?**
Yes, it was noted during the package upgrade of onlyoffice-documentserver that the postinst script reported an error.  Apt log follows:
```
Log started: 2020-10-29  06:27:38
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%^M(Reading database ... 30%^M(Reading database ... 35%^M(Reading database ... 40%^M(Reading database ... 45%^M(Reading database ... 50%^M(Reading database ... 55%^M(Reading database ... 60%^M(Reading database ... 65%^M(Reading database ... 70%^M(Reading database ... 75%^M(Reading database ... 80%^M(Reading database ... 85%^M(Reading database ... 90%^M(Reading database ... 95%^M(Reading database ... 100%^M(Reading database ... 182746 files and directories currently installed.)^M
Preparing to unpack .../onlyoffice-documentserver_6.0.1-32_amd64.deb ...^M
Preparing for shutdown, it can take a lot of time, please wait...Done^M
Stopping documentserver services...^M
ds:docservice: stopped^M
ds:converter: stopped^M
ds:spellchecker: stopped^M
ds:metrics: stopped^M
Unpacking onlyoffice-documentserver (6.0.1-32) over (6.0.0-105) ...^M
^[[1mdpkg:^[[0m ^[[1;33mwarning:^[[0m old onlyoffice-documentserver package post-removal script subprocess returned error exit status 1^M
^[[1mdpkg:^[[0m trying script from the new package instead ...^M
^[[1mdpkg:^[[0m ... it looks like that went OK^M
Setting up onlyoffice-documentserver (6.0.1-32) ...^M
Installing new version of config file /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf ...^M
/var/lib/dpkg/info/onlyoffice-documentserver.postinst: 124: [: false: unexpected operator^M
Generating AllFonts.js, please wait...Done^M
Generating presentation themes, please wait...Done^M
Congratulations, the ONLYOFFICE documentserver has been installed successfully!^M
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...^M
Log ended: 2020-10-29  06:35:38
```

**DocumentServer version:**
6.0.1-32
**Operating System:**
Linux Ubuntu 18.04 and 20.04
**Browser version:**
Firefox 82.0

**Comment by caniwi** [comment] 2020-10-28 21:38
Downgrading back to 6.0.0-105 and the problem does not exist.

**Comment by ShockwaveNN** [comment] 2020-10-29 06:59
> /var/lib/dpkg/info/onlyoffice-documentserver.postinst: 124: [: false: unexpected operator^M

Yeah, this not look correct

And errors in `/var/log/onlyoffice`?

**Comment by caniwi** [comment] 2020-11-01 20:47
Well that snippet was the apt log when applying the upgrade.  I will provide a tar of the /var/log/onlyoffice from the day.

**Comment by caniwi** [comment] 2020-11-01 20:50
[onlyoffice-logs.tar.gz](https://github.com/ONLYOFFICE/DocumentServer/files/5471720/onlyoffice-logs.tar.gz)

**Comment by ShockwaveNN** [comment] 2020-11-02 08:36
There is several errors in your logs, but nothing releated for upgrade process, seems for me

You didn't anwser on my question of some installation configs, could you show result of 

```
sudo debconf-show onlyoffice-documentserver
```
(replace `onlyoffice-documentserver` on your package type, like `onlyoffice-documentserver-ee`)

**Comment by joskapista44** [comment] 2020-11-02 10:27
Hello, 
Same error here during upgrade (onlyoffice-documentserver (6.0.1-32) over (5.4.2-46)):
/var/lib/dpkg/info/onlyoffice-documentserver.postinst: 124: [: false: unexpected operator

**Comment by ShockwaveNN** [comment] 2020-11-02 11:07
Hm. I can confirm 

```
/var/lib/dpkg/info/onlyoffice-documentserver.postinst: 124: [: false: unexpected operator
```

even on clean install using [this](https://github.com/ONLYOFFICE-QA/documentserver-install-from-manual/blob/master/Ubuntu-20.04/Dockerfile) Docker, but seems everything working fine even with this error, need some time to figure out

**Comment by ShockwaveNN** [comment] 2020-11-02 13:04
Seems problem happened on database cleanup, because something wrong with $CLUSTER_MODE variable (seems extra `=` sign, but not 100% true)

on those lines in postinst

```
if [ ! $CLUSTER_MODE == true ]; then
  $PSQL -d $DB_NAME -f "$DIR/server/schema/postgresql/removetbl.sql" \  
  >/dev/null 2>&1
fi
$PSQL -d $DB_NAME -f "$DIR/server/schema/postgresql/createdb.sql" \  
  >/dev/null 2>&1
```

Both those files are here https://github.com/ONLYOFFICE/server/tree/master/schema/postgresql, if you want you can try to apply them manually

**Comment by caniwi** [comment] 2020-11-02 22:55
Hi,
  Yes it definitely looks like the CLUSTER_MODE if statement is incorrect.  I include the requested defconf output...

dpkg -l |grep -i onlyoffice
ii  onlyoffice-documentserver             6.0.0-105                             amd64        Document Server is an open-source office suite that includes


sudo  debconf-show onlyoffice-documentserver
* onlyoffice/db-pwd: (password omitted)
  onlyoffice/rabbitmq-pwd: (password omitted)
* onlyoffice/jwt-secret: secret
  onlyoffice/db-host: localhost
* onlyoffice/spellchecker-port: 8080
* onlyoffice/jwt-enabled: false
  onlyoffice/db-user: onlyoffice
* onlyoffice/ds-port: 80
  onlyoffice/rabbitmq-user: guest
* onlyoffice/jwt-header: Authorization
* onlyoffice/example-port: 3000
* onlyoffice/db-type: postgres
* onlyoffice/docservice-port: 8000
  onlyoffice/rabbitmq-host: localhost
* onlyoffice/cluster-mode: false
  onlyoffice/db-port:
  onlyoffice/remove-db: false
  onlyoffice/db-name: onlyoffice

**Comment by ShockwaveNN** [comment] 2020-11-10 08:58
This issue fixed at https://github.com/ONLYOFFICE/document-server-package/commit/126f91aefe6d0b7d8c2722fa79936e1d21e8d5fe (sorry, private repo)
And we're currently working to release it in DocumentServer 6.0.2 as soon as possible

**Comment by ShockwaveNN** [comment] 2020-11-13 09:48
DocumentServer v6.0.2 is released and 
```
/var/lib/dpkg/info/onlyoffice-documentserver.postinst: 124: [: false: unexpected operator^M
```
error should be fixed, feel free to comment or open new issue if got any troubles

**Closed by ShockwaveNN** 2020-11-13 09:48 UTC
Labels: bug, fixed

**Comment by Tachi107** [comment] 2021-01-17 15:11
I'm having the same issue with onlyoffice-documentserver-ee 6.1.0-83
`/var/lib/dpkg/info/onlyoffice-documentserver-ee.postinst: 127: [: false: unexpected operator`

**Comment by ShockwaveNN** [comment] 2021-01-18 07:25
@Tachi107 Yeah, see https://github.com/ONLYOFFICE/DocumentServer/issues/1088 for details
