### ISSUE TITLE
Issue with french keyboard OS X, Linux and Windows

### ISSUE THREAD

**Issue by remisharrock** [ONLYOFFICE/DocumentServer#11] opened 2015-10-01 22:01 UTC
- on Mac OS X (tested on Safari, Chrome and Firefox latest versions) : whenever I type the "^" key followed by the "e" key, it should write "ê" but it doesn't (types "e" instead).
  The same goes wrong for the key " ¨ " followed by the key "i" should be " ï " + all variants: â , ô , ë etc....
- on Linux tested on Firefox, Chrome latest versions: same issue with ê and ï and variants.
- on Windows 7 (tested on Firefox, Chrome latest versions): ê and ï do work ! but ALT-GR does not work, therefore cannot input characters "@", "~", "#" and so on...
- on Windows 10 (tested on Edge , Chrome, Firefox): ê and ï do work ! but ALT-GR does not.

Why on Windows 7 and Windows 10 the ê and ï do work but not on Mac OS X and Linux ?
Why on Linux ALT-GR does work but not on Windows ? (ALT-GR does not exist on Mac keyboard)

It does work however with hieroglyph input (not tested on all OSes and in every conditions yet) but not user friendly.

I think it is related to:
- http://dev.onlyoffice.org/viewtopic.php?f=3&t=163&p=418
- http://dev.onlyoffice.org/viewtopic.php?f=3&t=849&p=1245
- http://dev.onlyoffice.org/viewtopic.php?f=38&t=6535
- http://feedback.onlyoffice.com/forums/138243-documents/suggestions/9495609-what-s-about-to-make-alt-gr-working-it-s-a-big-i

Keyboard on Windows:
![ec-900-azerty](https://cloud.githubusercontent.com/assets/8048877/10235243/eec5cbc2-689a-11e5-8ac0-915eab2140e4.jpg)

Keyboard on Mac:
![ht1171_01-wireless_keyboard-001-fr](https://cloud.githubusercontent.com/assets/8048877/10235257/07ba02f6-689b-11e5-806c-6844b0d324f7.png)

**Comment by AnaMih** [comment] 2015-10-02 16:02
1) To input special symbols from your keyboard use left shift+key combination.
2) To input non keyboard special symbols use left alt+character code combination. The special symbols table is currently in the stage of developing. For example ALT+456 outputs symbol "╚"
3) Before using special letters you should switch the keyboard layout to hieroglyphs and hold AltGR in the necessary layout. The input method using only AltGR is in the developing. It should be released in next version.

**Comment by remisharrock** [comment] 2015-10-02 17:54
Thank you very much but that does not solve the problem, let me try to explain.
As you can see in the image on my previous message, for all AZERTY french keyboards (either mac or windows keyboards) you always have this special key:
![trema](https://cloud.githubusercontent.com/assets/8048877/10251873/2b4b21e8-6934-11e5-86d7-decf475cfa6e.jpg)
This key is used very often when writing in french that's why it is always present.
This key is called a [DEAD KEY](https://en.wikipedia.org/wiki/Dead_key) because rather than being pressed and held while another key is struck, the DEAD KEY is **pressed and released before** striking the key to be modified. Therefore, the DEAD KEY is different from a typical modifier key (such as AltGr or ⌥ Option) because, when pressed and immediately released, it temporarily changes the mapping of the keyboard waiting for the next keystroke, so it activates a special keyboard mode rather than generates a modifier character.
Here are 2 examples for typing "î" and "ï":
* To write the character î you will first press the ^ key, release it, and then press the i key:
![accent1](https://cloud.githubusercontent.com/assets/8048877/10252284/c8e7b770-6936-11e5-8cbe-77447edfeb1a.jpg)
* To write the character ï you will first press the shift key and the "¨" key while shift is maintained, release both keys, and then press the i key:
![accent](https://cloud.githubusercontent.com/assets/8048877/10252337/1f2ab312-6937-11e5-9f8f-061a7607c1c8.jpg)

My conclusion is that there is a bug in your keystroke capture engine for Mac OS X and Linux (maybe [here](https://github.com/ONLYOFFICE/DocumentServer/blob/master/OfficeWeb/apps/common/main/lib/core/keymaster.js) ? ) . Indeed, for Windows 7 and Windows 10, the DEAD KEY is performing well whereas in Mac OS X and Linux it doesn't do anything, as if the DEAD KEY was not captured...

To answer your solutions:

1) I guess you wanted to say "left alt + key combination" instead of "left shift + key combination" . In this case, many combinations simply don't exist, like the character " â " (even with Alt+Shift or Alt+Ctrl or Alt+Shift+Ctrl modifiers). The only way to write â is to use the dead key explained above. 
2) I tried hard to play with the left ALT key + codes but it does not write anything, never (whereas in other editors it does).
3) As you can see in the Windows Keyboard pictures in my previous message, the AltGr is used for many special characters like #  {  [  |  \  @   ...  it is not user friendly to switch to hieroglyphs input only to type these characters, and it doesn't exist for Spreadsheets (these characters might be quite important for spreadsheets).

Finally, something very interesting in spreadsheets. When editing a cell right in the spreadsheet (double click on it), the DEAD KEY doesn't work on OS X and Linux (but it works on Windows):
![screenshot_2015-10-02_19-39-55](https://cloud.githubusercontent.com/assets/8048877/10253394/675d5d14-693d-11e5-832d-e8261d358921.png)


But when you select a cell and edit the content via the "function bar" at the top THE DEAD KEY WORKS (Mac OS X, Linux and Windows)!:
![screenshot_2015-10-02_19-36-34](https://cloud.githubusercontent.com/assets/8048877/10253311/01c18264-693d-11e5-80bd-f1c032adb95c.png)

Even more strange, when using AltGr to type characters like #  {  [  |  \  @ : When editing a cell right in the spreadsheet (double click on it), the AltGr doesn't work on Windows. But when editing a cell with the "function bar" at the top the AltGr is working ! (except for AltGr + 5 = [ )


Unfortunately, this strange behavior makes it unusable for french casual users to modify the documents with onlyoffice (either word, excel or powerpoint). If I compare with Google Docs/Presentation/Spreadsheets and with Microsoft Office Online (word excel powerpoint), the DEAD KEY and the AltGr are working perfectly on Windows, Mac OS X and Linux on all the latest browsers.

Thanks for reading this to the end, I hope it can help to solve the problem.

**Comment by liangzhengai** [comment] 2016-01-25 02:01
Hello
i'm one of users for your document server.
it is good software.
i like it but there isn't table of contents in word editor.
table of contents is very critical function in document editing.

How can i implement it?
What is problem to implement the table of contents?

in zoho, they implemented table of contents.
Thank you.

**Comment by ibnpetr** [comment] 2016-01-25 11:53
Hello 
Thanks for your feedback!
We will certainly consider implementing your idea in future updates.
Btw 
feel free to share your ideas on our [web forum] (http://dev.onlyoffice.org/viewforum.php?f=42&sid=aebdb52b1660161030e5f5f5997b6cb8)

**Comment by zertrin** [comment] 2016-01-28 13:40
Same problem on German keyboard. No way to enter `@ € { [ ] } \ | ~` in the Document Editor... (All these are to be entered with AltGr key)

This is a critical issue because as long as the problem exist, the community edition is pretty useless for use in the current state. **I've seen that it works correctly on the SaaS version of the product** (on *.onlyoffice.eu). When will the fix be available to the community edition?

I see that the problem already exists since at least last October. What is the current status? It was said on the forum that the fix would come in the next version. When is it due? (approximately, like in 10 days, 1 month, 6 months or 1 year ?)

@liangzhengai please don't hijack this issue for another problem. Either open a new issue or ask on the forum :wink:

**Comment by trofim24** [comment] 2016-06-30 10:15
We are release Open Source Version 4.0.0-9 and fix it.

**Comment by lgrawet** [comment] 2019-06-04 11:23
Hi,

I have the same dead keys issue with Firefox 60.7.0esr/Linux (Debian 9) and OnlyOffice 5.3.0 docker container (accessed from Nextcloud container).

I also have a very similar problem with Mac OS X (not sure about the Firefox version). 
Windows not tested.

"^" + "e" should print "ê"
Linux : prints nothing
Mac OS X : prints "^e"

Same problem with "ë", "ï"...

Chrome browser has no problem.
Firefox + Collabora : no problem.

Thank you

**Comment by Rita-Bubnova** [comment] 2019-06-04 13:06
Hello, @ibnpetr.
Thank you. I can confirm - this is a bug, issue 41773 in our internal issue tracker.

**Comment by ShockwaveNN** [comment] 2019-06-04 13:13
I reopen this issue, seems problem actual almost in same case as original topic starter

**Comment by simmstein** [comment] 2019-06-20 11:35
Any news?

**Comment by Rita-Bubnova** [comment] 2019-06-20 11:49
Hello, @simmstein.
Sorry, no news.

**Comment by simmstein** [comment] 2019-07-17 07:18
Hello! Any news? How can we help?

**Comment by Rita-Bubnova** [comment] 2024-05-06 11:56
> Hello, @ibnpetr. Thank you. I can confirm - this is a bug, issue 41773 in our internal issue tracker.

This has been fixed. 
DocumentServer v8.0.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-05-06 11:56 UTC
Labels: confirmed-bug
