### ISSUE TITLE
Formatting changed when selecting a paragraph with the keyboard

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#2595] opened 2024-02-06 16:36 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

8.0.0

### Expected Behavior

One should be able to select a paragraph with the keyboard without change in formatting.

### Actual Behavior

When selecting a paragraph with the keyboard, there is a sudden change in formatting, as if a long tab is inserted.

### Reproduction Steps

Steps to reproduce:
- Open the attached .docx file in OO
- Place the cursor at the end of line 14
- Hold the shift key and press several times on the down key to select several lines, until line 23
- => There is a sudden change of formatting of line 23

[bug-OO-formatting-changed-with-cursor-movement.docx](https://github.com/ONLYOFFICE/DesktopEditors/files/14183486/bug-OO-formatting-changed-with-cursor-movement.docx)

**Comment by TatianaKirillova** [comment] 2024-04-23 12:21
@parrenin I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/dfbfad609c2a8762cf931939bffb8d54eb3b9d22) and will be included in the next release. Don't miss updates)

**Comment by Juan-132** [comment] 2024-04-24 13:10
Thank you!

**Comment by parrenin** [comment] 2024-06-20 16:41
So this is now fixed in 8.1.0. Thank you.

**Comment by Rita-Bubnova** [comment] 2024-06-21 15:17
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-06-21 15:17 UTC
Labels: confirmed-bug, fixed-release
