### ISSUE TITLE
Font files are not cached by browser and downloads anew each document open

### ISSUE THREAD

**Issue by jfzhangak** [ONLYOFFICE/DocumentServer#1047] opened 2020-10-30 06:02 UTC
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Opening the PDF file is extremely slow and you need to download the JS file
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Uploaded PDF file, copy can be downloaded
**What is the expected behavior?**
Quick open PDF
**Did this work in previous versions of DocumentServer?**
I don't know
**DocumentServer version:**
5.5.3
**Operating System:**
windows10
**Browser version:**
google

**Comment by jfzhangak** [comment] 2020-10-30 06:02
[Uploading 08_预览时包含embedded字样请求耗时严重且无法缓存，对应请求资源在缓存目录下.pdf…]()

**Comment by jfzhangak** [comment] 2020-10-30 06:03
[08_预览时包含embedded字样请求耗时严重且无法缓存，对应请求资源在缓存目录下.pdf](https://github.com/ONLYOFFICE/DocumentServer/files/5463236/08_.embedded.pdf)

**Comment by jfzhangak** [comment] 2020-10-30 06:06
![image](https://user-images.githubusercontent.com/40625956/97666622-07f99080-1ab9-11eb-9cab-2cdd0073b772.png)
Download the JS file

**Comment by ShockwaveNN** [comment] 2020-10-30 08:44
Hi, thanks for your report. We already know about this problem. Issue #47181 in our private bug tracker, but currently we have no great solution for this problem, so I will not promise we will fix it any time soon

**Comment by cpot** [comment] 2020-10-30 08:57
Is this part of the re-write of the PDF Export engine ?

**Comment by ShockwaveNN** [comment] 2020-10-30 09:00
> Is this part of the re-write of the PDF Export engine ?

It's more like rewrite of `docservice` service, this problem is actual not for PDF files but for other files as well

**Comment by nn200433** [comment] 2020-11-02 07:46
I also have this problem, no matter what file, as long as it is opened, it is very slow, almost all the time is spent on downloading fonts

---

*The files used in the demo pictures are 2 different ppt files*


* demo file1
![image](https://user-images.githubusercontent.com/15652213/97842068-fe269600-1d21-11eb-94bb-c3a3faf8b751.png)

* demo file 2
![image](https://user-images.githubusercontent.com/15652213/97842134-172f4700-1d22-11eb-89ae-6a4cde1be093.png)

**Comment by ShockwaveNN** [comment] 2020-12-15 09:34
Issue is fixed on develop branch
https://github.com/ONLYOFFICE/server/commit/ce89110328c42b9c75dd300eea37c671acf0fee2

This will be fixed in over one release, probably 6.3. Currently we do not have ETA of this release, maybe somewhere in first half of 2021

**Comment by jlemangarin** [comment] 2021-03-17 17:37
Hello !

Any ETA on this issue ? Fonts loading seems to be +60% of the loading time.

Thanks in advance !

**Comment by cpot** [comment] 2021-03-17 18:01
In fact we are expecting it in 6.3, can you confirm, it will be great, thx

**Comment by ShockwaveNN** [comment] 2021-03-18 07:39
@jlemangarin @cpot Hi
I can confirm this issue is fixed and I just checked v6.3.0.20 again and font files are cached on example of PDF of topic starter
Please note that v6.3.0 currently in very early stage of release process so I think it'll take several months until it's released

If you want to check it by yourself you can install docker image `onlyoffice/4testing-documentserver-ee:6.3.0.20` but make sure you're did it in test environment, there is plenty of bugs for production use

**Comment by cpot** [comment] 2021-03-18 08:10
> 
> 
> @jlemangarin @cpot Hi
> I can confirm this issue is fixed and I just checked v6.3.0.20 again and font files are cached on example of PDF of topic starter
> Please note that v6.3.0 currently in very early stage of release process so I think it'll take several months until it's released
> 
> If you want to check it by yourself you can install docker image `onlyoffice/4testing-documentserver-ee:6.3.0.20` but make sure you're did it in test environment, there is plenty of bugs for production use

Thank you very much @ShockwaveNN, this is a good news . We were expecting to include Onlyoffice 6.3 in GoFAST 3.10 expected by mid-april, i see now that it will be difficult to do so. Let's wait and see.

**Comment by ShockwaveNN** [comment] 2021-03-18 08:28
@cpot As usual I'm in no position to guarantee any estimates, you're better to contact someone from management position

**Comment by cpot** [comment] 2021-05-14 12:55
@ShockwaveNN we noticed that Release notes for 6.3 are published https://github.com/ONLYOFFICE/DocumentServer/blob/changelog/v6.3.0/CHANGELOG.md

Is this issue fix is included as expected ? 

Thanks, Christopher

**Comment by ShockwaveNN** [comment] 2021-05-14 13:06
@cpot Yeah, I just rechecked latest dev build 6.3.0.104 and font caching seems fine for me

We are on latest phase on preparation of 6.3.0 release, so we hope we'll release this version on next week if nothing critical happens

**Comment by cpot** [comment] 2021-05-14 14:51
Thank you 
We are in the process of releasing GoFAST v3.10 (currently with Onlyoffice 6.2.2) but we will see if we can delay by 1 week to be in sync with your Onlyoffice 6.3 release

**Comment by ShockwaveNN** [comment] 2021-05-14 14:58
@cpot Only advice I can give - do not expect exact time frame for our release, we are usually not very good at deadlines and current release deadline may be moved, since currently we got several critical bugs not fixed

**Comment by cpot** [comment] 2021-05-21 10:49
hi @ShockwaveNN OO6.3 is out, this issue can be closed i imagine. 

"BTW, do you know were we can find the whole bug fix list of 6.3 ?" is still unanswered ;-)

**Comment by cpot** [comment] 2021-05-21 14:10
Well in fact we still have the problem in our QA environment 

![image](https://user-images.githubusercontent.com/3287514/119150771-0987a780-ba4f-11eb-8282-f0fdca2d9655.png)

**Comment by ShockwaveNN** [comment] 2021-05-24 08:17
> hi @ShockwaveNN OO6.3 is out, this issue can be closed i imagine.

Sorry was on vacation, will close all issues soon

> "BTW, do you know were we can find the whole bug fix list of 6.3 ?"

Sorry, we do not have any public list - best chance just look at github, major part of fixed issue come from our private issue tracker and we cannot disclose them fully in changelog by several reason, mainly because there may be hundreds of them and we simply have no manpower to handle this list

> Well in fact we still have the problem in our QA environment

This is interesting, I've got several ideas:
1. Original issue was for PDF file, and I always checked this issue - maybe you got some kind of another problem
2. Maybe your network configuration more complicated - could you try to setup simplest enviroment with just `onlyoffice/documentserver` docker and try to reproduce your problem using integrated test example?

**Comment by cpot** [comment] 2021-05-24 14:01
@ShockwaveNN In fact we discovered that this issue is when it is a private browser that is used, we don't know why, perhaps because the font (WenQuanYi Bitmap Song) is large, and in private mode they are cache size limitation (not sure)

Anyhow is it related to https://github.com/ONLYOFFICE/DocumentServer/issues/1047 where we are going to post additional comments

**Comment by ShockwaveNN** [comment] 2021-05-24 14:39
> private browser that is used

Shouldn't private browser work as like having clean cache? You're sure thit is not a normal situation for private browser

> Anyhow is it related to #843 where we are going to post additional comments

In that case I'll close this issue, since original issue should be resolved

**Closed by ShockwaveNN** 2021-05-24 14:39 UTC
Labels: bug, fixed
