### ISSUE TITLE
WOPI: Access token empty in CheckFileInfo request

### ISSUE THREAD

**Issue by hristianita** [ONLYOFFICE/DocumentServer#1889] opened 2022-09-01 19:05 UTC
Hello, 

I am encountering a problem which might be a bug in the newly implemented OnlyOffice WOPI functionality.

We have implemented our own WOPI host. We run WOPI discovery successfuly and open a web page with an iframe to display the document. This is done similarly to your example test page (which works on its own). In the URL we use on this page, we pass the access token as a query parameter, as required. The problem is that the access token is not sent to our WOPI host in subsequent requests

In the attached picture of a log, it can be seen that in the initial request to OnlyOffice, ,we have added the access token as a query parameter and this is recognized by OnlyOffice. However, OnlyOffice then issues to me a CheckFileInfo request with an empty access token (="").

As a result, our WOPI host returns 401 Unauthorized to this request and the loading of the file fails.

https://drive.google.com/file/d/1GYJpZhYpZl4qqJRRXJxS_1kA-PaYbF5H/view?usp=sharing

Could you please tell us why this is happening? Isn't the WOPI client supposed to use the same access token provide at the start?

DocumentServer version: 7.1.1

Operating System: OnlyOffice installed in Docker container, the browser and our application run on Windows 10

Browser version: Google Chrome

Thank you

**Comment by igwyd** [comment] 2022-09-02 08:12
Hello @hristianita, i checked the integration of our editors with the owncloud, we sending an access token as you see. I think the problem is in the settings of your wopi host. Сheck out our site about wopi integration, maybe you missed something? https://api.onlyoffice.com/editors/wopi/
![log](https://user-images.githubusercontent.com/67538082/188087490-a1fdc185-2fec-49aa-8925-f880a73a4f50.png)

**Comment by hristianita** [comment] 2022-09-05 11:04
Hello, 
Thank you for your reply.
I found the issue - I was passing the access token as a qery parameter rather than in the body of the request.
Now it works.
Thank you!

**Comment by ShockwaveNN** [comment] 2022-09-05 11:47
I'll close this issue if it resolved

**Closed by ShockwaveNN** 2022-09-05 11:47 UTC
