### ISSUE TITLE
Failure at reboot - ubuntu 16.04

### ISSUE THREAD

**Issue by vClouds** [ONLYOFFICE/DocumentServer#77] opened 2017-02-08 22:30 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
nginx error 503
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?** 4.2.8-5

**Comment by ShockwaveNN** [comment] 2017-02-09 08:59
Can you describe steps to reproduce the problem?
Do you use .deb package or docker image?

**Comment by lennonrich** [comment] 2017-02-23 14:18
We're having this too, hopefully a little more info here for you

**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
After installing, if you reboot the server nginx will 502 Bad Gateway

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Fresh Ubuntu 16.04
2. Install OnlyOffice in accordance with [instructions here](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx)
3. Test the document server, get the welcome page
4. Reboot the Ubuntu server
5. Test the document server, get 502 Bad Gateway

**What is the expected behavior?**
Not a bad gateway ;)

**Which versions of DocumentServer, and which browser / OS are affected by this issue? Did this work in previous versions of DocumentServer?**

onlyoffice-documentserver_4.2.10-10_amd64.deb

All browsers, all OS's

**More info**
Doing apt-get install --reinstall onlyoffice-documentserver will get it working again, but after a reboot you're right back to 502 Bad Gateway

/var/log/onlyoffice/documentserver/nginx.error.log displays:
`2017/02/23 13:54:10 [error] 1473#1473: *82 no live upstreams while connecting to upstream, client: 172.168.254.87, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://docservice/favicon.ico", host: "172.168.254.16", referrer: "http://172.168.254.16/welcome/"
2017/02/23 13:59:26 [error] 1427#1427: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.168.254.87, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "172.168.254.16"
2017/02/23 13:59:26 [error] 1427#1427: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.168.254.87, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "172.168.254.16"
2017/02/23 13:59:26 [error] 1427#1427: *1 no live upstreams while connecting to upstream, client: 172.168.254.87, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://docservice/favicon.ico", host: "172.168.254.16", referrer: "http://172.168.254.16/welcome/"
2017/02/23 14:07:31 [error] 1467#1467: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.168.254.88, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "172.168.254.16"
2017/02/23 14:07:31 [error] 1467#1467: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.168.254.88, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "172.168.254.16"
2017/02/23 14:07:31 [error] 1467#1467: *1 no live upstreams while connecting to upstream, client: 172.168.254.88, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://docservice/favicon.ico", host: "172.168.254.16", referrer: "http://172.168.254.16/welcome/"
2017/02/23 14:07:48 [error] 1467#1467: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.168.254.87, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://[::1]:8000/welcome/", host: "172.168.254.16"
2017/02/23 14:07:48 [error] 1467#1467: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.168.254.87, server: , request: "GET /welcome/ HTTP/1.1", upstream: "http://127.0.0.1:8000/welcome/", host: "172.168.254.16"
2017/02/23 14:07:49 [error] 1467#1467: *5 no live upstreams while connecting to upstream, client: 172.168.254.87, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://docservice/favicon.ico", host: "172.168.254.16", referrer: "http://172.168.254.16/welcome/"
`

**Comment by ShockwaveNN** [comment] 2017-02-25 18:31
Seems this is an issue with `supervisor` - see https://github.com/Supervisor/supervisor/issues/735#issuecomment-251936885
and use this to fix it:
```
# Make sure Supervisor comes up after a reboot.
sudo systemctl enable supervisor

# Bring Supervisor up right now.
sudo systemctl start supervisor
```

**Comment by harrie006** [comment] 2017-04-04 11:13
For ubuntu 14.04

 # Make sure Supervisor comes up after a reboot - following will enable the service
 sudo update-rc.d supervisor defaults

 #Bring Supervisor up right now - following will start only office document server
 sudo service supervisor start

**Comment by ShockwaveNN** [comment] 2018-05-17 11:52
Closing since issue should be not actual, supervisor seems fixed it

**Closed by ShockwaveNN** 2018-05-17 11:52 UTC
