### ISSUE TITLE
Uncaught DOMException when third party Cookie blocked (Firefox) 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#1611] opened 2022-01-27 16:11 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when using third Domain, document doesnt load with error:
Uncaught DOMException: The operation is insecure. index.html:262

and

Uncaught DOMException: The operation is insecure. sdk-all-min.js:1249

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
using Firefox and use another domain, block third party cookies and try to load document

**What is the expected behavior?**
load document

**Did this work in previous versions of DocumentServer?**

YES

**DocumentServer version:**
7.0 and 6.4.2

**Operating System:**
debian 11

**Browser version:**
91.5.0esr (64-Bit)
Chromium load document anyway

**Comment by hahaxd35** [comment] 2022-01-28 08:22
here you can see it: (sorry settings in german)
![cookiesettings](https://user-images.githubusercontent.com/48324739/151512109-8b85262c-d8e8-40fa-a207-bd4f784e8788.png)
![error](https://user-images.githubusercontent.com/48324739/151512123-86614985-871c-4352-a4e0-073814ca0cac.png)
![console-error](https://user-images.githubusercontent.com/48324739/151512153-fab34650-0ae4-4fa1-8ec7-0adaf81a6e4e.png)
![with-allowed-cookies](https://user-images.githubusercontent.com/48324739/151512169-ebe44285-2145-4912-a5fc-1d2b20b0e24e.png)
![no-error](https://user-images.githubusercontent.com/48324739/151512187-4f2b42cf-de17-4b98-b070-08f7b29d3b07.png)

**Comment by matveevms** [comment] 2022-01-31 15:59
Hello, @hahaxd35 
Thank you for the report.
I can confirm - this is a bug, issue 55240 in our private issue tracker.

**Comment by matveevms** [comment] 2022-03-23 11:09
Hi.
The problem is fixed via https://github.com/ONLYOFFICE/sdkjs/commit/8608ac4e12c5e8474d61b680617f10e5ad94bce8 and will be available as DocumentServer v7.1, but currently, we have no ETA date

**Comment by ShockwaveNN** [comment] 2022-05-12 16:43
DocumentServer v7.1.0 is released. This issue should be fixed

I'll close this issue, but feel free to comment or open new issues if there are some troubles

**Closed by ShockwaveNN** 2022-05-12 16:43 UTC
Labels: bug, fixed
