### ISSUE TITLE
[Bug] Headers and Footers aren't rendering in documents created and/or edited by MS Office

### ISSUE THREAD

**Issue by Dvlnst** [ONLYOFFICE/DocumentServer#776] opened 2020-02-09 20:58 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Headers and Footers aren't rendering in documents created and/or edited by MS Office. It also happens if header/footer were created with OnlyOffice.

**What is the expected behavior?**
Compatibility between MS Office and OnlyOffice with headers and footers.

**Did this work in previous versions of DocumentServer?**
I don't know.

**DocumentServer version:**
5.4.2-46 (installed from debian repository).

**Operating System:**
Debian 10.

It also happens with OnlyOffice desktop editors version 5.4.2.30 here in Linux so I didn't know where exactly report it. I apologize if you are already awared of this one.

Kind regards.

**Comment by Rita-Bubnova** [comment] 2020-02-10 07:27
Hello, @Dvlnst.
Could you attach file with problem?

**Comment by Dvlnst** [comment] 2020-02-17 12:01
Hi, sorry for late reply. I cannot attach those documents. I've tried to reproduce the problem creating new documents but it seems to work fine.. What can I do to find the problem in these particular documents?

**Comment by perelandra** [comment] 2020-02-19 10:47
We have a similar problem with Docker based Document Editor 5.4.2  
We foundt that: w:header and w:top in the document.xml files don't work as expected.

Scenario: first page header is different from next pages. 
![header-msword](https://user-images.githubusercontent.com/3647980/74826779-76703700-530c-11ea-8777-dc4e138c2cc5.png)
Altering the position, onlyoffice changes not the same attribute as microsoft word desktop.
![header-as-top-onlyoffice](https://user-images.githubusercontent.com/3647980/74826773-740ddd00-530c-11ea-9ca2-e343e140011b.png)
Thanks.

**Comment by Rita-Bubnova** [comment] 2020-02-19 12:25
@Dvlnst, can you replace the contents of the document without changing its structure (especially the headers and f footers ) and attach it?

@perelandra, we are not sure if your problem is with the original issue. Please create a new issue. 
Could you attach file with problem and attach video or gif of this problem?

**Comment by Dvlnst** [comment] 2020-02-19 17:03
I copied an affected document, remove all the content and just keep a couple of pages and then it's working, headers and footers (except pages number style). I attach them here if it helps:
[- Original.](https://github.com/ONLYOFFICE/DocumentServer/files/4226234/TEST-original.docx)
[- Edited (with MS Office).](https://github.com/ONLYOFFICE/DocumentServer/files/4226235/TEST-edited.docx)

**Comment by Rita-Bubnova** [comment] 2020-02-20 08:15
@Dvlnst, what do you mean by "Headers and Footers aren't rendering in documents created and / or edited by MS Office. It also happens if header / footer were created with OnlyOffice"?

I see that the page number differs in the footer (see Screenshot). is the problem this? Can you describe the actions that led to this result?

![Issue](https://user-images.githubusercontent.com/25282241/74913686-34a9c400-53d2-11ea-9e1b-c20c6bc96729.png)

**Comment by Dvlnst** [comment] 2020-02-24 18:12
Sorry for late reply, I've had very busy days. Check the images below:

**- Original document:**

![Screenshot from 2020-02-24 18-12-16](https://user-images.githubusercontent.com/36289254/75174786-7cfa1680-5731-11ea-9bca-d432e1b9f904.png)

**- Once edited in MS Office:**

![Screenshot from 2020-02-24 18-12-32](https://user-images.githubusercontent.com/36289254/75174882-a87d0100-5731-11ea-9583-545a743f4f8b.png)

As you can see, when these documents are edited with MS Office headers/footers disappear. I tried to reproduce the issue creating new fresh documents (for testing), but it seems to work aside page numbers style (as you noticed) and title font that turns to Calibri (see images below).

**- Original Testing document: (Title and date are in Times New Roman)**
![Screenshot from 2020-02-24 18-23-53](https://user-images.githubusercontent.com/36289254/75175657-0d852680-5733-11ea-9163-866a8b254055.png)

**- Once edited in MS Office: (Title and date are in Calibri)**
![Screenshot from 2020-02-24 18-24-17](https://user-images.githubusercontent.com/36289254/75175667-11b14400-5733-11ea-93cd-d3e64b6a9a0c.png)

Those are minor problems, so going back to the main problem, any idea how to find what it's interfering with headers/footers? When we work on those documents with OnlyOffice everything works as expected until they are edited with MS Office. If it's a bug, it's a tricky one probably.

I hope it helps.

**Comment by Rita-Bubnova** [comment] 2020-02-25 13:29
Regarding the screenshot “Original document for testing: (Name and date are in Times New Roman)” I can confirm - this is a bug, issue 44634 in our internal issue tracker.

Regarding the screenshots "Original document" and "Once edited in MS Office" you attached files in which only 4 pages ("Original" and "Edited (with MS Office)") and I do not see this problem there.

**Comment by Dvlnst** [comment] 2020-03-01 13:43
I sent you an email to support@onlyoffice.com with new documents affected. I hope it helps you.

**Comment by Rita-Bubnova** [comment] 2020-08-07 14:41
>  I can confirm - this is a bug, issue 44634 in our internal issue tracker.

This bug is fixed (https://github.com/ONLYOFFICE/sdkjs/commit/b7f4de00df04f197d30dab1d2e88adb61ef1a647) in future major release.

**Comment by ShockwaveNN** [comment] 2021-06-15 13:32
I'm closing this issue, since fix is released in v5.6.0

**Closed by ShockwaveNN** 2021-06-15 13:32 UTC
