### ISSUE TITLE
Spellchecker missing

### ISSUE THREAD

**Issue by BuRaGoChan** [ONLYOFFICE/DocumentServer#715] opened 2019-12-13 04:07 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Keep receiving error messages in the development console once the Document Editor is open, saying "GET http://localhost:8000/spellchecker/doc/50/c/info?t=1576209881659 404 (Not Found)" 
![spellchecker error](https://user-images.githubusercontent.com/32910292/70768591-d690ad00-1da0-11ea-8165-9687ff22cc19.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. open document editor
2. document is loaded
3. errors popped out in the Development Tools
**What is the expected behavior?**
The spellchecker should work perfectly.
**Did this work in previous versions of DocumentServer?**
Not sure.
**DocumentServer version:**
5.4.0.17
**Operating System:**
Windows Server
**Browser version:**
Chrome version 78.0

**Comment by ShockwaveNN** [comment] 2019-12-13 06:06
Which version of nodejs you using?

**Comment by BuRaGoChan** [comment] 2019-12-16 09:09
Nodejs version 8.11.4

**Comment by ShockwaveNN** [comment] 2019-12-16 09:16
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/312

**Comment by BuRaGoChan** [comment] 2019-12-16 09:30
Hi, 

I couldn't follow the solution #312 as I am using Windows server, could you please tell me what I should do to fix it as I am new to OnlyOffice.

Also, the language option in the status bar isn't gray out and I didn't have any error logs in Log/spellchecker, so I am not sure if it is the same problem as #312 .

![image](https://user-images.githubusercontent.com/32910292/70895360-c2abac00-2029-11ea-88cd-5d078498a965.png)

Thanks

**Comment by ShockwaveNN** [comment] 2019-12-16 09:34
Ok, leave issue opened
I have no knowledge in Windows, but steps should be similar,
Stop DocumentServer services
```
cd /var/www/onlyoffice/documentserver/server/SpellChecker
mv node_modules/ node_modules_old/
npm install
```
Start DocumentServer services

**Comment by BuRaGoChan** [comment] 2019-12-16 09:42
Hi,

I have got errors when executing the indicated commands, attached is the error.log.

it said:
767 verbose stack Error: spawn git ENOENT
767 verbose stack     at _errnoException (util.js:992:11)
767 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
767 verbose stack     at onErrorNT (internal/child_process.js:372:16)
767 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
767 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
768 verbose cwd C:\Program Files\ONLYOFFICE\DocumentServer\server\SpellChecker
769 verbose Windows_NT 10.0.18362
770 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
771 verbose node v8.11.4
772 verbose npm  v6.13.4
773 error code ENOENT
774 error syscall spawn git
775 error path git
776 error errno ENOENT
777 error enoent Error while executing:
777 error enoent undefined ls-remote -h -t https://git@github.com/ONLYOFFICE/nodehun.git
777 error enoent
777 error enoent
777 error enoent spawn git ENOENT
778 error enoent This is related to npm not being able to find a file.

Any Ideas please?

Thanks

[2019-12-16T09_40_55_480Z-debug.log](https://github.com/ONLYOFFICE/DocumentServer/files/3967223/2019-12-16T09_40_55_480Z-debug.log)

**Comment by BuRaGoChan** [comment] 2019-12-16 09:51
If the version of Nodejs matters, should I just update Nodejs to a newer version and see if it works?

**Comment by ShockwaveNN** [comment] 2019-12-16 10:01
@BuRaGoChan you should try to downgrade to 6 version of nodejs
Your error indicate that you have no git on your system

**Comment by BuRaGoChan** [comment] 2019-12-17 02:11
Hi,

I have tried the following steps:
1. Stop all OnlyOffice services
2. downgraded Nodejs to version 6
3. rename node_modules
4. execute npm install in Spellchecker directory which resulted in getting a new node_modules directory and files inside it
5. restart all OnlyOffice services

However, the errors still remain.  I would like to ask what Spellchecker files is the Document Server/Document Service looking for?
As I have tried to access Spellchecker via its port number and I have got the following message:
![image](https://user-images.githubusercontent.com/32910292/70958888-8887ec00-20b5-11ea-856f-d76a08d698bb.png)
Not sure what the problem is but hope that I could fix it, thanks.

**Comment by ShockwaveNN** [comment] 2019-12-17 06:05
@DenisDeeSign take a look, seems a Windows specific problem

**Comment by BuRaGoChan** [comment] 2019-12-19 02:56
Any updates please?

**Comment by mikaka65** [comment] 2019-12-23 09:49
@BuRaGoChan Please do not duplicate your messages in different sites. As you have a license and already open tickets at https://onlyofficesupport.zendesk.com/, please write your questions on our technical support site. All information will be in one place and our manager will be able to communicate with you more efficiently. We are aware of this problem, as soon as information appears, we will contact you.

**Comment by ShockwaveNN** [comment] 2019-12-26 10:11
This issue is discussed at http://helpdesk.onlyoffice.com
I'm closing it here

**Closed by ShockwaveNN** 2019-12-26 10:11 UTC

**Comment by BuRaGoChan** [comment] 2020-01-16 10:07
Hi All,

So I have figured out what's wrong which led to the missing Spellchecker in windows.  Actually the SSL/HTTPS has to be set up in order for the spellchecker to work!

Thanks
