### ISSUE TITLE
Document scrolls to cursor when someone edits and make it moves while reading another page

### ISSUE THREAD

**Issue by unteem** [ONLYOFFICE/DocumentServer#2428] opened 2023-10-18 08:05 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1.1

### Expected Behavior

I'm editing on a page and if i scroll up or down to another page to read I want my view to stay on that page

### Actual Behavior

Someone edits where my cursor is and make it moves, I'm scrolled back to where my cursor is while I was reading some content on another page

### Reproduction Steps

1. Edit somewhere
2. Scroll up or down to another page
3. Someone edits on the same paragraph where my cursor is make it move

**Comment by TatianaKirillova** [comment] 2023-10-20 07:52
Hello, @unteem 
Thanks for your request!
I can confirm - this is know bug, issue #63435 with your issue

**Comment by amovsisyan** [comment] 2024-02-07 19:44
Hello dear @TatianaKirillova and @Rita-Bubnova 
May we expect any updates about this known bug ? what is the status ? did it released ? if no, when it would be released 
our customers are really struggling with this problem,

Thanks

**Comment by Rita-Bubnova** [comment] 2024-02-08 10:23
@amovsisyan, Sorry, currently we have no ETA.
I'm just a QA specialist, I'm not in position to gurantee any dates. You better contact sales@onlyoffice.com.

**Comment by TatianaKirillova** [comment] 2024-07-09 13:07
Hello @unteem ! I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/c9979671c7278b0c1965d535e1525ccefa3e50f8) and will be included in the next release. Don't miss updates. Have a nice day!

**Comment by Rita-Bubnova** [comment] 2024-07-17 08:29
DocumentServer v8.1.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-07-17 08:29 UTC
Labels: confirmed-bug, fixed-release
