### ISSUE TITLE
DocumentServer do not support TLSv1.3

### ISSUE THREAD

**Issue by florian-bellencontre** [ONLYOFFICE/DocumentServer#1298] opened 2021-06-09 09:14 UTC
**Do you want to request a *feature* or report a *bug*?**
It seems that this is a bug because the problem was not present before.

**What is the current behavior?**
When we try to edit a document we get a TLS protocol error. My old instance worked perfectly and then one day it stopped working. This instance was running on Debian 10 with a nginx proxy. 

Error:
```
==> converter/out.log <==
[2021-06-08T15:26:13.373] [ERROR] nodeJS - error downloadFile:url=https://domain/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.PVO5b0Jnsc_26516IQcnrzlwYfijhHVbRxE6pWVG0Y0;attempt=1;code:EPROTO;connect:null;(id=conv_check_1627013602_docx)
Error: write EPROTO 140064833886016:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70

    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
[2021-06-08T15:26:14.379] [ERROR] nodeJS - error downloadFile:url=https://domain/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.PVO5b0Jnsc_26516IQcnrzlwYfijhHVbRxE6pWVG0Y0;attempt=2;code:EPROTO;connect:null;(id=conv_check_1627013602_docx)
Error: write EPROTO 140064833886016:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70

    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
[2021-06-08T15:26:15.386] [ERROR] nodeJS - error downloadFile:url=https://domain/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.PVO5b0Jnsc_26516IQcnrzlwYfijhHVbRxE6pWVG0Y0;attempt=3;code:EPROTO;connect:null;(id=conv_check_1627013602_docx)
Error: write EPROTO 140064833886016:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70

    at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
```

Looking through the issues on github I found one that was similar (https://github.com/ONLYOFFICE/DocumentServer/issues/946). I thought that the problem was Erlang < 22 which did not support TLS 1.3. I then created a new instance under Ubuntu 20.04 to have the version 22 of Erlang, but the problem was still present.

The certificate is ok, I checked on SSL Labs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
You can either edit a document or try to modify the onlyoffice server on Nextcloud.

**Did this work in previous versions of DocumentServer?**
As specified above the server was working and one day it was not working anymore.

**DocumentServer version:** ONLYOFFICE-DocumentServer-6.3.0

**Operating System:** Try on Ubuntu Focal and Debian Buster

**Comment by ShockwaveNN** [comment] 2021-06-09 09:24
> As specified above the server was working and one day it was not working anymore.

Am I right you didn't install any updates, it just stopped working

Maybe it's a clock problem? Please check that all clocks are correct on nextcloud and DocumentServer instance

Also I found this:
https://github.com/nodejs/help/issues/2908

Maybe it's a good idea to update openssl on both machines

**Comment by florian-bellencontre** [comment] 2021-06-09 10:09
Thank you for this quick feedback.
Indeed no update has been done.

No problem on the time, the 2 servers are well up to date.

openssl is up to date because it uses the last version of the system packages and the machines have just been created:
Ubuntu: openssl 1.1.1f-1ubuntu2.4
Debian: openssl 1.1.1d-0+deb10u6

**Comment by ShockwaveNN** [comment] 2021-06-09 10:14
> I checked on SSL Labs.

Which version of TLS it showed?

**Comment by florian-bellencontre** [comment] 2021-06-09 11:55
Basically we use this:
![Screenshot_20210609_134732](https://user-images.githubusercontent.com/57491181/121349019-57dee680-c929-11eb-8943-fa8c012530d3.png)

But I also tried with these versions:
![Screenshot_20210609_133825](https://user-images.githubusercontent.com/57491181/121349012-557c8c80-c929-11eb-8f57-f0827de9558f.png)

**Comment by ShockwaveNN** [comment] 2021-06-09 13:09
Yeah, tls v1.2 seems like a reasonable choice

To be clear - those screenshots are from Nextcloud server, not from DocumentServer?

Because I still think there is something wrong with TLS, since

> Error: write EPROTO 140064833886016:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol  version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70

SSL alert number 70 means protocol version problem

**Comment by florian-bellencontre** [comment] 2021-06-09 13:21
No it's screeshot were performed on the DocumentServer not on Nextcloud.

Yes, but I don't understand where this version problem comes from. Is it possible that the problem comes from Nextcloud ?

**Comment by florian-bellencontre** [comment] 2021-06-09 13:21
Ok I just did the test on another Nextcloud instance and it works. I'll do more research on it.

**Comment by ShockwaveNN** [comment] 2021-06-09 13:27
@florian-bellencontre Yeah, problem comes from nextcloud, since in logs error while DocumentServer downloading file to cache to open it on view/edit

Maybe there is some problem with nextcloud cert\protocol\proxy

**Comment by florian-bellencontre** [comment] 2021-06-09 17:32
I just found out what the problem was. On the Nextcloud instance we only support TLSv1.3 via our reverse proxy. Once I enabled TLSv1.2 again everything is back to normal.

Onlyoffice does not support TLSv1.3 ?

**Comment by ShockwaveNN** [comment] 2021-06-10 07:18
> Onlyoffice does not support TLSv1.3 ?

Actually I'm not 100% sure, but we should definitely check it

@igwyd Please take a look at this issue, need to setup Nextcloud with TLSv1.3 only and connect to DocumentServer and see that happened

**Comment by igwyd** [comment] 2021-06-11 13:43
Hello, @florian-bellencontre.
Thank you for report.
I can confirm - this is bug, issue 50835 in our private issue tracker.

**Comment by acsfer** [comment] 2021-08-09 22:26
I can confirm this; once TLSv1.3 is forced on Nextcloud server (nginx), files can't be downloaded by DocumentServer with:

```
[ERROR] nodeJS - error downloadFile:url=https://documentserver/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NTgwMjYxNjYsInVzZXJJZCI6ImNmZXJyZWlyYWV4dCJ9.e5uK_hYhCE8_N1wKQeckLTiVtsldVHbRe4_GJUL2Uis;attempt=3;code:EPROTO;connect:null;(id=1623387810)
Error: write EPROTO 140402382194496:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70
```

**Comment by igwyd** [comment] 2021-11-02 07:18
@florian-bellencontre it's fixed at: https://github.com/ONLYOFFICE/build_tools/commit/0a4aaa05837ae260b56698164b7c43a7a40f19e6
And will be release as v7.0.0

**Comment by ShockwaveNN** [comment] 2022-01-18 12:27
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual

**Closed by ShockwaveNN** 2022-01-18 12:27 UTC
Labels: bug, fixed
