### ISSUE TITLE
When I run "make install" in server dir, It reported the error "Segmentation fault"

### ISSUE THREAD

**Issue by githublyx** [ONLYOFFICE/DocumentServer#611] opened 2019-07-12 08:27 UTC
[ins.log](https://github.com/ONLYOFFICE/DocumentServer/files/3385639/ins.log)

**Comment by ShockwaveNN** [comment] 2019-07-12 08:32
I think this is a duplicate of #377 
And there is a possible solutino at https://github.com/ONLYOFFICE/DocumentServer/issues/377#issuecomment-500024765

**Closed by ShockwaveNN** 2019-07-12 08:32 UTC
