### ISSUE TITLE
Option to hide password protection in menu 

### ISSUE THREAD

**Issue by rushlr** [ONLYOFFICE/DocumentServer#1306] opened 2021-06-23 02:50 UTC
**Do you want to request a *feature* or report a *bug*?**
feature
**DocumentServer version:**
6.3.1

Ability to hide password protection in menu

**Comment by ShockwaveNN** [comment] 2021-06-23 06:03
Hi, could you describe in detail why you need to hide it?

**Comment by rushlr** [comment] 2021-06-23 06:07
Use DocumentServer for general file editing, and there is a potential threat that any user will set a password on the document

**Comment by ShockwaveNN** [comment] 2021-06-23 06:10
Am I right that your case looks like this:

1. You're the owner of Document
2. You share this document to someone
3. This someone set password for your document
4. You cannot known this password and lost access to it

**Comment by rushlr** [comment] 2021-06-23 06:12
Yes

**Comment by ShockwaveNN** [comment] 2021-06-23 07:39
I agree with you, having ability to disable setting password as option is a good thing

I've created issue 50962 in out private issue tracker to discuss implementation with our dev team

**Comment by ShockwaveNN** [comment] 2021-09-20 12:51
This option is added in https://github.com/ONLYOFFICE/web-apps/pull/1168

This will be available in the next major release v6.5.0
Currently this version is on early stage of testing, so no ETA for release date

**Comment by bjxcar** [comment] 2021-11-02 03:55
it very good if can  hide anyone  in menu  （ for example： by changge  config.json or by API)

**Comment by ShockwaveNN** [comment] 2022-01-18 12:27
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual

**Closed by ShockwaveNN** 2022-01-18 12:27 UTC
Labels: enhancement, fixed
