### ISSUE TITLE
.doc import: wrong line length in this file

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/DocumentServer#1132] opened 2021-01-24 18:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
In this .doc file, in particular in page 2, OnlyOffice has additional lines compared to Word 2016.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* open the .doc file in OnlyOffice
* open the same file in Word 2016
* compare, in particular page 2

**What is the expected behavior?**
The file should look the same in OnlyOffice and Word 2016.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
OnlyOffice 6.1.0, debian 11 Bullseye.

The .doc file can be found here:
https://cloud.univ-grenoble-alpes.fr/index.php/s/EEBe4ZrQco8FwjP

**Comment by ShockwaveNN** [comment] 2021-01-25 10:03
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by Rita-Bubnova** [comment] 2021-02-16 08:15
This bug fixed (https://github.com/ONLYOFFICE/core/commit/6be7618e8346d7bb2f968a375a5779b242ad45c6, https://github.com/ONLYOFFICE/core/commit/898d84cdad118970c7b9bf6a48972e443a23b5c0) in future major release.

**Comment by ShockwaveNN** [comment] 2021-03-19 08:36
DocumentServer and DesktopEditors v6.2.0 are released.
This issue should be fixed.
Feel free to comment or open new issue if got any troubles.

**Comment by parrenin** [comment] 2021-03-19 20:45
I have tested with 6.2.0, and for me there are still issues when opening this .doc file.
I don't think this bug should be closed.

**Comment by ShockwaveNN** [comment] 2021-03-22 07:56
@parrenin This is strange, I'll reopen it
@Rita-Bubnova Please take a look again in v6.2.0

**Comment by Rita-Bubnova** [comment] 2021-03-23 12:18
> I have tested with 6.2.0, and for me there are still issues when opening this .doc file.
> I don't think this bug should be closed.

I can confirm - this bug reproduce in ONLYOFFICE Desktop Editors version 6.2.0.148.

**Comment by parrenin** [comment] 2022-04-07 13:34
So it seems this issue is now fixed in 7.0.2.

**Comment by Rita-Bubnova** [comment] 2022-04-08 20:23
@parrenin, you're right.
This issue fixed in version 7.0.1.

**Comment by ShockwaveNN** [comment] 2022-04-09 11:50
I'll close this issue, sorry we forgot to report about it's fix earlier

**Closed by ShockwaveNN** 2022-04-09 11:50 UTC
Labels: bug, fixed
