### ISSUE TITLE
When opening history, some versions will be jssdk errors in individual editions.how i can Deal with this problem

### ISSUE THREAD

**Issue by lingks** [ONLYOFFICE/DocumentServer#351] opened 2018-07-21 01:42 UTC
When opening history, some versions will be jssdk errors in individual editions.how i can Deal with this problem
![qq 20180719152606](https://user-images.githubusercontent.com/32865119/43030907-09371208-8cca-11e8-98da-c11d837b5815.png)

**Comment by ShockwaveNN** [comment] 2018-07-24 11:21
@lingks could you attach original file which openes and archive changesurl zip for version for which error occured
And also fill out version info and OS info for issue

**Comment by lingks** [comment] 2018-07-25 02:31
changesurl:    http://183.60.252.250:8888/changeurl.zip
cacheurl:    http://183.60.252.250:8888/cacheurl.docx
original file:   http://183.60.252.250:8888/appdoc.docx
onlyoffice version is 5.1.4
os version is :　Linux version 3.10.0-693.11.6.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

**Comment by lingks** [comment] 2018-07-26 02:05
changesurl : http://183.60.252.250:8888/changesurl.zip

**Comment by lingks** [comment] 2018-07-30 03:14
Is there a solution for this problem? is is a bug 
Or the settings is wrong

**Comment by lingks** [comment] 2018-07-30 03:15
is it a bug Or the settings is wrong,have any suggestions?

**Comment by ShockwaveNN** [comment] 2018-07-30 06:59
@lingks sorry we still not able to reproduce your problem and do not know

**Comment by lingks** [comment] 2018-07-31 07:30
http://183.60.252.250:31111/cms/api/doc/edit/16b3ec91-f3d4-4710-b1ef-327625b90a31?access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzX2FwcHRlbSIsIm9yZGVyLXNlcnZpY2UiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiZXhwIjoxNTMzNDgxMzgxLCJhdXRob3JpdGllcyI6W10sImp0aSI6IjI0YTUyNmY2LTg2NmYtNDMzYi05YmI4LTg0MWFkZWM1ZTI1NiIsImNsaWVudF9pZCI6IiQyYSQxMCRYT1ZzNFoxWXRQS3FLd1FWeXdHOWoueExBcVhZUlFMR1pNR01yWkROYnRsNnBVQzBXZXRlcSJ9.K7jP5kCUzdzbVaO30D7wEgM1BPfUFWCf-8A3yYCWRRX9kVRZuWJTZkIyYmwemT5UYF0XAX9pLQkPBWYLfmAedd_GBvpQ88uPWvOkcUZa_QUzE_NgKoFHNepQyVvvdYuilSwi-CM_CduW7Rs3JjuJVTAGcDh6VOadg9S2lS8ot8DV1eIxjyVD2SOZUWcJZhDqtx7DIe9D1CzKIrnOI6-1YNoCyBp8zLkAwhwg-gtipamwk7q5x-Zx9SPM-rKPvX1FwuiTvLdFzu1_XzObfqRmV6-y3qx2tz9B2Y87_zla1AHbZSHxOdE5dz92RvRiWqgAMXWdSuDTScbCtRDJ9n6_og


hi ! man ,look at the version 3 and the version 6  of the file,you will see the problem ! the version 3 it can be open but can not open over some times later

**Comment by ShockwaveNN** [comment] 2018-07-31 07:57
@lingks yeah, thanks, we were able to reproduce your issue on local server but currently have no solution for this, we inform you as soon as we figure something out

**Comment by lingks** [comment] 2018-07-31 08:44
thanks！

**Comment by ShockwaveNN** [comment] 2018-07-31 10:50
We think something wrong with your conifg
We found out strange thing
Version 4 of your doc is:
![image](https://user-images.githubusercontent.com/668524/43455342-2c264ba2-94c8-11e8-861d-3207a71cc339.png)
Version 5 of your doc is:
![image](https://user-images.githubusercontent.com/668524/43455377-3eb83654-94c8-11e8-9f4e-7f1693b1f8f0.png)


It's clearly visible that difference in those version are one sentence in start of document.
But this changes are not highlighted.

Version 5 should look like something like this (with highlight of first sentence):
![image](https://user-images.githubusercontent.com/668524/43455416-648fc16c-94c8-11e8-801d-6945f273e7d1.png)

So seems you send incorrect data of something like this. Could you reproduce this issue in simpler document (preferable without chinese symbols, it's very hard to read for us.  And start from empty document)

**Comment by lingks** [comment] 2018-08-01 02:43
http://183.60.252.250:31111/cms/api/doc/edit/7e10d441-2bbc-445c-8886-e29576eeb652?access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzX2FwcHRlbSIsIm9yZGVyLXNlcnZpY2UiXSwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiZXhwIjoxNTMzNDgxMzgxLCJhdXRob3JpdGllcyI6W10sImp0aSI6IjI0YTUyNmY2LTg2NmYtNDMzYi05YmI4LTg0MWFkZWM1ZTI1NiIsImNsaWVudF9pZCI6IiQyYSQxMCRYT1ZzNFoxWXRQS3FLd1FWeXdHOWoueExBcVhZUlFMR1pNR01yWkROYnRsNnBVQzBXZXRlcSJ9.K7jP5kCUzdzbVaO30D7wEgM1BPfUFWCf-8A3yYCWRRX9kVRZuWJTZkIyYmwemT5UYF0XAX9pLQkPBWYLfmAedd_GBvpQ88uPWvOkcUZa_QUzE_NgKoFHNepQyVvvdYuilSwi-CM_CduW7Rs3JjuJVTAGcDh6VOadg9S2lS8ot8DV1eIxjyVD2SOZUWcJZhDqtx7DIe9D1CzKIrnOI6-1YNoCyBp8zLkAwhwg-gtipamwk7q5x-Zx9SPM-rKPvX1FwuiTvLdFzu1_XzObfqRmV6-y3qx2tz9B2Y87_zla1AHbZSHxOdE5dz92RvRiWqgAMXWdSuDTScbCtRDJ9n6_og

look this,i just changed the font color  and the background color, the first version history is error open

**Comment by lingks** [comment] 2018-08-01 03:11
A strange question，When I change the background color of a text, the problems often arise. else if i add something  ,mabe it was nothing happend

**Comment by ShockwaveNN** [comment] 2018-08-01 10:45
@lingks there is access error while opening your link

**Comment by lingks** [comment] 2018-08-03 07:14
sorry about that, the server was down yesterday， look the verson 4 of the file you will seen the error , i  has changed the font color and the background color


http://183.60.252.250:31111/cms/api/doc/edit/b196eb17-6082-47a5-bebd-2a3cb9cb574b?access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzX2FwcHRlbSIsIm9yZGVyLXNlcnZpY2UiXSwidXNlcl9uYW1lIjoibGluc2hlbmciLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiZXhwIjoxNTMzNzQwNTYwLCJhdXRob3JpdGllcyI6W10sImp0aSI6IjdlMzAwY2Y2LTYzNWQtNDdhOC1hZTYyLTQ4YWRhNTUyNDhiOSIsImNsaWVudF9pZCI6IiQyYSQxMCRYT1ZzNFoxWXRQS3FLd1FWeXdHOWoueExBcVhZUlFMR1pNR01yWkROYnRsNnBVQzBXZXRlcSJ9.ILTbdiAcNFa5gbvkbZ-UtTbbEiS9iQsgSOTY8WRhcNAS6Isl3y9eBy1UMzZvtM2nS6JlyhUBH5Rkx-2OHo_o4M77sbKLsAYT2bM00E7nZt00iRCyWbO--55imGastVBnNZoEL1LzeRdS8kPB_C_pnAvFV-YrkolNwT_EUe7yXV6-DQkY2tHXGzQE0OGq8YhnpbPcVClUOQPMEk9rnttvRC5LYSPHXpyQ7v-Ldk5dI6OrOqnSv2sGjH428gmmLe99xAca9PQfOP37VliF9ZMiqMKE_iouSSOSERrdYScqqSNHa12XXiykjcDn3SH7xIiQCW_xIUOiV_5vrB9OdTt1Ag

**Comment by lingks** [comment] 2018-08-04 02:08
when the version is the first, how the  previous params setting

**Comment by ShockwaveNN** [comment] 2019-04-29 11:46
I'll close this issue since we were unable to reproduce problem. If issue still occure - please create new issue with exact steps to reproduce it

**Closed by ShockwaveNN** 2019-04-29 11:46 UTC
