### ISSUE TITLE
As Chrome updated to version 93,the navigator of document can not display correctly in Document Editor version 6.0.0

### ISSUE THREAD

**Issue by linlongye** [ONLYOFFICE/DocumentServer#1428] opened 2021-09-17 10:01 UTC
**DocumentServer version:6.0.0.105**

**Operating System: Windows 10**

**Browser version: Chrome 93.0.4577.82**

**Comment by ShockwaveNN** [comment] 2021-09-17 10:26
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1368

It's fixed in v6.3.1 and you should upgrade to the latest v6.4.0, we only support the current stable version

**Closed by ShockwaveNN** 2021-09-17 10:26 UTC
