### ISSUE TITLE
Incorrect page layout after document export

### ISSUE THREAD

**Issue by aol-nnov** [ONLYOFFICE/DocumentServer#2526] opened 2023-12-22 10:57 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

Document has correct layout: A4, portrait

### Actual Behavior

Document has incorrect layout: user size 210x294, landscape

this incorrect size is only seen in foreign editos, i.e. MS Office, LibreOffice, etc (but not in onlyoffice or apple pages)

### Reproduction Steps

minimal reproduction spets:

1. start official docker image
2. navigate to web ui
3. start test example as it reads on the front page (i.e. `sudo docker exec xxxxxxxxx sudo supervisorctl start ds:example`)
4. go to test example and create new document
5. make sure it is portrait a4 sheet
6. go to "File" tab and choose "Download as DOCX"
7. open downloaded file in LibreOffice or MS Word
8. check page layout

<img width="669" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/43190/757ee9c0-39e4-4de5-bbb0-a4b1f9d6487b">

As far as I can tell, this regression was introduced in 7.5 or 7.4.

Please fix this annoying bug as it affects correct printing of the exported documents!

**Comment by aol-nnov** [comment] 2023-12-22 11:05
Let me summon @Rita-Bubnova as a well known, ahem, triage-er of my reports 😊

**Comment by igwyd** [comment] 2023-12-25 13:02
Hello @aol-nnov, I repeated this case in libre office but not repeated for MS office, maybe there are some additions to the script? 

This document works correctly in MS office.
![Снимок экрана 2023-12-25 175408](https://github.com/ONLYOFFICE/DocumentServer/assets/67538082/265631a7-e2d6-484a-9136-97f903df517a)

**Comment by aol-nnov** [comment] 2023-12-25 13:10
@igwyd no, reproduction steps for ms word are the same. Reportedly, it's MS Word 2010 here.

I'll return with more details tomorrow.

**Comment by aol-nnov** [comment] 2023-12-25 13:25
Kindly find MS Word version info attached
![telegram-cloud-photo-size-2-5211174092315678081-x](https://github.com/ONLYOFFICE/DocumentServer/assets/43190/6958b85c-4e6f-4574-ab44-5f4606469405)

**Comment by aol-nnov** [comment] 2023-12-25 14:08
> This document works correctly in MS office.

@igwyd also, please make sure that you did not accidentally fix the layout by saving the doc in Libre Office during check.

(I'm stressing that because we have a 100% repro in MS Word 2010)

**Comment by igwyd** [comment] 2023-12-25 19:14
You are right, in the MS Office 2010 the same behavior as Libre Office. I created ticket #65694 with your issue.

**Comment by aol-nnov** [comment] 2024-02-03 10:18
Hello, dears!

Today I've checked the document server Version: 8.0.0. Build: 99 and regrettably discovered that this annoying bug has not been fixed yet.

Any plans on fixing it any time soon?

Best,
Andrey

**Comment by igwyd** [comment] 2024-02-06 05:37
Hello, the importance of the bug is normal, developers not fix it in the current release.

**Comment by aol-nnov** [comment] 2024-02-06 06:50
@igwyd understood. And what about timeline? I have to decide whether to roll back or wait for the fix...

**Comment by igwyd** [comment] 2024-02-06 07:00
Unfortunately i haven't the information about timeline, this bug is not in priority. You can try contact the sales department to speed up it [sales@onlyoffice.com](mailto:sales@onlyoffice.com).

**Comment by Mer0me** [comment] 2024-06-12 12:21
The bug is not present on the Desktop editor :
1. Create a .docx with desktop editor and save it
2. Open the saved document with Word 2010 : the orientation is good (Portrait).

I have two separate instance of OnlyOffice DocumentServer, same version  (7.2.2.56) but one is in a docker container, the other is on a dedicated VM.

I cannot reproduce the problem on the dockered version. It's systematic on the VM one. Not sure if it's relevant.

When the problem occurs, it also affects 2-sides printing : long border Portrait become short border Landscape. As the orientation seems to be good on  Word 2010 layout menu, it's very confusing. You need to go to File -> Print -> Layout -> Orientation to check the real orientation status.

**Comment by Mer0me** [comment] 2024-06-12 12:51
On the (working) dockerized onlyoffice, the document.xml inside the .docx is like this : 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14"><w:body><w:p w:rsidR="004D6F8B" w:rsidRDefault="00040C38"><w:bookmarkStart w:id="0" w:name="_GoBack"/><w:bookmarkEnd w:id="0"/><w:r><w:t>Document normal</w:t></w:r></w:p><w:p w:rsidR="004D6F8B" w:rsidRDefault="004D6F8B"/><w:sectPr w:rsidR="004D6F8B"><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1418" w:right="1418" w:bottom="1418" w:left="1418" w:header="709" w:footer="709" w:gutter="0"/><w:cols w:space="708"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>
```

On the (not working) VM, the same file is like this : 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14"><w:body><w:p w:rsidR="005C1A5B" w:rsidRDefault="00AC358F"><w:bookmarkStart w:id="0" w:name="_GoBack"/><w:bookmarkEnd w:id="0"/><w:r><w:t>Document normal</w:t></w:r></w:p><w:p w:rsidR="005C1A5B" w:rsidRDefault="005C1A5B"/><w:sectPr w:rsidR="005C1A5B"><w:pgSz w:w="11906" w:h="16838" w:orient="landscape"/><w:pgMar w:top="1418" w:right="1418" w:bottom="1418" w:left="1418" w:header="709" w:footer="709" w:gutter="0"/><w:cols w:space="708"/></w:sectPr></w:body></w:document>
```

`w:orient="landscape" ` in the` <w:pgSz>` tag seems to be the relevant difference between the two files.

**Comment by igwyd** [comment] 2024-06-14 05:40
Hello @aol-nnov and @Mer0me, it's fixed and will be released in the next major release.

**Comment by Rita-Bubnova** [comment] 2024-06-21 15:16
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-06-21 15:16 UTC
Labels: confirmed-bug, fixed-release

**Comment by aol-nnov** [comment] 2024-06-22 08:27
I can confirm, this issue is now fixed.

Tested against `Version: 8.1.0. Build: 169` with official docker image `onlyoffice/documentserver:8.1`

Thank you for the good work!
