### ISSUE TITLE
DB and redis to connect with unix domain socket

### ISSUE THREAD

**Issue by rarapost** [ONLYOFFICE/DocumentServer#352] opened 2018-07-23 07:41 UTC
Feature Request

It would be great if documentserver were able to connect to database (namely postgreSQL) and redis through Unix Domain Socket, which is faster, less resource consuming and more secure then TCP connectoin (even usin 'localhost').

I did not find whether it is possible in current version.

**Comment by ShockwaveNN** [comment] 2018-07-23 08:47
Partial duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/227

**Closed** 2018-07-23 08:48 UTC
