### ISSUE TITLE
Is it possible to add an custom toolbar button to execute custom business logic?

### ISSUE THREAD

**Issue by softboy99** [ONLYOFFICE/DocumentServer#2665] opened 2024-03-19 09:52 UTC
![image](https://github.com/ONLYOFFICE/CommunityServer/assets/228731/c4f508dc-914d-4d55-a3bd-a99e0d650a17)
We want batch operation for multiple documents at the same time。

**Comment by Rita-Bubnova** [comment] 2024-03-19 10:36
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2652.

**Closed by Rita-Bubnova** 2024-03-19 10:36 UTC
