### ISSUE TITLE
spreadsheet: set multiple (selected) columns width or selected rows heigh all together

### ISSUE THREAD

**Issue by ratermir** [ONLYOFFICE/DocumentServer#604] opened 2019-07-08 17:03 UTC
Feature or bug ? 
In spreadsheets, all competiting offices (Google, Collabora/Libreoffice, MS office ... ) have a feature when I select multiple columns or row and I change width of single column from the selection (or height of single row), the rest of selected columns (rows) set their widths (heights) to the same values.

Onlyoffice Online is great tool, but I really miss this feature. Do you plan to implement it ?
I vote for a bug because I consider such functionality as a "standard" functionality of the office packages these days.

**Comment by Rita-Bubnova** [comment] 2019-07-09 08:43
Hello, @ratermir.
Thank you. I can confirm - this is a bug, issue 42043 in our internal issue tracker.

**Comment by ahmadhsalim** [comment] 2021-01-27 13:29
Will this issue be fixed? It's a very basic and important feature without it the user experience is very bad.

**Comment by ShockwaveNN** [comment] 2022-01-18 12:27
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual

**Closed by ShockwaveNN** 2022-01-18 12:27 UTC
Labels: bug, fixed

**Comment by HedvigS** [comment] 2023-02-03 17:33
I'm using OnlyOffice in a web browser for my work, this issue is still not solved for me.

**Comment by HedvigS** [comment] 2023-02-03 17:34
wait a minute... it works if highlighting "only" rows but not if highlighting all (top left corner).. okay. so sort of solved.

**Comment by wyntrson** [comment] 2023-05-15 14:34
Still waiting for this feature, when the top left corner is selected the resize doesn't work on all.

**Comment by raniesantos** [comment] 2023-06-26 21:34
Please reopen the issue. This doesn't work for setting widths for multiple columns.

**Comment by alexander-billings** [comment] 2023-07-05 00:25
Issue still present on Version 7.4.0.163 (Flatpak), unable to set width for multiple columns simultaneously. I'd be happy to test fixes or gather more information if needed.

**Comment by hdmr14** [comment] 2024-10-28 07:35
still doesn't work on 8.2.0.143.
should we open an another issue?
no any info?

**Comment by VladimirProkofiev52** [comment] 2024-10-28 14:45
Hello! @hdmr14 
I've reviewed your issue and would like to provide the following insights:

When you select multiple columns or rows with the mouse, all highlighted columns or rows resize simultaneously.

If you select multiple columns or rows while holding down the Ctrl key, only the size of the specific column or row whose border is adjusted will change.

This behavior is consistent with that in other editors, such as Excel.

However, I've noticed that when the entire table is selected using the special "select all" button, resizing affects only one column or row, regardless of whether the Ctrl key is pressed.

If this is the issue you were referring to, please create a separate discussion (issue) for it.

This issue was created for a different bug, which has now been resolved, and its behavior is described in points 1 and 2 of this message.

**Comment by wyntrson** [comment] 2024-10-28 16:08
It is like this in ONLYOFFICE
https://github.com/user-attachments/assets/e4656063-ac54-4061-bd16-70047804084d

And like this in Excel

https://github.com/user-attachments/assets/7d221425-2066-4962-a58a-30154c9baf44

**Comment by VladimirProkofiev52** [comment] 2024-10-28 21:22
Hello! @wyntrson 
I'm unable to view the video files you attached, possibly due to an upload error.

**Comment by wyntrson** [comment] 2024-10-28 22:19
> Hello! @wyntrson I'm unable to view the video files you attached, possibly due to an upload error.

You are probably using Firefox, the videos are standard mp4 format. If you open the page in another chromium-based browser it works fine.
Github and Firefox issue.

**Comment by hdmr14** [comment] 2024-10-29 09:12
@VladimirProkofiev52 Yes, the issue I mentioned concerns the behavior when selecting *ALL* cells using the "select all" button or Ctrl+A. In such cases, Excel changes the size of all selected cells. I plan to create a new issue regarding this.

I reviewed the video posted by @wyntrson, and I believe it shows the same phenomenon I am pointing out.

**Comment by sudoshindo** [comment] 2024-10-30 11:39
> > Hello! @wyntrson I'm unable to view the video files you attached, possibly due to an upload error.
> 
> You are probably using Firefox, the videos are standard mp4 format. If you open the page in another chromium-based browser it works fine. Github and Firefox issue.

Hello, sorry for being off topic but I really need to ask. Is there no way to fix this video playback issue on Firefox? It has been bothering me for a while now.
