### ISSUE TITLE
Issue on first load of new document from nextcloud

### ISSUE THREAD

**Issue by mattronix** [ONLYOFFICE/DocumentServer#220] opened 2017-12-06 17:18 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When creating a new document only office document server loads fine and document can be edited
When closing the document and reopening it again it gets stuck at loading until you refresh the page and then normal behaviour occurs and document can be worked on fine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Deploy a stack in docker swarm with onlyoffice document server image and use traeifk as load balancer for it.

**What is the expected behavior?**
click document and then it opens and loads for editing of first click.

**Did this work in previous versions of DocumentServer?**
New install N/A

**DocumentServer version:**
docker latest pulled today.

**Operating System:**
Debian 9

**Browser version:**

Chrome 
Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by agolybev** [comment] 2017-12-07 08:16
Hi @mattronix, cloud you provide `docker-compose.yml` file for test it?

**Comment by mattronix** [comment] 2017-12-07 08:50
Sure :) 

Here you go 

------------------------------
version: '3'
services:
  app:
    image: uptic/onlyoffice/documentserver
    deploy:
      labels:
        - "traefik.frontend.rule=Host:example.tld.com"      
        - "traefik.docker.network=publicnet"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.protocol=http"              
    networks:
      publicnet:
    stdin_open: true     
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
      - document_appdata:/var/lib/onlyoffice
      - document_public:/var/www/onlyoffice/documentserver-example/public/files
      - document_fonts:/usr/share/fonts
      - document_db:/var/lib/postgresql
     
networks:
  publicnet:
    external: true
volumes:
  document_data:
  document_log:
  document_appdata:
  document_public:
  document_fonts:
  document_db:

I can also give you the public facing address of the instance in DM if you want?

**Comment by agolybev** [comment] 2017-12-07 09:00
@mattronix, First, I'm going to reproduce the issue localy. If I couldn't repeate it on my compute I'd need real environment.

**Comment by mattronix** [comment] 2017-12-07 15:51
Perfect thank you, 

Ive noticed something and i am wondering if its related. 

After doing some debugging and checking headers i discovered an X-Forwarded-Host bug on a docker swarm it seems that the X-Forwarded-Host is set to the IP on the ingress network regardless of what i configure in traefik and i was wondering could this be causing the odd issue we are having? 

Here is the headers i record:

GET /web-apps/apps/api/documents/api.js HTTP/1.1
Host: the.correct.tld
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,nl;q=0.7
Cookie: _ga=GA1.2.1678074156.1512659687; _gid=GA1.2.1438219152.1512659687; _gat=1
X-Forwarded-For: 10.255.0.3
X-Forwarded-Host: the.correct.tld
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: 7f60f6d88b46
X-Real-Ip: 10.255.0.3

Following Bug has more info: 
https://github.com/moby/moby/issues/25526 

Thanks once again!

**Comment by agolybev** [comment] 2017-12-08 12:02
Hi @mattronix, I saw your docker-compose file, right now. 
I was expecting to see all services threre (traefik, documentserver, nextcloud).  So I can't reproducing the issue localy.
If traefik didn't setup http headers each times correctly, it'd be the cause of the problem. However I haven't  faced with such issue in swarm yet.

**Comment by mattronix** [comment] 2017-12-08 13:28
Currently we run the document server with self signed certs to get past the header issue :)

The docker compose file for nextcloud is from upstream and i will send the traefik config today.

**Comment by mattronix** [comment] 2017-12-08 13:30
# uptic B.V. LB Stack
# version 0.6
# Author Matthew Frost (matthew@uptic.nl)
##############################################
version: '3.4'

services:
  app:
    image: traefik:v1.5-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/traefik.toml:/traefik.toml
      - /data/traefik/acme.json:/acme.json
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host  
    networks:
      - publicnet
      - consulnet
      - appservicesnet
    deploy:
      labels:
        - "traefik.frontend.rule=Host:lb.ams.uptic.eu"      
        - "traefik.enable=true"      
        - "traefik.docker.network=publicnet"
        - "traefik.frontend.auth.basic=USER:SECRET"
        - "traefik.port=8080"
      resources:
       limits:
         memory: 1G
      placement:
        constraints: [node.role == manager]
networks:
  publicnet:
    external: true
  consulnet:
    external: true
  appservicesnet:
    external: true

**Comment by sfreiberg** [comment] 2018-03-21 18:02
I've also seen this issue when we had postgres, redis and rabbit on external servers and the document server behind an elastic load balancer. When everything was on a single box everything was fine.

**Comment by ShockwaveNN** [comment] 2019-04-26 13:51
Closing this issue since we were able to reproduce this issue locally. If issue stil actual - please open new issue

**Closed by ShockwaveNN** 2019-04-26 13:51 UTC
