### ISSUE TITLE
Whether excel document support dark mode？？？

### ISSUE THREAD

**Issue by zxuanhong** [ONLYOFFICE/DocumentServer#2436] opened 2023-10-20 09:35 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

1. At present, both word and ppd support document dark mode. Can excel also support it? Otherwise it would be incongruous
2. Now the interface is very inconsistent
<img width="1576" alt="image" src="https://github.com/ONLYOFFICE/DocumentServer/assets/62740686/830ceae6-0aa4-410a-b008-fd646eb26255">

**Comment by Rita-Bubnova** [comment] 2023-10-20 10:17
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1944.

**Closed by Rita-Bubnova** 2023-10-20 10:17 UTC
