### ISSUE TITLE
Editor customization ignores empty logo URL

### ISSUE THREAD

**Issue by ssams** [ONLYOFFICE/DocumentServer#1323] opened 2021-07-06 09:20 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When setting the custom URL to be used when clicking on the logo image in the editor to null or an empty string (as documented [here](https://api.onlyoffice.com/editors/config/editor/customization#logo)), the link remains unchanged and targets https://www.onlyoffice.com/.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```javascript
new DocsAPI.DocEditor('placeholder',
      {
        'type': 'embedded',
        'width': '100%',
        'height': '100%',
        'documentType': 'word',
        'document': {
          // ...
        },
        'editorConfig': {
          // ...
          'mode': 'view',
          'customization': {
            'logo': {
              'url': '', // set empty logo-URL
            },
          },
        },
      });
```

**What is the expected behavior?**
Logo should not be clickable as documented.

**Did this work in previous versions of DocumentServer?**
unknown / not tested

**DocumentServer version:**
6.3.1 (via Docker image *onlyoffice/documentserver:6.3* -> image digest `sha256:e3c51ded05a96209be4ab427a7d6ff39e16146d2df111dca073cb4b2364f468d`)

**Operating System:**
n/a
**Browser version:**
Firefox 89.0.2 (but probably not browser dependent)

**Comment by ssams** [comment] 2021-07-06 09:23
suppose this could be caused by the check in https://github.com/ONLYOFFICE/web-apps/blob/a113f189f9060c9c14173f6a2b37dfe971490d0e/apps/spreadsheeteditor/embed/js/ApplicationController.js#L335-L337  - empty string evaluates to `false`, hence `href` attribute is not overwritten.

**Comment by ShockwaveNN** [comment] 2021-07-06 09:29
@igwyd Please take a llok

**Comment by igwyd** [comment] 2021-08-30 11:08
Hello @ssams, sorry for the late reply.
I tested documentserver with your logo settings and logo became not clickable for me. I guess it didn't work because you used the community version onlyoffice-documentserver. This [paragraph](https://api.onlyoffice.com/editors/config/editor/customization#logo) with a star,  below is a footnote "* - available for editing only for ONLYOFFICE Developer Edition". If you want it to work, try with [onlyoffice/documentserver-de](https://hub.docker.com/r/onlyoffice/documentserver-de/tags?page=1&ordering=last_updated)

**Comment by ssams** [comment] 2021-09-03 07:25
Missed the footnote initially and tested it with the Docker image `onlyoffice/documentserver-de:6.4` again. However I still don't see the described behavior in the "embedded" viewer, have you checked that one?

When I set `type: 'desktop'` in the config, it works as you describe it - in the Community Edition, the logo keeps the link to onlyoffice.com and when using the Developer Edition the logo becomes not clickable as expected and documented.

When using `type: 'embedded'` as mentioned in the initial description above however, the behavior is the same independent from the Edition in use: when specifying an arbitrary (non-empty) URL, the logo link is replaced and points to the set URL (e.g. using `url: 'https://example.com'`). But when passing `''` or `null` the value is ignored and the link keeps pointing to the default value / onlyoffice.com.

So apparently the reported bug is only present in the embedded viewer, there however it affects both the Community and Developer Editions (and contrary to the documentation, customization of the logo URL in general currently also works in the Community Edition, that's probably why I stumbled across it initially).

**Comment by igwyd** [comment] 2021-09-06 08:36
@ssams you're right, when using `type: 'embedded'` the logo keeps the link to https://onlyoffice.com. Probably this is bug, i created issue 52379 in our private issue tracker.

**Comment by igwyd** [comment] 2021-09-07 09:48
Thank you for report @ssams, fixed here https://github.com/ONLYOFFICE/web-apps/commit/1a00215605ee04e78b87f75dacff53ed27eb9d9a and will be release as v6.5.0

**Comment by ShockwaveNN** [comment] 2022-01-18 12:26
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual

**Closed by ShockwaveNN** 2022-01-18 12:26 UTC
Labels: bug, fixed
