### ISSUE TITLE
unable to open a .docx file, error after 52% loading

### ISSUE THREAD

**Issue by p-klassen** [ONLYOFFICE/DocumentServer#1297] opened 2021-06-09 08:42 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I want to open a specific .docx file in OnlyOffice (Nextcloud Integration), the editor loads to 52% and then reports an error
![grafik](https://user-images.githubusercontent.com/45001161/121321744-aaf77000-c90e-11eb-9e86-b8ff6bcf9fea.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. click on .docx file in Nextcloud
2. wait the document to load in the editor

**What is the expected behavior?**
Document can be opened and edited as usual

**Did this work in previous versions of DocumentServer?**
Not sure, this specific file is a very new one

**DocumentServer version:**
6.3

**Operating System:**
Server: Docker running on CentOS 7
Client: Error occurs on all OS

**Browser version:**
Occurs on all tested Browsers (latest firefox, chrome, safari, internet explorer, edge)

Funny enough: When the very same file i copied, it can be opened.
But this is no solution for us, since many users need to edit this file simultaneously.

**Comment by ShockwaveNN** [comment] 2021-06-09 09:08
Is there JS error in Chrome developers console and errors in DocumentServer logs?

Could you download this file from nextcloud and attach here?

**Comment by p-klassen** [comment] 2021-06-09 09:19
/var/log/onlyoffice/documentserver/converter/err.log and /var/log/onlyoffice/documentserver/documentserver/err.log are completly empty

this is what I see in the console:
![grafik](https://user-images.githubusercontent.com/45001161/121328253-738bc200-c914-11eb-9bf3-c37d5890e08d.png)

I can't share the file public, since it contains sensitive informations. Can I somehow provide it to you directly?

**Comment by ShockwaveNN** [comment] 2021-06-09 09:22
You can send it to files@onlyoffice.com

**Comment by p-klassen** [comment] 2021-06-09 09:30
Ok, just sent an email

**Comment by ShockwaveNN** [comment] 2021-06-09 09:41
Ok, we got your file, but currently we do not know that the reason of this error, we'll invistigate

**Comment by ShockwaveNN** [comment] 2021-06-09 09:43
Could you show connectors settings like those:
![image](https://user-images.githubusercontent.com/668524/121332224-552bc380-c920-11eb-97b8-2ee508fc085a.png)

**Comment by p-klassen** [comment] 2021-06-09 09:55
![grafik](https://user-images.githubusercontent.com/45001161/121333948-89e84c80-c919-11eb-9ae2-6c20fc303856.png)

**Comment by ShockwaveNN** [comment] 2021-06-09 10:02
@p-klassen Currently we are unable to reproduce your problem on latest version of DocumentServer v6.3.1 - could you update to 6.3.1 and see if problem persists (we released this version yesterday)

But in meantime we'll try to reproduce in with 6.3.0, but currently not sure if that problem actually originate to your file and it was broken by some actions, but not for example some network error or something like this

**Comment by p-klassen** [comment] 2021-06-09 10:07
Well the thing is, that when you copy the file (like replicating it without modifying its contents) the error does not occur.
So in case you copied the file to your instance for trying to reproduce the error, it most likely will work as expected.

**Comment by p-klassen** [comment] 2021-06-09 10:07
I will update to 6.3.1 tonight and see if the error is still there.

**Comment by p-klassen** [comment] 2021-06-09 22:57
Just did the Update from 6.3.0 to 6.3.1 and it seems that the error is gone now. Not sure if a patch in the new version fixed it or if it was something else.

**Comment by ShockwaveNN** [comment] 2021-06-10 07:23
@p-klassen I'm not sure either, not remember that we were fixing error like this in 6.3.1 but maybe even simplest restart of DocumentServer during update is helped

In that case I'll close this issue, please feel free to comment here or create new one if some new troubles appears

**Comment by p-klassen** [comment] 2021-06-14 09:31
Hey there! Error is back again out of a sudden. Tried to restart the services and the whole docker container itself, but the issue is still there.

**Comment by ShockwaveNN** [comment] 2021-06-15 07:22
@p-klassen I'll reopen this issue but I've no idea that the case of that.

Is there any proxy\cdn or anything other involved in your setup except nextcloud and DocumentServer?

**Comment by p-klassen** [comment] 2021-06-15 07:25
You mean like between Nextcloud and the DocumentServer? No, they're in the same subnet without a firewall or proxy between them.

**Comment by ShockwaveNN** [comment] 2021-06-15 07:27
@DenisDeeSign Could you take a look at this, do you have any idea?

**Comment by DenisDeeSign** [comment] 2021-06-16 06:49
Hello, @p-klassen,
a link has expired. Could you generate a new one so I will pass it to our developers?

**Comment by p-klassen** [comment] 2021-06-16 08:48
Someone of our users replaced the file with a copy that works. But since the error appears again and again, it will surely come back.

I will send a link to said file as soon as the problem appears again.

Besides that: I still wonder why the logs in /var/log/onlyoffice/documentserver/converter/err.log and /var/log/onlyoffice/documentserver/documentserver/err.log are empty. Is logging deactivated per default?

**Comment by ShockwaveNN** [comment] 2021-06-16 08:51
> Besides that: I still wonder why the logs in /var/log/onlyoffice/documentserver/converter/err.log and /var/log/onlyoffice/documentserver/documentserver/err.log are empty. Is logging deactivated per default?

Yes, in this files send only critical errors with full service stop, all other errors send to `out.log` and those files cannot be empty

**Comment by DenisDeeSign** [comment] 2021-06-16 09:46
@p-klassen, the error only occurs during a changes are applying to previous version and means that there is a conflict between sdk versions. Did you update DocumentServer to 6.3.0 version while this document was edited?

**Comment by p-klassen** [comment] 2021-06-16 11:29
In did shutdown the DocumentServer before I did the update to 6.3.1. But the first time the problem appeared was with a new document that was only used on 6.3.0

**Comment by ShockwaveNN** [comment] 2022-07-04 07:16
Hi, is this issue still actual in latest stable v7.1.1? We made a lot of changes in shutdown process so I think it should be resolved by now

**Comment by p-klassen** [comment] 2022-07-04 08:42
Hi! The issue was still there after my last message.
But thank you for reminding, I will update to the latest version this evening and will check if the problem still exists.

**Comment by p-klassen** [comment] 2022-07-04 19:34
Just did the Update. For now it seems to work fine and load the .docx file

**Comment by ShockwaveNN** [comment] 2022-07-05 06:48
@p-klassen Ok in that case I'll close this issue if this error reappear itself - please comment here

**Closed by ShockwaveNN** 2022-07-05 06:48 UTC
Labels: waiting feedback
