### ISSUE TITLE
ppt cann't play audio or video

### ISSUE THREAD

**Issue by James-jordan-coder** [ONLYOFFICE/DocumentServer#1881] opened 2022-08-26 07:37 UTC
hi developer, i created a ppt file,and insert a audio an a video into the ppt file,then upload the ppt file to the onlyoffice server,i opened the uploated file in webview,but the ppt file cann't play the audio and video, the uploated andio and video just show a pic.thanks for your answer.

**Comment by ShockwaveNN** [comment] 2022-08-26 07:45
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1534

**Closed by ShockwaveNN** 2022-08-26 07:45 UTC
Labels: duplicate

**Comment by hwwjason** [comment] 2023-03-15 06:38
我这边同样有这样的问题，有办法解决吗
