### ISSUE TITLE
Compiling for arm, arm64 or x86?

### ISSUE THREAD

**Issue by jiriks74** [ONLYOFFICE/DocumentServer#1063] opened 2020-11-09 11:34 UTC
Hi,
I have an raspberry pi 4 server running at home. I tried compiling your server, but I ran into issues. Is it even possible to compile it for arm platform? Also, I can run x86 code on it, so if it were possible to compile for x86 it would be good. Are you planning on supporting these platforms? I'd like to integrate only office to my next loud server.

**Comment by ShockwaveNN** [comment] 2020-11-09 12:07
Hi, this is duplicate of #152 
We got this in plans, but currently have no real progress

**Closed by ShockwaveNN** 2020-11-09 12:07 UTC
