### ISSUE TITLE
Onlyoffice docker is running but can't edit files (ubuntu)

### ISSUE THREAD

**Issue by fabnext77** [ONLYOFFICE/DocumentServer#2084] opened 2023-02-01 19:35 UTC
Hello,
it was working fine till a docker image update done yesterday. Now it runs but can't edit. Please check images
![image](https://user-images.githubusercontent.com/71324914/216145167-d7398536-8a4e-46cc-b145-03ccd6c7f3e0.png)

when I edit the files:
![image](https://user-images.githubusercontent.com/71324914/216145275-913268f3-7858-4ecc-ad1e-5ac4a1c0976d.png)

what could be the problem?
thanks

**Comment by DenisDeeSign** [comment] 2023-02-02 07:01
Moving this issue to DocumentServer repo, since the issue in not related to CommunityServer.

**Comment by igwyd** [comment] 2023-02-02 08:14
Hello @fabnext77, show the command with which you started the documentserver and check log files inside container /var/log/onlyoffice/documentserver, are there any errors?

**Comment by fabnext77** [comment] 2023-02-02 09:14
Hello igwyd, thank you for your reply
my cointainer are:
![image](https://user-images.githubusercontent.com/71324914/216281123-77741b7a-b349-45e1-b38e-65084362d75a.png)

inside the folder:
/merged/var/log/onlyoffice
there aren't any file/log, maybe is the rong one? how to get it right?

test example was started with the following command proposed in the welcome page:
sudo docker exec 2e824496d179 sudo supervisorctl start ds:example

thank you

**Comment by derdjme** [comment] 2023-02-02 14:21
I'm having the exact same issue.

**Comment by fabnext77** [comment] 2023-02-03 08:58
Hello, to leave feedback: the problem is with onlyoffice docker 7.3, I rolled back to 7.2 and it works.
I hope that they will fix soon.

**Comment by hunimuni** [comment] 2023-02-03 14:46
When setting the DOC_SERV_SITE_URL environment variable, make sure the URL ends with "/"

**Comment by derdjme** [comment] 2023-02-03 16:34
> leave feedback: the problem is with onlyoffice docker 7.3, I rolled back to 7.2 and it works.
> I hope that they will fix soon.

I can confirm that this issue only applies for version 7.3

**Comment by igwyd** [comment] 2023-02-05 19:33
I guess you are using Apache proxy. Since version 7 we use socket.io and our apache configs for proxy was broken. We fixed it in this PR https://github.com/ONLYOFFICE/document-server-proxy/pull/27 try add changes in your config.

**Comment by Rita-Bubnova** [comment] 2023-08-11 21:08
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-08-11 21:08 UTC
