### ISSUE TITLE
Request for a new Shortcut

### ISSUE THREAD

**Issue by oMrSmith** [ONLYOFFICE/DocumentServer#1582] opened 2022-01-12 23:16 UTC
which will immediately insert text from the clipboard
_without the original formation_!

This works very well in Thunderbird
with the shortcut Control+Shift+V...

In MS Word this would open a dialog first
which I find so annoying as it slows everything down.

**Comment by Rita-Bubnova** [comment] 2022-01-13 07:08
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1002.

**Closed** 2022-01-13 07:12 UTC
Labels: duplicate
