### ISSUE TITLE
Looking for and not finding license.lic

### ISSUE THREAD

**Issue by unleashit** [ONLYOFFICE/DocumentServer#814] opened 2020-03-17 22:57 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Getting an error in the document server logs that it can't find a license file.

I'm running the docker version of document server, nextcloud, the onlyoffice plugin.  My setup was working perfectly for about two years and I'm not sure what could have changed to cause the issue other than recent upgrades to new versions of Document Server and Nextcloud (now 18). 

I notice whenever I try to save the settings in Nextcloud, in addition to `Error when trying to connect. Error occurred in the document service (Error while downloading the document file to be converted).`, I get an error in the OO Document Server logs that it is looking for a license file but can't find it (see below). Thus is why I'm posting here and not on the repo for the plugin.

I've tried most of the posted solutions and none work. A few things I've done: 

- checked to see if the Nextcloud full text search plugin was activated (no), because it is a known issue with the plugin
- verified that the document server container can access the nginx and nextcloud containers on the network
- temporarily reverted some nginx settings that I changed when upgrading Nextcloud like X-Frame-Options "SAMEORIGIN"
- nuked and recreated all containers, rebooted the server

The image I'm using is onlyoffice/documentserver:latest which is the community one so I'm assuming it shouldn't be looking for a license? Or if there should be a default one in there I did manually check the directory the error mentions and it's empty. 

My setup is basically a modified version of: https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud. Everything is running (Nginx, Nextcloud, Document Server) on the same machine. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

No errors

**Did this work in previous versions of DocumentServer?**

Yes

**DocumentServer version:**

5.5.0.165

**Operating System:**

Ubuntu 16

**Browser version:**

Firefox 74.0

```
[2020-03-17T19:28:37.028] [WARN] nodeJS - { Error: ENOENT: no such file or directory, open '/var/www/onlyoffice/documentserver/../Data/license.lic'
    at Object.openSync (fs.js:443:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:490:32)
    at Object.readFileSync (fs.js:343:35)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:686:36)
    at Object.exports.readLicense (/snapshot/server/build/server/Common/sources/license.js:0:0)
    at exports.readLicense.next (<anonymous>)
    at readLicense (/snapshot/server/build/server/DocService/sources/server.js:0:0)
    at readLicense.next (<anonymous>)
    at /snapshot/server/build/server/DocService/sources/server.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/DocService/node_modules/co/index.js:65:19)
    at /snapshot/server/build/server/DocService/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/snapshot/server/build/server/DocService/node_modules/co/index.js:50:10)
    at StatWatcher.updateLicense (/snapshot/server/build/server/DocService/sources/server.js:0:0)
    at StatWatcher.emit (events.js:198:13)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/www/onlyoffice/documentserver/../Data/license.lic' }
[2020-03-17T19:28:37.178] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
```

**Comment by ShockwaveNN** [comment] 2020-03-18 08:45
Hi, this is a known issue in our private bug tracker (44694)
And this error in logs should not have any impact on service, so I think it's better to ignore it until we fix it

**Comment by unleashit** [comment] 2020-03-18 18:43
Thanks for the reply. Are you sure it wouldn't impact the service? Because in my case it's not working and I've tried all of the usual stuff I could find. At this point, I guess I'll have to nuke my whole Nextcloud setup and start a new one because I've already spent a lot of time on this.

**Comment by ShockwaveNN** [comment] 2020-03-19 09:34
> Because in my case it's not working

I think you may got some other troubles, as far as I known this error is harmless

But this error: `Error when trying to connect. Error occurred in the document service (Error while downloading the document file to be converted).` is not right.

Could you search logs for any other errors?
And can you access http://documentserver-url/healthcheck and see if it return true

**Comment by ShockwaveNN** [comment] 2020-03-19 10:09
Also error in logs with license is fixed by https://github.com/ONLYOFFICE/server/commit/e85563f81126c38dedba6fb4af6ebd49565f04f0
and will be released in 5.5.1

**Comment by unleashit** [comment] 2020-03-19 20:07
Healthcheck returns true.

In converter/out.log (hadn't checked there before) I'm getting a bunch of:

```
[2020-03-19T19:32:13.405] [ERROR] nodeJS - error downloadFile:url=http://nginx-server/index.php/apps/onlyoffice/empty?doc=[base64stuffremovedIncaseItmatters];attempt=3;code:null;connect:null;(id=conv_check_1636191773_docx)
Error: Error response: statusCode:404 ;body:
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.9</center>
</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
In docservice/one.log (including the last archived version) other than the license error there is a Node warning about fs.watch availability:

[2020-03-17T17:23:11.868] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).

I confess that I don't fully understand how all these moving parts are supposed to work and unfortunately unless the above gives you any clues (and don't spend too much time on it) I'm just going to start over since I've already spent so much time on this. I'm sure it's related to upgrading from older versions of everything (it's been a cpl of years).

**Comment by ShockwaveNN** [comment] 2020-03-20 08:00
@unleashit I think your current problem is not related to DocumentServer per-se, but related to integration to nextcloud, so please create new issue in https://github.com/ONLYOFFICE/onlyoffice-nextcloud/

**Comment by GITStone-tech** [comment] 2020-03-22 12:12
I had the same problem with latest docker image - I went back to 5.4.0.21 and the docker image is running fine again without changing anything in my docker-compose.yml ... license file does not seem to be the problem, but I encountered various errors in converter err.log

Hope this helps.

**Comment by ShockwaveNN** [comment] 2020-03-23 07:38
>  but I encountered various errors in converter err.log

could you describe your errors?

**Comment by GITStone-tech** [comment] 2020-03-27 15:45
Sorry for the delay, but I needed to set it up again in order to get them errors ... basically I wonder why docserver and converter are not running - this is the snippet from docker-compose.yml and the log output from docker-compose up onlyoffice-document-server:

#
# ONLYOFFICE DEFINITION
#
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
#    image: onlyoffice/documentserver:5.4.0.21
    stdin_open: true
    tty: true
    restart: always
    environment:
      - NGINX_WORKER_PROCESSES=5
      - NGINX_WORKER_CONNECTIONS=50
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
      #- ./onlyoffice/Data:/var/www/onlyoffice/Data
      #- ./onlyoffice/log:/var/log/onlyoffice
      - ./onlyoffice/etc/onlyoffice/documentserver/default.json:/etc/onlyoffice/documentserver/default.json

default.json uploaded 

[default.json.zip](https://github.com/ONLYOFFICE/DocumentServer/files/4394499/default.json.zip)

onlyoffice-document-server    | Creating new PostgreSQL cluster 10/main ...
onlyoffice-document-server    | /usr/lib/postgresql/10/bin/initdb -D /var/lib/postgresql/10/main --auth-local peer --auth-host md5
onlyoffice-document-server    | The files belonging to this database system will be owned by user "postgres".
onlyoffice-document-server    | This user must also own the server process.
onlyoffice-document-server    | 
onlyoffice-document-server    | The database cluster will be initialized with locale "en_US.UTF-8".
onlyoffice-document-server    | The default database encoding has accordingly been set to "UTF8".
onlyoffice-document-server    | The default text search configuration will be set to "english".
onlyoffice-document-server    | 
onlyoffice-document-server    | Data page checksums are disabled.
onlyoffice-document-server    | 
onlyoffice-document-server    | fixing permissions on existing directory /var/lib/postgresql/10/main ... ok
onlyoffice-document-server    | creating subdirectories ... ok
onlyoffice-document-server    | selecting default max_connections ... 100
onlyoffice-document-server    | selecting default shared_buffers ... 128MB
onlyoffice-document-server    | selecting default timezone ... Etc/UTC
onlyoffice-document-server    | selecting dynamic shared memory implementation ... posix
onlyoffice-document-server    | creating configuration files ... ok
onlyoffice-document-server    | running bootstrap script ... ok
onlyoffice-document-server    | performing post-bootstrap initialization ... ok
onlyoffice-document-server    | syncing data to disk ... ok
onlyoffice-document-server    | 
onlyoffice-document-server    | Success. You can now start the database server using:
onlyoffice-document-server    | 
onlyoffice-document-server    |     /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start
onlyoffice-document-server    | 
onlyoffice-document-server    | Ver Cluster Port Status Owner    Data directory              Log file
onlyoffice-document-server    | 10  main    5432 down   postgres /var/lib/postgresql/10/main /var/log/postgresql/postgresql-10-main.log
onlyoffice-document-server    |  * Starting PostgreSQL 10 database server[ OK ] 
onlyoffice-document-server    |  * Starting RabbitMQ Messaging Server rab[ OK ] erver       
onlyoffice-document-server    | Starting redis-server: redis-server.
onlyoffice-document-server    | CREATE DATABASE
onlyoffice-document-server    | CREATE ROLE
onlyoffice-document-server    | GRANT
onlyoffice-document-server    | Usage: grep [OPTION]... PATTERN [FILE]...
onlyoffice-document-server    | Try 'grep --help' for more information.
onlyoffice-document-server    | Starting supervisor: supervisord.
onlyoffice-document-server    |  * Starting periodic command scheduler cr[ OK ]   
onlyoffice-document-server    |  * Starting nginx nginx                  [ OK ] 
onlyoffice-document-server    | Generating AllFonts.js, please wait...Done
onlyoffice-document-server    | Generating presentation themes, please wait...Done
onlyoffice-document-server    | ds:docservice: ERROR (not running)
onlyoffice-document-server    | ds:docservice: ERROR (spawn error)
onlyoffice-document-server    | ds:converter: ERROR (not running)
onlyoffice-document-server    | ds:converter: ERROR (spawn error)
onlyoffice-document-server    |  * Reloading nginx configuration nginx   [ OK ] 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
onlyoffice-document-server    |     at Config.get (/snapshot/server/build/server/Common/node_modules/config/lib/config.js:203:11)
onlyoffice-document-server    |     at Object.<anonymous> (/snapshot/server/build/server/Common/sources/license.js:0:0)
onlyoffice-document-server    |     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
onlyoffice-document-server    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
onlyoffice-document-server    |     at Module.load (internal/modules/cjs/loader.js:651:32)
onlyoffice-document-server    |     at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
onlyoffice-document-server    |     at Function.Module._load (internal/modules/cjs/loader.js:583:3)
onlyoffice-document-server    |     at Module.require (internal/modules/cjs/loader.js:690:17)
onlyoffice-document-server    |     at Module.require (pkg/prelude/bootstrap.js:1166:31)
onlyoffice-document-server    |     at require (internal/modules/cjs/helpers.js:25:18)
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
onlyoffice-document-server    |     at Config.get (/snapshot/server/build/server/Common/node_modules/config/lib/config.js:203:11)
onlyoffice-document-server    |     at Object.<anonymous> (/snapshot/server/build/server/Common/sources/license.js:0:0)
onlyoffice-document-server    |     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
onlyoffice-document-server    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
onlyoffice-document-server    |     at Module.load (internal/modules/cjs/loader.js:651:32)
onlyoffice-document-server    |     at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
onlyoffice-document-server    |     at Function.Module._load (internal/modules/cjs/loader.js:583:3)
onlyoffice-document-server    |     at Module.require (internal/modules/cjs/loader.js:690:17)
onlyoffice-document-server    |     at Module.require (pkg/prelude/bootstrap.js:1166:31)
onlyoffice-document-server    |     at require (internal/modules/cjs/helpers.js:25:18)
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/metrics/err.log <==
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/metrics/out.log <==
onlyoffice-document-server    | 27 Mar 15:39:13 - [911] reading config file: ./config/config.js
onlyoffice-document-server    | 27 Mar 15:39:13 - server is up INFO
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==
onlyoffice-document-server    | 
onlyoffice-document-server    | ==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
onlyoffice-document-server    | [2020-03-27T15:39:13.894] [WARN] nodeJS - start cluster with 1 workers
onlyoffice-document-server    | [2020-03-27T15:39:13.918] [WARN] nodeJS - worker 939 started.
onlyoffice-document-server    | [2020-03-27T15:39:14.846] [WARN] nodeJS - Express server starting...
onlyoffice-document-server    | [2020-03-27T15:39:14.934] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode

**Comment by GITStone-tech** [comment] 2020-03-27 15:46
If I try to connect to OO from NC I have no success (using HTTP). Exposing ports did not help - so I remembered a correct setup half a year ago and so I went back version 5.4.0.21

**Comment by ShockwaveNN** [comment] 2020-03-30 07:12
```
onlyoffice-document-server    | ds:docservice: ERROR (not running)
```
This is not right

Could you try to restart your compose without some volumes, I think there may be some error with permissions with some of them

**Comment by GITStone-tech** [comment] 2020-03-30 16:14
I have re-written the docker-compose.yml: 

version: '3.5'
services:

#
# ONLYOFFICE DEFINITION
#
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
#    image: onlyoffice/documentserver:latest
    image: onlyoffice/documentserver:5.4.0.21
    stdin_open: true
    tty: true
    restart: always
    environment:
      - NGINX_WORKER_PROCESSES=5
      - NGINX_WORKER_CONNECTIONS=50
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
      #- ./onlyoffice/Data:/var/www/onlyoffice/Data
      #- ./onlyoffice/log:/var/log/onlyoffice
      - ./onlyoffice/etc/onlyoffice/documentserver/default.json:/etc/onlyoffice/documentserver/default.json
networks:
  onlyoffice:
   driver: bridge
volumes:
  document_data:
  document_log:


I am running docker-compose as root and at the same moment I am using 5.4.0.21 everything is working; commenting "default.json" makes the latest image working.

So I think there is a change in default.json from version 5.4.0.21 to latest document server version?

Regards, D

**Comment by ShockwaveNN** [comment] 2020-03-31 07:40
Yeah, we updated default.json

There is errors in 
`/var/log/onlyoffice/documentserver/converter/err.log`
log
`services.CoAuthoring.server.editorDataStorage is not defined`
See correct one https://github.com/ONLYOFFICE/server/blob/89db803eb5f1722ba84cb3ac9e94c503d434f6ea/Common/config/default.json#L87

In general you should not edit default.json, but local.json instead

**Comment by GITStone-tech** [comment] 2020-03-31 18:12
I know about local.json; the only thing I changed was "reject_unauthorized", but was not aware of the change through the different minor version of document server ... I will switch to local.json.

Sorry for confusing as it was not a real error or bug.

**Comment by ShockwaveNN** [comment] 2020-04-01 07:08
@GITStone-tech To be clear - your problem is resolved? If so since this problem not related to original issue I mark our dialog as unrelated.

**Comment by GITStone-tech** [comment] 2020-04-01 07:28
Yes - the problem is resolved and it is ok to mark the discussion as "not related", but it may help someone else :-)

**Comment by ShockwaveNN** [comment] 2020-04-09 14:21
DocumentServer 5.5.1 released. This issue should be fixed.

**Closed by ShockwaveNN** 2020-04-09 14:21 UTC
Labels: bug, fixed
