### ISSUE TITLE
Warning An error occurred during the work with the document.

### ISSUE THREAD

**Issue by e7868a** [ONLYOFFICE/DocumentServer#833] opened 2020-04-07 02:38 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Failed to open a **Spreadsheet** after Co-Editing. When open the document, it popup a dialog says: 
> "An error occurred during the work with the document. Use the 'Download as...' option to save the file backup to your computer hard drive"。

After download the document to my computer, when opening with Excel, It says  "The file is corrupted, need repair"。

Excel create a repair log, it's content like
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <logFileName>error056080_01.xml</logFileName>
    <summary>在文件“C:\Users\user\Downloads\Spreadsheet.xlsx”中检测到错误</summary>
    <additionalInfo>
        <info>Excel 已完成文件级验证和修复。此工作簿的某些部分可能已被修复或丢弃。</info>
    </additionalInfo>
    <repairedRecords summary="以下是修复列表:">
        <repairedRecord>已修复的记录: /xl/drawings/drawing1.xml 部分的 绘图 (绘图形状)</repairedRecord>
    </repairedRecords>
</recoveryLog>
```

There is a error log on DocumentServer /var/log/onlyoffice/documentserver/docservice/out.log
```
[2020-04-03T07:58:14.214] [ERROR] nodeJS - changesError: docId = 1015025223 Error: Uncaught TypeError: Cannot read property 'height' of undefined Script: http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js Line: 7719:241 userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 platform: Win32 isLoadFullApi: true isDocumentLoadComplete: true StackTrace: TypeError: Cannot read property 'height' of undefined
    at w.L7 (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:7719:241)
    at w.iBa (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:7719:336)
    at Da.Uqa (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:4207:402)
    at Ha.Da.Ha.PFb (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:4132:4)
    at Da.Pa.ve (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:4142:311)
    at w.Vpg (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:7730:504)
    at h.Yf (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:7670:154)
    at h.z9b (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:7671:435)
    at h.AKf (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:7670:220)
    at h.resize (http://192.168.1.197:7070/ds-vpath/5.5.0-165/sdkjs/cell/sdk-all.js:7676:229)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

don't know how to reproduce.

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

doesn't know

**DocumentServer version:**

5.5.0

**Operating System:**

Windows 7

**Browser version:**

Google Chrome 59.0

**Comment by Rita-Bubnova** [comment] 2020-04-07 07:27
Hello, @e7868a.
Can you attach original file and file that opens with an error "An error occurred during the work with the document. Use the 'Download as...' option to save the file backup to your computer hard drive"?

**Comment by e7868a** [comment] 2020-04-08 02:45
> Hello, @e7868a.
> Can you attach original file and file that opens with an error "An error occurred during the work with the document. Use the 'Download as...' option to save the file backup to your computer hard drive"?

Hi, I can't attach the original file, the data content is restrict, i can't take outside my office。I can provide the `/xl/drawings/drawing1.xml` which Excel sayed it repaired。Both the corrupted and the repaired version.

The document was created  in Nextcloud。We create 3 sheets, create about 70000 rows in first sheet, 5000 rows in other sheets.

[drawing1-corrupted-repaired.zip](https://github.com/ONLYOFFICE/DocumentServer/files/4447903/drawing1-corrupted-repaired.zip)

**Comment by Rita-Bubnova** [comment] 2020-04-08 08:41
Thank you for your report. 
I can confirm - this is a bug, issue 45093 in our internal issue tracker.

**Comment by e7868a** [comment] 2020-04-08 10:27
Does this bug cause data lost？We are trying ONLYOFFICE  to confirm whether it is suitable for work needs.

**Comment by SergeyLuzyanin** [comment] 2020-04-08 14:48
Hello, @e7868a.
The problem is caused by drawings placed in rows starting from 21476. 
The bug will be fixed in version 5.5.2. Files will be saved correctly. Corrupted flies will be opened and repaired after saving. After repairing the only lost information will be coordinates of drawings placed in rows starting from 21476.

**Comment by ShockwaveNN** [comment] 2020-05-22 11:25
DocumentServer v5.5.3 is released. This problem should be fixed

**Closed by ShockwaveNN** 2020-05-22 11:25 UTC
Labels: bug, fixed

**Comment by piiskop** [comment] 2021-09-17 22:39
I get the same warning every now and after in any file that's currently open. I've noticed no data loss however that warning is very annoying. It started to happen after an upgrade of either ONLYOFFICE or Nextcloud. The version of ONLYOFFICE is _ONLYOFFICE/6.1.0.83_.
