### ISSUE TITLE
Incorrect row height when wrap text is applied in hidden column

### ISSUE THREAD

**Issue by vladad** [ONLYOFFICE/DocumentServer#1482] opened 2021-10-25 13:20 UTC
Hello,
you have one wrong behavior when displaying XLSX file with hidden column.

In MS Excel I have two columns:
![image](https://user-images.githubusercontent.com/6140850/138701144-2a227244-cb43-4843-83ae-5ebe71a0a8df.png)

I set width of second column to 0:
![image](https://user-images.githubusercontent.com/6140850/138701358-4c6111c5-30b4-4734-bb74-7db2c50c5c4a.png)

When I open this file in Spreadsheet editor, height of row is incorrectly enlarged:
![image](https://user-images.githubusercontent.com/6140850/138701631-175eaf18-15f5-4e43-9780-f8bfa39e6bf7.png)

Version: OnlyOffice Community 6.4.2

Example file:
[InvisibleColumn.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/7410244/InvisibleColumn.xlsx)

Thanks for solving.

**Comment by osm-frasch** [comment] 2022-06-29 07:15
I can agree with that as well. We can reproduce the same bug here in OnlyOffice version: 7.0.1.37 (Enterprise) in Nextloud. It has already been confirmed with the OnlyOffice helpdesk (support)

**Comment by LuckySpecialist** [comment] 2024-05-21 18:55
The problem was fixed in release 7.2 with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/371cbaa5d3197cabb69a7b4a1f3740d0e3af1de4), so it can be closed.

**Comment by Rita-Bubnova** [comment] 2024-05-22 11:43
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed as completed by Rita-Bubnova** 2024-05-22 11:43 UTC
Labels: confirmed-bug, fixed
