### ISSUE TITLE
Navigation panel not showing full TOC

### ISSUE THREAD

**Issue by awsong** [ONLYOFFICE/DocumentServer#1368] opened 2021-08-03 02:48 UTC
I'm running community server 11.5.2.1542 with Control panel 3.0.0.381 and Document server 6.3.1.32. 

My navigation panel only works with Safari. I tried MS Edge, Chrome, Firefox, they all have same problem with navigation, only show the very first section of my word document, the rest are gone.

**Comment by ShockwaveNN** [comment] 2021-08-03 06:47
Moving this issue to DocumentServer, since it have nothing to do with CommunityServer

Thanks for your report, we already know about this issue, seems one of Chrome\Firefox\Edge update broke it

@Rita-Bubnova please take a look, I think we already has an issue about this

**Comment by Rita-Bubnova** [comment] 2021-08-03 07:36
Hello. 
@awsong, @ShockwaveNN I can confirm - this is known bug, issue 51297 in our private issue tracker. 
This issue fixed (https://github.com/ONLYOFFICE/web-apps/commit/af084dacc16038717c77759428e3022ba55debde) in future major release.

**Comment by ShockwaveNN** [comment] 2021-08-06 11:37
We're planning to release v6.3.2 with with fix next week

https://github.com/ONLYOFFICE/web-apps/commit/bbb0d0d6e2bbf4c7e7128070675f6930f7de593d

**Comment by ShockwaveNN** [comment] 2021-08-10 11:59
DocumentServer v6.3.2 is release and this issue should be fixed

**Closed by ShockwaveNN** 2021-08-10 11:59 UTC
Labels: bug, fixed

**Comment by awsong** [comment] 2021-08-12 07:48
Confirm it's fixed in v6.3.2. 
Thanks a lot.

**Comment by ShockwaveNN** [comment] 2021-08-12 08:08
@awsong Glad to hear, it's not a common situation for us that browsers update broke our interface
