### ISSUE TITLE
chinese font family bug

### ISSUE THREAD

**Issue by causkycn** [ONLYOFFICE/DocumentServer#1211] opened 2021-04-06 08:56 UTC
chinese font family name  is not working
<img width="806" alt="图片" src="https://user-images.githubusercontent.com/28042942/113684901-45adb580-96f8-11eb-81ad-94aaab432e9f.png">
documentserver-generate-allfonts lost binary files "documentserver/fonts/xxx" & "documentserver/server/FileConverter/bin/libgraphics.so"

english font family name is working
<img width="830" alt="图片" src="https://user-images.githubusercontent.com/28042942/113685181-8dccd800-96f8-11eb-9989-031ad34eb3c2.png">

**Comment by causkycn** [comment] 2021-04-06 08:57
version: 6.2.1-24

**Comment by ShockwaveNN** [comment] 2021-04-06 12:06
Hi
I'm not fully understand your problem - could this be duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/332

If not - please describe step-by-step how to reproduce your problem and attach font files to this issue

**Comment by causkycn** [comment] 2021-04-06 13:33
if ttf Font Family is "Chinese characters", i can select it int the fonts selection. 
<img width="168" alt="图片" src="https://user-images.githubusercontent.com/28042942/113718454-3beb7880-971f-11eb-99b6-700380c30a3e.png">
i can see the font, but it not working.  can't change the font.

**Comment by ShockwaveNN** [comment] 2021-04-06 15:03
1. Try to cleanup cache, sometimes there is a need to cleanup cache to change font to work
2. If 1 not help - please attach this font to issue, as I asked earlier

**Closed** 2021-04-15 02:06 UTC

**Comment by causkycn** [comment] 2021-04-15 02:08
<img width="750" alt="图片" src="https://user-images.githubusercontent.com/28042942/114803557-3c94a680-9dd2-11eb-995a-ba5d9f312049.png">

**Comment by MysticEEEE** [comment] 2021-04-16 03:37
hi, causkycn, would you mind sharing those fonts files? Thanks!
Here is my problem:
I deployed the ONLYOFFICE in windows 7 recently, the fonts names were not shown like you, they were all shown in English.
BTW, did you meet the problem that Chinese can't be typed(e.g. I type “你好”，it would show nihao only not 你好).

**Comment by islercn** [comment] 2021-04-20 13:26
@causkycn could you share your solution or pr please?
