### ISSUE TITLE
The picture is not displayed correctly in excel

### ISSUE THREAD

**Issue by SizerSong** [ONLYOFFICE/DocumentServer#1804] opened 2022-06-24 03:40 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The picture is not displayed correctly in excel（Stretched or shortened）

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Upload a excel containing images

**What is the expected behavior?**
Normal display of pictures

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
docker image: d08ace600ec4ad172e707b861c1cea758430756fe326a6d34e44f2af17c98829

**Operating System:**
Debian 10

**Browser version:**
chrome v102.0.5005.63

**Comment by ShockwaveNN** [comment] 2022-06-24 07:09
Hi first of all we need file you talking about

Second - by using Excel do you mean ONLYOFFICE Spreadsheet Editor?

**Comment by SizerSong** [comment] 2022-06-24 10:11
> Hi first of all we need file you talking about
> 
> Second - by using Excel do you mean ONLYOFFICE Spreadsheet Editor?

Here is one of my test pictures. In fact, I tested several images, and they all looked the same
![cover_Eddie-Yuyan-Peng-hairstyle1](https://user-images.githubusercontent.com/25151613/175513207-66a575b5-730a-4da5-a8f5-bca66eee724b.jpg)

Yes, i installed the ONLYOFFICE Docs Community Edition, when i upload a excel with picture, the picture is not displayed correctly like this:
![test](https://user-images.githubusercontent.com/25151613/175514367-1835bdac-0e42-413f-b77a-d6e4e114267a.png)

**Comment by ShockwaveNN** [comment] 2022-06-24 11:07
What do you mean by "not displaying"?

I've uploaded it and it shown fine:
![image](https://user-images.githubusercontent.com/668524/175522601-741d8f15-79ef-4cd2-bf79-77a2d0b244be.png)


And it shown fine on your screenshot or I don't understand you

Please provide all necessary information to reproduce your issue, it's some kind of puzzle for me right now with part I need to guess

And please do not call our Spreadsheet Editor `excel` - this is name for Microsoft products

**Comment by SizerSong** [comment] 2022-06-27 02:22
> ONLYOFFICE Spreadsheet Editor

Hi,
Thanks for your reply.
In my screenshot, the picture does not display correctly, its **lateral** position was narrowed, and my docker image was d08ace600ec4ad172e707b861c1cea758430756fe326a6d34e44f2af17c98829. could you please test ONLYOFFICE Spreadsheet Editor for this version?

**Comment by ShockwaveNN** [comment] 2022-06-27 09:07
> d08ace600ec4ad172e707b861c1cea758430756fe326a6d34e44f2af17c98829

I cannot find this hash in our [official repo](https://hub.docker.com/r/onlyoffice/documentserver/tags?page=1&name=d08ace6)

But judging by this [article](https://www.cfanz.cn/resource/detail/rMxQxqwjoOGKq) this may be version v7.0.1

I think you need to update to the latest official image v7.1.1 and check for your problem once again, since I've checked this version

**Comment by SizerSong** [comment] 2022-06-28 03:06
> > d08ace600ec4ad172e707b861c1cea758430756fe326a6d34e44f2af17c98829
> 
> I cannot find this hash in our [official repo](https://hub.docker.com/r/onlyoffice/documentserver/tags?page=1&name=d08ace6)
> 
> But judging by this [article](https://www.cfanz.cn/resource/detail/rMxQxqwjoOGKq) this may be version v7.0.1
> 
> I think you need to update to the latest official image v7.1.1 and check for your problem once again, since I've checked this version

OK, I will try it, thanks again！

**Comment by SizerSong** [comment] 2022-06-28 06:35
> > d08ace600ec4ad172e707b861c1cea758430756fe326a6d34e44f2af17c98829
> 
> I cannot find this hash in our [official repo](https://hub.docker.com/r/onlyoffice/documentserver/tags?page=1&name=d08ace6)
> 
> But judging by this [article](https://www.cfanz.cn/resource/detail/rMxQxqwjoOGKq) this may be version v7.0.1
> 
> I think you need to update to the latest official image v7.1.1 and check for your problem once again, since I've checked this version

Hi,
I tried onlyoffice/documentserver:7.1.1 but still have the problem, here is my docker-compose.yml:
```version: '3'
services:
  onlyoffice-doc-test:
    container_name: onlyoffice-doc-71-tmp
    image: onlyoffice/documentserver:7.1.1
    stdin_open: true
    tty: true
    ports:
#     - '8081:80'
     - '8499:443'
    restart: always
    volumes:
     - ./local-test.json:/etc/onlyoffice/documentserver/local-test.json
     - ./logs:/var/log/onlyoffice
     - ./data:/var/www/onlyoffice/Data
     - ./lib:/var/lib/onlyoffice
     - ./rabbitmq:/var/lib/rabbitmq
     - ./redis:/var/lib/redis
     - ./db:/var/lib/postgresql
    environment:
      - SSL_CERTIFICATE_PATH=/var/www/onlyoffice/Data/certs/hidden.crt
      - SSL_KEY_PATH=/var/www/onlyoffice/Data/certs/hidden.key
```
and here is local-test.json
```{
    "services": {
        "CoAuthoring": {
             "autoAssembly": {
                 "enable": true,
                 "interval": "5m"
             }
        }
    }
 }
```

xlsx file in my local PC:
![git1](https://user-images.githubusercontent.com/25151613/176108751-258653a5-5ca6-49cd-a625-f14572b30cff.png)

After upload to Onlyoffice document server:
![git2](https://user-images.githubusercontent.com/25151613/176108920-d8fb22b8-6a7f-4958-b6d6-79cda475fa8b.png)
![git3](https://user-images.githubusercontent.com/25151613/176109032-d96597bb-d1ce-41e3-8d63-6ff39423aa09.png)

and here is my xlsx file:
[图片拉伸测试.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/8998247/default.xlsx)

I wonder if it's a character set problem or something, could you please test this xlsx file in your DocumentServer? If you have other ideas, please let me know, I got my head kicked by this question.

Thanks.

**Comment by SizerSong** [comment] 2022-06-28 06:55
> What do you mean by "not displaying"?
> 
> I've uploaded it and it shown fine: ![image](https://user-images.githubusercontent.com/668524/175522601-741d8f15-79ef-4cd2-bf79-77a2d0b244be.png)
> 
> And it shown fine on your screenshot or I don't understand you
> 
> Please provide all necessary information to reproduce your issue, it's some kind of puzzle for me right now with part I need to guess
> 
> And please do not call our Spreadsheet Editor `excel` - this is name for Microsoft products

By the way, I'm not uploading photos to onlyoffice doc editors, i insert the photo into xlsx file and upload xlsx file to onlyoffice, I guess there's something wrong with this step

**Comment by LuckySpecialist** [comment] 2022-06-28 15:53
Hi @SizerSong, judging by the provided file, it was not made in our application. Therefore, I do not think that this can be considered our problem.
If you upload a picture to our application, the proportions of the image are correct.
I checked how the file opens on three editors and didn't notice any difference.
![MS_LIBRE_OO_OpenFile](https://user-images.githubusercontent.com/19473546/176224656-2e622105-719c-4ac9-b4f2-000fc90bf187.PNG)

**Comment by SizerSong** [comment] 2022-06-29 03:43
> Hi @SizerSong, judging by the provided file, it was not made in our application. Therefore, I do not think that this can be considered our problem. If you upload a picture to our application, the proportions of the image are correct. I checked how the file opens on three editors and didn't notice any difference. ![MS_LIBRE_OO_OpenFile](https://user-images.githubusercontent.com/19473546/176224656-2e622105-719c-4ac9-b4f2-000fc90bf187.PNG)

Hi,
Thanks for your reply, do you mean there's something wrong with the file itself? Maybe **Microsoft office 2016 Professional Plus** has compatibility problems?
But we have a number of scenarios for uploading spreadsheets. How can we avoid this problem? 
Thanks again.

**Comment by SizerSong** [comment] 2022-06-29 03:45
> Hi @SizerSong, judging by the provided file, it was not made in our application. Therefore, I do not think that this can be considered our problem. If you upload a picture to our application, the proportions of the image are correct. I checked how the file opens on three editors and didn't notice any difference. ![MS_LIBRE_OO_OpenFile](https://user-images.githubusercontent.com/19473546/176224656-2e622105-719c-4ac9-b4f2-000fc90bf187.PNG)

By the way, we want to upgrade our certificate to EE(enterprise edition), but we're not sure how many connection we need, did EE have a free trail version?

**Comment by LuckySpecialist** [comment] 2022-06-29 10:26
I want to say that the file is created this way and is displayed here as in other editors. I can't say anything about the problems of third-party editors. It is better for you to contact the application developer.
Fix probably only manually make changes to the source file, I think.

The second question is better solved directly with the sales department (sales@onlyoffice.com).

**Comment by SizerSong** [comment] 2022-07-01 03:03
> I want to say that the file is created this way and is displayed here as in other editors. I can't say anything about the problems of third-party editors. It is better for you to contact the application developer. Fix probably only manually make changes to the source file, I think.
> 
> The second question is better solved directly with the sales department ([sales@onlyoffice.com](mailto:sales@onlyoffice.com)).

OK，thank you for the response, i'll try another way to create spreadsheets

**Comment by ShockwaveNN** [comment] 2022-07-01 07:23
I'll close this issue since we found a root case of problem and it's not in our code.
But feel free to comment if you got any more finds

**Closed by ShockwaveNN** 2022-07-01 07:23 UTC
