### ISSUE TITLE
how to change http to https

### ISSUE THREAD

**Issue by Terryisthebest** [ONLYOFFICE/DocumentServer#2857] opened 2024-08-26 08:26 UTC
<img width="1533" alt="iShot_2024-08-25_20 46 02" src="https://github.com/user-attachments/assets/fcae1b42-d58f-49c1-a23f-610e04081be0">
<img width="1548" alt="iShot_2024-08-25_20 46 42" src="https://github.com/user-attachments/assets/903dbda4-fa6a-49e7-83eb-ade7624f07b6">
<img width="1548" alt="iShot_2024-08-25_20 47 54" src="https://github.com/user-attachments/assets/8b39a43f-40c3-4806-bb52-a98ed3ed6afa">
How to solve it? Help me!!

_Originally posted by @Terryisthebest in https://github.com/ONLYOFFICE/DocumentServer/issues/2824#issuecomment-2308821316_

**Comment by igwyd** [comment] 2024-09-02 07:46
Hello @Terryisthebest, this is duplicate of #2824, continue communicate in first isssue.

**Closed** 2024-09-02 07:47 UTC
