### ISSUE TITLE
can not found spreadsheet file version

### ISSUE THREAD

**Issue by tbs575** [ONLYOFFICE/DocumentServer#1177] opened 2021-03-10 01:37 UTC
Using DocumentServer, In word file, I can see edit history. but in spreadsheet, can not find, where is it? thanks

**Comment by Rita-Bubnova** [comment] 2021-03-10 07:39
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1085.

**Closed** 2021-03-10 07:40 UTC
Labels: duplicate
