### ISSUE TITLE
Embedded viewer: download option visible when not configured

### ISSUE THREAD

**Issue by brianagriffith** [ONLYOFFICE/DocumentServer#1239] opened 2021-04-21 20:18 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?** 
In the embedded viewer, the download option is always visible if the print option is visible. Even when shareUrl is not provided and the download permission is false. If print is turned off, then the download option behaves as expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Configure the editor for embedded viewing with the print permission = true and download = false (or just not specified at all). The download option is still displayed in the menu. Selecting download will actually launch the browser print dialog.

**What is the expected behavior?** 
The download option should only be visible if the editor is configured for download.

**Did this work in previous versions of DocumentServer?** 
Unknown

**DocumentServer version:** 
6.2.2

**Operating System:** 
Windows

**Browser version:** 
Chrome 90.0.4430.85

**Comment by ShockwaveNN** [comment] 2021-04-22 08:46
@igwyd please take a look

**Comment by igwyd** [comment] 2021-04-22 10:46
Hello @brianagriffith
What operating system is the onlyoffice-documentserver installed?

**Comment by brianagriffith** [comment] 2021-04-22 14:01
@igwyd - Windows Server

**Comment by igwyd** [comment] 2021-04-23 15:11
Thank you for report @brianagriffith
I can confirm, download available in embedded mode with permission download = false. This is bug, issue 49866 in our private issue tracker.

You also wrote that "Selecting download will actually launch the browser print dialog". I can't reproduce it, in my case select download launch downloading document(docx, xlsx or pptx). If i use download option on PDF file in embedded mode it is opened in browser with print option, not print dialog.

**Comment by igwyd** [comment] 2021-11-02 13:33
It's fixed at: https://github.com/ONLYOFFICE/web-apps/commit/1b4cc723ea7453b733eba8623a1246eb9da54106
And will be release as v7.0.0

**Comment by ShockwaveNN** [comment] 2022-01-18 12:27
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual

**Closed by ShockwaveNN** 2022-01-18 12:27 UTC
Labels: bug, fixed
