### ISSUE TITLE
Export Word document to PDF with table of content

### ISSUE THREAD

**Issue by romale** [ONLYOFFICE/DocumentServer#1042] opened 2020-10-28 09:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
OO + nextcloud

**What is the expected behavior?**
Save word document as pdf with table of content

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer version:**
OO 5.5.3.39 docker

**Operating System:**
centos7

**Browser version:**
FF 78.4.0esr

**Comment by Rita-Bubnova** [comment] 2020-10-28 16:22
Maybe, duplicate of #https://github.com/ONLYOFFICE/DesktopEditors/issues/419 ?

**Comment by ShockwaveNN** [comment] 2020-11-30 11:17
This issue was closed due to no response.

**Closed by ShockwaveNN** 2020-11-30 11:17 UTC

**Comment by romale** [comment] 2020-11-30 11:38
This bug Is solved?

**Comment by ShockwaveNN** [comment] 2020-11-30 11:43
No, original issue #419 is still actual, I've just closed this issue as duplicate

**Comment by romale** [comment] 2020-11-30 11:46
Ok, thanks
