### ISSUE TITLE
Drop - down box problem after merging cells

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1199] opened 2021-03-30 09:00 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Take the combination of four cells K8/L8/M8/N8 as an example. OnlyOffice does not only display one drop-down box for the merged cell, but displays four drop-down boxes for the four cells K8/L8/M8/N8 respectively. Only the drop-down box corresponding to K8 on the left will display the contents of the merged cell
(K8/L8/M8/N8 in the description refers to the cell coordinates)

**What is the expected behavior?**
When the four cells K8/L8/M8/N8 are combined, only one drop-down box is displayed
(K8/L8/M8/N8 in the description refers to the cell coordinates)

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer version:**
5.5.3

**Operating System:**
win10

**Browser version:**
Chrome Version 89.0.4389.90 (Official) (64-bit)

**Comment by ShockwaveNN** [comment] 2021-03-30 09:18
Hi

> DocumentServer version:
> 5.5.3

This version is very old, could you update to current version 6.2 and see if this problem exists

**Comment by nobt854** [comment] 2021-03-30 11:44
Hi,
After updating version 6.2, I still had this problem by using OnlyOffice to set the same drop-down box for four adjacent cells, and then combining the four adjacent cells.The question now is in the merged ONLYOFFICE in merge cells still shows four drop-down box on the options, expectations are merged cells show only a drop-down box option, and from the drop-down box to choose directly displayed as merged cell values, and displayed on the merge cells drop-down box set drop-down box should be like a single cell, the down arrow on the right side of the cell.

Thank you. Have a nice day!

**Comment by ShockwaveNN** [comment] 2021-03-30 11:45
@Rita-Bubnova Could you take a look?

**Comment by Rita-Bubnova** [comment] 2021-03-30 12:03
Hello, @nobt854, @ShockwaveNN.
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/854.

**Comment by ShockwaveNN** [comment] 2021-03-30 12:09
@Rita-Bubnova Thanks

**Closed by ShockwaveNN** 2021-03-30 12:09 UTC

**Comment by nobt854** [comment] 2021-03-30 12:11
@Rita-Bubnova Thanks
