### ISSUE TITLE
Incorrectly sorted data for Turkish language in spreadsheets

### ISSUE THREAD

**Issue by mdagtek** [ONLYOFFICE/DocumentServer#1505] opened 2021-11-06 08:27 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.4.2.6

### Expected Behavior

If the data  spreadsheet is set to Turkish language it should sort based on the alphabet of the Turkish language. 

For example:

`ALİ`
`MURAT`
`İSMAİL`

should be sorted as 

`ALİ`
`İSMAİL`
`MURAT`

[s.xlsx](https://github.com/ONLYOFFICE/DesktopEditors/files/7490079/s.xlsx)

### Actual Behavior

The data is sorted wrong when it includes the following characters which are a part of the alphabet in Turkish:

`Ç,Ö,İ,Ğ,Ü,ı,ğ,ü,ç,ö`

The following is the entered data:

`ALİ`
`MURAT`
`İSMAİL`

This is what comes out after sorting:

`ALİ`
`MURAT`
`İSMAİL`

### Reproduction Steps

1-) Create a new spreadsheet
2-) Set "Regional Settings" under "Advanced Settings" to Turkey.
3-) Put the following values in the cells of a column:

`ALİ`
`İSMAİL`
`MURAT` 

4-) Select the data and sort them
5-) The data is sorted wrong.

### Additional information

The Turkish alphabet consists of  the following letters in order:

`A B C Ç D E F G Ğ H I İ J K L M N O Ö P R S Ş T U Ü V Y Z`
`a b c ç d e f g ğ ı i j k l m n o ö p r s ş t u ü v y z`

**Comment by ShockwaveNN** [comment] 2021-11-09 07:40
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by TatianaKirillova** [comment] 2024-06-17 09:02
Hello @mdagtek!
I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/609243b5d1a76f7a5cfa5580f94cb20fc0995b8d) and will be included in the next release. Don't miss updates)

**Comment by Rita-Bubnova** [comment] 2024-06-21 15:11
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-06-21 15:11 UTC
Labels: confirmed-bug, fixed-release
