### ISSUE TITLE
Mobile Editor license change (in browser)

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/DocumentServer#846] opened 2020-04-16 09:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Use Documenteditor in Browser (on iPad) say Blabla[..] Mobile Web editor not available in Open Source Version -> we have bought a license 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
upgrade to 5.5.0?
**What is the expected behavior?**
When use in Browser equal its on mobile or desktop you can use it

**Did this work in previous versions of DocumentServer?**
Yes 
**DocumentServer version:**
5.5.0

**Operating System:**
Debian 10.3
**Browser version:**
Safari 
![OOError](https://user-images.githubusercontent.com/48324739/79442273-9e141080-7fd8-11ea-96c1-e413dfe53d94.png)

**Comment by hahaxd35** [comment] 2020-04-16 10:01
with User-agent switcher -> android works?!?

**Comment by ShockwaveNN** [comment] 2020-04-16 11:03
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/805

**Closed by ShockwaveNN** 2020-04-16 11:03 UTC

**Comment by hahaxd35** [comment] 2020-04-16 11:44
we have a paid version...

**Comment by hahaxd35** [comment] 2020-04-16 11:51
i notice i have installed "onlyoffice-documentserver" not "onlyoffice-documentserver-de" 

is "onlyoffice-documentserver" the "opensource Version"?!?
i would name the "not opensource" part -> enterprise

**Comment by ShockwaveNN** [comment] 2020-04-16 12:30
> is "onlyoffice-documentserver" the "opensource Version"?!?

yes

> i would name the "not opensource" part -> enterprise

It's just be that way historically. And yes we changed, that `onlyoffice-documentserver` cannot read licenses. You better install paid version (`onlyoffice-documentserver-de` or `onlyoffice-documentserver-ie`)
