### ISSUE TITLE
Every upgrade overwrites custom configuration

### ISSUE THREAD

**Issue by supercompman** [ONLYOFFICE/DocumentServer#464] opened 2018-12-26 15:56 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using the official OnlyOffice repository for Debian ( http://download.onlyoffice.com/repo/debian ), every upgrade to the Document Server causes any customization made to the /etc/onlyoffice/documentserver/nginx/onlyoffice-documentserver.conf to be overwritten with the default configuration.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install OnlyOffice Document Server from the repository at http://download.onlyoffice.com/repo/debian
2. Customize this file /etc/onlyoffice/documentserver/nginx/onlyoffice-documentserver.conf
3. Upgrade to a new version of the OnlyOffice Document Server

**What is the expected behavior?**
The /etc/onlyoffice/documentserver/nginx/onlyoffice-documentserver.conf file should not be modified, or changes should be merged into this configuration, or the user performing an upgrade should be given the option to leave the configuration alone or replace it with the default from the package.

**Did this work in previous versions of DocumentServer?**
Not that I'm aware of, no.

**DocumentServer version:**
Document Server 5.2.6 (upgraded from 5.2.4)

**Operating System:**
Ubuntu Server 18.04.1 LTS

**Browser version:**
N/A

**Comment by mvvvmd** [comment] 2018-12-27 15:06
Same issue here, killed my install this way for the second time, recovering is difficult because of changes you need to figure out. Just restoring the old config is not enough.

**Comment by merced317** [comment] 2019-12-18 14:05
Updating via apt using the official OnlyOffice repository for Debian overwrites /etc/onlyoffice/documentserver/local.json as well.  All configuration files need to be marked as conffiles.  See this man page for assistance: https://manpages.debian.org/testing/dpkg-dev/deb-conffiles.5.en.html

**Comment by igwyd** [comment] 2023-10-03 06:56
This is Duplicate of #216

**Comment by Rita-Bubnova** [comment] 2023-10-03 10:26
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-03 10:26 UTC
Labels: duplicate
