### ISSUE TITLE
web-apps spreadsheet missing french formulas

### ISSUE THREAD

**Issue by deajan** [ONLYOFFICE/DocumentServer#333] opened 2018-07-02 10:15 UTC
In the DocuementServer changelog.md file, version 5.1.3 states:
```Add French translation for formulas```

I've checked in apps/spreadsheeteditor/main/ressources/formula-lang, no fr.json file is present (in web-apps repo).
Any plans on that ?

**Comment by ShockwaveNN** [comment] 2018-07-02 10:17
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/321

**Closed by ShockwaveNN** 2018-07-02 10:17 UTC

**Comment by deajan** [comment] 2018-07-02 10:21
Thanks (wow! Fastest github issue ever. Didn't finish to update my issue and you already answered :)
