### ISSUE TITLE
Empty string underline problem

### ISSUE THREAD

**Issue by nn200433** [ONLYOFFICE/DocumentServer#2619] opened 2023-05-18 11:40 UTC
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

edit document

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![underline](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/15652213/7391d20d-9c2d-4a0f-9d74-c126e9658fdf)

As shown in the gif demo.

If you enter a blank character and underline it, the underline will not be displayed.

**What is the expected behavior?**

Blank characters can show underline

**Did this work in previous versions of DocumentServer?**

I don't know

**DocumentServer Docker tag:**

version is 7.0.1.37

```dockerfile
# 镜像来源
FROM onlyoffice/documentserver:7.0.1.37

# 设置时区
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive

# 设置时区为上海
RUN apt-get update \
    && apt-get install -y tzdata \
    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

# 移除一些插件
RUN rm -rf /var/www/onlyoffice/documentserver/sdkjs-plugins/youtube
RUN rm -rf /var/www/onlyoffice/documentserver/sdkjs-plugins/translator
RUN rm -rf /var/www/onlyoffice/documentserver/sdkjs-plugins/zotero
RUN rm -rf /var/www/onlyoffice/documentserver/sdkjs-plugins/mendeley
RUN rm -rf /var/www/onlyoffice/documentserver/sdkjs-plugins/thesaurus
RUN rm -rf /var/www/onlyoffice/documentserver/sdkjs-plugins/ocr

# 移除字体
RUN rm -rf /usr/share/fonts/truetype/dejavu
RUN rm -rf /usr/share/fonts/truetype/liberation

# 导入中文字体
COPY ./fonts/ /usr/share/fonts/

# 修正hightlight js引用问题
RUN sed -i "s/https:\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/2.2.2\/jquery.min.js/vendor\/jQuery-2.2.2-min\/jquery-v2.2.2-min.js/" /var/www/onlyoffice/documentserver/sdkjs-plugins/highlightcode/index.html

# 添加中文字号
RUN sed -i "s/{value:8,displayValue:\"8\"}/{value:42,displayValue:\"初号\"},{value:36,displayValue:\"小初\"},{value:26,displayValue:\"一号\"},{value:24,displayValue:\"小一\"},{value:22,displayValue:\"二号\"},{value:18,displayValue:\"小二\"},{value:16,displayValue:\"三号\"},{value:15,displayValue:\"小三\"},{value:14,displayValue:\"四号\"},{value:12,displayValue:\"小四\"},{value:10.5,displayValue:\"五号\"},{value:9,displayValue:\"小五\"},{value:7.5,displayValue:\"六号\"},{value:6.5,displayValue:\"小六\"},{value:5.5,displayValue:\"七号\"},{value:5,displayValue:\"八号\"},{value:8,displayValue:\"8\"}/g" `grep -rwl --include="*.js" "{value:8,displayValue:\"8\"}" /var/www/onlyoffice/documentserver/web-apps/apps`

# 固定字体列表高度
RUN sed -i "s/{cls:\"input-group-nr\",menuStyle:\"min-width: 55px;\"/{cls:\"input-group-nr\",menuStyle:\"min-width: 55px;height: 500px;\"/g" `grep -rwl --include="*.js" "{value:8,displayValue:\"8\"}" /var/www/onlyoffice/documentserver/web-apps/apps`

# 修改文件缓存时间
# 修改24小时为1小时
RUN sed -i  "s/86400/3600/" /etc/onlyoffice/documentserver/default.json

EXPOSE 80 443

ARG COMPANY_NAME=onlyoffice
VOLUME /var/log/$COMPANY_NAME /var/lib/$COMPANY_NAME /var/www/$COMPANY_NAME/Data /var/lib/postgresql /var/lib/rabbitmq /var/lib/redis /usr/share/fonts/truetype/custom

ENTRYPOINT ["/app/ds/run-document-server.sh"]
```

**Host Operating System:**

CentOS 7.9

---

Today, I tried the latest docker image, but it was the same as the old one.

![DI1NJ2{Q9G1HANZQ4P6G~ 2](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/15652213/8ea058e3-e3bd-48cc-8208-b144168a98a8)

![9 UK`LH4LZ )IO@%1BWTJHM](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/15652213/c3802b82-0931-4465-b4e3-cabf11728bca)

**Comment by ElenaMaaya** [comment] 2024-03-01 08:58
Hello @nn200433!
Thank you for report!
I can confirm that the problem exists. I created ticket 66683  in our  issue tracker.

**Comment by Rita-Bubnova** [comment] 2024-03-01 09:14
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2554.

**Closed by Rita-Bubnova** 2024-03-01 09:14 UTC
