### ISSUE TITLE
Compatibility issue: Content in MS Word document is obscured when opened with OnlyOffice.

### ISSUE THREAD

**Issue by JiffyChen** [ONLYOFFICE/DocumentServer#2808] opened 2024-07-11 07:54 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Windows 10 / 8.1 / 7

### Version information

ONLYOFFICE Desktop Editors  8.0.1.31 (x64 exe)

### Expected Behavior

[test.docx](https://github.com/user-attachments/files/16173279/test.docx)
When I opened the document using only office, I found that the document format created in MS Word had significant misalignment.
ms word:![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/4900504/ff56d262-6ed1-48af-a4a8-60d74ca772c6)
onlyoffice:
![image](https://github.com/ONLYOFFICE/DesktopEditors/assets/4900504/38c6c97e-ec33-4cc2-be8e-3cbc2d2726cf)

### Actual Behavior

 document format created in MS Word had significant misalignment.

### Additional information

ms office:  office 2013 pro

**Comment by ElenaMaaya** [comment] 2024-07-19 11:29
Duplicate of #1640.

**Closed** 2024-07-19 11:30 UTC
Labels: confirmed-bug, duplicate
