### ISSUE TITLE
documentserver-generate-allfonts.sh use sudo, but sudo is not required by package

### ISSUE THREAD

**Issue by jmcclelland** [ONLYOFFICE/DocumentServer#364] opened 2018-08-14 14:06 UTC
Currently, if you follow the directions to install the linux version of the DocumentServer without having sudo installed on your host, the installation will proceed without incident, but documentserver-generate-allfonts.sh will fail because it depends on sudo. Without AllFonts.js, the application fails to work properly.

It would be helpful to either list sudo as a dependency in the instructions or make sudo a dependency in the debian package so it is pulled in by default.

Tested in Debian Stretch

Thanks!

**Comment by ShockwaveNN** [comment] 2018-08-14 14:14
@jmcclelland Ok, I agree with you, `documentserver-generate-allfonts.sh` contains sudo commands
@agolybev take a look at this, maybe it's better to remove sudo from `documentserver-generate-allfonts.sh` altougether and require user to run it with `sudo documentserver-generate-allfonts.sh`

**Comment by strugee** [comment] 2019-04-15 06:41
Looks like the script uses `sudo -u onlyoffice` mostly for file ownership. I would suggest just adding a `chown` call after, in which case `sudo` would not be needed. But you could also just add `sudo` to the package dependencies.

**Comment by igwyd** [comment] 2023-10-03 07:21
Hello @jmcclelland, sorry for the late reply. Now the installation required ```sudo``` and documentserver-generate-allfonts.sh too. The Issue is not longer relevant.

**Comment by Rita-Bubnova** [comment] 2023-10-03 10:31
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-03 10:31 UTC
Labels: confirmed-bug, question
