### ISSUE TITLE
 HTTPS Error: Mixed Contents 

### ISSUE THREAD

**Issue by ketlinapuci** [ONLYOFFICE/DocumentServer#2423] opened 2023-10-16 07:48 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package), Docker

### Version information

 ONLYOFFICE Docs v7.4 Docker

### Expected Behavior

Hello, I have installed onlyoffice in one Ubuntu 22.04.2 server following the instructions as in the onlyoffice.com page in docker.

sudo docker run -i -t -d -p 80:80 -p 443:443 --restart=always \
    -e LETS_ENCRYPT_DOMAIN=yourdomain.com -e LETS_ENCRYPT_MAIL=email@example.com -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver-de

and used this, I have changed the ports accordingly and added my domain. I have also added the config files in apache2/sites-available directory .

### Actual Behavior

After I enabled the site, I could access it at https://domain.com, but after I executed the example and went to create a new document or edit a created one, I am redirected to a blank page and get this in the console
```
Mixed Content: The page at 'https://onlyoffice.evolutivo.it/example/editor?fileName=new%20(1).docx' was loaded over HTTPS, but requested an insecure frame 'http://onlyoffice.evolutivo.it/7.4.1-36/web-apps/apps/documenteditor/main/index.html?_dc=7.4.1-36&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=https://onlyoffice.evolutivo.it'. This request has been blocked; the content must be served over HTTPS.
```

### Additional information

WHat could be wrong , can you help me with this issue?
thank you

**Comment by igwyd** [comment] 2023-11-16 05:51
This is Duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/669

**Closed** 2023-11-16 22:41 UTC
Labels: duplicate
