### ISSUE TITLE
 Document Bouncing When Editing A Shared Document #2

### ISSUE THREAD

**Issue by pierreozoux** [ONLYOFFICE/DocumentServer#2445] opened 2023-10-24 12:29 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.1

### Expected Behavior

When editing a document, I want to be able to see what I'm editing. I don't want the document to start jumping up and down every time someone else on the document makes an edit.

### Actual Behavior

When editing a shared document, whenever someone makes an edit the document would jump around. So, when working on a shared document with multiple people, the document is very jittery. It is constantly jumping up and down, making it feel like you are editing during an earthquake.

### Reproduction Steps

- Share a document with multiple people using an external link
- Set everyone's access (the shared external link) to full access
- Have everyone edit the document at the same time live

### Additional information

Seems like a regression from:
https://github.com/ONLYOFFICE/DocumentServer/issues/1955

So I copied mostly the issue.

We also checked that we don't have this behavior using HedgeDoc or GoogleDrive.

**Comment by Rita-Bubnova** [comment] 2023-10-25 14:38
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2428.

**Closed by Rita-Bubnova** 2023-10-25 14:38 UTC

**Comment by TatianaKirillova** [comment] 2024-07-09 13:08
Hello @pierreozoux ! I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/commit/c9979671c7278b0c1965d535e1525ccefa3e50f8) and will be included in the next release. Don't miss updates. Have a nice day!
