### ISSUE TITLE
Broken xlsx: empty fills node violates spec

### ISSUE THREAD

**Issue by mjg** [ONLYOFFICE/DocumentServer#682] opened 2019-11-04 15:06 UTC
OnlyOffice changed the format in which it writes fills to `xl/styles.xml` inside xlsx files:
Where it used to write
```<fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="none"/></fill></fills>```
it is now
```<fills count="2"><fill></fill><fill></fill></fills>```
which makes some readers crash (see [openpyxl issue](https://bitbucket.org/openpyxl/openpyxl/issues/1362/load_workbook-crashs-for-workbooks-from)) and supposedly violates the spec.
Since this is a corporate install I cannot pinpoint the version which introduced this.
[Test.xlsx](https://github.com/ONLYOFFICE/CommunityServer/files/3804596/Test.xlsx)

**Comment by Rita-Bubnova** [comment] 2019-11-06 07:39
Hello, @mjg.
Thank you. I can confirm - this is a bug, issue 43480 in our internal issue tracker.

**Comment by vincowl** [comment] 2019-12-10 18:47
Do you have an idea when this fix will be available in the docker image version (available [here](https://hub.docker.com/r/onlyoffice/documentserver/)) ?

**Comment by Rita-Bubnova** [comment] 2019-12-11 07:39
This bug fixed (https://github.com/ONLYOFFICE/sdkjs/commit/46f4a284c03448195ef83e4b75038b1b90b741ca,
https://github.com/ONLYOFFICE/sdkjs/commit/31097d5838fdbe514b2c08edc649b54114b3331a) and will be released in future major release.

**Comment by vincowl** [comment] 2019-12-11 07:51
Thanks @Rita-Bubnova , but what does it mean in terms of time ? We have projects severely impacted by this and no possible hack since every files are minified. We have to decide if we have to foresee an alternative solution or if this will be solved soon.
So question is : when do you plan this future major release ?

**Comment by Rita-Bubnova** [comment] 2019-12-11 08:07
@vincowl, sorry, currently we have no ETA.

**Comment by mjg** [comment] 2019-12-11 08:28
I don't know @vincowl 's toolchain, but two possible workarounds are:
- patch each OnlyOffice-generated generated xlsx before external consumption (by reverting the above substitution; simply update xl/styles.xml in that zip). I used to do this for a while.
- switch to a different "external consumer" if you have only one. I ditched openpyxl (because of that developer's response) for the more lenient xlrd,

**Comment by vincowl** [comment] 2019-12-11 10:38
@Rita-Bubnova That's fine to me. Let's fine a workaround so !

@mjg That's exactly what we were looking at. I have to modify by script xlsx files which are stored on a dedicated nextcloud server coupled to onlyoffice. We are forced to use python or php to develop this script. Every time a user modifies an xlsx file, the script is launched to update cell-styles in an other worksheet (indeed a range of cells which adress is given in a list of other cells). No way to do so with formulas, and macros don't work here. I was using openpyxl which crashed. So I have updated this script to modify the styles.xml file inside the zip, but other problems occurs. Xlrd does not seem to support modifying files. I would have to do so with xlwt which doesn't handle xlsx. No way to downgrade to xls format since onlyoffice doesn't handle it... Any idea ?

**Comment by vincowl** [comment] 2019-12-11 11:22
I made a few tests : it is working with the docker image v5.1.4.22. Testing to check when the trouble occures in term of version

**Comment by vincowl** [comment] 2019-12-11 12:24
Finally updated my python scripts. This hack works while waiting for the fix to be released. Thanks !

**Closed** 2020-03-04 15:15 UTC
Labels: bug
