### ISSUE TITLE
OnlyOffice is completely inaccessible with screenreader

### ISSUE THREAD

**Issue by heull001** [ONLYOFFICE/DocumentServer#2837] opened 2024-08-09 16:56 UTC
I tried to edit a document in OnlyOffice via [sciebo](https://sciebo.de). This is completely impossible for screenreader users. The main problems are:

1. there is no way to focus the text-area, so the document can't be readed or written.
2. Almost none of the buttons are labeled.

There may be more problems, but until the basic problems are fixed, I am not able to find them.

I tested on Windows with Firefox and Edge as browsers and with JAWS and NVDA as screenreaders. the problems are so profound that i assume that other screen readers do not work better here either.

**Comment by TatianaKirillova** [comment] 2024-08-12 18:06
Hello,  @[heull001](https://github.com/heull001)
Thanks for your request!
I can confirm that the problem exists, issue #69679 for your problem. Please use Google Chrome browser until the problem is fixed.

**Comment by TatianaKirillova** [comment] 2024-11-29 12:04
@heull001 I'm happy to report that the issue is fixed in this commit and is already included in the 8.2.2 release. Don't miss updates. Have a good day!

**Comment by Rita-Bubnova** [comment] 2024-11-29 12:06
DocumentServer v8.2.2 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-11-29 12:06 UTC
Labels: confirmed-bug
