### ISSUE TITLE
Document Server doesnt finish the call the docbuilder service

### ISSUE THREAD

**Issue by sibalonat** [ONLYOFFICE/DocumentServer#2360] opened 2023-08-02 14:08 UTC
**Do you want to request a *feature* or report a *bug*?**
I have the docker version of the document server. 
Im using Laravel for the backend and Vue for the frontend. 

**What is the current behavior?**
I try to make a call to the docservice(IP address)/docbuilder and it returns 200, but without any change whatsoever. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

builder.OpenFile('${urlPath}');
var oWorksheet = Api.GetSheet('${$workingSheet}');
oWorksheet.GetRange('${firstCell}').SetValue('${firstValue}');
oWorksheet.GetRange('${secondCell}').SetValue('${secondValue}');
oWorksheet.GetRange('${thirdCell}').SetValue('${thirdValue}');
builder.SaveFile('xlsx', '${OutputFilePath}');
builder.CloseFile();
xlsx file called xlsx.docbuilder
i try to change the content of this file with PHP and it changes the content, but it doesn't change the file i want it to change.

**What is the expected behavior?**
i should pick one defined sheet and thange some values into that sheet.

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**
windows with docker

**Comment by trofim24** [comment] 2023-08-25 11:23
Moved to main repo. The issue is in Document Server

**Comment by askonev** [comment] 2023-08-28 18:27
@sibalonat POST method of Web Document Builder API does not modify already existing documents

According to the documentation, the response body will contain the url to the edited document

https://api.onlyoffice.com/editors/documentbuilderapi

POST method of Web Document Builder API does not modify already existing documents

According to the documentation, the response body will contain the url to the edited document

>There is also a problem with using js from script context in context of builder() methods.

Those when used correctly

```js
var jsVar = "123.docx";
builder.SaveFile("docx", jsVar); // Incorrect
builder.SaveFile("docx", jsValue(jsVar)); // Correct
```

script will not work

**Comment by Rita-Bubnova** [comment] 2023-10-17 12:59
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-17 12:59 UTC
Labels: duplicate
