### ISSUE TITLE
When obtaining changeshistory, track returned created time in an incorrect timezone.

### ISSUE THREAD

**Issue by zgpnuaa** [ONLYOFFICE/DocumentServer#2492] opened 2023-11-27 10:10 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

The actual created time of the changeshistory is 2023-11-27 17:25:20 local time.

### Actual Behavior

But track return 'created': '2023-11-27 09:25:20',  due without considering the local time zone, it is 8 hours later than the local time.

`{'key': '-2768594560439373992', 'version': 2, 'changes': [{'created': '2023-11-27 09:25:20', 'user': {'id': '1', 'name': '\xa0}}], 'serverVersion': '7.5.1', 'created': '2023-11-27 09:25:20', 'user': {'id': '1', 'name': ''}}, `

### Reproduction Steps

The changes:created of the changeshistory returned by track should also consider time zones.

**Comment by TatianaKirillova** [comment] 2023-11-29 09:38
Hello, @[zgpnuaa](https://github.com/zgpnuaa) 
Thanks for your request!
I can confirm - this is know bug, issue #55862 with your problem

**Comment by Rita-Bubnova** [comment] 2023-11-29 09:40
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1664.

**Closed by Rita-Bubnova** 2023-11-29 09:40 UTC
