### ISSUE TITLE
Equation Copy to tex

### ISSUE THREAD

**Issue by PhilipYip1988** [ONLYOFFICE/DocumentServer#2090] opened 2022-12-30 14:01 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### TeX Copy Equation Editor

In Microsoft Word, in the equation editor, TeX can be selected. The WYSIWYG equation editor can be used and the TeX code can then be copied:

![Microsoft Word](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/vlcsnap-2022-12-30-13h44m26s797.png)

This allows the equation editor in Microsoft Word to be used to create an equation for a web application such as a Markdown File:

```
$$\left(1+x\right)^n=1+\frac{nx}{1!}+\frac{n\left(n-1\right)x^2}{2!}+\ldots$$
```

$$\left(1+x\right)^n=1+\frac{nx}{1!}+\frac{n\left(n-1\right)x^2}{2!}+\ldots$$

![Markdown](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/vlcsnap-2022-12-30-13h44m51s028.png)

![Markdown 2](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/vlcsnap-2022-12-30-13h45m00s622.png)

In Document, the Copy Button is greyed out if an equation is selected:

![Document](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/vlcsnap-2022-12-30-13h45m32s138.png)

**Comment by TatianaKirillova** [comment] 2024-04-23 12:48
@PhilipYip1988 I'm happy to report that the issue is fixed with [this commit](https://bugzilla.onlyoffice.com/show_bug.cgi?id=61007) and will be included in the next release. Don't miss updates)

**Comment by Rita-Bubnova** [comment] 2024-06-21 15:11
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-06-21 15:11 UTC
Labels: confirmed-bug, fixed-release
