### ISSUE TITLE
Use IE browser to Edit Excel files, unable to complete movement, copy, paste.

### ISSUE THREAD

**Issue by ggp2018** [ONLYOFFICE/DocumentServer#341] opened 2018-07-10 07:05 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Edit the Excel table using IE:
Q1. right-copy the table with background color, and paste into the blank table, but the background color disappears.
Q2. Select one column of data, then right-paste it to another cell, and the data will be pasted normally, but the data will start from the next cell of the selected cell, not from the selected cell, and if you paste with ctrl v, the result will be normal.
Q3.Select multiple adjacent cells, and then try to drag and drop to other cell locations, but not successfully.
Q4.After selecting 3 columns of data, right-click copy or cut, then select a blank cell, right-paste, but the data will be merged into 1 column display. It is normal to use Ctrl V.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Q1.Don't lose the background color.
Q2.Consistent with the effect of pasting with ctrl v.
Q3.The selected cell data can be dragged or moved successfully.
Q4.Selected 3 columns of data can be pasted successfully.
**Did this work in previous versions of DocumentServer?**
No validation.
**DocumentServer version:**
5.1.2 (build:9)
**Operating System:**
CentOS 7.2  64bits
**Browser version:**
IE 11.09

**Comment by Rita-Bubnova** [comment] 2018-07-10 08:22
Hello, @ggp2018.

Thank you. I can confirm - this is a new bugs, issues 38167, 38168, 38169 in our internal issue tracker.

Unfortunately, one of the problems could not be reproduced:
"Q3.Select multiple side cells, and then try to drag and drop to other cell locations, but not successfully." 
Can you attach video or gif of this problem?

**Comment by ggp2018** [comment] 2018-07-11 01:06
Thank you for your reply. I uploaded Q3 GIFs, please pay attention.
![example for ie11](https://user-images.githubusercontent.com/37365552/42545291-9746f998-84e9-11e8-924b-5244a0c0d702.gif)
![example](https://user-images.githubusercontent.com/37365552/42545292-977f67e2-84e9-11e8-9835-cbf1843984ed.gif)

**Comment by Rita-Bubnova** [comment] 2018-07-11 07:43
In version 5.1.4 (22), this problem has already been fixed.
Please update your document server to latest version.

**Comment by ShockwaveNN** [comment] 2018-07-19 09:39
Closing, since fixed in 5.1.4

**Closed by ShockwaveNN** 2018-07-19 09:39 UTC
Labels: bug
