### ISSUE TITLE
Attributes having custom namespace within custom.xml are not retained on downloading an edited copy

### ISSUE THREAD

**Issue by varunrathi1** [ONLYOFFICE/DocumentServer#2244] opened 2023-05-18 07:29 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.3.3.49

### Expected Behavior

When a DOCX, PPTX or XLSX file having metadata with a custom namespace in the custom.xml is edited and saved back from DocumentServer, the attributes using the custom namespace should be saved in the downloaded files.

### Actual Behavior

When a DOCX, PPTX or XLSX file having metadata with a custom namespace in the custom.xml is edited and saved back from DocumentServer, the attributes using the custom namespace are not retained in the downloaded files.
This was tested through OnlyOffice personal (https://personal.onlyoffice.com).
The data that is being lost is mentioned within the 'op:property' tags. Reference images have been attached in the additional indormation section.

Files that can be be used for testing are :
[Presentation.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/11502382/Presentation.pptx)
[Book.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/11502384/Book.xlsx)
[Document.docx](https://github.com/ONLYOFFICE/DocumentServer/files/11502385/Document.docx)

### Reproduction Steps

1. Unzip DOCX, PPTX or XLSX file having custom metadata (above given files) and open the custom.xml file located within the docProps folder to see the contents.
2. Open the file in OnlyOffice, edit and download it. 
3. Unzip the downloaded DOCX, PPTX or XLSX file and compare the contents of the custom.xml with the uploaded file. The attributes defined with custom tags are not retained (data within 'op:property' tag).

### Additional information

This was tested in a previous version(6.3.1) and it did not work as well.

custom.xml of the file that is uploaded :
![UploadedFileCustomXml](https://github.com/ONLYOFFICE/DocumentServer/assets/133850965/d91a83d9-3010-4806-aa57-c9c94371e3f8)

custom.xml of the downloaded file : 
![DownloadedFileCustomXml](https://github.com/ONLYOFFICE/DocumentServer/assets/133850965/c40b8292-572e-4462-a823-9b330dab8b5f)

**Comment by varunrathi1** [comment] 2023-05-26 12:49
Hi,
Do you have any updates regarding the recreation of the issue and its current status?

**Comment by varunrathi1** [comment] 2023-06-11 19:33
Hi,
Do let me know if you were able to recreate the issue or if you need any further information.

**Comment by LuckySpecialist** [comment] 2023-06-26 16:38
Hi, @varunrathi1 
I apologize for the delay, I will check this problem and write an answer.

**Comment by LuckySpecialist** [comment] 2023-06-28 15:10
Hi, @varunrathi1
The problem is that in your file the tags start with a prefix, that our application cannot read.
If you use tags without prefixes, as MS Office does, then everything will be saved correctly.
According to your request, I have issued Bug 63221 in our internal tracker.
Thanks for the feedback.

**Comment by varunrathi1** [comment] 2023-07-03 18:59
Hi,
MS Office is able to read and preserve the custom metadata when a file is opened or edited in it.

**Comment by LuckySpecialist** [comment] 2023-10-05 16:08
The problem has been fixed by [this commit](https://github.com/ONLYOFFICE/core/commit/a3fd4e26c20ae49632128fe85a6a74869e071ca3) and will be included in the next release.

**Comment by Rita-Bubnova** [comment] 2023-10-19 11:12
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-19 11:12 UTC
Labels: confirmed-bug, fixed-release
