### ISSUE TITLE
Pop-over in track changes mode hides text & cursor  on small screens

### ISSUE THREAD

**Issue by vasyugan** [ONLYOFFICE/DocumentServer#1266] opened 2021-05-14 15:01 UTC
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**

When a paragraph contains tracked changes, that are still pending, those changes are displayed in a bubble that overlays the text one is editing. On a small screen (12''), the bubble is being displayed not in the margin but over the text itself, making editing very very hard, because it doesn't even go away when I try to edit text that is right under it. 
![image](https://user-images.githubusercontent.com/3313208/118288856-0f244100-b4d5-11eb-8f09-3424c80b1ef5.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The bubble/popover should go elsewhere, when the cursor moves into ins place.
**Did this work in previous versions of DocumentServer?**
I don't know. 
**DocumentServer version:**

I suppose, 6.2.2 
![image](https://user-images.githubusercontent.com/3313208/118289703-e6e91200-b4d5-11eb-9bff-e66c6a2268fe.png)

**Operating System:**
Debian Bullseye

**Browser version:**
Firefox 88.0.1

**Comment by Rita-Bubnova** [comment] 2021-05-19 12:48
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/878.

**Closed** 2021-05-25 07:46 UTC
Labels: duplicate
