### ISSUE TITLE
Spell check thinks an apostrophe showing omission is incorrect. It isn't.

### ISSUE THREAD

**Issue by jdaviescoates** [ONLYOFFICE/DocumentServer#1017] opened 2020-10-07 12:57 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Spellcheck thinks an apostrophe showing omission is incorrect. It isn't.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

If I write couldn't, we've, isn't or any other example of an apostrophe showing omission the spell check thinks it is incorrect spelling.

**What is the expected behavior?**

I expect the spell check not to get such words wrong.

**Did this work in previous versions of DocumentServer?**

I don't know.

**DocumentServer version:**

I'm using OnlyOffice (ONLYOFFICE Document Server 5.6.5) connected to my Nextcloud (19.0.3), both running on Cloudron (5.6.1)

**Operating System:**

Ubuntu 18.04

**Browser version:**

Firefox 81.0 (64bit)

**Comment by Rita-Bubnova** [comment] 2020-10-07 14:39
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/576.

**Closed** 2020-10-07 14:43 UTC
