### ISSUE TITLE
date in ISO format

### ISSUE THREAD

**Issue by mcanepa** [ONLYOFFICE/DocumentServer#1100] opened 2020-12-07 19:55 UTC
In spreadsheets, is it possible to format a date to ISO?

Right now I have a xlsx file with a date like 23/10/1964 (dd/mm/yyyy) but I couln't find a way to change it to 1964-10-23 (yyyy-mm-dd).

I see a lot of possible formats for date or custom, but none of them is ISO

**Comment by ShockwaveNN** [comment] 2020-12-15 12:29
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by HectorB-2020** [comment] 2021-01-14 12:36
Let me add more details from my recent report #https://github.com/ONLYOFFICE/DesktopEditors/issues/542#issue-778068932

**What is the current behavior?**
Date format YYYY-MM-DD is treated as an ordinary text which causes undesired behavior with auto-filling.
![](https://user-images.githubusercontent.com/64358003/103535860-8bad7000-4ea2-11eb-8d4a-23522fefaa35.png)

Unfortunately the context menu "Number Format", "More formats" doesn't contain the required date format either:
![](https://user-images.githubusercontent.com/64358003/103536298-4dfd1700-4ea3-11eb-8601-35254cc9714e.png)

**What is the expected behavior?**
The expected behavior is to recognize date format YYYY-MM-DD.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
Windows 10 20H2
Only Office 6.1.0.90

**Comment by Rita-Bubnova** [comment] 2021-01-19 12:11
This issue fixed (https://github.com/ONLYOFFICE/sdkjs/commit/57fff58febb4799fcde783d5b624d31867e72b55).
This fix is only on develop, so it's will be not in version 6.2 but in next version.

**Comment by ShockwaveNN** [comment] 2021-05-24 12:54
DocumentServer v6.3.0 is released. This problem should be fixed

**Closed by ShockwaveNN** 2021-05-24 12:54 UTC
Labels: enhancement, fixed

**Comment by ZachreyNM** [comment] 2024-03-20 21:12
I have similar issue as of 3/20/2024. I just downloaded a csv file from my bank and in the comma delimited ascii csv file, I see this:

"Account Name","Processed Date","Description","Check Number","Credit or Debit","Amount"
"checking",2023-12-29,"desc esth rt srtnsgf1",,"Debit",9.99
"checking",2023-12-26,"desc esth rt srtnsgf2",,"Credit",1.99
"checking",2023-12-21,"desc esth rt srtnsgf3",,"Credit",1.99

When I open it in OnlyOffice I get this:

Account Name	Processed Date	Description	Check Number	Credit or Debit	Amount
checking	26.03.7369	desc esth rt srtnsgf1		Debit	9.99
checking	30.05.7368	desc esth rt srtnsgf2		Credit	1.99
checking	16.01.7367	desc esth rt srtnsgf3		Debit	1.99

Any suggestions on how to correct this problem?

THANKS!!

**Comment by Rita-Bubnova** [comment] 2024-03-21 13:03
@ZachreyNM, Could you create a new issue?
