### ISSUE TITLE
How can I set one or two cells edit disabled?

### ISSUE THREAD

**Issue by eraizi** [ONLYOFFICE/DocumentServer#595] opened 2019-06-26 02:40 UTC
How can I set one or two cells edit disabled?

**Comment by ShockwaveNN** [comment] 2019-06-26 07:14
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/488 or explain your issue in more details

**Comment by ShockwaveNN** [comment] 2019-07-23 16:44
This issue was closed due to no response.

**Closed by ShockwaveNN** 2019-07-23 16:44 UTC
Labels: waiting feedback
