### ISSUE TITLE
ReferenceError: dd is not defined

### ISSUE THREAD

**Issue by cord44** [ONLYOFFICE/DocumentServer#2748] opened 2024-05-30 18:31 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.2

### Expected Behavior

Completely load the document to edit, yesterday when I tested this it worked.

### Actual Behavior

I have opened the onlyoffice editor from my app and I have had the next problem:
```
sdk-all.js:9 Uncaught 
ReferenceError: dd is not defined
    at sdk-all.js:9:63
    at sdk-all.js:13852:84
sdk-all-min.js:1032 Uncaught 
TypeError: Cannot read properties of undefined (reading 'ia')
    at b.ia (sdk-all-min.js:1032:466)
    at b.Me (sdk-all-min.js:1032:343)
    at e.bBd (sdk-all-min.js:1211:455)
    at h.bBd (sdk-all-min.js:1551:451)
    at HTMLScriptElement.<anonymous> (sdk-all-min.js:1156:441)
sdk-all-min.js:1396 Uncaught 
TypeError: Cannot read properties of null (reading 'Ub')
    at h.cod (sdk-all-min.js:1396:356)
    at h.n (sdk-all-min.js:1361:390)
    at h.Krd (sdk-all-min.js:1398:400)
    at h.Uob (sdk-all-min.js:1520:163)
    at e.u7c (sdk-all-min.js:1211:146)
    at sdk-all-min.js:1175:314
    at nb (sdk-all-min.js:715:343)
    at sdk-all-min.js:716:83
    at K.hb.onreadystatechange (sdk-all-min.js:510:140)
sdk-all-min.js:1542 Uncaught (in promise) 
TypeError: Cannot read properties of null (reading 'Ub')
    at h.xRc (sdk-all-min.js:1542:224)
    at h.Lcd (sdk-all-min.js:1405:124)
    at qm.Tob (sdk-all-min.js:1192:26)
    at e.Eih (sdk-all-min.js:208:30)
    at Dm.Tob (sdk-all-min.js:200:418)
    at f.pYe (sdk-all-min.js:223:429)
    at f.cYe (sdk-all-min.js:227:185)
    at f.rVg (sdk-all-min.js:231:64)
    at f.FVg (sdk-all-min.js:238:462)
    at i.<anonymous> (sdk-all-min.js:238:328)
```
I had could to see it in the browser console. This only happen for excel and word files, when I try to open an power point file this works fine.

Then, I reinstalled all the server from scrash in docker and I tried to open the word example file and happened the same error.

![Captura de pantalla 2024-05-30 a la(s) 12 29 19 p m](https://github.com/ONLYOFFICE/DocumentServer/assets/171281024/a6a4aef6-9565-431f-bca7-84d402576e6b)

### Reproduction Steps

- sudo docker run -i -t -d -p 80:80 --name only_office --restart=always -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver-de
-  sudo docker exec d05ab411a8b9 sudo supervisorctl start ds:example

**Comment by stepjacky** [comment] 2024-06-03 07:07
i  think  you  can try to  updating onlyoffice  to  the lasted  version  to  avoiding  this  issue

**Comment by cord44** [comment] 2024-06-03 16:03
> i think you can try to updating onlyoffice to the lasted version to avoiding this issue

Thank you for your support, but I am actually working with the lastest versión of `onlyoffice/documentserver`
<img width="467" alt="Captura de pantalla 2024-06-03 a la(s) 10 00 30 a m" src="https://github.com/ONLYOFFICE/DocumentServer/assets/171281024/e0c5c066-c789-4db2-a275-af4e849dc5b6">

**Comment by brainframe-me** [comment] 2024-06-03 21:01
I have exactly the same @cord44 but then with actual latest version 8.0.1, 3 days ago all worked, and now this breaks with the same error
Could it by chance be you were also recently on the commercial edition documentserver-de using the same domain name just before?

**Comment by cord44** [comment] 2024-06-03 21:58
Yes, you are correct @brainframe-me , I started to use the `onlyoffice/documentserver` with `-de`, then this expire and I changed to `documentserver` without `-de`, this worked for some days and then this just return the error when I open the editor.

**Comment by zou123456** [comment] 2024-09-14 09:56
Do you have a solution to this problem?

**Comment by avdddd1111** [comment] 2024-09-17 08:08
Hello @cord44 , @brainframe-me !

Sorry for late reply!


Please update the document server to the latest version. And check if the issue persists.

Since we only support the current latest version, and your issue may already be fixed in it.

I was unable to reproduce the issue, so I need a more detailed description of the scenario.

If the issue persists, please provide a detailed scenario for reproducing the problem.

**Comment by Rita-Bubnova** [comment] 2024-10-17 09:12
This issue was closed due no response.

**Closed by Rita-Bubnova** 2024-10-17 09:12 UTC
Labels: waiting feedback
