### ISSUE TITLE
copy/paste pictures not working (Document Editor)

### ISSUE THREAD

**Issue by R2DPIO** [ONLYOFFICE/DocumentServer#532] opened 2019-03-26 12:32 UTC
if i try to copy a picture from one document to another document, it does not work.
(Nextcloud 15.0.5, onlyoffice/documentserver latest docker image)

![image](https://user-images.githubusercontent.com/43437349/54996778-7f586b80-4fca-11e9-82d3-794715acbf40.png)

ctrl-v

![image](https://user-images.githubusercontent.com/43437349/54996898-c8102480-4fca-11e9-9f9b-26230d4e1bb7.png)

![image](https://user-images.githubusercontent.com/43437349/54996910-ce9e9c00-4fca-11e9-9856-4e4204442ceb.png)

thx

**Comment by flaminestone** [comment] 2019-04-02 14:25
@R2DPIO,this case reproducing on all documents? Can you attach one of it, and show document server version, please.

**Comment by ShockwaveNN** [comment] 2019-05-14 13:06
This issue was closed due to no response.

**Comment by R2DPIO** [comment] 2019-05-15 09:26
sorry for the late reply,

document server version is 5.2.8 CE
nextcloud now is version 16.0.0
chrome version 74.0.3729.131

the problem is still there - on all documents...

Thanks!

![rec](https://user-images.githubusercontent.com/43437349/57764430-b8c47200-7703-11e9-8ef1-1c1d9622c24b.gif)

[Dokument1.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3181447/Dokument1.docx)
[Dokument2.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3181448/Dokument2.docx)

**Comment by flaminestone** [comment] 2019-05-15 09:38
@R2DPIO, Dokument1.docx and Dokument2.docx is empty. Can you attach file with image?

**Comment by R2DPIO** [comment] 2019-05-15 10:00
[Dokument1.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3182031/Dokument1.docx)
[Dokument2.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3182032/Dokument2.docx)

sorry...

**Comment by flaminestone** [comment] 2019-07-03 12:22
I'm sorry to have kept you waiting. I can't reproduce this issue. Are you still having this problem? Do you have any errors in console?

**Comment by ShockwaveNN** [comment] 2019-08-23 10:47
This issue was closed due to no response.

**Comment by ShockwaveNN** [comment] 2022-05-23 14:04
@Noofayroz I think it's better to create a new issue with detailed step-by-step instruction and environment details, rather than using this 2019 issue

**Comment by Noofayroz** [comment] 2022-05-23 14:05
> @Noofayroz I think it's better to create a new issue with detailed step-by-step instruction and environment details, rather than using this 2019 issue
i have did
https://github.com/ONLYOFFICE/DesktopEditors/issues/928

**Comment by markNZed** [comment] 2022-07-29 17:10
I wonder if this is only happening in teh Firefox browser.  I saw this behavior (could not copy/paste between windows with the same document) but it worked in Chrome. It might have even copied the image but just not dispalyed it in Firefoc correctly (I saw the white rectangle with red diagonals)

**Comment by stepsequencer** [comment] 2022-08-08 14:50
> 
Same issue here :'/ 

I have tested with the latest Docker image but only with Nextcloud integration. However, none of my web browsers could handle this operation. 
Hopefully, you guys thought of the built in navigator which is handful in those cases. 

I've not tried on the server itself nor with the local application, but I'll try in the next few days

**Comment by cpot** [comment] 2023-08-25 14:26
problem still exist in 7.4.1.36 /  Firefox 116 / Win 10 PRO

**Comment by TatianaKirillova** [comment] 2023-08-30 13:25
@cpot I'm sorry, but I can't reproduce the problem. Do you have any Firefox extensions installed?

**Comment by cpot** [comment] 2023-08-30 14:26
@TatianaKirillova we reproduce the problem on different PC / browsers (in fact the problem exists also on Edge and Chrome)
Few extensions on Firefox, non on Egde or Chrome

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/3287514/203ae0f6-d0fc-4c01-993b-fdb43f39a3e7)

**Comment by TatianaKirillova** [comment] 2023-08-30 14:30
@cpot 
Thank you! Is the image format always PNG or can it be different?

**Comment by cpot** [comment] 2023-08-30 14:50
here it is a JPG. same problem with PNG. for your information if we do a copy paste from onlyoffice to "paint" then copy paste from "paint" to onlyoffice it is working

**Comment by TatianaKirillova** [comment] 2023-10-24 12:38
Hello, @cpot 
Thanks for the help!
I can confirm - this is know bug, issue #48506 with your issue

**Comment by Rita-Bubnova** [comment] 2023-10-24 12:47
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2143.

**Closed by Rita-Bubnova** 2023-10-24 12:47 UTC
