### ISSUE TITLE
cells merged filter only display first row  in sheet

### ISSUE THREAD

**Issue by web-wu** [ONLYOFFICE/DocumentServer#3050] opened 2024-12-09 01:38 UTC
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

latest

### Expected Behavior

![1](https://github.com/user-attachments/assets/a4147837-d1cd-4939-8641-a11565cff7dc)
![2](https://github.com/user-attachments/assets/46d1e2ae-5c43-457a-ac73-185c4d0c19b7)
![4](https://github.com/user-attachments/assets/267a9956-48a2-47d2-877f-8c6bec91ca28)

### Actual Behavior

![1](https://github.com/user-attachments/assets/d101b466-c416-4933-b630-f346294ee55a)
![2](https://github.com/user-attachments/assets/75b25a3b-f05a-496e-8c51-59e5185d3d1a)
![3](https://github.com/user-attachments/assets/cce8fcc2-0999-4b43-861a-6955e026cdac)

**Comment by Dmitry-Kov** [comment] 2024-12-09 12:47
Hello @web-wu! Thank you for the report.

This behavior is not a bug. When dealing with merged cells, the filter’s behavior follows certain logic inherited from Excel and LibreOffice. In a merged range, the data is actually stored only in the top-left cell. When you apply a filter, the rows underneath that merged cell are treated as empty, which results in only the first “complete” row being displayed once the option to show empty values is turned off.

This is a standard and expected behavior for office products compatible with the Microsoft format. Considering our goal of maintaining compatibility with the classic format, ONLYOFFICE’s current implementation aligns with what most users are accustomed to.

If you have any additional questions or suggestions, we would be happy to hear them. Thank you for your understanding!

**Comment by web-wu** [comment] 2024-12-10 00:53
@Dmitry-Kov What do I need to configure if I want to filter and merge cells to be fully displayed so that statistics are easy to work with? Or do you have any suggestions?

**Comment by Dmitry-Kov** [comment] 2024-12-10 12:39
@web-wu,
   Unfortunately, there is no direct setting to change this behavior. If your goal is to have all rows in a merged range remain visible under the filter, you might consider adjusting how your data is formatted:
   1. **Avoid merging cells where you need filtering:** Instead of merging cells, you could format the table so that each row contains the necessary value in the corresponding cell. This ensures the filter can properly recognize and display each row.
   2. **Copy values downward:** If you want the appearance of merged cells for visual clarity, consider filling the cells below the top cell with the same data (instead of leaving them empty). This way, when filtering, none of the rows under that block will be considered empty.
   3. **Alternative formatting methods:** Some users rely on formatting techniques like “Center Across Selection” as an alternative to merging. This visually centers text without actually merging cells, and may improve filter behavior.

At the moment, these workarounds are the best approach. I hope that one of these options will help you solve your problem.

**Comment by web-wu** [comment] 2024-12-11 11:56
@Dmitry-Kov When monitoring a sheet cell update, How to obtain the value before the update?
![image](https://github.com/user-attachments/assets/4af22754-9935-41e2-ab22-21860d77ed22)

**Comment by Dmitry-Kov** [comment] 2024-12-11 13:02
@web-wu,
This question is not related to the original one and does not match the topic of the request. If you have other issues, please create a separate request for each one. The answer to the initial request is provided at “https://github.com/ONLYOFFICE/DocumentServer/issues/3050#issuecomment-2527834857”. Since this behavior is not a bug, we are forced to close this request.

Have a great day!

**Closed** 2024-12-11 13:13 UTC
