### ISSUE TITLE
[Bug] `AscCommon.Gd` is undefined

### ISSUE THREAD

**Issue by acsfer** [ONLYOFFICE/DocumentServer#1634] opened 2022-02-11 09:54 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error message in logs

**DocumentServer version:**
7.0.0-132 Enterprise Edition

**Operating System:**
Ubuntu 20.04

```
[ERROR] nodeJS - changesError: docId = 2342245916 Error: TypeError: AscCommon.Gd is undefined Script: https://hostname.tld/onlyoffice/7.0.0-132/sdkjs/cell/sdk-all-min.js Line: 1202:374 userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0 platform: Win32 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: yd.prototype.G3d/this.nl.YRa@https://hostname.tld/onlyoffice/7.0.0-132/sdkjs/cell/sdk-all-min.js:1202:374
yd.prototype.M9f@https://hostname.tld/onlyoffice/7.0.0-132/sdkjs/cell/sdk-all-min.js:173:433
yd.prototype.pe/this.km.YRa@https://hostname.tld/onlyoffice/7.0.0-132/sdkjs/cell/sdk-all-min.js:166:299
de.prototype.lxc@https://hostname.tld/onlyoffice/7.0.0-132/sdkjs/cell/sdk-all-min.js:188:223
de.prototype.yTf@https://hostname.tld/onlyoffice/7.0.0-132/sdkjs/cell/sdk-all-min.js:201:65
de.prototype.A4d/xe.onmessage@https://hostname.tld/onlyoffice/7.0.0-132/sdkjs/cell/sdk-all-min.js:200:98
[5]</r.prototype.dispatchEvent@https://hostname.tld/onlyoffice/7.0.0-132/web-apps/vendor/sockjs/sockjs.min.js:2:2888
[14]</</r.prototype._transportMessage/<@https://hostname.tld/onlyoffice/7.0.0-132/web-apps/vendor/sockjs/sockjs.min.js:2:12860
[14]</</r.prototype._transportMessage@https://hostname.tld/onlyoffice/7.0.0-132/web-apps/vendor/sockjs/sockjs.min.js:2:12838
[3]</r.prototype.emit@https://hostname.tld/onlyoffice/7.0.0-132/web-apps/vendor/sockjs/sockjs.min.js:2:1762
r/this.ws.onmessage@https://hostname.tld/onlyoffice/7.0.0-132/web-apps/vendor/sockjs/sockjs.min.js:3:4924
```

**Comment by ShockwaveNN** [comment] 2022-02-11 09:58
Hi, this is almost definitely a problem, but I don't think we'll able to localize it just by error message (since it's minimized and have almost no useful info for us)

Maybe you could provide a scenario of when this happened?

**Comment by acsfer** [comment] 2022-02-11 10:02
Well, i don't really know, i'm the Sysadmin, not the end user (more than 1000... hard to know).
The most thing users report are files that can be opened with MSOffice, but not with OnlyOffice on Nextcloud (see https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/584)

But as this message appear very frequently, surrounded by these, I've reported it.
```
[2022-02-11T09:46:51.110] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 25 ; startIndex: 24 ; deleteCount: -1
[2022-02-11T09:46:57.089] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 27 ; startIndex: 26 ; deleteCount: -1
[2022-02-11T09:47:05.513] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 29 ; startIndex: 28 ; deleteCount: -1
[2022-02-11T09:51:27.482] [WARN] nodeJS - error description: docId = 3782498218 errorId = Update Version error
[2022-02-11T09:52:03.843] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 39 ; startIndex: 38 ; deleteCount: -1
[2022-02-11T09:53:09.261] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 43 ; startIndex: 42 ; deleteCount: -1
[2022-02-11T09:53:15.730] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 44 ; startIndex: 43 ; deleteCount: -1
[2022-02-11T09:53:20.918] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 46 ; startIndex: 45 ; deleteCount: -1
[2022-02-11T09:53:27.619] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 52 ; startIndex: 51 ; deleteCount: -1
[2022-02-11T09:53:32.642] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 54 ; startIndex: 53 ; deleteCount: -1
[2022-02-11T09:53:35.312] [ERROR] nodeJS - Error saveChanges docid: 3202186387 ; deleteIndex: 64 ; startIndex: 63 ; deleteCount: -1
[2022-02-11T09:57:11.890] [WARN] nodeJS - error description: docId = 3782498218 errorId = Update Version error
```
Nextcloud and OnlyOffice are on the same LAN, but different servers.

**Comment by ShockwaveNN** [comment] 2022-02-11 13:23
Our developers think they localize problem and fix it here:
https://github.com/ONLYOFFICE/sdkjs/commit/39b98256c61b70bbdfcf352c8812a681f17bdf9d

It's not 100% sure, since we were not able to reproduce you problem, only by analyzing logs

But we really hope that in v7.0.1 we release (probably this month) your problem will be fixed

**Comment by acsfer** [comment] 2022-02-12 20:07
Ok thanks; i'll report back once new version will be put in production.

**Comment by ShockwaveNN** [comment] 2022-02-22 15:02
DocumentServer v7.1 is released
This issue should be fixed

Feel free to comment or reopen it otherwise

**Closed by ShockwaveNN** 2022-02-22 15:02 UTC
Labels: bug, fixed
