### ISSUE TITLE
The font size decreases after printing certain symbols in the equation

### ISSUE THREAD

**Issue by visvaldas01** [ONLYOFFICE/DocumentServer#2183] opened 2023-02-28 19:30 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.3.0-1

### Expected Behavior

I was using an ABC with overbar formula and entered an "&" symbol here. I expected that the size of the symbols will remain.

### Actual Behavior

The symbols before an "&" (including it) became smaller.

![image](https://user-images.githubusercontent.com/60853667/221958930-948e6db2-c906-4565-ab96-0d6aa398e11a.png)

### Reproduction Steps

1. Insert -> Equation/Insert Equation -> Accents -> ABC with overbar.
2. Place cursor before C.
3. Press "&", "+", "-" or "=" (I assume there also are other symbols).

### Additional information

I'm on Manjaro 22.0.4 Sikaris with x86_64 Linux 5.15.94-1-MANJARO kernel, using the onlyoffice-desktopeditors from the community repository.

BTW, it doesn't happen if you copy/cut-paste the symbol into the formula from the outside text. But if you type something and press a symbol, then all the symbols up to the rightmost copied become smaller.
![image](https://user-images.githubusercontent.com/60853667/221962197-efef730a-ebf9-4c0a-b8ca-7d2df54041c5.png)
![image](https://user-images.githubusercontent.com/60853667/221962279-0ce2c3c2-c865-489d-b56a-2141b4f08922.png)

**Comment by TatianaKirillova** [comment] 2024-10-01 16:02
@visvaldas01 I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/sdkjs/pull/4691/commits/2c27c4d9827351d82511e7bd07de8b94d4255a44) and will be included in the next release. Don't miss updates. Have a nice day!

**Comment by Rita-Bubnova** [comment] 2024-10-21 07:50
DocumentServer v8.2.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-10-21 07:50 UTC
Labels: confirmed-bug, fixed-release
