### ISSUE TITLE
Chinese font name display problem when working with CommunityServer

### ISSUE THREAD

**Issue by fendaq** [ONLYOFFICE/DocumentServer#1460] opened 2021-10-06 16:05 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
select chinese font：
![image](https://user-images.githubusercontent.com/31738692/136241183-79ec5af0-a850-4f23-9ffe-2554c0844c0a.png)

but show the english name：
![image](https://user-images.githubusercontent.com/31738692/136241252-eef4d007-7aa6-4153-b749-14182ae34582.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1 open a document 
2 select a chinese font name
3 see the font name

**What is the expected behavior?**
show the selected  chinese font name

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
6.4.1
**Operating System:**
ubuntu 16.04
**Browser version:**
chrome 92.0.4515.159

**Comment by ShockwaveNN** [comment] 2021-10-06 16:26
@Rita-Bubnova please take a look

**Comment by fendaq** [comment] 2021-10-13 08:21
Uploading onlyoffice-compiling-server [正在运行] - Oracle VM VirtualBox 2021-10-13 16-08-49.mp4…

**Comment by fendaq** [comment] 2021-10-13 09:00
i use  official docker version ，not compile DocumentServer yourself

**Comment by Rita-Bubnova** [comment] 2021-10-13 10:22
Sorry, @fendaq. I can't reproduce your problem.

https://user-images.githubusercontent.com/25282241/137115027-8fd8361c-59d3-465a-834e-251485041878.mp4

**Comment by ShockwaveNN** [comment] 2021-10-14 07:30
@fendaq Sorry, I don't think that there is any configurations that can directly relate to this issue

Only idea I have - judging by URL I presume you've using integration with ONLYOFFICE CommunityServer

Could you try and check that if DocumentServer set up without any integration - with problem occurs on integrated test example (you can read how to run it at `http://docserver-url/welcome` page)

**Comment by ShockwaveNN** [comment] 2021-10-14 08:15
This is interesting, we'll try to reproduce it with integration with CommunityServer

Which user language are you using on CommunityServer side when creating new file?

**Comment by ShockwaveNN** [comment] 2022-07-04 07:19
This issue is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/19ce9924125c24f1d6dc6ed4a0fca0409677f2c2 and was released in v7.0.0 quite a time ago

**Closed by ShockwaveNN** 2022-07-04 07:19 UTC
Labels: bug
