### ISSUE TITLE
For the XLS file - Hyperlinks in cells are themselves deleted or are mixed up in places.

### ISSUE THREAD

**Issue by KarenArzumanyan** [ONLYOFFICE/DocumentServer#2678] opened 2024-03-27 08:43 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (SNAP)

### Version information

8.0.1.31

### Expected Behavior

Data:
- There is a column in which a text with a hyperlink is entered next to the next cell.
- The column has filtering enabled.
- **Opening and editing files is done only online through OnlineOffice in Nextcloud.**

Expected Behavior:
- Hyperlinks in cells are always in place and working.

### Actual Behavior

Actual Behavior
- From time to time there is a problem with links in the XLS document cell.

Problems:
- Two problems found (possibly related):
1) At some point in time, it happens that the text is in place but the links in them are mixed up. The links are swapped, but the text remains in place.
2) The link is completely removed, while the text remains visually consistent in style. It looks like there is a link, but in reality there is not.

### Reproduction Steps

So far we can’t understand the sequence or reason.
Problem occurs periodically.

### Additional information

Ubuntu 22.04.4 LTS + NextCloud 27.1.7 integratred OnlyOffice 8.0.1

> Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-101-generic x86_64)
> 
> sudo snap info nextcloud
> snap-id:      njObIbGQEaVx1H4nyWxchk1i8opy4h54
> tracking:     latest/stable
> latest/stable:    27.1.7snap1               2024-03-10 (40887) 321MB -
> 
> sudo snap info onlyoffice-ds
> snap-id:      zZWL0GK8BltYmYJcaTUQro9X2Rd6yVaN
> tracking:     latest/stable
> latest/stable:    8.0.1 2024-03-11 (210) 873MB -

**Comment by KarenArzumanyan** [comment] 2024-03-28 07:59
The problem file in its original form contains confidential information, so it has been slightly edited. 
But this is exactly the file with which there were problems.
[Портфель.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/14785860/default.xlsx)

**Comment by KarenArzumanyan** [comment] 2024-04-22 06:31
Hi Artem @rsnegirev 
I ask users periodically. 
They say that the problem has not yet recurred.
🤔

**Comment by rsnegirev** [comment] 2024-08-13 11:13
Since the described behavior could not be reproduced and users say that the problem has not yet recurred, we are closing the issue.

Feel free to reopen it if you have more questions.

**Closed** 2024-08-13 12:00 UTC
