### ISSUE TITLE
compile onlyoffice version 7.2.0 'hb.h' can not found 

### ISSUE THREAD

**Issue by stepjacky** [ONLYOFFICE/DocumentServer#1919] opened 2022-10-01 01:50 UTC
**Do you want to report a *bug*?**
this is a bug
**What is the current behavior?**
compile onlyoffice document docs  7.2.0 on windows server 2016 with visual studio 2019 and qt 6.2 ,an error message of  "'hb.h' can not be found" 
be throw by cl.exe 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
metioned above ,compile it just 
**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
in previous version 7.1.1 ,that is ok
**DocumentServer version:**
7.2.0
**Operating System:**
windows server 2016
**Browser version:**
chrom lasted

i search this error message on google , it mignt be a bug of visual studio 2019 on compile harfbuzz ,hope to fix it!

**Comment by ShockwaveNN** [comment] 2022-10-09 17:26
I'll mark this as a duplicate of https://github.com/ONLYOFFICE/build_tools/issues/105

Since as of now we still have no proper instruction how to compile windows version, so anything can happen

**Closed by ShockwaveNN** 2022-10-09 17:26 UTC
