### ISSUE TITLE
JSON Secret resets upon docker restart despite JWT_SECRET Env Variable

### ISSUE THREAD

**Issue by lbwtaylor** [ONLYOFFICE/DocumentServer#2087] opened 2023-02-03 02:26 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.3

### Expected Behavior

Using docker-compose, the following:

    environment:
      - JWT_SECRET=SECRETWORD

Should result in a persistent JWT_SECRET upon restarting docker application. 

### Actual Behavior

Using the following command:

sudo docker exec 24c87d9960af /var/www/onlyoffice/documentserver/npm/json -f /etc/onlyoffice/documentserver/local.json 'services.CoAuthoring.secret.session.string'

Shows that the secret changes upon each run of the application.

**Comment by oldunclez** [comment] 2023-06-09 07:08
I have a similar issue as your . 
In my case , I don't use JWT_SECRET Env Variable , 
but the secret string in /etc/onlyoffice/documentserver/local.json will be changed automatically whenever I restaring the docker container .

**Comment by igwyd** [comment] 2023-08-15 11:45
Hello @lbwtaylor, sorry for the late reply. I checked on the DocumentServer actual version 7.4.1 and JWT_SECRET Env Variable works correctly, my secret has not changed after ```docker restart <container>```. Please provide your server version, docker version, and docker-compose file.

Hello @oldunclez this is the expected behavior because the secret is automatically generated when the container is started/restarted. In your case, you should use docker env variable, for example ```-e JWT_SECRET=supersecret"``` so that the secret doesn't change.

**Comment by vzvl** [comment] 2024-06-14 12:48
I have the same problem. I pulled the git repository and changed the compose file, including uncommenting the JWT part and setting my own secret. Despite that, every time I restart the container a new secret is being generated.

**Comment by Rita-Bubnova** [comment] 2024-06-17 07:04
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-06-17 07:04 UTC
