### ISSUE TITLE
build error, add #include <cmath> to PdfWriter/OnlineOfficeBinToPdf.cpp

### ISSUE THREAD

**Issue by arturlangner** [ONLYOFFICE/DocumentServer#374] opened 2018-08-24 07:06 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug (build time)

**What is the current behavior?**
Build fails with 'sqrt' is not a member of 'std' in PdfWriter/OnlineOfficeBinToPdf.cpp

It is fixed by adding `#include <cmath>` to PdfWriter/OnlineOfficeBinToPdf.cpp Please add this to mainline.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
cd DocumentServer/core ; make

**What is the expected behavior?**
DocumentServer builds successfully

**Did this work in previous versions of DocumentServer?**
I don't know

**DocumentServer version:**
git 94548131a14c93e3aa00d991acf52535db3e5d71

**Operating System:**
Ubuntu 18.04.1 LTS, gcc 5.5.0

**Browser version:**
not applicable

**Comment by ShockwaveNN** [comment] 2018-08-24 07:51
@arturlangner Ok, I checking it, but could you recheck this problem with gcc-7? Cause this is default gcc on ubuntu 18.04 and AFAIU I can instlal gcc5 on Ubuntu 18.04 only via custom ppa

**Comment by arturlangner** [comment] 2018-08-24 07:55
I could not use gcc-7 because then I ran into this build bug with bundled v8 https://bugs.chromium.org/p/chromium/issues/detail?id=691681

**Comment by ShockwaveNN** [comment] 2018-08-24 08:00
@arturlangner Ok, I try to build with gcc-5

**Comment by ShockwaveNN** [comment] 2018-08-24 12:13
Just checked with Ubuntu 18.04.1
With
```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-12ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1) 
```

And core build fine from `release/v5.2.0` branch. Could you check it?
If it still be falling for you - can you make a Dockerfile with problem.

**Comment by arturlangner** [comment] 2018-08-24 12:27
Thanks, the core repo, not DocumentServer repo. If I follow https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx will I get everything from a stable branch or master?

**Comment by ShockwaveNN** [comment] 2018-08-24 12:29
@arturlangner yeah, I mean only core repo, since I didn't try any steps further, since I want to reproduce your problem.
You could just checkout `core`

**Comment by ShockwaveNN** [comment] 2018-08-24 14:18
@arturlangner you can take a look at Dockerfile I used to tes thttps://github.com/onlyoffice-testing-robot/documentserver-from-source-build/blob/feature/ubuntu-18.04/Ubuntu18.04/Dockerfile

**Comment by chrispydizzle** [comment] 2018-09-02 22:54
Hey guys. I just came across your project this weekend- great stuff! 

I have the same issue when building the DocumentServer from master, and can confirm that the same change <cmath> fixed my build as well. Sqrt being a part of std is something typically windows compilers tolerate, so it blows up on linux. This project actually wouldn't build under gcc-7 on ubuntu for me, gcc-6 worked just fine though.

I don't know what the process is here, sounds like I'm not the only one to find and fix it (I don't even write c++ much, heh)- do you guys want a pull req?

**Comment by ShockwaveNN** [comment] 2019-04-26 13:40
I think this issue fixed by https://github.com/ONLYOFFICE/core/commit/cb729d306b42afc31905f6863685a4c0fb1fb7eb

**Closed by ShockwaveNN** 2019-04-26 13:40 UTC
