### ISSUE TITLE
Calculating Working Hours

### ISSUE THREAD

**Issue by Caaruzo** [ONLYOFFICE/DocumentServer#1355] opened 2021-07-25 08:59 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Whenever i use a custom Cell format like [HH]:MM i cant calculate working hours. When it hits 24:00 instead its getting shown as 00:00. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add Cells with timeformat like 3 cells with 08:00. Add an 4th celll with custom format [HH]:MM and add up thoose other 3 with an formular. Its getting shown as 00:00 worked hours.

**What is the expected behavior?**
like in excel the custom formular [HH]:MM or [hh]:mm should allow to calculate with more that 24h and also be able to show negative hours.

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
v6.3.1.56 on Windows 10 - 21H1

**Comment by alinasafonova** [comment] 2021-12-30 13:31
This problem is fixed in https://github.com/ONLYOFFICE/sdkjs/commit/c2238dd0b9a78bbf255fb286c257e4e3add25e59

It will be released as v7.0.0

**Comment by cpot** [comment] 2021-12-31 09:49
> This problem is fixed in [ONLYOFFICE/sdkjs@c2238dd](https://github.com/ONLYOFFICE/sdkjs/commit/c2238dd0b9a78bbf255fb286c257e4e3add25e59)
> 
> It will be released as v7.0.0
@alinasafonova @Rita-Bubnova @ShockwaveNN  : Do you have a release date now for v7.0.0, we planed to include it in GoFAST v4 but cannot delay too much our release

Thank you and Happy New Year to Onlyoffice team !
Christopher

**Comment by ShockwaveNN** [comment] 2021-12-31 10:07
> > This problem is fixed in [ONLYOFFICE/sdkjs@c2238dd](https://github.com/ONLYOFFICE/sdkjs/commit/c2238dd0b9a78bbf255fb286c257e4e3add25e59)
> > 
> > It will be released as v7.0.0
> @alinasafonova @Rita-Bubnova @ShockwaveNN  : Do you have a release date now for v7.0.0, we planed to include it in GoFAST v4 but cannot delay too much our release
> 
> Thank you and Happy New Year to Onlyoffice team !
> Christopher 

Hi, it will be after 13 of January, really hope to release around this week, and 100% not earlier, since we got long holidays in our country

- I don't remember planning date, but i think it's 15 or 18 on January

**Comment by ShockwaveNN** [comment] 2021-12-31 10:35
@cpot Oops, sorry do not understand you message correctly from my phone )

Anyway thank you and happy new year ) And my statement about planned the release date is still correct )

**Comment by ShockwaveNN** [comment] 2022-01-18 12:26
DocumentServer and DesktopEditors v7.0.0 are released, so this issue should be resolved and I'm closing it

Feel free to comment or open a new issue if the problem is still actual

**Closed by ShockwaveNN** 2022-01-18 12:26 UTC
Labels: bug, fixed

**Comment by UnCanard14** [comment] 2024-04-24 12:43
I'd like to do time tracking so I'd like to sum up the time spent but if the sum exceeds 24:00 the sum returns to 00:00 how can I keep the duration above 24h?

This may not be the place, but I thought it had something to do with the basic question. 😅

Thank you for your answer.

**Comment by UnCanard14** [comment] 2024-04-24 13:30
It's work thank you very much @alinasafonova, is there a doc on this ? 
Now I'd like to multiply this duration by an hourly price but I've got a value that doesn't correspond (before I used the HOUR function but I've got an extra number at 24:00 now...).

**Comment by alinasafonova** [comment] 2024-04-24 13:52
To get hours in number format multiply sum by 24, then you can use it in further calculations
![Screenshot_20240424_164624](https://github.com/ONLYOFFICE/DocumentServer/assets/53475320/be2b3ce8-c6e4-4f74-b8b7-8121be6b054d)

**Comment by UnCanard14** [comment] 2024-04-24 14:08
Ohhhh thank you very much @alinasafonova !
