### ISSUE TITLE
When the mouse cursor is placed behind the same text, the mouse cursor is sometimes larger and sometimes smaller

### ISSUE THREAD

**Issue by YanaDH** [ONLYOFFICE/DocumentServer#2854] opened 2024-08-22 07:24 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

8.1.1.27

### Expected Behavior

When the mouse is behind the same text, the mouse remains the same size

### Actual Behavior

When the mouse cursor is placed behind the same text, the mouse cursor is sometimes larger and sometimes smaller
![17243114107214](https://github.com/user-attachments/assets/3e03aa21-1b0c-4ee4-a806-e84b0b6eb678)
![17243114002198](https://github.com/user-attachments/assets/f6461614-f832-496a-a18f-aceb53797b17)

**Comment by TatianaKirillova** [comment] 2024-08-24 11:27
Hello, @YanaDH! Thanks for your request!
In the ONLYOFFICE editor, this behavior is not a bug, this logic of cursor behavior is correct - the cursor size is inherited from the closest character to the stopping point where the click was made.

**Comment by Rita-Bubnova** [comment] 2024-08-28 08:50
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-08-28 08:50 UTC
