### ISSUE TITLE
VLOOKUP function in Spreadsheet Editor doesn't work properly

### ISSUE THREAD

**Issue by pjivers** [ONLYOFFICE/DocumentServer#1544] opened 2021-12-11 05:10 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Sometimes the value returned from VLOOKUP is from the incorrect row.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. In a new sheet, fill in the following data in cells A1:B9:

|A|B|
|---|---|
|Daily|365|
|Weekly|52|
|Fortnightly|26|
|Monthly|12|
|Quarterly|4|
|Bi-annually|2|
|Yearly|1|
|Biennially|0.5|
|Triennially|0.333|

2. In another cell, enter the following formula: `=VLOOKUP("Weekly", A1:B9, 2)`

**What is the expected behavior?**

The value returned _should_ be `52`, but it returns `2`. Similar behaviour is seen when substituting "Weekly" with "Fortnightly" (returns `365` instead of `26`) and "Monthly" (returns `365` instead of `12`), but all other values seem to be correct. I've also checked this VLOOKUP formula in Apple Numbers and it works as expected there.

**Did this work in previous versions of DocumentServer?**

Unknown.

**DocumentServer version:**

Unknown. I'm using the Spreadsheet Editor as part of the CryptPad suite (https://cryptpad.fr)

**Operating System:**

macOS Monterey 12.0.1 (21A559)

**Browser version:**

Firefox Browser for macOS (version 95.0, 64-bit)

**Screenshots:**

Not working correctly ❌

<img width="302" alt="weekly-not-working" src="https://user-images.githubusercontent.com/1411509/145664876-9323aea1-9442-49d6-acd4-eb2a9e5e9134.png">

Working correctly ✅

<img width="320" alt="biennially-working" src="https://user-images.githubusercontent.com/1411509/145664882-d1fc00e8-28b8-44c6-8d76-47763a68e725.png">

**Comment by ShockwaveNN** [comment] 2021-12-11 12:47
> Unknown. I'm using the Spreadsheet Editor as part of the CryptPad suite (https://cryptpad.fr)

Judging by looking out for code of this solution (never heard of this before) - it's not our official version but seems it was built from source code, so there may be any kind of modifications above our source code. Maybe introduced this bug, maybe not

To continue your issue could you try to reproduce your problem on our official version, you can try DesktopEdtiors for example, latest version is v6.4.2

**Comment by pjivers** [comment] 2021-12-11 13:26
@ShockwaveNN , no problem. I'll give the DesktopEditors example a try. In the meantime, I have been looking through the source and found the following comment (I'm not sure if it's related):

> Perform a binary search that relies on lookup_array being sorted in ascending order. If not sorted, invalid results will be returned.

https://github.com/ONLYOFFICE/sdkjs/blob/master/cell/model/FormulaObjects/lookupandreferenceFunctions.js#L2178

So I decided to try sorting the data in ascending order by column A and guess what... it worked. It seems there's a problem with how the lookup search is being performed.

**Comment by ShockwaveNN** [comment] 2021-12-11 13:39
> It seems there's a problem with how the lookup search is being performed.

Sorry, I'm not very good at digging in our codebase, but if you'll able reproduce your error in DesktopEdtitors - we'll definitely take a look at that

**Comment by pdehaye** [comment] 2021-12-15 22:33
I landed here because I am also having extensive problems with VLOOKUP, originally on Infomaniak's hosted version of OnlyOffice. The conversation above was helpful in part, but I was able to reproduce a bug  (there might be multiple) **also on DesktopEditors**. It has to do with capitalization and alphabetical ordering being required for VLOOKUP. 
See image and attachment. 
![image](https://user-images.githubusercontent.com/3274335/146275080-838879b2-7fe8-4681-ba6d-11f6f37c59fa.png)
[test_vlookup.ods](https://github.com/ONLYOFFICE/DocumentServer/files/7723134/test_vlookup.ods)

**Comment by ShockwaveNN** [comment] 2021-12-16 08:44
@pdehaye Hi, we make a liittle research on your issue and seems that your issue is not directly related to OP's one

But we can confirm that there is some problem with our implementation of VLOOKUP with your example
Could you please create a new issue, so we can correctly handle it, without messing two directly unrelated issues

**Comment by ShockwaveNN** [comment] 2022-01-17 09:05
This issue was closed due to no response.

I'll gladly reopen it it issue reproducible in our official builds

**Comment by Mysterycz** [comment] 2022-02-07 11:49
Hello, we are using official last release of onlyoffice/documentserver via docker and I can reproduce this issue.
It only works when you sort alphabetically you data.
![lookup](https://user-images.githubusercontent.com/20899532/152782637-ed536746-c5ae-4383-b150-4e1730dc72aa.PNG)

VYHLEDAT = LOOKUP in CZ version.
Can you check it out? Same bug is in VLOOKUP function and similar search/lookup functions.

**Comment by ShockwaveNN** [comment] 2022-02-07 11:51
@Mysterycz Could you create a new issue, I think it's will be easier to handle, because I'm not 100% sure it's the same issue as original topic

Also please attach file with example

**Comment by Mysterycz** [comment] 2022-02-07 11:56
Example file created in onlyOffice:
[onlyoffice bug.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/8014983/onlyoffice.bug.xlsx)
It is same behaviour and same bug as pjivers posted.

**Comment by ShockwaveNN** [comment] 2022-02-07 11:57
Ok

@alinasafonova Please take a look

**Comment by Mysterycz** [comment] 2022-02-07 12:00
But maybe it is not a bug at all, because excel from Microsoft works the same way? 
You have to sort your data first to do a binary search?

**Comment by alinasafonova** [comment] 2022-02-07 12:49
Hello, @Mysterycz
 
 This is not a bug. In your example file formulas are really calculated incorrectly for unsorted data, but for correct calculation it is necessary to sort data, due to specifics of VLOOKUP function. 
 In MS Excel formulas in your file are also calculated incorrectly.

**Comment by ShockwaveNN** [comment] 2022-08-15 08:11
This issue was closed due to no response.

Since this issue is a combination of several similar problems for several products - if you want to comment on it - I think it's better to create new one

**Closed by ShockwaveNN** 2022-08-15 08:11 UTC
