### ISSUE TITLE
Add Support for Text Direction to Enable Proper RTL Language Formatting

### ISSUE THREAD

**Issue by mahdishalchian** [ONLYOFFICE/DocumentServer#3065] opened 2024-12-23 06:09 UTC
### This issue is unique.

- [ ] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

In our text tools, there are two distinct features:
**Text Align** and **Text Direction.**

### Text Align
This feature specifies the placement of text within a textbox or page, with the following options:
    • Left
    • Right
    • Center
It also includes a justified option, which aligns the text to span the entire width of the box or page.

![image](https://github.com/user-attachments/assets/6820e43c-5c74-42ab-907e-6873c373c0dd)
(Example image of how text align works. The text align tool is shown with a red stroke and one of the tools is applied to each paragraph. Blue: Left align text. Red: Center text. Green: Right align text. And then with the justify property)

### Text Direction
This is an entirely different feature, primarily related to the text's language. Some languages are written from right to left (RTL), such as Arabic, Persian, and Hebrew.

![image](https://github.com/user-attachments/assets/a240bbec-e92b-4ecf-87e5-a97f13d970b3)
(Example image of how text direction works. It looks very similar to text align but has key differences. While text direction can be set to any direction, text align is also available and active.)

The Text Direction feature ensures proper rendering and formatting for right-to-left languages. Without this feature, users of RTL languages encounter significant issues, making the tool practically unusable as the text is not displayed correctly.

### Common Problems:
**1. Punctuation Misplacement:**
        ◦ Punctuation marks like periods, question marks, and exclamation points often appear at the start of a sentence instead of at the end (unless the sentence continues, which mitigates the issue).

![image](https://github.com/user-attachments/assets/93280c9b-8101-4518-9fbc-eabaa2366269)
(Example image of punctuation misplacement. For example, in English, when the right text direction option is enabled, the punctuation mark at the end of the sentence is moved to the beginning of the sentence. However, in Persian writing, there is no problem because the right text direction is enabled.)

**2. Mixed Language Issues:**
        ◦ When writing in an RTL language and inserting words from left-to-right (LTR) languages (e.g., English) or numbers (which are LTR), the text alignment breaks completely, and the order becomes distorted.

![image](https://github.com/user-attachments/assets/c14309ae-f3ad-4d14-ac8e-f3dbfeab4f86)
(Example image of mixed language issues. In the first line in blue, the text is Left text direction and as it is clear, the Persian word in the middle of the sentence has not caused the sentence to be distorted. In the second line in red, the text direction is from the right and the sentence structure is distorted. The green lines indicate the flow of the sentence. In the third line, the text direction is in the right mode and the Persian sentence is displayed correctly. The fourth line is what we see by default in right-to-left languages ​​in **ONLYOFFICE**.)

### Why Text Direction Is Essential
Text Direction is a critical feature for supporting RTL languages. It is included in almost all modern text and graphic tools. The absence of this feature renders any writing tool unsuitable for RTL languages, as users cannot achieve correct formatting or readability.

I hope these explanations are clear. Thank you.

**Comment by ElenaMaaya** [comment] 2024-12-25 10:21
Hi @mahdishalchian! 
Thanks for reaching out and providing detailed feedback about the issues you've encountered with ONLYOFFICE. 
We're aware of these issues and are actively working on solutions.  Your input is valuable to us and helps us improve the product.
Duplicate of #3002.

**Closed** 2024-12-25 10:31 UTC
