### ISSUE TITLE
RTL (Right to Left) Support - Re-request.

### ISSUE THREAD

**Issue by ItzYeho** [ONLYOFFICE/DocumentServer#1620] opened 2022-02-03 09:53 UTC
**Do you want to request a *feature* or report a *bug*?** A feature.

**What is the current behavior?** RTL is viewed as LTR.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** It's not really a bug, it's just not implemented.

**What is the expected behavior?** RTL languages should be viewed from right, to left. And not left, to right.

**Did this work in previous versions of DocumentServer?** Nope.

**DocumentServer version:** 7.0

**Operating System:** Arch Linux

**Browser version:** N/A

**Comment by ShockwaveNN** [comment] 2022-02-03 11:33
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Closed by ShockwaveNN** 2022-02-03 11:33 UTC
Labels: duplicate

**Comment by ItzYeho** [comment] 2022-02-03 12:01
I know it's a duplicate. It's to bring more awareness to the issue. https://github.com/ONLYOFFICE/DocumentServer/issues/19#issuecomment-276645715

ONLYOFFICE team members said it would come "soon". How soon is **5 years?**

**Comment by ShockwaveNN** [comment] 2022-02-03 12:04
Sorry, but we are completely aware of this issue, and I see no point to making a mess from our issue tracker

It will be done as soon at it's ready, and it's not ready now
