### ISSUE TITLE
Equation editor crashes in Presentations

### ISSUE THREAD

**Issue by asbl** [ONLYOFFICE/DocumentServer#1960] opened 2022-10-21 17:33 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

7.2.204

### Expected Behavior

When editing a formula in Onlyoffice-Presentations (in onlyoffice-word everything works fine) under manjaro linux, auto-Format should convert a formula, e.g. 1/2 becomes the corresponding fraction.

### Actual Behavior

Onlyoffice crashes when auto-format should be applied and the user is promted to save its files. The current slide can't be edited anymore and onlyoffice must be restarted.

### Reproduction Steps

1. Start onlyoffice presentations
2. Add an equation
3. Insert e.g. 1/2 SPACE (or another formula, where auto-format is triggered)

### Additional information

I'm using Manjaro 21.3.7.

**Comment by avachon100510** [comment] 2023-01-05 22:51
Issue still persists as of 7.2.2... When I try to apply exponent via shortcut, the document and equation editor crashes

**Comment by Rita-Bubnova** [comment] 2023-01-06 06:45
@avachon100510, I checked [original problem](https://github.com/ONLYOFFICE/DocumentServer/issues/1960#issue-1425377311) and it didn't reproduce in Document Server version 7.2.2.56.
Could you create a new issue for your problem and give more details (or video)?

**Comment by asbl** [comment] 2023-01-06 07:34
Still present on Onlyoffice Desktop(!), see video. The second time, the program crashes the moment I press Space - Unfortunately, I have been able to reproduce this over and over again and it makes working with formulas in OO-Desktop almost impossible.

[video](https://user-images.githubusercontent.com/32521553/210952406-5bb73405-a7a4-4466-9139-3ce5195097b6.webm)

**Comment by Rita-Bubnova** [comment] 2023-01-06 08:48
@asbl, the problem was fixed in Document Server version 7.2.2.56. 
The latest release version of Desktop Editors is 7.2.1.36 and the problem repeats in it. So. this will be fixed in the next version of the Desktop Editors.

**Comment by avachon100510** [comment] 2023-01-06 13:20
> @avachon100510, I checked [original problem](https://github.com/ONLYOFFICE/DocumentServer/issues/1960#issue-1425377311) and it didn't reproduce in Document Server version 7.2.2.56. Could you create a new issue for your problem and give more details (or video)?

I see, I'm not using the same version as yours! It's version 7.2.1.36

**Comment by avachon100510** [comment] 2023-01-06 13:23
I think we need to have automatic updates

**Comment by avachon100510** [comment] 2023-01-06 14:35
I can't install version 7.2.2 on Windows... what's going on?

**Comment by avachon100510** [comment] 2023-01-06 14:41
> @asbl, the problem was fixed in Document Server version 7.2.2.56. The latest release version of Desktop Editors is 7.2.1.36 and the problem repeats in it. So. this will be fixed in the next version of the Desktop Editors.

Um, why can't I install this version on Windows? Is it because it's not available yet?
And when did this bug first appear?

**Comment by Rita-Bubnova** [comment] 2023-01-08 06:36
Sorry, I don't know when this problem appeared.
We have not released desktop version 7.2.2 and I have no information about it.

**Comment by ikulagin** [comment] 2023-02-01 21:18
@Rita-Bubnova 
The last release of Desktop Editor (7.3.0) fixed this issue.
Thank you very much!

**Closed** 2023-02-02 07:54 UTC
Labels: bug, fixed

**Comment by DenisDeeSign** [comment] 2023-02-02 07:56
Glad to hear it! Feel free to comment or reopen it if you got further questions.
