### ISSUE TITLE
Essential Needs! RTL Language Feature 

### ISSUE THREAD

**Issue by vCentre** [ONLYOFFICE/DocumentServer#85] opened 2017-03-08 16:15 UTC
Despite the fact that, DocumentServer is the most reliable productivity web-editor among other solutions, still having the most critical lack of RTL languages support for unforeseen reasons!

Screening placed issues and forum posts, RTL feature is in question since 2014! and yet keep promising that, it is going to be introduced in coming releases.

This is to emphasize the importance of RTL feature for wide-range of users and humbly request our loved developers of OnlyOffice to consider it ASAP.
You have done already great job! Please complete it!

**Comment by ShockwaveNN** [comment] 2017-03-09 07:20
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

**Closed by ShockwaveNN** 2017-03-09 07:20 UTC
