### ISSUE TITLE
In spreadsheet paste values only on filtered cells 

### ISSUE THREAD

**Issue by jpberdejo** [ONLYOFFICE/DocumentServer#1754] opened 2022-02-23 15:49 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When a filter is applied to a spreadsheet, copying and pasting a value replaces all cells hidden by the filter and only the displayed cells should be replaced.

**Comment by ShockwaveNN** [comment] 2022-05-20 14:47
v7.1 has been released and this problem should be fixed

**Closed by ShockwaveNN** 2022-05-20 14:47 UTC
Labels: bug, fixed

**Comment by VladimirProkofiev52** [comment] 2025-03-07 13:54
Hello! @corareg 
I see that the issue described above has been marked as fixed. 
If you're encountering a similar problem, please create a separate Issue with a detailed description, including the version of your editor, and we'll do our best to assist you. 
If applicable, attach the file (if the issue is specific to it) or a screen recording demonstrating the problem.
