### ISSUE TITLE
Pivot table doesn't work.

### ISSUE THREAD

**Issue by rardcode** [ONLYOFFICE/DocumentServer#2939] opened 2024-10-24 12:06 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.2.0.1

### Expected Behavior

Pivot table enabled

### Actual Behavior

After upgrade to v.8.2.0.1, when I click in the cell that has the pivot table, it does not offer me the choices.

### Reproduction Steps

1. Open xlsx file.
2. Go to cell, example F31, or F32 or F33 etc..

### Additional information

I attache xlsx file and problem screen in Onlyoffice/Nextcloud page.

![image](https://github.com/user-attachments/assets/186716f2-e7ad-452a-af88-79435346c9e7)

[WEEKLY_OTTOBRE.xlsx](https://github.com/user-attachments/files/17506424/WEEKLY_OTTOBRE.xlsx)

**Comment by rsnegirev** [comment] 2024-10-25 10:22
Hi @rardcode 

Your issue is duplicate of this one:
https://github.com/ONLYOFFICE/DocumentServer/issues/2931

Problem was already fixed. Fixes will be released in the hotfix to 8.2.0 version soon.

Commit: 0df4e5ba2afec2beccaefd78d3e29c27528de7ff

**Closed** 2024-10-25 10:53 UTC
Labels: duplicate
