### ISSUE TITLE
DocumentServer installation require removal of mariadb in Ubuntu 18.04

### ISSUE THREAD

**Issue by jotoeri** [ONLYOFFICE/DocumentServer#1126] opened 2021-01-13 00:01 UTC
**Do you want to request a *feature* or report a *bug*?**
Depends on the point of view...?! ;)

**What is the current behavior?**
When installing via apt repository, postgresql and mysql are required for installation, whereby it does NOT check for mysql OR mariadb. Result: I had mariadb installed for my Nextcloud instance, but documentserver required mysql, which removed mariadb 😵 . (Indeed i should have looked a bit more into the details of that package-installation block)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install mariadb-server via apt, then install documentserver from onlyoffice-repo via apt.

**What is the expected behavior?**
Especially as all those database-servers seem to be pure Alternatives to the documentserver, the Package should ideally check if either ONE is installed, or (if really necessary to install postgres and mysql) at least check for mysql OR mariadb.

(Somehow related to #943 and/or #607)

**DocumentServer version:**
6.1.0
**Operating System:**
Ubuntu 18.04

**Comment by ShockwaveNN** [comment] 2021-01-13 07:06
Hi, could you provide Dockerfile to reproduce this issue?

**Comment by jotoeri** [comment] 2021-01-13 10:09
Hm, there is no Dockerfile, i'm using a pure Installation via aptitude according to this guide: https://helpcenter.onlyoffice.com/installation/docs-enterprise-install-ubuntu.aspx

---
Probably you could test it somehow like this with docker? But tbh, i'm no docker expert, just found this on the Internet without testing it....
`docker run -it ubuntu:18.04 bash`
Which should spin up an ubuntu container and show you its bash, if i understand that right, so you can within that Ubuntu container
`apt install mariadb-server`
`apt install onlyoffice-documentserver`

**Comment by ShockwaveNN** [comment] 2021-01-13 11:43
Currently I have not enought time to be able to correctly reproduce this problem and without it we cannot make any fixes

So If anyone wiling to help - I need a example Dockerfile in which install ONLYOFFICE DocumentServer will result removing of `mariadb`

**Comment by jotoeri** [comment] 2021-01-13 15:27
Hmpf. Took me quite a while now, whereas if one works more often with docker, that shouldn't be too much of a problem, no? 😞 

Last Command gets aborted as it does not have the `-y` switch. But one sees the essential, that the package-list lists mariadb as to remove.
![grafik](https://user-images.githubusercontent.com/47433654/104472082-e12cff80-55bb-11eb-83f0-0613438bef1d.png)



```
# Get the base image
FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

# Install some dependencies and mariadb
RUN \
apt update && \
apt install -y ca-certificates dialog apt-utils gnupg2 && \
apt install -y mariadb-server

#Install documentserver
RUN \
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5 && \
echo "deb https://download.onlyoffice.com/repo/debian squeeze main" | tee /etc/apt/sources.list.d/onlyoffice.list && \
apt update && \
apt install onlyoffice-documentserver
```

**Comment by ShockwaveNN** [comment] 2021-01-13 15:51
> whereas if one works more often with docker, that shouldn't be too much of a problem, no? disappointed

Sorry, if this looks mean, but I've tried before answering you, a little bit complicated example
```
FROM ubuntu:20.04

ENV TZ=Etc/UTC
ENV DS_PRODUCT=onlyoffice-documentserver
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y curl \ 
                                         gnupg \
                                         mariadb-server \
                                         sudo

RUN sudo apt-get update && sudo apt-get install -y redis-server
RUN sudo apt-get update && sudo apt-get install -y rabbitmq-server
RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
RUN sudo echo "deb http://download.onlyoffice.com/repo/debian squeeze main" | sudo tee /etc/apt/sources.list.d/onlyoffice.list
RUN echo ${DS_PRODUCT} onlyoffice/db-pwd select onlyoffice | sudo debconf-set-selections
RUN echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections
RUN sudo apt-get update && sudo apt-get -y install ${DS_PRODUCT}

```

But my variant seems not to remove mariadb, so I answered that way since I cannot reproduce your issue.

Your variant indeed remove, maybe base image is the different

**Comment by ShockwaveNN** [comment] 2021-01-14 07:43
> maybe base image is the different,

Indeed, changing first line in your variant to `FROM ubuntu:20.04` will not resulting of removal of `mariadb`. This is interesting, seems `postgresql` or `mariadb` in 20.04 somehow changed its requirements

But this enought for me to send info to our dev team, thank you
I've create a issue 48237 in our private issue tracker

**Comment by jotoeri** [comment] 2021-01-14 10:26
Interesting. Thank you! 😌

**Comment by ShockwaveNN** [comment] 2022-09-09 11:48
This issue is resolved at https://github.com/ONLYOFFICE/document-server-package/pull/302/files
`mariadb` will not be uninstalled while install DocumentServer on Ubuntu 18.04

It will be release in v7.2.0

**Comment by ShockwaveNN** [comment] 2022-09-23 16:14
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Closed by ShockwaveNN** 2022-09-23 16:14 UTC
Labels: bug, fixed
