### ISSUE TITLE
Allow disabling keyboard shortcuts overlay

### ISSUE THREAD

**Issue by Cuperino** [ONLYOFFICE/DocumentServer#1660] opened 2022-02-26 23:50 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Issue
When using ONLYOFFICE on Linux, I press `Ctrl+Alt+Arrow_Keys` to move between workspaces. The letting go of Alt in that key combination sometimes gets registered by ONLYOFFICE, triggering the display of an overlay showing the various shortcuts the user can use to navigate the program with their keyboard. Since I don't use this functionality, I would like to disable it.

### Proposed Solution 1
Add a checkbox to the `Advanced Settings` menu allowing enabling/disabling this functionality.

### Proposed Solution 2
Alternatively, there could be a dropdown on the `Advanced Settings` menu, allowing the user to disable or change the trigger key to a different key on non-Windows systems.

Thanks for the great software! Have a nice day!

**Comment by ShockwaveNN** [comment] 2022-02-28 14:11
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by spfmoby** [comment] 2024-05-09 15:05
Same problem on Mac OS if you use an alternative task switcher like AltTab. When you press the option (alt) + tab command, then release the alt key, it is registered by onlyoffice. When you come back in onlyoffice and continue typing, it doesn't work as the alt key is still active.

**Comment by kayzzen01** [comment] 2024-10-27 03:29
Hi,

The behavior in version 8.2 became bad, because now when disabling the Alt key shortcut, the shortcut keys are no longer displayed, but the cursor is moved to the Home menu, making it necessary to press the Alt key to be able to type or click the mouse in the area you want to continue editing.

**Comment by uc-ai2** [comment] 2024-10-30 08:22
Hello, @kayzzen01!
I can confirm - this is a bug, issue 71299 in our private issue tracker. Thank You for the report.

**Comment by Rita-Bubnova** [comment] 2024-11-14 07:22
DocumentServer v8.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-11-14 07:22 UTC
Labels: confirmed-bug, feature request, fixed-hotfix

**Comment by tukykarmakar** [comment] 2025-05-08 04:09
I know it's been closed for a while, but I feel the need to mention that this wouldn't have been an issue if the shortcut overlay appeared when Alt is held instead of pressed once. Sometimes it's easier to use the shortcuts but you might not remember it, so holding down Alt to see the overlay is how it's usually done in other standardised applications.

**Comment by uc-ai2** [comment] 2025-05-13 09:14
Hi, @tukykarmakar!
Yes, indeed, the behavior when holding down Alt differs between our app and other standard applications. I’ve submitted a feature request (74427) on this matter. Thank you for your contribution!

**Comment by uc-ai2** [comment] 2025-05-13 12:00
Hi, @tukykarmakar!
This request concerns a different issue and has been closed. Please create a new one referencing this. Thank you for your understanding.
(74427)

**Comment by m-GDEV** [comment] 2025-09-29 02:28
In case anyone doesn't know how to do it:
`File -> Advanced Settings (at bottom) -> Workspace -> Uncheck 'Use Alt key to navigate the user interface using the keyboard' -> Apply`
