### ISSUE TITLE
Text rendering fuzzy on Firefox on Ubuntu

### ISSUE THREAD

**Issue by baarkerlounger** [ONLYOFFICE/DocumentServer#757] opened 2020-01-23 19:28 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Text  Rendering on Firefox (72.0.1) for Linux (Ubuntu 19.10) is fuzzy on both spreadsheet and documents. Chrome on Linux renders the same fonts fine as does Firefox on Mac Os.

**What is the expected behavior?**
Rendering should match across browsers/operating systems

**DocumentServer version:**
5.4.2

**Operating System:**
Ubuntu 18.04 LTS x86 (DocumentServer). Ubuntu 19.10 (Client)

**Browser version:**
Firefox 72.0.1

**Comment by Rita-Bubnova** [comment] 2020-06-18 09:54
Hello, @baarkerlounger.
Sorry, we didn’t answer for a long time.
Blur seems to be related to your browser scale. What scale is set in your browser?

**Comment by baarkerlounger** [comment] 2020-06-19 08:52
@Rita-Bubnova by scale do you mean zoom? If so it's set to 100% but increasing or decreasing makes no difference the fonts stay fuzzier than on other platforms.

If you mean a different scale setting I'm not aware of changing any defaults but happy to check if you let me know what to look for.

**Comment by Rita-Bubnova** [comment] 2020-06-19 09:46
@baarkerlounger yes, I mean browser zoom.
Could you attach screenshots demonstrating the problem?

**Comment by baarkerlounger** [comment] 2020-06-19 11:13
@Rita-Bubnova sure:

Ubuntu:

![image](https://user-images.githubusercontent.com/5101747/85126858-32dbfa00-b226-11ea-8165-45c56868aa57.png)

Mac:

![image](https://user-images.githubusercontent.com/5101747/85126870-3a030800-b226-11ea-8004-c1ced93647d5.png)

**Comment by Rita-Bubnova** [comment] 2020-06-19 12:51
@baarkerlounger, I'm still not sure that you have 100% on screenshot (Ubuntu) , could you attach these screenshots with zoom setting visible?

![Issue 757](https://user-images.githubusercontent.com/25282241/85134093-9e34c480-b244-11ea-9721-4725efc0e687.png)

**Comment by baarkerlounger** [comment] 2020-06-19 12:57
@Rita-Bubnova sure:

![image](https://user-images.githubusercontent.com/5101747/85134635-bc92c400-b234-11ea-97e0-4c6a2a1de886.png)

Note you can also see the zoom level in the bottom right hand corner of the above screenshots but this is reproducable at all zoom levels.

**Comment by Rita-Bubnova** [comment] 2020-06-19 14:45
> Note you can also see the zoom level in the bottom right hand corner of the above screenshots but this is reproducable at all zoom levels.

Zoom in the bottom right corner is not a browser zoom.

Unfortunately, so far we cannot repeat your problem (used Ubuntu 18.04 Firefox 72.0.1 DocumentServer 5.5.3).
Can you upgrade DocumentServer and browser Firefox to the latest versions?
What is your display resolution and DPI?

**Comment by baarkerlounger** [comment] 2020-06-19 19:31
I've updated Firefox to the latest (77.0.1) and Document Server as well (5.5.3-39). Still reproducible. Display resolution is 1920 x 1080 and DPI:

```
$ xrdb -query | grep dpi
Xft.dpi:	120
```

**Comment by Rita-Bubnova** [comment] 2020-06-22 08:10
Could you change DPI to 96 and check the problem?

**Comment by baarkerlounger** [comment] 2020-06-23 12:52
So I currently have 
```
$ xrdb -query | grep dpi
Xft.dpi:	120

$ xdpyinfo | grep dots
  resolution:    96x96 dots per inch

$ xrandr
Screen 0: minimum 16 x 16, current 1920 x 1080, maximum 32767 x 32767
XWAYLAND0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     59.96*+
```

Not sure what I'd need to run to change this? @Rita-Bubnova

**Comment by Rita-Bubnova** [comment] 2020-06-23 13:24
@baarkerlounger, unfortunately, I do not know how to change this to Ubuntu.

We think your problem may be a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/765

**Comment by baarkerlounger** [comment] 2020-06-23 16:35
Is there a fix branch I could help test?

**Comment by baarkerlounger** [comment] 2020-06-23 19:02
So I realised in Gnome-Tweaks I had text-scaling set to 1.25 but setting this down to 1.00 did not resolve the issue. (Still only affects OnlyOffice and only in Firefox).

**Comment by Rita-Bubnova** [comment] 2020-06-25 07:16
@baarkerlounger, our team thinks this is duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/765.
If this problem will be reproduce after fixed https://github.com/ONLYOFFICE/DocumentServer/issues/765, then you can reopen this issue.

**Closed** 2020-06-25 07:19 UTC
