### ISSUE TITLE
SVG objects with encoding="windows-1252" are not included in printouts (paper and PDF)

### ISSUE THREAD

**Issue by Norbert80** [ONLYOFFICE/DocumentServer#2792] opened 2024-07-03 13:17 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

Version 8.1.0.169 (deb)

### Expected Behavior

Printouts (paper and PDF) should contain SVG objects.

### Actual Behavior

Printouts (paper and PDF) do not contain SVG objects.

### Reproduction Steps

- open a blank document
- insert a SVG picture
- print to PDF or paper

**Comment by Norbert80** [comment] 2024-07-07 20:30
It seems, that the printout struggles with encoding="windows-1252" in the prolog. Change it to encoding="UTF-8" and the import works.

In case it is somehow useful, I would like to point out that LibreOffice has a similar problem, but fails even when importing the SVG:
https://bugs.documentfoundation.org/show_bug.cgi?id=161938

**Comment by CrazyJET** [comment] 2024-10-09 03:41
Can this issue be fixed in the upcoming 8.2 version

**Comment by CrazyJET** [comment] 2024-10-10 00:52
> It seems, that the printout struggles with encoding="windows-1252" in the prolog. Change it to encoding="UTF-8" and the printout works.
> 
> In case it is somehow useful for fixing ONLYOFFICE, I would like to point out that LibreOffice has a similar problem, but already fails when importing the same SVG: https://bugs.documentfoundation.org/show_bug.cgi?id=161938

Are there any other solutions?

**Comment by TatianaKirillova** [comment] 2024-11-06 11:01
@Norbert80 I'm happy to report that the issue is fixed with [this commit](https://github.com/ONLYOFFICE/core/commit/b00fbeff53b557660af9f772c9999cbaa4efbf75) and will be included in the next release. Don't miss updates. Have a nice day!

**Comment by Rita-Bubnova** [comment] 2024-11-14 07:18
DocumentServer v8.2.1 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-11-14 07:18 UTC
Labels: confirmed-bug, fixed-hotfix
