### ISSUE TITLE
Persist CustomXML parts/tags in DOCX files

### ISSUE THREAD

**Issue by BadaievOleksii** [ONLYOFFICE/DocumentServer#792] opened 2020-03-01 18:27 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
OnlyOffice editor removes any custom xml parts from the DOCX archive, as well as `<w:dataBinding>` tags in `/w:sdt/w:sdtPr`. 
As far as I know, it is intended for OO, to remove any unsupported xml files / tags.

But such behaviour breaks the data-binding functionality - defined by [OpenDOPE conventions](https://www.opendope.org/opendope_conventions_v2.3.html) and [MS Word Content Controls bindings](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-binding-content-controls-to-custom-xml-parts?view=vs-2019).
In one of my projects, it was a use-case for us - to use [DOCX4J](https://www.docx4java.org/blog/2018/04/from-variablereplace-to-opendope-data-binding/) library on the backend for external data insertion, and OnlyOffice as the user-side editor. And we faced an issue, that any data-binded docx, opened in OO and then saved - becomes incompatible with any further data-binding (because of missing custom xml parts, and removed w:dataBinding tags).  

_Please, note that this feature request is not about the actual data binding, or changing the behaviour of ContentControls in OO. The information is provided simply as preface, for understanding of the initial purpose to these changes._

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug

**What is the expected behavior?**
OnlyOffice Document Editor should persist all custom-xml parts of the loaded DOCX, as well as keep custom xml tags in `document.xml`. Additional processing is not needed.
As an example - [Macroses ](https://api.onlyoffice.com/plugin/macros) plugin injects custom files, that **are included in docx file** at saving of DocumentEditor session.

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer version:**
Current stable version 

**Operating System:**
Any

**Browser version:**
Any

**Comment by flaminestone** [comment] 2020-03-02 12:28
Hello @BadaievOleksii. Can you attach the file with the tags, which are deleted after saving in the document editors?

**Comment by BadaievOleksii** [comment] 2020-03-04 14:46
Hi, @flaminestone 
Yes, sure:
[binding-simple.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4287872/binding-simple.docx)

And the same file, simply opened and saved as new file in OO:
[binding-simple-oo.docx](https://github.com/ONLYOFFICE/DocumentServer/files/4287871/binding-simple-oo.docx)

Unzipping both of them - it is clear that CustomXML parts are removed at all.

```
~/dev/docx                                                                                                                                                  
▶ unzip binding-simple.docx -d binding
Archive:  binding-simple.docx
  inflating: binding/[Content_Types].xml  
  inflating: binding/_rels/.rels     
  inflating: binding/word/_rels/document.xml.rels  
  inflating: binding/word/document.xml  
  inflating: binding/word/theme/theme1.xml  
  inflating: binding/word/glossary/document.xml  
  inflating: binding/word/settings.xml  
  inflating: binding/word/glossary/_rels/document.xml.rels  
  inflating: binding/word/glossary/settings.xml  
  inflating: binding/docProps/core.xml  
  inflating: binding/docProps/app.xml  
  inflating: binding/word/glossary/fontTable.xml  
  inflating: binding/customXml/itemProps1.xml  
  inflating: binding/customXml/_rels/item1.xml.rels  
  inflating: binding/customXml/item1.xml  
  inflating: binding/word/glossary/stylesWithEffects.xml  
  inflating: binding/word/styles.xml  
  inflating: binding/word/stylesWithEffects.xml  
  inflating: binding/word/webSettings.xml  
  inflating: binding/word/fontTable.xml  
  inflating: binding/word/glossary/styles.xml  
  inflating: binding/word/glossary/webSettings.xml  
````
```
~/dev/docx                                                                                                                                                  
▶ unzip binding-simple-oo.docx -d binding-oo
Archive:  binding-simple-oo.docx
  inflating: binding-oo/[Content_Types].xml  
  inflating: binding-oo/docProps/app.xml  
  inflating: binding-oo/docProps/core.xml  
  inflating: binding-oo/_rels/.rels  
  inflating: binding-oo/word/fontTable.xml  
  inflating: binding-oo/word/document.xml  
  inflating: binding-oo/word/settings.xml  
  inflating: binding-oo/word/webSettings.xml  
  inflating: binding-oo/word/styles.xml  
  inflating: binding-oo/word/theme/theme1.xml  
  inflating: binding-oo/word/_rels/document.xml.rels  

```

**Comment by teamoo** [comment] 2021-02-04 17:07
We are having exactly the same problem. Our files heavily depend on these parts and get useless once edited on the platform.

Given this example file:
[demo-2_ORIGINAL.docx](https://github.com/ONLYOFFICE/CommunityServer/files/5927306/demo-2_ORIGINAL.docx)

When inspecting the package, we can see that the document is using [customXML Parts](https://docs.microsoft.com/de-de/office/vba/api/office.customxmlpart):
![image](https://user-images.githubusercontent.com/171527/106928396-6ca93480-6713-11eb-9046-b476c06b9a2a.png)


When uploading that file to the CommunityServer and Downloading it again, we can see that the parts are still there. But as soon as we change anything in the document or choose "Download As.." they will get removed permanently (even if the Download As format is DOCX).

**Comment by ShockwaveNN** [comment] 2021-02-04 19:31
Thank you for your report, sorry for long waiting
I can confirm this is a bug and I've created a issue 48580 in our private issue tracker
But currently I cannot provide any time frame for resolving this issue, because this can pretty complex time and take a lot time

**Comment by ShockwaveNN** [comment] 2021-03-11 08:02
Hello, your issue is fixed by

https://github.com/ONLYOFFICE/core/commit/1a722a46cbb8109eeb749ee64a1993736eec953d
https://github.com/ONLYOFFICE/sdkjs/commit/ecbe369dfadf04a4a6b63de6383a9a46b7628987

This fixes will be included in version 6.3.0 of DocumentServer.
This version currently on early stage of testing, so my best quess it take month or two to release it, but I cannot guarantee it

**Comment by teamoo** [comment] 2021-03-13 17:08
Thanks for the feedback!

**Comment by ShockwaveNN** [comment] 2021-05-24 12:55
DocumentServer v6.3.0 is released. This problem should be fixed

**Closed by ShockwaveNN** 2021-05-24 12:55 UTC
Labels: bug, fixed

**Comment by teamoo** [comment] 2021-06-07 15:37
Yes, I can confirm that! Thanks.

**Comment by ShockwaveNN** [comment] 2021-06-07 15:40
@teamoo Glad to hear that, you're welcome
