### ISSUE TITLE
The content on the first page appears on the second page

### ISSUE THREAD

**Issue by huzedong2015** [ONLYOFFICE/DocumentServer#2550] opened 2024-01-17 08:12 UTC
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.5.1

### Expected Behavior

Everything is on the first page

### Actual Behavior

Part of the content appears on the second page

### Reproduction Steps

1. Download [file](https://github.com/ONLYOFFICE/DocumentServer/files/13960355/test.zip)

2. Open with Onlyoffice

### Additional information

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/14806813/0906e233-a98d-4436-89be-e8ccc09a78b5)

**Comment by ccsheller** [comment] 2024-01-18 08:42
Because ONLYOFFICE does not support row grids.
![Uploading CA064C20-B365-4eb4-857A-A1D9612AD006.png…]()

**Comment by huzedong2015** [comment] 2024-01-18 09:29
But this is a default option in MS Word. Will it be supported later?

**Comment by maruacat** [comment] 2024-02-01 11:35
Hello @huzedong2015 and @ccsheller!
I can confirm that this is known bug #24876 and the offset issue is due to the lack of support for row grids in our editor.

**Comment by Rita-Bubnova** [comment] 2024-02-01 13:02
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1640.

**Closed by Rita-Bubnova** 2024-02-01 13:02 UTC
